import Link from '@/components/wiki-link';
import { DirectoryDetailsIntro, DirectoryIndex } from '@/components/directory-navigation';
import { GuideBreadcrumbs, RelatedGuides } from '@/components/guide-navigation';
import { PageIntro } from '@/components/page-intro';
import { PixelImage } from '@/components/pixel-image';
import { SiteFrame } from '@/components/site-frame';
import { craftingRecipes, systemFor } from '@/lib/crafting';
import { consumableDuration, consumableEffect, consumableTarget, consumableValue, consumables, content, humanize } from '@/lib/content';
import { coatingLifecycle } from '@/lib/crafting-overview';
import { TruthPair } from '@/components/truth-pair';

const recipeFor = (name: string) => craftingRecipes.find((recipe) => recipe.result === name);

export default function ConsumablesPage() {
  const scentMask = content.items.find((item) => item.id === 'scent_mask');
  const solvent = content.items.find((item) => item.id === 'solvent');
  return <SiteFrame sidebar><GuideBreadcrumbs items={[{ label: 'Home', href: '/' }, { label: 'Consumables and Field Kit' }]} /><PageIntro eyebrow="Reference" title="Consumables and Field Kit" summary="Browse every current supply, then use the shared rules below to prepare the Field Kit, choose legal targets, read durations, and commit one exact carried item." />
    <DirectoryIndex label="Browse consumables" entries={consumables.map((item) => ({ href: `/items/${item.slug}`, name: item.name, imageURL: item.assetURL, imageAlt: `${item.name} icon` }))} />
    <DirectoryDetailsIntro title="Compare consumables" summary="Check each item’s current effect, legal target, duration or value, and recipe route before opening its full entry." />
    <p className="catalogue-guidance">Select an item image or name to open its full entry.</p>
    <div className="table-wrap data-table catalogue-summary"><table><thead><tr><th aria-label="Image" /><th>Item</th><th>Rarity</th><th>Effect</th><th>Target</th><th>Value / duration</th><th>Current recipe route</th></tr></thead><tbody>{consumables.map(item => { const recipe = recipeFor(item.name); const system = recipe ? systemFor(recipe.system) : null; return <tr key={item.id}><td><Link href={`/items/${item.slug}`} aria-label={`Open ${item.name}`}><PixelImage src={item.assetURL} alt={`${item.name} icon`} /></Link></td><td><Link href={`/items/${item.slug}`}>{item.name}</Link><small>{item.summary}</small></td><td>{humanize(item.rarity)}</td><td>{consumableEffect(item)}</td><td>{consumableTarget(item)}</td><td>{consumableDuration(item) !== 'No duration listed' ? consumableDuration(item) : consumableValue(item, 'potency')}</td><td>{recipe && system ? <><Link href={`/crafting/${recipe.system}`}>{system.station}</Link><small>{recipe.name}</small></> : 'No current recipe published'}</td></tr>; })}</tbody></table></div>
    <section className="article-section"><h2>Prepare the next Field Kit at Home</h2><div className="definition-grid"><div><h3>Choose eligible supplies</h3><p>Use Storehouse to review exact identified supplies and move the chosen quantities into the next Field Kit plan.</p></div><div><h3>Confirm the plan</h3><p>Review shortages and current capacity before departure. A changed or over-capacity plan must be reviewed again.</p></div><div><h3>Keep instruments separate</h3><p>Instruments and Supplies have separate Field Kit sections. Choose instruments through the Survey Post route.</p></div><div><h3>Inspect in the world</h3><p>Open Field Kit, choose Supplies, select one carried item, and read its exact effect and available targets before use.</p></div></div></section>
    <section className="article-section two-column"><div><h2>Healing and direct supplies</h2><p>A healing supply shows each current party member with their displayed health. Choose the exact target. Other ready supplies show their current direct use when no separate target is needed.</p><p>An unavailable or changed target does not become a completed use.</p></div><div><h2>Scent Mask</h2><p>{scentMask ? 'Scent Mask applies its current 12-turn field effect from the carried item detail.' : 'Use the current item detail for its exact field duration.'} Animals relying only on scent hesitate for one action; other senses, close contact, and apexes are not hidden.</p><p><Link href="/statuses/scent-mask">Read the complete Scent Mask effect</Link></p></div></section>
    <section className="article-section two-column"><div><h2>Solvent and unidentified curios</h2><p>{solvent ? 'Solvent lists only the carried unidentified curios it can identify.' : 'A current identification supply lists only valid carried targets.'} When none are present, no identification completes.</p><p><Link href="/curios">Browse curios and key items</Link></p></div><div><h2>Trying an unknown curio</h2><p>An unidentified curio keeps its result unknown and shows only legal party targets. Read the confirmation before trying it; Cancel leaves it unused.</p></div></section>
    <section className="article-section note-card"><h2>Commit only the shown use</h2><p>Preparing a supply does not automatically pack it. Selecting, closing, cancelling, or losing the shown target changes nothing. A completed use applies the exact displayed item, quantity, target, and current effect.</p></section>
    <section className="article-section"><h2>Weapon coating duration</h2><TruthPair current={coatingLifecycle.current} accepted={coatingLifecycle.intended} acceptedLabel="Locked intended rule" /><p><strong>Existing campaigns:</strong> {coatingLifecycle.migration}</p></section>
    <RelatedGuides links={[{ label: 'Storehouse', href: '/buildings/storehouse' }, { label: 'Curios', href: '/curios' }, { label: 'Conditions and effects', href: '/statuses' }, { label: 'Resources', href: '/resources' }, { label: 'Crafting', href: '/crafting' }, { label: 'Exploration', href: '/systems/exploration' }]} />
  </SiteFrame>;
}
