import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { PageIntro } from '@/components/page-intro';
import { PixelImage } from '@/components/pixel-image';
import { ItemCraftingRoutes } from '@/components/item-crafting-routes';
import { GuideBreadcrumbs, RelatedGuides } from '@/components/guide-navigation';
import { SiteFrame } from '@/components/site-frame';
import { TruthPair } from '@/components/truth-pair';
import { coatingLifecycle } from '@/lib/crafting-overview';
import { consumableDuration, consumableEffect, consumableTarget, content, humanize, isWeaponCoating } from '@/lib/content';

export function generateStaticParams() { return content.items.filter(item => !item.gear).map(item => ({ slug: item.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const item = content.items.find(entry => entry.slug === slug); return item ? { title: item.name, description: item.summary } : {}; }

export default async function ItemDetail({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const item = content.items.find(entry => entry.slug === slug); if (!item) notFound();
  return <SiteFrame sidebar><GuideBreadcrumbs items={[{ label: 'Reference', href: item.consumable ? '/consumables' : '/curios' }, { label: item.consumable ? 'Consumables' : 'Curios and key items', href: item.consumable ? '/consumables' : '/curios' }, { label: item.name }]} /><div className="entity-heading"><PixelImage src={item.assetURL} alt={`${item.name} icon`} size={96} /><PageIntro eyebrow={`${humanize(item.rarity)} ${humanize(item.category)}`} title={item.name} summary={item.summary} /></div>
    {item.consumable && <><section className="article-section"><h2>Current use</h2><dl className="fact-grid"><div><dt>Effect</dt><dd>{consumableEffect(item)}</dd></div><div><dt>Target</dt><dd>{consumableTarget(item)}</dd></div><div><dt>Current value</dt><dd>{humanize(item.consumable.potency)}</dd></div><div><dt>Duration</dt><dd>{consumableDuration(item)}</dd></div></dl></section>{isWeaponCoating(item) && <section className="article-section"><h2>Current and intended coating duration</h2><TruthPair current={coatingLifecycle.current} accepted={coatingLifecycle.intended} acceptedLabel="Intended design" /><p><strong>Existing campaigns:</strong> {coatingLifecycle.migration}</p></section>}<section className="article-section two-column"><div><h2>Field Kit and carrying</h2><p>Choose this identified item in the next Field Kit plan at home. It travels only when the plan is confirmed for departure; inspect its carried detail before use.</p></div><div><h2>Use the selected item</h2><p>The item is spent only when it can affect the target you chose. Cancelling, closing the details, or finding that the target is no longer available leaves the item unspent.</p></div></section></>}
    {!item.consumable && <section className="article-section two-column"><div><h2>Identification and knowledge</h2><p>An unknown curio stays unknown until one example is studied at Home, identified with Solvent while carried, or tried in a suitable situation. This guide does not reveal its result before you discover it. Once a family is known, later matching examples can reveal immediately.</p></div><div><h2>Use and storage</h2><p>Check whether the object is in the Storehouse, Waiting, or carried in a world. The available station or world action explains how it can be used. If the object or situation changes, reopen the detail rather than assuming a different object was used.</p></div></section>}
    <ItemCraftingRoutes item={item} />
    <section className="article-section two-column"><div><h2>Trading</h2><p>{item.tradingPostDisposition === 'sellable' ? 'An identified transferable object can be sold at the Trading Post. Unknown curios stay protected from ordinary sale.' : 'This object is protected from ordinary sale.'}</p></div><div><h2>Recycler</h2><p>{item.recyclerDisposition === 'recyclable' ? 'The Recycler can preview and dismantle this eligible item.' : 'The Recycler does not treat this object as recyclable gear.'} Previewing or cancelling never changes the selected object.</p></div></section>
    <RelatedGuides links={[{ label: item.consumable ? 'All consumables' : 'All curios and key items', href: item.consumable ? '/consumables' : '/curios' }, ...(item.consumable ? [{ label: 'Field Kit', href: '/consumables' }] : [{ label: 'Library and records', href: '/buildings/library' }, { label: 'Storehouse', href: '/buildings/storehouse' }, { label: 'Recycler', href: '/recycling' }, { label: 'Economy and exchange', href: '/trading' }]), ...(item.tradingPostDisposition === 'sellable' ? [{ label: 'Trading offer and sale terms', href: '/trading' }] : []), ...(item.recyclerDisposition === 'recyclable' ? [{ label: 'Recycler return reference', href: '/recycling' }] : []), { label: 'Crafting', href: '/crafting' }, { label: 'All resources', href: '/resources' }, { label: 'All systems', href: '/systems' }]} />
  </SiteFrame>;
}
