import Link from '@/components/wiki-link';
import { GuideBreadcrumbs, RelatedGuides } from '@/components/guide-navigation';
import { PageIntro } from '@/components/page-intro';
import { PixelImage } from '@/components/pixel-image';
import { SiteFrame } from '@/components/site-frame';
import { content } from '@/lib/content';

export default function AnimalsCompanionshipGuide() {
  const menagerie = content.stations.find((station) => station.id === 'menagerie');
  const bestiary = content.stations.find((station) => station.id === 'bestiary');
  return <SiteFrame sidebar>
    <GuideBreadcrumbs items={[{ label: 'Systems', href: '/systems' }, { label: 'Animals and companionship' }]} />
    <PageIntro eyebrow="Current system guide" title="Animals and companionship" summary="Meet an eligible animal in a world, use Attend once the Menagerie teaches it, earn that individual animal’s trust, then decide at Home whether the companion joins the party or rests at the Menagerie." />
    <section className="article-section journey-strip">{menagerie?.assetURL && <Link href={`/buildings/${menagerie.slug}`}><PixelImage src={menagerie.assetURL} alt="Menagerie building visual" size={64} /><span><strong>Menagerie</strong><small>Build it after recruiting Sabine to learn Attend and manage animal companions.</small></span></Link>}{bestiary?.assetURL && <Link href="/bestiary"><PixelImage src={bestiary.assetURL} alt="Bestiary building visual" size={64} /><span><strong>Bestiary</strong><small>Review encountered creature records without revealing unseen creatures.</small></span></Link>}</section>
    <section className="article-section"><h2>Start with an eligible animal</h2><div className="definition-grid"><div><h3>Learn Attend</h3><p>Recruit Sabine and build the Menagerie. Attend is then available only during an active expedition.</p></div><div><h3>See it and give it space</h3><p>Attend needs a visible animal within two tiles, but not immediately adjacent to the party.</p></div><div><h3>Do not harm it</h3><p>An animal that is pursuing the party, has been harmed during the current expedition, is an apex, or is a rooted hazard cannot accept attention.</p></div><div><h3>Read the refusal</h3><p>If the animal is unavailable, too far away, or otherwise ineligible, its current state remains unchanged. Move, reveal, or choose another animal rather than treating Attend as completed.</p></div></div></section>
    <section className="article-section two-column"><div><h2>Build trust with an individual animal</h2><p>Attend shows what that animal needs. Some animals need a carried material with the stated useful property; others need patient company for a certain number of turns. An unsuitable offering is not consumed.</p></div><div className="note-card"><h3>Join only after trust is complete</h3><p>Once that animal trusts the party, choose Join. Progress with one animal cannot recruit a different one, and unfinished trust does not create a companion.</p></div></section>
    <section className="article-section"><h2>Home, party, and returning</h2><p>A joined animal rests at the Menagerie until you add it to the travelling party at Home. It takes one party place, just like another companion. If the party is full or the selection changes, the existing party stays as it was.</p><p>When an expedition ends, a travelling animal returns to the Menagerie. Use the companion and party screens to see which animals are available and choose who travels next.</p><p><Link href="/places/menagerie">Open the Menagerie</Link> · <Link href="/buildings/firepit">Review human party placement</Link> · <Link href="/systems/party-preparation">Prepare the party</Link></p></section>
    <section className="article-section"><h2>Animal companions in combat</h2><p>A travelling animal takes its own turn, with its health and combat values shown alongside the party. It can make its instinctive attack and has one trait-led technique: Interpose, Harrier, Slip Away, Warning Display, or Commit.</p><div className="definition-grid"><div><h3>Choose a valid target or rank</h3><p>The encounter shows which enemy, ally, or position the animal can choose. If that choice changes before confirmation, choose again.</p></div><div><h3>Passed out animals do not act</h3><p>An animal that has passed out has no available combat action for that turn.</p></div><div><h3>Animal-specific preparation</h3><p>Animals do not use human equipment or combat trees. Their companion action comes from the individual animal that joined.</p></div><div><h3>Use the Combat guide</h3><p>Open Combat for turn order, encounter actions, damage, defence, and item use around the animal’s turn.</p></div></div><p><Link href="/systems/combat">Open Combat</Link></p></section>
    <section className="article-section"><h2>Bestiary relationship</h2><p>The in-game Bestiary records encountered creature information. The Player Wiki’s named profiles help you read current encounter types, but neither reference marks an animal as encountered or turns a creature record into an automatic companion.</p><p><Link href="/bestiary">Open Bestiary profiles</Link></p></section>
    <RelatedGuides links={[{ label: 'Attend an animal', href: '/actions/attend-animal' }, { label: 'Menagerie', href: '/places/menagerie' }, { label: 'Bestiary records', href: '/bestiary' }, { label: 'Exploration', href: '/systems/exploration' }, { label: 'Party preparation', href: '/systems/party-preparation' }, { label: 'Combat', href: '/systems/combat' }, { label: 'Firepit and travelling party', href: '/buildings/firepit' }]} />
  </SiteFrame>;
}
