import Link from '@/components/wiki-link';

export function CreatureHabitatDecisions() {
  return <section className="article-section note-card">
    <h2>Creature bodies and habitats</h2>
    <p><strong>Current development status:</strong> Physical habitat placement and the narrow Hide reward have development checks. Body-adapted generation and the wider flying movement below are not yet delivered to the phone.</p>
    <p><strong>Decided intended behavior:</strong> A creature’s body must suit its home. Land creatures stay on suitable ground. Shore creatures can use shallows and adjacent banks; a fish-shaped shore creature needs supporting limbs. Aquatic creatures stay in connected shallow and deep liquid water. Aerial creatures need membrane or feathered wings and may cross ground and water without a perch requirement.</p>
    <p>Flight does not let the party walk across deep water or pull an unreachable creature into combat. Trees, blocking deposits, chasms and crumbled gaps remain obstacles in this first slice. Ice is not liquid habitat. Existing worlds keep their creatures and movement.</p>
    <p><strong>Bone delivered in phone324:</strong> qualifying internal skeletons now supply typed Bone with actual source measurements, colour/Pattern, species quantity and Anatomy. Reward, Return and trading preserve exact portions without an extra roll or generic duplicate. Forge’s complete typed-Bone component choices, statistics, prices and recovery are delivered too. Specialist consumers remain pending; flight never proves Hollow Bone, and the wider anatomy rework remains separate.</p>
    <p><strong>Bestiary arrangement — tested in the Simulator:</strong> Sky, Water, Amphibious and Land, with body-shape subcategories: Four-legged, Two-legged, Serpentine, Segmented, Radial, Fish-shaped and Amorphous. Supported habitat chooses the section; Amphibious means water-and-land movement. Aimee approved this arrangement and lifted the Bestiary work hold on 5 September. Five focused checks and a native Library → Bestiary route passed. This later update is not included in phone build 307; presentation acceptance remains pending.</p>
    <p><strong>Tested Simulator discovery behavior:</strong> Sorting and search use recorded kinds only, with no hidden-species total or locked creature fillers. Missing older habitat stays Unclassified; missing trustworthy shape stays Shape not recorded within the known habitat. A kind follows its latest recorded shape while retaining its older individual records. Only represented chapters and body groups appear; recorded knowledge survives reopening and individual-record pruning. Existing encounter records do not require victory, and a separate distant-sighting record remains unfinished.</p>
    <p><strong>Next ecology design:</strong> Role and movement descriptions must match the creature’s actual body and behavior. Membranes alone do not make a flier, weak weapons do not prove a grazing diet, and low bone density does not prove hollow bones. These naming changes are specified but not implemented; they add no new abilities or feeding simulation.</p>
    <p><strong>Next weather/body correction:</strong> The existing cold-water tendency toward extra appendages will apply only to supported water or amphibious creatures with actual liquid habitat. Land creatures and fliers keep ordinary body variation. This correction is specified but not implemented; it adds no weather immunity, material reward or changing-weather simulation.</p>
    <p><strong>New solid-part reward plan — not implemented:</strong> actual Fur Pelt, Scales, Chitin, Shell, Protective Spines, Feathers and useful Horns now have specified source, quantity, quality, colour/Pattern, Return and trade rules. Generic Plate/Fin and automatic Oil/Venom/Ichor are not valid replacements for anatomy. The next first-pass proposal now defines actual tooth/claw/tusk parts, Down, membrane sheets and fluid chemistry, with narrow optional equipment/preparation uses. Their producers and adapters are not implemented; solid-part roles now specify protective panels, Pelt lining and Horn supports, with Spines/Feathers deliberately raw-sale-only; actual integration and natural prevalence remain unfinished; the complete shops already use Resin, Toxic Sap and Dyer’s Root without those fluids.</p>
    <p><strong>Complete discovery journey — designed, not implemented:</strong> first full sight will add a limited Seen note, Look will explain supported visible parts, and actual encounters retain their existing specimen knowledge and discovery reward. Only committed rewards confirm recovered material quantities, quality and source colour/Pattern. Return and Library preserve knowledge without granting loot again; Seen and Encountered remain one identity. Hidden chemistry, distant Apex markers and planned-only parts do not become material discoveries.</p>
    <p><strong>Food and shelter — first-pass proposal, not implemented:</strong> low-leaf browsing, soft-fungal feeding and smaller-prey links now have defined body, actual-source and habitat-access requirements. Unsupported diets stay unspecified; no hunger, breeding or population simulation is added. A real nest or den requires a structure, and creature ownership requires an actual use link. Fliers do not gain a perch requirement.</p>
    <p><strong>Climate and observation — first-pass proposal, not implemented:</strong> cold, heat, wetness and air shape generation tendencies without proving material anatomy or immunity. Food still needs an actual suitable source and host. Future Bestiary notes can remember weather genuinely presented when a creature was seen; hidden creatures and older unknown weather earn no note. Wet coats, migration and seasonal breeding remain unselected ideas.</p>
    <p><strong>Remaining diets and natural play:</strong> a finite first-pass table now keeps unsupported aquatic, aerial, radial, amorphous and chemical diets explicitly unspecified rather than inventing intake or food sources. The later availability plan uses ordinary sightings, actual rewards, Return and crafting choices; no spawn frequency, corpus run or full-map requirement has been added.</p>
    <p><strong>Remaining work:</strong> The wider creature rework, additional anatomical materials, and food, nesting and weather relationships remain unfinished. Existing Hide, Anatomy and source-colour decisions are preserved.</p>
    <p><Link href="/references/design-decisions-september-4">Read the habitat decisions and current development limits</Link></p>
  </section>;
}
