import Link from '@/components/wiki-link';

export function CreatureHabitatDecisions() {
  return <section className="article-section note-card">
    <h2>Creature bodies and habitats</h2>
    <p><strong>Current generation:</strong> build333 delivers compatible body layouts and independent appendage groups for new worlds;339 expands their visible construction and corrects admission of legal remote aquatic starts. Existing worlds keep their saved generation. Bounded native evidence does not establish every habitat or material through ordinary play.</p>
    <p><strong>Decided intended behavior:</strong> A creature’s body must suit its home. Land creatures stay on suitable ground. Shore creatures can use shallows and adjacent banks; a fish-shaped shore creature needs supporting limbs. Aquatic creatures stay in connected shallow and deep liquid water. Aerial creatures need membrane or feathered wings and may cross ground and water without a perch requirement.</p>
    <p><strong>Aquatic access:</strong> some swimmers may start in dark water you cannot reach and approach shallows only after noticing you. Actual senses, behavior and legal water routes govern that approach; it is not guaranteed, and hidden creatures stay hidden.</p>
    <p>Flight does not let the party walk across deep water or pull an unreachable creature into combat. Trees, blocking deposits, chasms and crumbled gaps remain obstacles in this first slice. Ice is not liquid habitat. Existing worlds keep their creatures and movement.</p>
    <p><strong>Bone delivered in phone324:</strong> qualifying internal skeletons now supply typed Bone with actual source measurements, colour/Pattern, species quantity and Anatomy. Reward, Return and trading preserve exact portions without an extra roll or generic duplicate. Forge’s complete typed-Bone component choices, statistics, prices and recovery are delivered too. Specialist consumers remain pending; flight never proves Hollow Bone, and the wider anatomy rework remains separate.</p>
    <p><strong>Bestiary arrangement — delivered:</strong> Sky, Water, Amphibious and Land, with body-shape subcategories: Four-legged, Two-legged, Serpentine, Segmented, Radial, Fish-shaped and Amorphous. Supported habitat chooses the section; Amphibious means water-and-land movement. Aimee approved this arrangement and lifted the Bestiary work hold on 5 September. Five focused checks and a native Library → Bestiary route passed. The implementation and its native checks are included in the delivered310 source. Presentation acceptance remains separate.</p>
    <p><strong>Current recorded-discovery behavior:</strong> Sorting and search use recorded kinds only, with no hidden-species total or locked creature fillers. Missing older habitat stays Unclassified; missing trustworthy shape stays Shape not recorded within the known habitat. A kind follows its latest recorded shape while retaining its older individual records. Only represented chapters and body groups appear; recorded knowledge survives reopening and individual-record pruning. Existing encounter records do not require victory. Build375 adds separate Seen notes from genuine full current sight, without granting a measured specimen or encounter reward.</p>
    <p><strong>Next ecology design:</strong> Role and movement descriptions must match the creature’s actual body and behavior. Membranes alone do not make a flier, weak weapons do not prove a grazing diet, and low bone density does not prove hollow bones. These accepted naming rules add no new abilities or feeding simulation; full natural ecological coherence remains unverified.</p>
    <p><strong>Current weather/body boundary:</strong> the modular generation in333 includes corrected cold/count handling. The cold-water tendency applies only to supported water or amphibious creatures with actual liquid habitat. Land creatures and fliers keep ordinary body variation; it adds no weather immunity, material reward or changing-weather simulation.</p>
    <p><strong>Solid materials — installed in376:</strong> Build376 enables solid creature materials in newly written books: Fur Pelt, Overlapping Scales, Armoured Scales, Chitin, Chitin Plate, Shell, Protective Spines, Flight Feathers, Contour Feathers and useful Horn. Actual body parts determine what can be recovered. Existing books, creatures and earned stock keep their saved rules; Hide and Bone retain their existing recovery paths. After victory, qualifying solid parts have no separate recovery roll. Look can say “After victory: Shell” for a supported visible source; it does not reveal hidden measurements or grant a reward. Exact recovered portions retain their source colour, Pattern and quality through Return, grouped stock, trade and supported crafting. Matching subtype and quality share one stack; tap it for the individual source details. The Forge now accepts2 Shell for a Shield face or1 useful Horn for a Pointed Blade or Cutting Blade grip. Pay the ordinary remaining components; starter alternatives and0 Essence crafting stay unchanged. Shell contributes Protection; Horn contributes support workmanship without extra Power. Refitting returns displaced current components once, retaining their exact source details.</p>
    <p><strong>Build376 limits:</strong> Fifteen internal checks passed, including new-book activation, old-book preservation and a controlled Shell source → reward → Return → Forge → reopening journey. That route used existing screens and controlled encounters; it does not establish natural material frequency or complete tap navigation. Installation is verified, but successful phone launch and physical usability remain unverified. The ten material icons are interim and are being polished; final creature artwork is also unfinished. Specialist equipment roles and proposed teeth, claws, tusks, Down, membranes and fluid chemistry remain unfinished.</p>
    <p><strong>Discovery journey — installed in375:</strong> Build375 records a limited Seen note when a creature is genuinely in full current sight, including on normal expedition entry or resume. Look remains read-only and explains supported visible parts. Actual encounters retain their existing specimens, measurements and discovery reward without requiring victory. Only committed rewards confirm recovered type, quantity, quality and source colour/Pattern; Return records kept or lost portions, and Library history remains after those portions are spent or lost. Seen, Encountered and Recovered facts share one known identity without granting stock or Writing knowledge again. Hidden chemistry, distant Apex markers and planned-only parts do not become material discoveries.</p>
    <p><strong>Bone is recorded history:</strong> Look does not inspect a new creature’s hidden Bone plan because another member of its kind was encountered. It may say “Previously recovered from this kind: Bone” only from an actual committed reward linked to that known kind; this is history, separate from Possible materials. Existing earned specimen measurements remain available.</p>
    <p><strong>Build375 verification:</strong> Ten focused and normal-route checks passed, including durable sight recording, source-specific Bone history, encounter rewards, Return and reopening. The internal journey used controlled encounters and existing screens; it does not establish natural difficulty, complete tap navigation or final creature artwork. Installation is verified; successful phone launch and physical usability remain unverified.</p>
    <p><strong>Food and shelter — first-pass proposal, not implemented:</strong> low-leaf browsing, soft-fungal feeding and smaller-prey links now have defined body, actual-source and habitat-access requirements. Unsupported diets stay unspecified; no hunger, breeding or population simulation is added. A real nest or den requires a structure, and creature ownership requires an actual use link. Fliers do not gain a perch requirement.</p>
    <p><strong>Climate and observation — first-pass proposal, not implemented:</strong> cold, heat, wetness and air shape generation tendencies without proving material anatomy or immunity. Food still needs an actual suitable source and host. Future Bestiary notes can remember weather genuinely presented when a creature was seen; hidden creatures and older unknown weather earn no note. Wet coats, migration and seasonal breeding remain unselected ideas.</p>
    <p><strong>Remaining diets and natural play:</strong> a finite first-pass table now keeps unsupported aquatic, aerial, radial, amorphous and chemical diets explicitly unspecified rather than inventing intake or food sources. The later availability plan uses ordinary sightings, actual rewards, Return and crafting choices; no spawn frequency, corpus run or full-map requirement has been added.</p>
    <p><strong>Remaining work:</strong> The wider creature rework, additional anatomical materials, and food, nesting and weather relationships remain unfinished. Existing Hide, Anatomy and source-colour decisions are preserved.</p>
    <p><Link href="/references/design-decisions-september-4">Read the habitat decisions and current development limits</Link></p>
  </section>;
}
