import Link from '@/components/wiki-link';

export function FieldInteractionDecisions({ study = false }: { study?: boolean }) {
  return <section className="article-section note-card">
    <h2>Field controls and resource placement</h2>
    <p><strong>Current gathering —399:</strong> Build399 automatically uses an applicable tool already available to the gathering action, without changing your saved preference or swapping equipment. A valid chosen source takes priority; otherwise a live source under your character comes first across resource types. With nothing underfoot, a workable adjacent source comes before one whose requirement you cannot meet. The selected name, direction, action, base highlight and availability now agree in the compact and expanded context. Tool requirements remain readable, with the full explanation available by expanding the panel. Existing tool eligibility, reach, costs and saved harvest rules remain.</p>
    <p><strong>Gathering rules and retained access limits:</strong> The automatic-tool and source-selection rules are delivered in399. Gathering keeps each source’s existing tool and access requirements; choosing a source does not equip gear, buy anything, spend a turn or activate a site or portal. Existing access limits remain: some older resource nodes prevent gathering certain neighbouring sources while you stand on them. Step to a legal working position beside the source to gather it.</p>
    <p><strong>Current target selection —399:</strong> Build399 replaces the Interact tool chooser with source selection when several gathering sources are in reach. Hold for 0.40 seconds, keep holding while sliding to a source, then release to select it. Release outside to cancel. The next ordinary tap performs the labelled action; selection itself never harvests or spends a turn. A chosen source whose requirement you cannot meet stays selected and explains that requirement. Cancelling or releasing a stale choice does not perform another action. The choice clears when you move, leave or lose access to that source. The explicit Field Kit remains available.</p>
    <p><strong>Verification and limits:</strong> Internal tests and native review cover target selection, readable requirements, cancellation, a refused choice, one explicit harvest and failed-save preservation. Build399 installation and ordinary launch are verified. This does not establish a physical-phone gameplay walkthrough or every source combination.</p>
    <p><strong>Current resource placement — build364:</strong> one tile holds one physical source across rooted plants, minerals and loose finds. Later placement follows the same rule. One source may yield several units; canopy overhang and ground texture are not extra source bases.</p>
    <p><strong>Gameplay notices — installed correction:</strong> Build403 removes internal world-repair notices and acknowledgements from gameplay, including old pending notices after reopening. It also restores the actual source’s refusal explanation when you attempt gathering underfoot, without spending a turn or switching to an adjacent source. Internal checks covered a real refusal attempt with optional gathering messages muted, preserved saving and repair failure handling, and reopening. Installation and ordinary launch succeeded; physical-phone gameplay was not inspected.</p>
    <p><strong>Decided intended feedback:</strong> World maintenance and saved-world repairs must not interrupt play with a notice or acknowledgement. Normal gameplay feedback stays: when you try to gather from a source you cannot work, explain that source’s actual unmet requirement or refusal. Refusal spends no turns or materials and does not switch to a different source. Your notification preferences stay unchanged.</p>
    <p><strong>Existing overlaps:</strong> build364 repairs an affected group only when its sources, work, quantities, remembered records and legal access can all be preserved. Build403 keeps relocation diagnostics internal, without a player notice or acknowledgement. Ambiguous or unsafe cases remain intact for further correction; no progress is erased. Adjacent mining remains valid.</p>
    {study && <p><strong>Current water study:</strong> the example scene has deeper water, a north-up/east-right view with downward pitch, and a connected flat dry area for four-direction walking, delivered in build312. Tree fading remains. Its chosen example heights do not establish production depths or swimming rules.</p>}
    {study && <p><strong>Remembered trees — current in build 316:</strong> fully seen trees keep their last-observed appearance after you walk away and reopen the game. Hidden changes stay hidden; seeing a tree again refreshes its record. Current-tree fading remains. Engineering reports build 316 installed and launched successfully.</p>}
    <p><strong>Current material stacks:</strong> shared material/subtype/quality totals are delivered in Field, Storehouse and supported shop displays. Return still has a confirmed path that lists physical lots separately; its grouping and icon correction is pending. Tap the total for exact colour and property variants; exact pieces remain available to crafting. Ordinary flora and plant textiles remain ungraded. Tannery uses one eligible Skin/Hide and one Salt to make one Leather, delivered in323.</p>
    <p><strong>Current Apex presentation:</strong> build388 gives the actual Apex creature a threatening red aura in the world and a red dot on the minimap. Earlier map and minimap badge labels are superseded. Separate inspection and encounter names remain available under the existing sight rules.</p>
    <p><strong>Current in build 320:</strong> optional notice settings start with monsters on, mining/gathering off, and finds/learning on. Your choices persist. Muting gathering also hides its separate result overlay, while damage, danger and required decisions remain visible. Collected resources are unchanged, and turning notices back on does not replay old messages.</p>
    <p><strong>Current in build321:</strong> new-world wood has a saved source colour shared by the visible tree stem and its harvested Logs. Remembered trees and stock colour chips retain it. Older Logs keep their supported uses; unknown historical colour stays unknown.</p>
    <p><strong>Colour progress:</strong> textile source choices and swatches are delivered in322/323; actual coloured Hafts are delivered in325. Finished component-coloured equipment artwork and the complete source-to-visible-item journey remain unfinished.</p>
    <p><Link href="/references/design-decisions-september-4">Read the field and terrain decisions</Link>.</p>
  </section>;
}
