export function PortalSiteDirection() {
  return <section className="article-section">
    <h2>Portals, camp and Workshop — installed; remaining site artwork — planned</h2>
    <p><strong>Current correction — installed in391:</strong> Build391 keeps sites and portals visible when you stand on them. Portal stone stays fully opaque; only the flowing blue magic is translucent. Entering a camp does not search or loot it. Fringe and remembered terrain are discernible again under the existing sight rules; unknown areas stay black and memories retain their last-observed state. Internal checks and art review support these corrections. Installation and ordinary iPhone launch succeeded; physical-phone appearance and interactive usability have not been inspected. Remembered camp and portal silhouettes remain very dark, and fine details and every plant or material appearance are not yet verified.</p>
    <p><strong>Settled presence and opacity:</strong> Walking onto a place must never hide or remove it. Sites stay in the world with their committed unlooted or looted appearance; entering or starting a search does not complete it. No intermediate looted appearance is being added now. A canopy or roof may soften only where it blocks the character, while the actual place stays visible. Portal stone is fully opaque; only the blue magic may be semitranslucent. Build394 Torch light is blocked by the portal’s actual stone frame while its blue veil and moving magical ribbons let light pass. This changes no portal artwork or travel rule. Installation is verified; ordinary launch subsequently succeeded in395 after the earlier394 locked-phone attempt. Physical appearance and interactive usability remain unverified. A loose object can leave the ground when it is actually collected, including an existing automatic pickup during a successful step; simply standing over an uncollected object must not hide it.</p>
    <p><strong>Current behavior:</strong> Build390 delivers authored stone portals with flowing blue Essence magic and a recognizable Wayfarer’s Camp. Its chest changes from closed to open after a committed search, while the shelter, bedroll and cold hearth remain. Both portal identities keep their actual Return home behavior. Beyond the camp and Workshop, site families still use unfinished markers. Installation and ordinary launch were verified for these earlier portal and camp additions; build401 has the separate launch limitation below.</p>
    <p><strong>Current Workshop artwork — installed in401:</strong> Build401 adds the recognizable Binder’s Workshop: a stone writing room with a walnut bench, paper and brass details. The central standing space stays clear, and a completed search changes its drawer while the room remains. Internal checks and art review covered unsearched, searched, occupied and remembered appearances. Installation is verified; ordinary launch, physical-phone appearance and interactive usability remain unverified for this build. Search effort, rewards, movement and saved-world generation keep their existing rules.</p>
    <p><strong>Decided intended behavior:</strong> The remaining icy vaults, exhausted housings, caverns, geyser basins, warrens, Tears and Atlas Seams will receive recognizable artwork of their own. Searching changes a place to searched or emptied where appropriate without erasing its identity or inventing physical changes. Spent Emanation Housing is already exhausted before search, and Atlas Seam keeps its separate anchoring purpose.</p>
    <p><strong>Decided intended Vault behavior:</strong> The Glacial Vault’s ice is a physical enclosure: its body blocks sight and Torch light even where the artwork looks partly translucent. Real openings can let sight and light through. This does not add melting, refraction or a new movement rule; its authored presentation is still intended, not delivered.</p>
    <p>Delivered portals and the camp keep frozen last-observed appearances with still materials in memory; hidden changes do not refresh them, and unknown objects stay hidden. Older memory without the recorded identity keeps its generic marker until the place is seen again. Build391 restores discernible remembered silhouettes, but they remain very dark; fine detail is not yet verified. Portal flow grants no extra light or sight. Travel, searching, rewards and existing confirmations keep their rules.</p>
  </section>;
}
