import Link from '@/components/wiki-link';

export type DecisionTopic = 'crafting' | 'progression' | 'exploration' | 'writing' | 'appearance' | 'people' | 'status';

const updates: Record<DecisionTopic, { current?: string; decided: string; tuning?: string; development?: string; open?: string }> = {
  crafting: {
    decided: 'Starter Blacksmith gear uses raw materials, with no separate Ingot, Haft, or Cord step. The basic forge improves the stone Pick and Axe with iron working parts. Basic healing no longer requires Quartz. Blacksmith T2 makes Iron Ingots for a better Scythe and a reinforced woven garment. Corrin can make a useful plant-cloth garment, gloves and boots before Ingots or Leather, and expands the pack through Carry. An optional Leather path uses actual creature coverings and Salt. Earlier recipes remain usable after an upgrade.',
    tuning: 'The new starter blade and either tool improvement use 4 Iron, 1 Log, 2 Plant Fibre, and 1 Coal, with no Essence. Lesser Salve uses 1 Resin and 1 Plant Fibre. These are intended first-pass recipes, not current phone costs.',
    development: 'Arranged native checks now cover the basic tool improvements, forge T2, Iron Ingots, Scythe 2 and Tall Stem harvesting. The Tannery also completes Cord, Cloth, both woven Guards, Woven Gloves and Boots, Leather and the Leather Guard, with saved results checked after reopening. Separate Recycler checks recover the recorded prepared components. The updated Tannery panels and quotes also pass native plant and Leather preview checks, including missing-input guidance and Cancel without spending. A connected prepared playtest now gathers Salt, returns it, selects actual raw Hide, makes the Leather Guard and reaches 14 pack spaces, retaining the results after reopening. Save-failure presentation still needs a visual check. Source colours and parent materials stay recorded; exact creature-to-Leather colour artwork remains pending. Full natural gathering, affordability, final art and physical-phone playthrough are not established by these checks.',
    open: 'Refining an existing piece toward Peerless is being designed. The proposed Mote + maximum shop + attending keeper guarantee is not implemented; partial odds and Mote spending on a miss remain open. The old twentieth-copy rule is reopened.',
  },
  progression: {
    decided: 'Begin with a stone Pick, Axe, and Scythe in the dedicated tool roll. First Pick and Axe improvements belong at the basic forge. Healing must not depend on a later mineral upgrade. Nessa and Halloway can be discovered from the beginning; Bryn, Corrin, and Noll can follow after one recruit. Useful location clues can still reach ahead. The first two pack projects belong to the opening Storehouse; Corrin’s larger expansion follows. Pack capacity reaches 23, with Sela’s separate +2 taking it to 25. Recipes and costs remain revisable.',
    tuning: 'Apothecary: 20 Essence, 4 Clay, 4 Logs. Blacksmith: 20 Essence, 8 Iron, 4 Plant Fibre, 4 Logs. Starter Plant Fibre means Stem or Leaf Fibre; Logs mean Softwood or Hardwood. These are the starting values in Early Overhaul Playtest; existing ordinary campaigns retain their own rules.',
    development: 'Phone build 307 now offers Settings → Campaigns → New Game → Early Overhaul Playtest as a separate durable campaign. Installation and launch are confirmed; physical-phone visual acceptance and the full natural route remain pending. The later tested Bestiary sorting is Simulator-only. The Storehouse pack projects now reach 14 spaces and survive reopening; an arranged opening campaign then bound its next world for 10 Essence, retaining 15 Essence and all 14 spaces. Separate specialist checks preserve Corrin’s 23 spaces and Sela’s independent increase to 25. Old purchases and active expedition contents are protected. Woven Gloves and Boots pass their own crafting and recovery checks without a Carry requirement. A separate prepared Simulator playtest now connects Salt gathering and Return to Leather crafting and these first two pack projects. Full natural affordability and physical-phone playthrough remain pending.',
    open: 'The arranged Salve journey is complete, but three natural expeditions have not recruited Nessa. The first gathered all healing materials; the next was too dark, and the Sun-written third was too saline. The third ended in defeat; a separately fixed turn-order bug prevents treating that loss as ordinary combat-balance evidence. The saved campaign has 29 Essence and all banked healing materials. Water vocabulary remains unlearned. That preserved campaign stays at three expeditions; a separate fresh-start Simulator build is now available with the ordinary 40 Essence start and no supplied stock, recruited helpers or selected seeds. Its independent acceptance campaign passed two paid departures, ordinary gathering/combat/Return and a naturally collected Substrate lesson read for free and retained after reopening. No maker has joined in that checked route. No new arrival or teaching guarantee has been approved. Natural healing-route acceptance and physical-phone playthrough remain pending.',
  },
  exploration: {
    decided: 'A successful journey should usually leave worthwhile territory unexplored. Trees, canopy, and branching routes create choices without hiding required teaching or erasing earned minimap knowledge. There is no artificial reveal cap or routine full-map reward. Pinning a known recipe highlights useful sources as soon as normally visible, including new creatures, without prior inspection or a suitable tool. Random drops remain possible; fog and hidden rewards stay hidden. The accepted three-quarter view makes trunk-base Axe targeting clear and fades obstructing foreground art without granting extra sight. New early worlds will usually choose Faint or Moderate conditions for things you left unwritten, while keeping every source type and stronger intensities possible. Your own written choices and existing worlds remain unchanged.',
    open: 'The full development test found connected growing habitat in 296 of 1,000 unwritten worlds, above the 25% review target. Actual Softwood appeared in 293 worlds; habitat and placed sources are separate measures. The original test failed on six Softwood or Coal shortfalls. Three are confirmed shared-space limits; the other three now pass focused runtime checks after protecting scarce required sites before flexible and optional choices. The original full-sample counts have not been remeasured. The single map-generation failure now passes focused checks after correcting how small flowing-water totals are divided into channels, with its exact water total preserved. All placed sources retained reachable working positions. The explicit written Iron guarantee and its source-budget credit now pass development checks; broader written-resource guarantees are not implied. Natural pacing and physical-phone playthrough remain pending. Drainage is not part of this revision; no universal map-completion percentage is fixed.',
  },
  writing: {
    decided: 'The intended opening teaches Illumination and Sun through a safe introductory excursion, then visibly connects the player’s first written choice to the world they bind. Unwritten features remain generated. Deliberately writing Iron into Substrate promises one reachable two-deposit cluster within the ordinary source budget; repeated statements and strength, size or count words do not multiply that guarantee. The complete promise is checked before spending for Bind. Explicit Salt in Substrate similarly promises one reachable hand-gathering crust for 2 Salt, using existing gathering capacity; it may form a single local crust in otherwise fresh suitable ground without changing the surrounding water or terrain. Traveller clues use recognizable world facts and vocabulary the player has had a chance to learn; existing knowledge and Pages remain in older saves.',
    open: 'Early maker clues and the next water, River, ground, and Iron lessons are specified. The Iron-first guarantee is implemented and tested in development: a collected-page quote, Bind and entry succeeded in the native app, with direct and compound statement rules checked separately. Natural learning and writing progression, pacing and physical-phone playthrough still need verification. Written Salt now passes a native quoted Bind, seven-step walk, hand-gather of 2 Salt and reopen check, with nineteen focused checks passing. Ordinary Salt gathering also has its own passing development checks. This adds no new Coal, Clay or Resin writing vocabulary, and the wider campaign order remains separate.',
  },
  appearance: {
    decided: 'Material colour is a worthwhile gathering goal. Early fibres inherit the saved foliage colour unless their plant has an assigned shade; Cord, Cloth and the corresponding garment parts keep the selected colour without blending. Every equipment component region receives its selected tint while keeping its silhouette and shading. Quality colours the name highlight and thumbnail border, not the item art; potions keep recognizable authored colours. World palettes stay stable, with separate foliage (including grass), water, and sky channels; an assigned shade takes precedence. Grass colour does not grant harvestability. Recipe tracking uses a thin soft pulsing outline, then a brief collection/completion sparkle.',
    open: 'Three-quarter top-down presentation, local water heights, clear trunk-base targeting, and foreground fade are decided. Actual 3D rendering with a fixed orthographic camera and sprites is under consideration, not selected. Engineering recommends a separate Simulator trial; no renderer, Blender import or performance demonstration is implemented. The full shallow-water-bed proof needs explicit water-depth and bed-height facts, and hidden terrain must not leak through shadows. Exact artwork dimensions, composition, and fade timing await the bounded in-game proof. Final world-entry layer sizes, placement, and movement remain open. Aimee’s Library work is in progress; sky/cloud homework is optional study work.',
  },
  people: {
    decided: 'The intended priority is Vance, then Nessa and Halloway, then Bryn, Corrin, and Noll. Nessa is sought in fresh growing land, Halloway near workable Iron, and Corrin near fibre-bearing growth. Suitable ground counts together across the area connected to the entrance, while retaining each plant’s habitat requirements. Early makers no longer wait behind the old three-recruit requirement. Old clues keep their discovery value and receive updated hints.',
    open: 'This is an intended discovery priority, not a compulsory single-file sequence. Current character pages retain delivered behavior. The wider campaign redesign and actual early-route pacing remain separate work.',
  },
  status: {
    current: 'Ordinary consumable and physical-gear crafts now confirm success only after saving. A failed save refuses the craft without spending ingredients or granting the item. This correction is delivered and covered by focused tests; interactive crafting playthrough is still pending. The Binder and human Gambits/Training presentation update is also delivered, including clearer rule colours, capitalized labels, and the earned-automation explanation. The Apothecary recipe tiles, detail, and preparation presentation are now delivered too, with existing recipes and knowledge preserved.',
    decided: 'The wiki separates current behavior, decided intended behavior, unsettled proposals, and first-pass tuning. Today’s crafting, stone-tool, exploration, recipe-tracking, and colour decisions are intended changes. Costs and order can be revised.',
    open: 'Scent Mask and Seamlight can be prepared, but Field Kit use is unverified for the current phone build. The crafting correction covers ordinary consumable and physical-gear crafts, not every economy action or the overhaul. Interactive campaign playthrough and physical-phone visual acceptance of the Party and Apothecary presentation are still pending. Unlocks, existing entitlements, Training rules, and Gambit rules are unchanged.',
  },
};

export function SeptemberDecisions({ topic }: { topic: DecisionTopic }) {
  const update = updates[topic];
  return <section className="article-section note-card">
    <h2>4 September decisions</h2>
    <p><strong>Current behavior:</strong> {update.current ?? 'Sections labelled current describe the existing game. The intended changes recorded here are not yet verified as delivered.'}</p>
    <p><strong>Decided intended behavior:</strong> {update.decided}</p>
    {update.tuning && <p><strong>First-pass tuning:</strong> {update.tuning}</p>}
    {update.development && <p><strong>Tested in development:</strong> {update.development}</p>}
    {update.open && <p><strong>{topic === 'status' ? 'Verification pending' : 'Unsettled proposals and remaining work'}:</strong> {update.open}</p>}
    <p><Link href="/references/design-decisions-september-4">Read the complete decisions and early recipe tables</Link> · <Link href="/references/aimee-homework">Aimee Homework</Link></p>
  </section>;
}
