import Link from '@/components/wiki-link';

export function WorldViewDirection() {
  return <section className="article-section note-card">
    <h2>Three-quarter world view</h2>
    <p><strong>Current behavior:</strong> Build357 brings the three-quarter3D view into normal Bind, Enter and Continue, in the same campaign. New books use normal resource generation; existing books retain their terrain, resources and saved progress. Movement, Look, Use Tile, sight and harvesting keep their rules. Settings trials remain separate. Internal entry, controls, reopening and Return checks passed and phone installation is verified; physical play acceptance and finished artwork remain separate.</p>
    <p><strong>Generation — current in333:</strong> plants and creatures are assembled in game when a world is written, from its actual traits and stable saved choices. Reusable parts are allowed; finished premade species are not the system. Dragon DNA’s independent part systems inform creature variation, with equivalent relevant modularity for flora. The reviewed system covers six creature layouts and five flora construction families; the old seven creature labels are not a limit on detail. Actual connected elevated water can form a waterfall into lower water; overlapping or disconnected pools cannot. Introduced through the3D trial, these rules now also appear in normal3D expeditions in357. Natural waterfall occurrence and finished procedural richness remain unverified.</p>
    <p><strong>Appearance — current in336:</strong> softer stripes, tapered woody supports, bowed branches and varied opposite/alternate broad-leaf angles are joined by fuller woody broad-leaf crowns above shorter bare supports. Counts, source traits/materials and old saved assemblies remain unchanged. Internal native specimens verify the refinements; the ordinary expedition contained fleshy flora, so no natural woody encounter or phone performance is claimed. Foliage remains clustered and finished richness is still incomplete.</p>
    <p><strong>Height routes — installed in338:</strong> newly bound worlds allow a direct step up or down by at most one elevation level. Most high ground has a connected route from the entrance; sparse unreachable scenery may show water and decorative vegetation but contains no animals or resource nodes. Existing worlds and unfinished opening expeditions keep their earlier rules. Internal native checks passed. Launch verification was blocked at the338 checkpoint; the later344 delivery includes a successful ordinary launch. This is not a claim of physical-phone gameplay acceptance. The ordinary example contained no isolated scenery, so its natural frequency remains unverified. This adds no jump, climbing, swimming or new menu.</p>
    <p><strong>Morphology v2 — installed in339:</strong> new early-game books use distinct creature cores and postures, independent shaped parts and support-based growth across all five flora families. Attachment and fleshy-rosette corrections are included. Old frozen appearances remain unchanged. Bounded internal checks and ordinary Bind/movement/Return/reopen passed; no usable harvest was reached. The later344 delivery includes successful ordinary launch; physical-phone gameplay acceptance of this morphology remains separate. Later updates add pressure-led families in351, colour/shine/markings in352 and shared readability in353. Finished richness and the selective iridescence effect remain unfinished.</p>
    <p><strong>Shared readability — current and intended:</strong> harmful growth already has a static first-full-sight warning. Build353 adds the actual Apex distinction and selected-source action feedback in3D. The base highlight identifies a currently valid action; overhanging leaves do not become targets. Warnings and selection marks preserve source colours, and remembered scenery reveals no current hidden danger, harvests or moving creatures.</p>
    <p><strong>Pressure-led families — installed in351:</strong> world conditions favour several compatible creature and flora construction families, with independent species and individual variation beneath them. A gentle repetition bias preserves variety without forcing every family into each world. Existing Bestiary navigation, source colours and saved worlds stay intact; this does not increase population or rendering capacity.</p>
    <p><strong>Decided intended behavior:</strong> Keep the square grid while showing the fronts and height of trees, rocks, characters, and cliffs.</p>
    <ul className="compact-list">
      <li>Water belongs to its local bed and surface height. A low river and a pond on raised land can coexist; shallow water can show its visible bed.</li>
      <li>Legal steps and slopes connect different heights. A cliff does not become a walkable route because its artwork overlaps another square.</li>
      <li>With an appropriate Axe selected, target the reachable trunk base. A small base highlight and “Chop tree” identify the action, and the impact lands at the trunk.</li>
      <li>Foreground art covering the character fades partly, keeping a faint silhouette and the already-visible blocking base. Only the obstructing cliff face fades, not the whole plateau.</li>
      <li>Fading preserves fog, gameplay canopy concealment, and earned minimap knowledge. It exposes only the character and surroundings the game already allows you to see.</li>
    </ul>
    <p><strong>Moving navigation — installed in359:</strong> the Field Kit and satchel strip, movement controls, minimap, Use Tile and Look move together between the bottom and top of the exploration view when your character approaches within two visible tile heights. They stay at the chosen edge until you approach there. Place information and notifications sit inward from the controls. The map keeps its size and tile scale during a switch; if both edges are too close, the block stays put instead of oscillating. A held press is cancelled when the controls move; press again at their new position. Both-anchor and detail interaction checks and Asset’s layout review passed, with phone installation verified.</p>
    <p><strong>Accepted for later, low priority:</strong> Trees, elevated land, bushes, resource nodes, and the player character should have shadows. Their treatment follows the new geometry and foreground visibility, behind the playable overhaul. Dynamic lighting and a day/night system are not part of this decision.</p>
    <p><strong>Ordinary 3D trial — introduced in327, updated in333:</strong> Settings → Owner Tools → 3D Trials offers one normally generated expedition with its own saved test state, using the current starting setup and normal costs. North stays up and east stays right in the square-projected three-quarter view. Normal expeditions now use3D in357 while these trial saves remain separate; placeholders are allowed. Existing movement, tools, encounters, visibility, memory and fading remain authoritative.</p>
    <p><strong>Build333 verification:</strong> one internal native ordinary expedition had four creature kinds and two flora kinds. Movement, an encounter, Withdraw, Continue and reopening passed; no usable harvest was reached. Its four water areas retained earlier presentation, so no natural waterfall was witnessed. A separate controlled native example verified a connected fall and shore slopes/steps. The phone update is installed and launches normally; your expedition was not played. Phone performance, complete material appearance, waterfall animation and finished organic artwork remain unverified or unfinished.</p>
    <p><strong>Earlier-world markers:</strong> build328 introduced rounded purple placeholders; existing worlds retain their earlier representation, while new worlds in333 use modular creatures. These are neutral markers, not species artwork or material colours. The isolated marker check adds no expedition or phone-performance evidence.</p>
    <p><strong>Build329 corrections:</strong> 3D tiles match the displayed 2D tile size, and opaque trees covering the player’s body or occupied tile participate in the existing fade, including remembered trees. The wood-colour trial menu entry is removed. Build330 now fills the normal Explore viewport at that same tile size, preserving clipping and knowledge limits. Installation and ordinary launch succeeded; supplied movement/reopen checks are Simulator evidence, with your visual acceptance still separate.</p>
    <p><strong>Approved water study — delivered in312:</strong> You approved a separate, clearly labelled example scene showing a raised shallow pond and a lower channel with their own water levels. It uses chosen example heights because existing saves lack measured water depths. Campaigns keep their current rules, and a visible surface reveals only a permitted bed. The decision is complete in <Link href="/references/aimee-homework">Aimee Homework</Link>; the existing-world camera trial continues alongside it.</p>
    <p><strong>Still to be worked out:</strong> Exact artwork sizes and composition for new consumers await their implementation. Existing tree fading keeps its delivered timing and opacity. This does not add stacked bridge floors or change saved worlds.</p>
    <p><Link href="/references/design-decisions-september-4">Read the complete world-view and exploration decisions</Link></p>
  </section>;
}
