import Link from '@/components/wiki-link';

export function WorldViewDirection() {
  return <section className="article-section note-card">
    <h2>Three-quarter world view</h2>
    <p><strong>Current startup status — build370:</strong> Build370 is installed and retains the startup correction from369. The phone app remained running for over 90 seconds with no new crash report during the bounded checks. A further reported opening crash remains unconfirmed by those checks;370 is not being described as a fix for that report. Physical-screen review and gameplay acceptance remain unverified. The earlier368 startup failure remains part of the record.</p>
    <p><strong>Ground textures — installed in368:</strong> Build368 adds the existing terrain textures to normal 3D ground and liquid surfaces, including grass, shallow water, deep water and solid ice. Their detail follows the world’s existing colours. Snow and settled ash keep their separate patches. Moving surface detail does not move the ground or change a turn. Remembered terrain keeps its last-observed appearance without live animation; older plain-looking memories keep that appearance until you see the place again.</p>
    <p><strong>Side textures — installed in370:</strong> Build370 adds recolorable side textures to existing growth, groundcover, ice and soil faces in the normal campaign. Each keeps its own world colours and actual shape; remembered faces retain their observed appearance. Soil now has irregular clod detail instead of the stretched strip pattern seen during development. No extra terrain or movement route is created.</p>
    <p><strong>Build370 verification:</strong> The four side textures passed internal review at ordinary campaign scale, alongside six focused integration checks and a four-terrain native check. Phone installation and sustained process checks are verified. These do not establish every world palette, final physical-screen appearance or a gameplay walkthrough. Build370 preserves saved progress, game rules and the previous ground textures.</p>
    <p><strong>Decided remaining texture work:</strong> Stone, sand, ash, rubble and mud sides still use plain world colours while their texture work continues. A visible shallow-water bed can have a support face, but its material has not been established; it keeps its plain appearance rather than becoming invented stone or soil. Complete the remaining surfaces without changing their material, height or world colours. Suitable existing artwork may be reused and recoloured; make new artwork where needed. Fuller atmosphere effects remain unfinished; illustrative study mist is not ordinary campaign weather.</p>
    <p><strong>Decided water and chasm boundaries:</strong> A bank beside water belongs to the land forming that bank and keeps its colours. Seeing water does not reveal an unknown bed or what it is made of. Deep-water beds remain hidden, and chasms do not gain floors or walls to fill an artwork gap. Older water retains its recorded appearance rather than gaining guessed measurements. Real waterfalls and shore steps keep their own shapes and rules; they are not ordinary support walls.</p>
    <p><strong>Decided complete texture coverage:</strong> Every existing terrain type should have texture detail that follows its world colours, including exposed sides where those sides exist. A textured top does not finish an otherwise plain side. Preserve suitable existing artwork, make missing recolorable detail, and keep stone, soil, vegetation, ice and water recognisable. This does not add cliffs, floors or terrain types where none exist. Ground textures arrived in368, and four side families are installed in370. Remaining surfaces are still being completed; full coverage is not yet delivered.</p>
    <p><strong>Build368 verification:</strong> Build368 installed the texture update but crashed during startup; its earlier process-start result did not establish successful startup. Build369 now retains those textures with the bounded startup recovery described above. Internal checks covered the existing terrain families, remembered appearance and surface motion; supplied views were reviewed at normal campaign scale and in a separate six-terrain example. The At this place text is also lighter and more readable. These checks do not establish a physical-phone playthrough, every moving-camera or waterfall view, or final artistic acceptance.</p>
    <p><strong>Decided atmosphere, not delivered:</strong> Show the atmosphere the world actually has: smoke, airborne ash, mist or miasma, with rain or snow where the existing world conditions call for them. Moving air changes the drift of existing effects. These visuals do not create new weather damage, slippery ground, puddles, freezing or accumulated snow. Unseen places stay hidden, remembered places show their last-observed state without live weather, and characters, useful objects, warnings and controls remain readable.</p>
    <p><strong>Unsettled visual choices:</strong> Specific cloud layers, volumetric fog techniques, sun shafts and day/night lighting treatments remain proposals. Existing sky and cloud authoring references stay available; this work does not replace that creative direction or add a new decision checklist.</p>
    <p><strong>Current behavior:</strong> Build357 brings the three-quarter3D view into normal Bind, Enter and Continue, in the same campaign. New books use normal resource generation; existing books retain their terrain, resources and saved progress. Movement, Look, Use Tile, sight and harvesting keep their rules. Settings trials remain separate. Internal entry, controls, reopening and Return checks passed and phone installation is verified; physical play acceptance and finished artwork remain separate.</p>
    <p><strong>Generation — current in333:</strong> plants and creatures are assembled in game when a world is written, from its actual traits and stable saved choices. Reusable parts are allowed; finished premade species are not the system. Dragon DNA’s independent part systems inform creature variation, with equivalent relevant modularity for flora. The reviewed system covers six creature layouts and five flora construction families; the old seven creature labels are not a limit on detail. Actual connected elevated water can form a waterfall into lower water; overlapping or disconnected pools cannot. Introduced through the3D trial, these rules now also appear in normal3D expeditions in357. Natural waterfall occurrence and finished procedural richness remain unverified.</p>
    <p><strong>Appearance — current in336:</strong> softer stripes, tapered woody supports, bowed branches and varied opposite/alternate broad-leaf angles are joined by fuller woody broad-leaf crowns above shorter bare supports. Counts, source traits/materials and old saved assemblies remain unchanged. Internal native specimens verify the refinements; the ordinary expedition contained fleshy flora, so no natural woody encounter or phone performance is claimed. Foliage remains clustered and finished richness is still incomplete.</p>
    <p><strong>Waterfall contact and motion — installed in361:</strong> a falling sheet that overlaps its own shore step sits just beyond its receiving face and remains joined to the upper water. Its width, drop, crossing rules and disclosure stay intact. Only the falling sheet animates. Internal checks and sequential-frame review passed for contact, exposure and sampled downward movement. Real-time smoothness/flicker, natural occurrence, physical-phone size and your visual acceptance remain unverified.</p>
    <p><strong>Stems and caps — installed in360:</strong> newly written worlds use actual authored, tapered fleshy stems and fungal caps. Basal rosettes are compact; branches and existing spore-bearing features attach to their actual surfaces. Source counts, colours, materials and older saved shapes stay intact. Internal checks and the16-image matched review passed for this correction. Long bare upper stems, weak needle/frond distinction at ordinary scale and stacked cap groups remain; this is not finished plant realism or your visual acceptance.</p>
    <p><strong>Plant distribution — decided, not delivered:</strong> leafy upright and branched fleshy plants will use coordinated stem taper, higher branch distribution, actual leaf-surface attachment and more of their saved leaf length. Opposite, alternating and grouped leaves keep their arrangement; fronds expose their existing broad face without facing the camera. Counts, materials, basal rosettes, other families and old books stay intact. New organs remain separate proposals.</p>
    <p><strong>Height routes — installed in338:</strong> newly bound worlds allow a direct step up or down by at most one elevation level. Most high ground has a connected route from the entrance; sparse unreachable scenery may show water and decorative vegetation but contains no animals or resource nodes. Existing worlds and unfinished opening expeditions keep their earlier rules. Internal native checks passed. Launch verification was blocked at the338 checkpoint; the later344 delivery includes a successful ordinary launch. This is not a claim of physical-phone gameplay acceptance. The ordinary example contained no isolated scenery, so its natural frequency remains unverified. This adds no jump, climbing, swimming or new menu.</p>
    <p><strong>Morphology v2 — installed in339:</strong> new early-game books use distinct creature cores and postures, independent shaped parts and support-based growth across all five flora families. Attachment and fleshy-rosette corrections are included. Old frozen appearances remain unchanged. Bounded internal checks and ordinary Bind/movement/Return/reopen passed; no usable harvest was reached. The later344 delivery includes successful ordinary launch; physical-phone gameplay acceptance of this morphology remains separate. Later updates add pressure-led families in351, colour/shine/markings in352 and shared readability in353. Finished richness and the selective iridescence effect remain unfinished.</p>
    <p><strong>Shared readability — current and intended:</strong> harmful growth already has a static first-full-sight warning. Build353 adds the actual Apex distinction and selected-source action feedback in3D. The base highlight identifies a currently valid action; overhanging leaves do not become targets. Warnings and selection marks preserve source colours, and remembered scenery reveals no current hidden danger, harvests or moving creatures.</p>
    <p><strong>Pressure-led families — installed in351:</strong> world conditions favour several compatible creature and flora construction families, with independent species and individual variation beneath them. A gentle repetition bias preserves variety without forcing every family into each world. Existing Bestiary navigation, source colours and saved worlds stay intact; this does not increase population or rendering capacity.</p>
    <p><strong>Decided intended behavior:</strong> Keep the square grid while showing the fronts and height of trees, rocks, characters, and cliffs.</p>
    <ul className="compact-list">
      <li>Water belongs to its local bed and surface height. A low river and a pond on raised land can coexist; shallow water can show its visible bed.</li>
      <li>Legal steps and slopes connect different heights. A cliff does not become a walkable route because its artwork overlaps another square.</li>
      <li>With an appropriate Axe selected, target the reachable trunk base. A small base highlight and “Chop tree” identify the action, and the impact lands at the trunk.</li>
      <li>Foreground art covering the character fades partly, keeping a faint silhouette and the already-visible blocking base. Only the obstructing cliff face fades, not the whole plateau.</li>
      <li>Fading preserves fog, gameplay canopy concealment, and earned minimap knowledge. It exposes only the character and surroundings the game already allows you to see.</li>
    </ul>
    <p><strong>Fixed controls and raised ground — corrected in362:</strong> only notifications switch edges; context and all movement, minimap, action and carried-item controls stay fixed. Known raised ground now has supporting faces and current objects have broader shadow coverage. Internal checks and supplied-image review passed; final visual acceptance remains separate.</p>
    <p><strong>World terrain colours — installed in363:</strong> terrain, water and banks use the saved world palette. Remembered terrain retains its observed colours. Build365 adds snow and settled-ash patches on existing solid terrain, retaining exposed ground, uncoated cliff faces and saved fog appearance. Separate shore ramps and crossings remain unchanged. Deeper drifts, melting and weather accumulation remain unimplemented proposals; bounded internal review is not final aesthetic acceptance. Build364 delivers saved-reward gathering feedback, shared source placement and lossless overlap repair, remembered non-enemy objects and expandable material totals. Raw Essence now uses a blue droplet; its remembered-fog appearance still awaits visual review. Five material icon replacements remain placeholders.</p>
    <p><strong>Accepted for later, low priority:</strong> Trees, elevated land, bushes, resource nodes, and the player character should have shadows. Their treatment follows the new geometry and foreground visibility, behind the playable overhaul. Dynamic lighting and a day/night system are not part of this decision.</p>
    <p><strong>Ordinary 3D trial — introduced in327, updated in333:</strong> Settings → Owner Tools → 3D Trials offers one normally generated expedition with its own saved test state, using the current starting setup and normal costs. North stays up and east stays right in the square-projected three-quarter view. Normal expeditions now use3D in357 while these trial saves remain separate; placeholders are allowed. Existing movement, tools, encounters, visibility, memory and fading remain authoritative.</p>
    <p><strong>Build333 verification:</strong> one internal native ordinary expedition had four creature kinds and two flora kinds. Movement, an encounter, Withdraw, Continue and reopening passed; no usable harvest was reached. Its four water areas retained earlier presentation, so no natural waterfall was witnessed. A separate controlled native example verified a connected fall and shore slopes/steps. The phone update is installed and launches normally; your expedition was not played. At that checkpoint, phone performance, complete material appearance, waterfall animation and finished organic artwork remained unverified or unfinished. Build361 subsequently delivers the bounded waterfall contact/motion correction above.</p>
    <p><strong>Earlier-world markers:</strong> build328 introduced rounded purple placeholders; existing worlds retain their earlier representation, while new worlds in333 use modular creatures. These are neutral markers, not species artwork or material colours. The isolated marker check adds no expedition or phone-performance evidence.</p>
    <p><strong>Build329 corrections:</strong> 3D tiles match the displayed 2D tile size, and opaque trees covering the player’s body or occupied tile participate in the existing fade, including remembered trees. The wood-colour trial menu entry is removed. Build330 now fills the normal Explore viewport at that same tile size, preserving clipping and knowledge limits. Installation and ordinary launch succeeded; supplied movement/reopen checks are Simulator evidence, with your visual acceptance still separate.</p>
    <p><strong>Approved water study — delivered in312:</strong> You approved a separate, clearly labelled example scene showing a raised shallow pond and a lower channel with their own water levels. It uses chosen example heights because existing saves lack measured water depths. Campaigns keep their current rules, and a visible surface reveals only a permitted bed. The decision is complete in <Link href="/references/aimee-homework">Aimee Homework</Link>; the existing-world camera trial continues alongside it.</p>
    <p><strong>Still to be worked out:</strong> Exact artwork sizes and composition for new consumers await their implementation. Existing tree fading keeps its delivered timing and opacity. This does not add stacked bridge floors or change saved worlds.</p>
    <p><Link href="/references/design-decisions-september-4">Read the complete world-view and exploration decisions</Link></p>
  </section>;
}
