import Link from '@/components/wiki-link';

export function WorldViewDirection() {
  return <section className="article-section note-card">
    <h2>Three-quarter world view</h2>
    <p><strong>Current behavior:</strong> The existing Settings3D view and foreground fading are available. Build333 adds modular life and measured-water rules for newly written ordinary worlds; old worlds retain their generation. Movement, sight and harvesting remain governed by their existing rules. Artwork is partial.</p>
    <p><strong>Generation — current in333:</strong> plants and creatures are assembled in game when a world is written, from its actual traits and stable saved choices. Reusable parts are allowed; finished premade species are not the system. Dragon DNA’s independent part systems inform creature variation, with equivalent relevant modularity for flora. The reviewed system covers six creature layouts and five flora construction families; the old seven creature labels are not a limit on detail. Actual connected elevated water can form a waterfall into lower water; overlapping or disconnected pools cannot. These functional rules are delivered through the existing3D trial. Natural waterfall occurrence and finished procedural richness remain unverified.</p>
    <p><strong>Appearance — current in336:</strong> softer stripes, tapered woody supports, bowed branches and varied opposite/alternate broad-leaf angles are joined by fuller woody broad-leaf crowns above shorter bare supports. Counts, source traits/materials and old saved assemblies remain unchanged. Internal native specimens verify the refinements; the ordinary expedition contained fleshy flora, so no natural woody encounter or phone performance is claimed. Foliage remains clustered and finished richness is still incomplete.</p>
    <p><strong>New height-route decision — not in336:</strong> a direct step may rise or fall at most one elevation level. Most high ground needs a connected route from the entrance; a few unreachable scenic areas may show water and decorative vegetation but contain no animals or resource nodes. Existing worlds keep their earlier rules. This adds no jump, climbing, swimming or new menu.</p>
    <p><strong>Decided intended behavior:</strong> Keep the square grid while showing the fronts and height of trees, rocks, characters, and cliffs.</p>
    <ul className="compact-list">
      <li>Water belongs to its local bed and surface height. A low river and a pond on raised land can coexist; shallow water can show its visible bed.</li>
      <li>Legal steps and slopes connect different heights. A cliff does not become a walkable route because its artwork overlaps another square.</li>
      <li>With an appropriate Axe selected, target the reachable trunk base. A small base highlight and “Chop tree” identify the action, and the impact lands at the trunk.</li>
      <li>Foreground art covering the character fades partly, keeping a faint silhouette and the already-visible blocking base. Only the obstructing cliff face fades, not the whole plateau.</li>
      <li>Fading preserves fog, gameplay canopy concealment, and earned minimap knowledge. It exposes only the character and surroundings the game already allows you to see.</li>
    </ul>
    <p><strong>Accepted for later, low priority:</strong> Trees, elevated land, bushes, resource nodes, and the player character should have shadows. Their treatment follows the new geometry and foreground visibility, behind the playable overhaul. Dynamic lighting and a day/night system are not part of this decision.</p>
    <p><strong>Ordinary 3D trial — introduced in327, updated in333:</strong> Settings → Owner Tools → 3D Trials offers one normally generated expedition with its own saved test state, using the current starting setup and normal costs. North stays up and east stays right in the square-projected three-quarter view. Ordinary 2D stays available; placeholders are allowed. Existing movement, tools, encounters, visibility, memory and fading remain authoritative.</p>
    <p><strong>Build333 verification:</strong> one internal native ordinary expedition had four creature kinds and two flora kinds. Movement, an encounter, Withdraw, Continue and reopening passed; no usable harvest was reached. Its four water areas retained earlier presentation, so no natural waterfall was witnessed. A separate controlled native example verified a connected fall and shore slopes/steps. The phone update is installed and launches normally; your expedition was not played. Phone performance, complete material appearance, waterfall animation and finished organic artwork remain unverified or unfinished.</p>
    <p><strong>Earlier-world markers:</strong> build328 introduced rounded purple placeholders; existing worlds retain their earlier representation, while new worlds in333 use modular creatures. These are neutral markers, not species artwork or material colours. The isolated marker check adds no expedition or phone-performance evidence.</p>
    <p><strong>Build329 corrections:</strong> 3D tiles match the displayed 2D tile size, and opaque trees covering the player’s body or occupied tile participate in the existing fade, including remembered trees. The wood-colour trial menu entry is removed. Build330 now fills the normal Explore viewport at that same tile size, preserving clipping and knowledge limits. Installation and ordinary launch succeeded; supplied movement/reopen checks are Simulator evidence, with your visual acceptance still separate.</p>
    <p><strong>Approved water study — implementation pending:</strong> You approved a separate, clearly labelled example scene showing a raised shallow pond and a lower channel with their own water levels. It uses chosen example heights because existing saves lack measured water depths. Campaigns keep their current rules, and a visible surface reveals only a permitted bed. The decision is complete in <Link href="/references/aimee-homework">Aimee Homework</Link>; the existing-world camera trial continues alongside it.</p>
    <p><strong>Still to be worked out:</strong> Exact artwork sizes, composition, and fade timing follow a bounded in-game proof. This does not add stacked bridge floors or change saved worlds.</p>
    <p><Link href="/references/design-decisions-september-4">Read the complete world-view and exploration decisions</Link></p>
  </section>;
}
