import {economyIdentityContract,economyIdentityFixtures,economyIdentityCommands,economyIdentityKey,economyContextRows} from "./economy-identity-kit.js";
const canvas=document.getElementById("bridge-proof"),x=canvas.getContext("2d"),c={bg:"#171614",panel:"#24221f",line:"#625b51",ink:"#eee5d5",muted:"#aaa397",accent:"#d6a85f"};
function text(v,px,py,size=8,color=c.ink){x.fillStyle=color;x.font=`${size}px monospace`;x.fillText(v,px,py);}
function gray(commands){return commands.map(command=>({...command,color:"#"+(()=>{const n=parseInt(command.color.slice(1),16),v=Math.round(((n>>16)*.299+((n>>8)&255)*.587+(n&255)*.114));return [v,v,v].map(q=>q.toString(16).padStart(2,"0")).join("");})()}));}
function icon(commands,px,py,scale=1){for(const o of commands){x.fillStyle=o.color;x.fillRect(px+o.x*scale,py+o.y*scale,o.w*scale,o.h*scale);}}
const contexts=[["INVENTORY","identity present"],["TRADING POST","eligibility external"],["RECYCLER","provenance external"],["BLACKSMITH","requirements external"]];
function shortKind(identity){return({resourceStack:"resource",worldMaterialSpecimen:"material",ordinaryItem:"item",foundGear:"found",craftedGear:"crafted"})[identity.identityKind];}
function visibleHandle(identity,contextHandle){
  if(identity.identityKind==="worldMaterialSpecimen"&&contextHandle==="not individually transferable")return "not traded";
  return identity.identityKind==="worldMaterialSpecimen"?contextHandle:economyIdentityKey(identity).replace("InstanceID:","id ").replace("ResourceID:","pool ");
}
function half(ox,grayscale=false){text(grayscale?"LITERAL GRAYSCALE":"COLOR",ox+12,22,9,c.accent);text("FIVE DISTINCT ICONS · SAME PIXELS THROUGH EVERY CONTEXT",ox+12,40,7,c.muted);for(const [row,[label,note]] of contexts.entries()){const y=58+row*116,rows=economyContextRows(economyIdentityContract.contexts[row]);text(label,ox+12,y+11,7,c.accent);text(note,ox+220,y+11,6,c.muted);for(const [index,{identity,contextHandle}] of rows.entries()){const px=ox+12+index*72,py=y+20;x.fillStyle=c.panel;x.fillRect(px,py,66,88);x.strokeStyle=c.line;x.strokeRect(px+.5,py+.5,65,87);const commands=economyIdentityCommands(identity);icon(grayscale?gray(commands):commands,px+17,py+5,1);text(shortKind(identity),px+4,py+51,5,c.muted);text(visibleHandle(identity,contextHandle).slice(0,13),px+4,py+66,5,c.ink);text("same icon",px+4,py+80,5,c.accent);}}
  text("DETAIL OWNS KNOWN FACTS; GRID ICON NEVER INFERS PRICE / YIELD",ox+12,538,6,c.accent);economyIdentityFixtures.forEach((identity,index)=>{text(`${index+1}. ${identity.name}`,ox+12,560+index*24,7,c.ink);text(identity.resolvedDetail,ox+154,560+index*24,6,c.muted);});
  text("UNLABELED NATIVE 32PX ROW · SEPARATE KEY 1–5 ABOVE",ox+12,684,6,c.accent);economyIdentityFixtures.forEach((identity,index)=>icon(grayscale?gray(economyIdentityCommands(identity)):economyIdentityCommands(identity),ox+18+index*54,696,1));
}
function draw(){x.imageSmoothingEnabled=false;x.fillStyle=c.bg;x.fillRect(0,0,800,760);half(6,false);half(406,true);text("ASSET CORRESPONDENCE FIXTURE · INTEGRATION READY: FALSE · RULES OWN ACTIONS",18,744,7,c.accent);}
draw();
const evidence=[`${economyIdentityContract.evidenceRole}; integration ready: ${economyIdentityContract.integrationReady}`,"Player-facing collection language is world resources; there is no Sample category","Five exact identity kinds: pooled resource, individual world-material specimen, ordinary item, found gear, crafted gear","Rubble resource icon stays identical in Inventory, Trading Post, Recycler, and Blacksmith contexts","Fine glassy quill is a specific world material value; selection and preview handles remain context-owned","Lesser Salve is an ordinary identified non-gear item","Chipped Blade owns its initialized found gear profile and rules-resolved authored salvage route forged_edge_v1","Pointed Blade remains catalog fallback Chipped Blade but owns a tier-2 versioned pointed_blade gear profile and exact ordered construction receipt","Actions, eligibility, price, recovery and recipe requirements remain rules-owned and outside the icon","All five dominant 32px icons remain distinct in literal grayscale"];document.getElementById("bridge-accessible-list").replaceChildren(...evidence.map(v=>{const li=document.createElement("li");li.textContent=v;return li;}));
document.getElementById("save-bridge-proof").addEventListener("click",()=>canvas.toBlob(async blob=>{try{const response=await fetch("/__artifact?name=economy-five-identity-bridge-proof-v0.3.png",{method:"POST",headers:{"Content-Type":"image/png"},body:blob});if(!response.ok)throw new Error(await response.text());const result=await response.json();document.getElementById("bridge-status").textContent=`Saved ${result.path}`;}catch(error){document.getElementById("bridge-status").textContent=`Save failed: ${error.message}`;}} ,"image/png"));
