import {fitCommands,hash,canonicalJSON} from "./generator.js";
const rect=(x,y,w,h,color)=>({op:"rect",x,y,w,h,color});
const ink="#211d19",page="#fffaf0",edge="#8a693a",muted="#665f56",warn="#9b6546",ready="#62765c";
export const campaignVisualVersion="campaign-bookplate-1.0.0";
export const campaignHealth=Object.freeze(["valid","corrupt","futureIncompatible"]);
function uuidBytes(id){if(typeof id!=="string"||!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(id))throw new Error("invalid-campaign-uuid");return id.replaceAll("-","").match(/../g).map(v=>parseInt(v,16));}
export function campaignBookplateCommands(id){const b=uuidBytes(id),spineRight=b[0]%2===1,spineX=spineRight?22:7,bodyX=spineRight?5:10,c=[rect(3,2,26,28,edge),rect(5,4,22,24,page),rect(spineX,6,3,20,ink),rect(bodyX,7,12,2,muted),rect(bodyX,23,12,2,muted)];const groupTop=10+(b[1]%4);for(let i=0;i<3;i++)c.push(rect(bodyX,groupTop+i*3,5+(b[i+2]%8),1,i%2?edge:ink));c.push(rect(6+(b[5]%15),27,3+(b[6]%3),3,page));return fitCommands(c,32,32,1);}
export function healthMarkCommands(health){if(!campaignHealth.includes(health))throw new Error("invalid-campaign-health");if(health==="valid")return[rect(2,2,8,8,ready),rect(4,5,2,2,page),rect(6,3,2,4,page)];if(health==="corrupt")return[rect(2,2,8,8,warn),rect(5,3,2,4,page),rect(5,8,2,1,page)];return[rect(2,2,8,8,ink),rect(4,4,4,4,page),rect(5,2,2,8,muted)];}
function exactKeys(value,keys){if(!value||typeof value!=="object"||Array.isArray(value)||JSON.stringify(Object.keys(value).sort())!==JSON.stringify([...keys].sort()))throw new Error("invalid-campaign-slot-shape");}
export function resolveCampaignCard(slot){exactKeys(slot,["id","name","lastPlayedISO","binderLevel","location","progression","health","hasKnownMetadata"]);uuidBytes(slot.id);if(typeof slot.name!=="string"||!slot.name.trim()||slot.name.length>48)throw new Error("invalid-campaign-name");if(!campaignHealth.includes(slot.health)||typeof slot.hasKnownMetadata!=="boolean")throw new Error("invalid-campaign-state");if(slot.health==="valid"&&!slot.hasKnownMetadata)throw new Error("valid-campaign-requires-metadata");if(slot.hasKnownMetadata){if(!Number.isInteger(slot.binderLevel)||slot.binderLevel<1||slot.binderLevel>999)throw new Error("invalid-binder-level");if(typeof slot.location!=="string"||!slot.location.trim()||typeof slot.progression!=="string"||!slot.progression.trim())throw new Error("invalid-known-metadata");if(!Number.isFinite(Date.parse(slot.lastPlayedISO)))throw new Error("invalid-last-played");}else if(slot.binderLevel!==null||slot.location!==null||slot.progression!==null||slot.lastPlayedISO!==null)throw new Error("unknown-metadata-must-be-null");const statusLabel=slot.health==="valid"?"Ready":slot.health==="corrupt"?"Needs recovery":"From a newer version",actionLabel=slot.health==="valid"?"Load":slot.health==="corrupt"?"Recovery details":"Compatibility details";return{...slot,commands:[...campaignBookplateCommands(slot.id),...healthMarkCommands(slot.health)],canLoad:slot.health==="valid",statusLabel,actionLabel,accessibilityLabel:slot.hasKnownMetadata?`${slot.name}. ${statusLabel}. Last played ${slot.lastPlayedISO}. Level ${slot.binderLevel}. ${slot.location}. ${slot.progression}. ${actionLabel}`:`${slot.name}. ${statusLabel}. Not loadable. ${actionLabel}`};}
export function campaignPresentation(slots){if(!Array.isArray(slots))throw new Error("invalid-campaign-list");const cards=slots.map(resolveCampaignCard).sort((a,b)=>{if(a.hasKnownMetadata&&b.hasKnownMetadata)return Date.parse(b.lastPlayedISO)-Date.parse(a.lastPlayedISO)||a.id.localeCompare(b.id);if(a.hasKnownMetadata!==b.hasKnownMetadata)return a.hasKnownMetadata?-1:1;return a.id.localeCompare(b.id);});return{cards,continueID:cards.find(card=>card.canLoad)?.id??null,isEmpty:cards.length===0};}
export function deleteConfirmation(slot){const card=resolveCampaignCard(slot);return{title:`Delete “${card.name}”?`,message:"Only this campaign will be removed. Other campaigns will not be changed.",cancel:"Cancel",confirm:`Delete “${card.name}”`,id:card.id,accessibilityOrder:[`Delete ${card.name}?`,"Only this campaign will be removed. Other campaigns will not be changed.","Cancel",`Delete ${card.name}`]};}
export const campaignFixtureSlots=Object.freeze([Object.freeze({id:"11111111-1111-4111-8111-111111111111",name:"Mossbound",lastPlayedISO:"2026-08-11T15:10:00Z",binderLevel:4,location:"At Base",progression:"3 travellers · 2 stations",health:"valid",hasKnownMetadata:true}),Object.freeze({id:"22222222-2222-4222-8222-222222222222",name:"Quiet Test",lastPlayedISO:"2026-08-10T21:00:00Z",binderLevel:2,location:"In a world",progression:"2 travellers · 1 station",health:"valid",hasKnownMetadata:true}),Object.freeze({id:"33333333-3333-4333-8333-333333333333",name:"Damaged campaign",lastPlayedISO:null,binderLevel:null,location:null,progression:null,health:"corrupt",hasKnownMetadata:false}),Object.freeze({id:"44444444-4444-4444-8444-444444444444",name:"Newer campaign",lastPlayedISO:null,binderLevel:null,location:null,progression:null,health:"futureIncompatible",hasKnownMetadata:false})]);
export const campaignContractHash=()=>hash(canonicalJSON({version:campaignVisualVersion,slots:campaignFixtureSlots.map(resolveCampaignCard)}));
