import { fitCommands,hash } from "./generator.js";
const rect=(x,y,w,h,color)=>({op:"rect",x,y,w,h,color});
const authored=[
  ["mara","surveyor","wide","crop","coat","satchel","left","ochre"],["edren","archaeologist","round","crop","coat","scroll","right","moss"],["halloway","smith","solid","bun","apron","kit","right","ember"],["isolde","calligrapher","slender","wrap","robe","scroll","left","indigo"],["sela","wanderer","light","loose","scarf","satchel","right","moss"],["tovin","binder","mantled","hood","mantle","scroll","left","indigo"],["bryn","warden","solid","crop","coat","kit","left","moss"],["orsa","keeper","round","loose","apron","satchel","right","ochre"],["vance","appraiser","wide","brim","coat","satchel","left","indigo"],["talin","blade","slender","crop","scarf","none","right","ember"],["nessa","apothecary","round","wrap","apron","kit","left","moss"],["corrin","tanner","wide","braid","apron","kit","right","ochre"],["dagg","hammer","solid","crop","coat","none","left","ember"],["rook","spear","tall","crest","coat","satchel","right","moss"],["lys","archivist","slender","bun","robe","scroll","left","indigo"],["bracken","armorer","solid","hood","apron","kit","right","moss"],["fen","bowyer","tall","loose","coat","kit","left","ochre"],["wren","skirmisher","light","crest","scarf","satchel","right","ember"],["kestrel","hunter","wide","brim","scarf","kit","left","moss"],["maud","weaponsmith","solid","wrap","apron","none","right","ember"],["marrick","formation","wide","crop","mantle","scroll","left","indigo"],["sabine","menagerist","round","loose","coat","satchel","right","ochre"],["grimmond","delver","solid","brim","mantle","kit","left","moss"],["oda","channelwright","tall","braid","robe","kit","right","indigo"],["auber","distiller","round","wrap","robe","satchel","left","ochre"],["ashe","emanation","mantled","crest","mantle","none","right","ember"],["perren","interpreter","slender","hood","robe","scroll","left","moss"],["nine","continuity","mantled","bun","mantle","scroll","right","indigo"]
];
export const namedCharacterCatalogue=Object.freeze(authored.map(([id,calling,build,hair,garment,carry,asymmetry,personalPalette])=>Object.freeze({id,calling,descriptor:Object.freeze({build,hair,garment,carry,asymmetry,personalPalette})})));
// Working review descriptor only. Noll is intentionally not promoted into the accepted named
// catalogue until Aimee reviews the current name/pronouns/identity direction.
export const provisionalNollDescriptor=Object.freeze({build:"light",hair:"wrap",garment:"coat",carry:"none",asymmetry:"right",personalPalette:"ochre",authoredVariant:"nollWrap"});
export const characterProfiles=Object.freeze({world:{width:16,height:16,camera:"compact-upright-proof"},baseSide:{width:16,height:16,camera:"village-side-view"},mapTopDown:{width:16,height:16,camera:"straight-top-down"},combat:{width:48,height:48,camera:"side-biased"}});
export const binderTemplate=Object.freeze({build:"wide",hair:"hood",garment:"mantle",carry:"scroll",asymmetry:"left",personalPalette:"indigo"});
export const gearReach=Object.freeze({blade:"close",spear:"mid",bow:"far"});
export const mapFacings=Object.freeze(["north","east","south","west"]);
export const mapTopDownContract=Object.freeze({integrationFacingProfile:"mapTopDown",legacyUprightProfile:"world",camera:"straight-top-down",occlusion:"crown-over-upper-back",facePlane:false,ownershipOverlay:"game-owned",bounds:16});
const palettes={ochre:{skin:"#c99b72",cloth:"#76553b",accent:"#65aaa3"},moss:{skin:"#b98f6d",cloth:"#536c4d",accent:"#c08b61"},ember:{skin:"#c69272",cloth:"#7b4537",accent:"#d2a35f"},indigo:{skin:"#b99078",cloth:"#555978",accent:"#a27eaf"}};
function gradedPalette(p,grade){if(grade==="neutral")return p;const shift=grade==="warm"?[10,2,-8]:[-8,3,12];return Object.fromEntries(Object.entries(p).map(([key,value])=>{const n=parseInt(value.slice(1),16),rgb=[n>>16,(n>>8)&255,n&255].map((channel,i)=>Math.max(0,Math.min(255,channel+shift[i])));return[key,`#${rgb.map(channel=>channel.toString(16).padStart(2,"0")).join("")}`];}));}
function worldGradedPalette(p,grade){if(!grade)return p;const shifts=[grade.red,grade.green,grade.blue].map(Number),value=Number(grade.value);if(!shifts.every(Number.isFinite)||!Number.isFinite(value))throw new Error("invalid-character-world-grade");return Object.fromEntries(Object.entries(p).map(([key,color])=>{const n=parseInt(color.slice(1),16),rgb=[n>>16,(n>>8)&255,n&255].map((channel,i)=>Math.max(0,Math.min(255,Math.round(channel+shifts[i]+value))));return[key,`#${rgb.map(channel=>channel.toString(16).padStart(2,"0")).join("")}`];}));}
const outline="#1b1817",metal="#bdc2bc";
const choices={build:["slender","light","round","wide","solid","tall","mantled"],hair:["crop","bun","braid","loose","crest","wrap","hood","brim"],garment:["coat","apron","robe","scarf","mantle"],carry:["none","satchel","scroll","kit"],asymmetry:["left","right"],personalPalette:["ochre","moss","ember","indigo"]};
const structuralAxes=["build","hair","garment","carry","asymmetry"],structuralCapacity=structuralAxes.reduce((n,key)=>n*choices[key].length,1),namedSignatures=new Set(namedCharacterCatalogue.map(person=>JSON.stringify(person.descriptor)));
function descriptorAt(index,paletteIndex){const descriptor={};let cursor=index;for(const key of structuralAxes){descriptor[key]=choices[key][cursor%choices[key].length];cursor=Math.floor(cursor/choices[key].length);}descriptor.personalPalette=choices.personalPalette[paletteIndex%choices.personalPalette.length];return descriptor;}
export function generatedCharacterDescriptor(seed){const raw=typeof seed==="number"&&Number.isSafeInteger(seed)?Math.abs(seed):parseInt(hash(String(seed)),16),start=(raw*2654435761)>>>0,paletteIndex=parseInt(hash(`${seed}:personal-palette`),16);for(let offset=0;offset<structuralCapacity;offset++){const descriptor=descriptorAt((start+offset)%structuralCapacity,paletteIndex+offset);if(!namedSignatures.has(JSON.stringify(descriptor)))return Object.freeze(descriptor);}throw new Error("generated-character-descriptor-space-exhausted");}
export function characterDescriptor(identity,{generatedSeed=null}={}){const named=namedCharacterCatalogue.find(person=>person.id===identity);if(named)return named.descriptor;if(identity==="generated_person"&&generatedSeed!=null)return generatedCharacterDescriptor(generatedSeed);throw new Error(`unknown-character-identity:${identity}`);}
const widthFor=build=>({slender:5,light:6,round:8,wide:9,solid:10,tall:6,mantled:9}[build]??7);
function worldIdentity(c,d,p){const bw=widthFor(d.build),x=Math.floor((16-bw)/2);c.push(rect(6,3,4,3,outline),rect(7,4,2,1,p.skin),rect(x,6,bw,3,outline),rect(x+1,7,bw-2,5,p.cloth),rect(5,12,2,3,outline),rect(9,12,2,3,outline));if(d.hair==="bun")c.push(rect(7,1,3,2,p.accent));if(d.hair==="braid")c.push(rect(d.asymmetry==="left"?4:10,3,2,5,p.accent));if(d.hair==="loose")c.push(rect(4,3,2,5,p.accent),rect(10,3,2,5,p.accent));if(d.hair==="crest")c.push(rect(7,0,2,3,p.accent));if(d.hair==="wrap")c.push(rect(5,2,6,2,p.accent));if(d.hair==="hood")c.push(rect(4,2,8,5,p.accent));if(d.hair==="brim")c.push(rect(3,2,10,2,p.accent));if(d.garment==="apron")c.push(rect(6,8,4,5,p.accent));if(d.garment==="robe")c.push(rect(4,10,8,4,p.accent));if(d.garment==="scarf")c.push(rect(5,6,6,2,p.accent));if(d.garment==="mantle")c.push(rect(3,6,10,3,p.accent));if(d.carry!=="none"){const cx=d.asymmetry==="left"?2:12;c.push(rect(cx,8,d.carry==="scroll"?2:3,d.carry==="kit"?4:3,p.accent));}}
function baseSideIdentity(c,d,p){const wide=Math.max(6,Math.min(9,widthFor(d.build))),torsoX=5;c.push(rect(7,2,5,4,outline),rect(8,3,4,2,p.skin),rect(torsoX,6,wide,3,outline),rect(torsoX+1,7,wide-2,5,p.cloth),rect(6,12,3,4,outline),rect(11,12,3,4,outline),rect(12,4,2,2,outline));if(d.hair==="brim")c.push(rect(4,1,10,2,p.accent));else if(d.hair==="hood")c.push(rect(6,1,7,5,p.accent));else if(d.hair==="wrap"&&d.authoredVariant==="nollWrap")c.push(rect(7,0,4,1,p.accent),rect(6,1,6,2,p.accent),rect(12,2,2,2,p.accent));else if(d.hair==="wrap")c.push(rect(6,1,7,2,p.accent));else if(d.hair==="bun")c.push(rect(6,1,3,2,p.accent));else if(d.hair==="loose")c.push(rect(6,2,2,5,p.accent));else if(d.hair==="braid")c.push(rect(5,3,2,6,p.accent));else if(d.hair==="crest")c.push(rect(8,0,2,3,p.accent));if(d.garment==="apron")c.push(rect(7,8,4,5,p.accent));if(d.garment==="robe")c.push(rect(5,10,8,4,p.accent));if(d.garment==="scarf")c.push(rect(6,6,6,2,p.accent));if(d.garment==="mantle")c.push(rect(4,6,9,3,p.accent));if(d.authoredVariant==="nollWrap")c.push(rect(14,8,2,3,outline));else if(d.carry!=="none")c.push(rect(d.asymmetry==="left"?2:13,8,d.carry==="scroll"?2:3,d.carry==="kit"?4:3,p.accent));}
function mapTopDownIdentity(c,d,p){const shoulder=Math.max(6,Math.min(10,widthFor(d.build))),sx=Math.floor((16-shoulder)/2),left=d.asymmetry==="left";c.push(rect(6,1,4,1,outline),rect(5,2,6,3,outline),rect(6,5,4,2,outline),rect(6,2,4,3,p.accent),rect(7,5,2,1,p.accent),rect(7,6,2,2,p.skin),rect(sx,7,shoulder,4,outline),rect(sx+1,8,shoulder-2,3,p.cloth),rect(left?sx-2:sx+shoulder,8,2,3,outline),rect(left?sx+shoulder:sx-2,9,2,2,outline),rect(5,11,6,3,outline),rect(6,11,4,2,p.cloth),rect(5,14,2,2,outline),rect(9,14,2,2,outline));if(d.hair==="bun")c.push(rect(7,0,3,2,p.accent));if(d.hair==="braid")c.push(rect(left?3:11,3,2,5,p.accent));if(d.hair==="loose")c.push(rect(4,2,2,5,p.accent),rect(10,2,2,5,p.accent));if(d.hair==="crest")c.push(rect(7,0,2,3,p.accent));if(d.hair==="wrap"&&d.authoredVariant==="nollWrap")c.push(rect(6,0,4,1,p.accent),rect(5,1,6,2,p.accent),rect(10,2,2,2,p.accent));else if(d.hair==="wrap")c.push(rect(4,1,8,3,p.accent));if(d.hair==="hood")c.push(rect(6,0,4,2,p.accent),rect(5,2,6,3,p.accent),rect(6,5,4,3,p.accent));if(d.hair==="brim")c.push(rect(2,2,12,2,p.accent));if(d.garment==="apron")c.push(rect(7,9,2,4,p.accent));if(d.garment==="robe")c.push(rect(4,11,8,3,p.accent),rect(5,14,2,2,outline),rect(9,14,2,2,outline));if(d.garment==="scarf")c.push(rect(sx+1,7,shoulder-2,2,p.accent));if(d.garment==="mantle")c.push(rect(sx,7,shoulder,2,p.accent),rect(sx+2,9,Math.max(2,shoulder-4),2,p.accent));if(d.build==="mantled")c.push(rect(4,11,8,2,outline),rect(5,11,6,1,p.cloth));if(d.carry!=="none"){const cx=left?Math.max(0,sx-3):Math.min(13,sx+shoulder+1);c.push(rect(cx,8,d.carry==="scroll"?2:3,d.carry==="kit"?4:3,p.accent));}}
function faceMapCommands(commands,facing){if(!mapFacings.includes(facing))throw new Error(`unknown-map-facing:${facing}`);if(facing==="north")return commands;return commands.map(command=>{const {x,y,w,h}=command;if(facing==="east")return{...command,x:16-y-h,y:x,w:h,h:w};if(facing==="south")return{...command,x:16-x-w,y:16-y-h};return{...command,x:y,y:16-x-w,w:h,h:w};});}
function combatIdentity(c,d,p){const bw=widthFor(d.build)+10,x=24-Math.floor(bw/2),headY=d.build==="tall"?2:4;c.push(rect(18,headY,12,12,outline),rect(20,headY+2,8,8,p.skin),rect(x,15,bw,7,outline),rect(x+2,18,bw-4,19,p.cloth),rect(x-3,20,4,15,outline),rect(x+bw-1,20,4,15,outline),rect(x+3,37,5,10,outline),rect(x+bw-8,37,5,10,outline));if(d.hair==="bun")c.push(rect(22,0,8,5,p.accent));if(d.hair==="braid")c.push(rect(d.asymmetry==="left"?14:30,7,5,17,p.accent));if(d.hair==="loose")c.push(rect(13,6,5,18,p.accent),rect(30,6,5,18,p.accent));if(d.hair==="crest")c.push(rect(22,0,5,7,p.accent));if(d.hair==="wrap"&&d.authoredVariant==="nollWrap")c.push(rect(20,2,10,3,p.accent),rect(18,5,14,4,p.accent),rect(30,8,4,4,p.accent));else if(d.hair==="wrap")c.push(rect(15,3,18,5,p.accent));if(d.hair==="hood")c.push(rect(13,2,22,17,p.accent));if(d.hair==="brim")c.push(rect(10,3,28,5,p.accent));if(d.garment==="apron")c.push(rect(19,22,10,16,p.accent));if(d.garment==="robe")c.push(rect(x,31,bw,12,p.accent));if(d.garment==="scarf")c.push(rect(15,14,20,6,p.accent));if(d.garment==="mantle")c.push(rect(x-3,15,bw+6,10,p.accent));if(d.authoredVariant==="nollWrap")c.push(rect(x+bw+5,23,3,8,outline));else if(d.carry!=="none"){const cx=d.asymmetry==="left"?x-7:x+bw+1;c.push(rect(cx,24,d.carry==="scroll"?4:7,d.carry==="kit"?13:9,p.accent));}}
function passedOutCommands(profile,d,p,gear){if(profile==="world"){const length=8+Math.floor(widthFor(d.build)/3),c=[rect(1,9,length,4,outline),rect(2,10,length-2,2,p.cloth),rect(1+length,8,3,4,outline),rect(2+length,9,2,2,p.skin),rect(d.asymmetry==="left"?2:7,7,3,2,p.accent),rect(4,13,5,2,outline)];if(["bun","crest","brim","hood"].includes(d.hair))c.push(rect(1+length,6,d.hair==="brim"?4:2,2,p.accent));if(d.garment==="robe"||d.garment==="mantle")c.push(rect(3,8,5,2,p.accent));if(gear!=="none")c.push(rect(1,15,gear==="bow"?9:gear==="spear"?12:6,1,metal));return fitCommands(c,16,16,0);}const bodyLength=22+widthFor(d.build),headX=Math.min(37,5+bodyLength),accentX=d.asymmetry==="left"?9:22,c=[rect(5,28,bodyLength,10,outline),rect(7,30,bodyLength-4,6,p.cloth),rect(headX,26,10,11,outline),rect(headX+1,28,7,7,p.skin),rect(accentX,27,9,5,p.accent),rect(8,38,13,5,outline),rect(24,38,12,5,outline)];if(d.hair==="bun")c.push(rect(headX+5,23,5,4,p.accent));if(d.hair==="braid")c.push(rect(headX+8,33,5,10,p.accent));if(d.hair==="loose")c.push(rect(headX-2,25,4,13,p.accent));if(d.hair==="crest")c.push(rect(headX+3,21,4,7,p.accent));if(d.hair==="wrap")c.push(rect(headX-1,25,12,4,p.accent));if(d.hair==="hood")c.push(rect(headX-2,24,14,14,p.accent));if(d.hair==="brim")c.push(rect(headX-3,24,16,4,p.accent));if(d.garment==="coat")c.push(rect(12,27,4,12,p.accent));if(d.garment==="robe")c.push(rect(8,35,16,6,p.accent));if(d.garment==="mantle")c.push(rect(7,27,18,6,p.accent));if(d.garment==="apron")c.push(rect(17,27,8,11,p.accent));if(d.garment==="scarf")c.push(rect(headX-3,32,6,4,p.accent));if(d.carry!=="none"){const cx=d.asymmetry==="left"?2:31;if(d.carry==="satchel")c.push(rect(cx,38,8,7,p.accent));if(d.carry==="scroll")c.push(rect(cx,37,4,9,p.accent));if(d.carry==="kit")c.push(rect(cx,40,10,5,p.accent));}if(gear==="blade")c.push(rect(8,45,22,2,metal));if(gear==="spear")c.push(rect(5,44,34,2,metal));if(gear==="bow")c.push(rect(3,43,42,2,metal),rect(7,46,34,1,outline));if(gear==="lightArmor")c.push(rect(12,29,13,7,metal));if(gear==="heavyArmor")c.push(rect(9,27,20,11,metal));return fitCommands(c,48,48,0);}
export function characterCommands(identity,{profile="world",generatedSeed=null,gear="none",pose="neutral",descriptor=null,environmentGrade="neutral",worldGrade=null,facing="north"}={}){const d=descriptor??characterDescriptor(identity,{generatedSeed}),p=worldGradedPalette(gradedPalette(palettes[d.personalPalette]??palettes.ochre,environmentGrade),worldGrade),c=[];if(!characterProfiles[profile])throw new Error(`unknown-character-profile:${profile}`);if(pose==="passedOut")return passedOutCommands(profile==="combat"?"combat":"world",d,p,gear);if(profile==="world")worldIdentity(c,d,p);else if(profile==="baseSide")baseSideIdentity(c,d,p);else if(profile==="mapTopDown")mapTopDownIdentity(c,d,p);else combatIdentity(c,d,p);if(profile!=="combat"){if(["blade","spear","bow"].includes(gear))c.push(rect(gear==="spear"?13:12,gear==="bow"?4:2,gear==="spear"?2:3,gear==="spear"?9:8,metal));if(["lightArmor","heavyArmor"].includes(gear))c.push(rect(5,8,6,gear==="heavyArmor"?5:3,metal));const fitted=fitCommands(c,16,16,0);return profile==="mapTopDown"?faceMapCommands(fitted,facing):fitted;}if(gear==="blade")c.push(rect(38,15,3,24,metal));if(gear==="spear")c.push(rect(39,10,3,30,metal));if(gear==="bow")c.push(rect(38,5,3,38,metal),rect(43,10,2,28,outline));if(gear==="lightArmor")c.push(rect(18,22,12,9,metal));if(gear==="heavyArmor")c.push(rect(14,19,20,17,metal),rect(11,20,5,12,metal));return fitCommands(c,48,48,0);}
export function silhouetteHash(commands){return hash(commands.map(({x,y,w,h})=>({x,y,w,h})));}
export function identityHash(identity,profile="world"){return silhouetteHash(characterCommands(identity,{profile}));}
