import { defaults,cloneDescriptor,creatureCommands,presets,renderCommands } from "./generator.js";
import { floraDefaults,floraCommands } from "./world-generator.js";
import { combatFixture,combatMetrics,actorPosition,validateCombatFixture,combatStageVersion } from "./combat-generator.js";
const sheet=document.getElementById("combat-sheet"),ctx=sheet.getContext("2d"),descriptors={};for(const [name,traits] of Object.entries(presets)){const descriptor=cloneDescriptor(defaults);descriptor.traits=cloneDescriptor(traits);descriptors[name]=descriptor;}
function sprite(actor){const canvas=document.createElement("canvas");canvas.width=canvas.height=48;if(actor.kind==="unknown"){const c=canvas.getContext("2d");c.fillStyle="#2a3032";c.fillRect(12,15,24,25);c.fillRect(18,8,12,8);c.fillStyle="#d9ddd8";c.font="bold 20px monospace";c.fillText("?",18,34);}else renderCommands(canvas.getContext("2d"),48,48,actor.kind==="active-flora"?floraCommands({...floraDefaults,traits:{...floraDefaults.traits,defenceType:"active",defence:90}},"hostile"):creatureCommands(descriptors[actor.kind],"fight"));return canvas;}
function stageBackground(c,x,y){c.fillStyle="#263033";c.fillRect(x,y,combatMetrics.width,combatMetrics.height);c.fillStyle="#334044";for(let row=0;row<5;row++)c.fillRect(x,y+combatMetrics.laneYs[row]+47,combatMetrics.width,1);c.fillStyle="#405052";c.fillRect(x+104,y,8,combatMetrics.height);c.fillStyle="#797167";c.font="8px monospace";c.fillText("BACK",x+4,y+14);c.fillText("FRONT",x+48,y+14);c.fillText("FRONT",x+120,y+14);c.fillText("BACK",x+164,y+14);}
function stateMarks(c,x,y,actor){const s=actor.state;if(s.selected){c.strokeStyle="#f2ead7";c.lineWidth=2;c.strokeRect(x+2,y+2,44,44);c.setLineDash([3,2]);c.strokeRect(x+5,y+5,38,38);c.setLineDash([]);}if(s.legal){c.strokeStyle="#d6a85f";c.lineWidth=2;c.beginPath();c.moveTo(x+24,y);c.lineTo(x+47,y+24);c.lineTo(x+24,y+47);c.lineTo(x+1,y+24);c.closePath();c.stroke();}if(s.cannotReach){c.strokeStyle="#e5e0d6";c.lineWidth=3;c.beginPath();c.moveTo(x+5,y+5);c.lineTo(x+16,y+16);c.moveTo(x+32,y+32);c.lineTo(x+43,y+43);c.moveTo(x+43,y+5);c.lineTo(x+32,y+16);c.moveTo(x+16,y+32);c.lineTo(x+5,y+43);c.stroke();}if(s.protected){c.fillStyle="#172126";c.fillRect(x+17,y-3,14,10);c.strokeStyle="#d7ddd8";c.lineWidth=2;c.beginPath();c.moveTo(x+18,y-2);c.lineTo(x+30,y-2);c.lineTo(x+30,y+3);c.lineTo(x+24,y+7);c.lineTo(x+18,y+3);c.closePath();c.stroke();}}
function reachOf(actor){return actor.kind==="active-flora"||actor.kind==="unknown"?"close":descriptors[actor.kind].traits.reach;}
function drawSelectedReach(c,stageX,stageY,actor){const p=actorPosition(actor),reach=reachOf(actor),steps={close:1,mid:2,far:3}[reach],direction=actor.side==="party"?1:-1,start=stageX+p.x+(direction>0?48:0),boundary=stageX+(actor.side==="party"?{close:112,mid:156,far:208}[reach]:{close:104,mid:60,far:8}[reach]),laneY=stageY+p.y+24;c.strokeStyle="#f2ead7";c.fillStyle="#f2ead7";c.lineWidth=1;c.beginPath();c.moveTo(start,laneY);c.lineTo(boundary,laneY);c.stroke();for(let index=0;index<steps;index++)c.fillRect(boundary+index*direction*3,laneY-6-index*2,1,12+index*4);c.font="bold 8px monospace";c.fillText(reach[0].toUpperCase(),boundary+direction*(steps*3+3)-(direction<0?6:0),laneY+3);}
function renderStage(target,x,y,mode){stageBackground(target,x,y);const fixture=combatFixture(mode),selected=fixture.actors.find(actor=>actor.state.selected);if(selected)drawSelectedReach(target,x,y,selected);for(const actor of fixture.actors){const p=actorPosition(actor),actorSprite=sprite(actor);target.save();if(actor.side==="foe"&&actor.kind!=="unknown"){target.translate(x+p.x+48,0);target.scale(-1,1);target.drawImage(actorSprite,0,y+p.y);}else target.drawImage(actorSprite,x+p.x,y+p.y);target.restore();stateMarks(target,x+p.x,y+p.y,actor);}}
function render(){ctx.fillStyle="#171614";ctx.fillRect(0,0,sheet.width,sheet.height);renderStage(ctx,6,12,"5v3");renderStage(ctx,234,12,"5v3");renderStage(ctx,6,360,"2v1");renderStage(ctx,234,360,"2v1");const image=ctx.getImageData(234,0,222,708);for(let i=0;i<image.data.length;i+=4){const value=Math.round(image.data[i]*.2126+image.data[i+1]*.7152+image.data[i+2]*.0722);image.data[i]=image.data[i+1]=image.data[i+2]=value;}ctx.putImageData(image,234,0);const issues=[...validateCombatFixture(combatFixture("5v3")),...validateCombatFixture(combatFixture("2v1"))];document.getElementById("combat-diagnostics").textContent=issues.length?issues.join(" · "):`${combatStageVersion} · fixtures valid · 44px targets`;}
function pixelHash(canvas){const bytes=canvas.getContext("2d").getImageData(0,0,canvas.width,canvas.height).data;let hash=0x811c9dc5;for(const byte of bytes){hash^=byte;hash=Math.imul(hash,0x01000193);}return(hash>>>0).toString(16).padStart(8,"0");}
function manifest(){return{schemaVersion:1,stageVersion:combatStageVersion,versions:{creatureSchemaVersion:3,floraSchemaVersion:1,combatSchemaVersion:1,grammarVersion:"combat-stage-0.3.0",compositorVersion:"browser-canvas-0.2.0"},metrics:combatMetrics,fixtures:[combatFixture("5v3"),combatFixture("2v1")],output:{profile:"static-combat-review",file:"assetlab-combat-stage-proof.png",pixelWidth:sheet.width,pixelHeight:sheet.height,colorSpace:"sRGB",format:"RGBA PNG",pixelHash:pixelHash(sheet)}};}
function download(name,blob){const link=document.createElement("a"),url=URL.createObjectURL(blob);link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
document.getElementById("export-combat").addEventListener("click",()=>sheet.toBlob(blob=>download("assetlab-combat-stage-proof.png",blob),"image/png"));
document.getElementById("export-combat-manifest").addEventListener("click",()=>download("assetlab-combat-stage-manifest.json",new Blob([JSON.stringify(manifest(),null,2)],{type:"application/json"})));
render();
