import crypto from "node:crypto";
export const TILE=16,MACRO=64;
export const styleGrounds=Object.freeze(["stone","soil","sand","ice","ash","water","deepWater","rubble","mud","growth","chasm","groundcover"]);
export const semanticRoles=Object.freeze(["deepShadow","bodyDark","body","bodyLight","highlight"]);
export const directions=Object.freeze(["north","east","south","west"]);
export const sourceCrops=Object.freeze({stone:{sheet:"accepted",x:12,y:12,width:313,height:313},soil:{sheet:"accepted",x:452,y:12,width:353,height:313},deepWater:{sheet:"accepted",x:826,y:12,width:322,height:313},water:{sheet:"accepted",x:12,y:571,width:313,height:314},groundcover:{sheet:"accepted",x:452,y:571,width:353,height:315},growth:{sheet:"accepted",x:826,y:571,width:322,height:315},sand:{sheet:"expansion",x:14,y:14,width:362,height:340},ice:{sheet:"expansion",x:394,y:14,width:363,height:340},ash:{sheet:"expansion",x:779,y:14,width:362,height:340},rubble:{sheet:"expansion",x:1160,y:14,width:362,height:340},mud:{sheet:"expansion",x:14,y:526,width:362,height:340},chasm:{sheet:"expansion",x:394,y:526,width:363,height:340},snow:{sheet:"expansion",x:779,y:526,width:362,height:340}});
export const roleNeutralRGBA=Object.freeze([[28,31,32,255],[62,66,65,255],[104,107,103,255],[151,153,145,255],[205,205,190,255]]);
export const baseRoleColors=Object.freeze({stone:["#282e30","#495153","#6d7674","#929a94","#c0c4b8"],soil:["#36261e","#573a28","#795337","#a0764d","#c7a475"],sand:["#5c482d","#80653d","#aa8954","#ceb174","#ead49b"],ice:["#496675","#688896","#91aeb7","#bed0d1","#edf3eb"],ash:["#202125","#3e3e42","#666368","#918b8c","#bbb4b0"],coverAsh:["#16171a","#292a2d","#3f3f43","#59575b","#747176"],water:["#10333f","#1b5260","#30747c","#58a0a0","#91c8bd"],deepWater:["#071d2b","#0e3345","#194e5e","#2b6b76","#55939a"],rubble:["#292725","#4b4742","#6f6861","#968d82","#c0b5a7"],mud:["#241a15","#443026","#654a38","#8b6b50","#b09170"],groundcover:["#263423","#3d512e","#5b703d","#80904f","#a9b46c"],growth:["#12271c","#203d27","#345c32","#568043","#86a65b"],chasm:["#02040a","#0a0e18","#171d29","#303746","#555d68"],snow:["#88979c","#aab7b7","#cbd4cf","#e4e9df","#fffdf0"]});
export const sha256=bytes=>crypto.createHash("sha256").update(bytes).digest("hex");
const exact=(o,keys,label)=>{if(!o||typeof o!=="object"||Array.isArray(o)||Object.keys(o).sort().join()!==[...keys].sort().join())throw Error(`invalid-${label}-fields`);};
export function normalizeStyleRequest(raw){exact(raw,["ground","point","visualSeed","featureVariant","cardinalNeighbors","edgeContourIDs","paletteID","motionPhase"],"style-request");exact(raw.point,["x","y"],"point");exact(raw.cardinalNeighbors,directions,"neighbors");exact(raw.edgeContourIDs,directions,"contours");if(!styleGrounds.includes(raw.ground)||!Number.isInteger(raw.point.x)||!Number.isInteger(raw.point.y)||!Number.isInteger(raw.visualSeed)||raw.visualSeed<0||!Number.isInteger(raw.featureVariant)||raw.featureVariant<0||raw.featureVariant>3||typeof raw.paletteID!=="string"||!raw.paletteID||!Number.isInteger(raw.motionPhase)||raw.motionPhase<0||raw.motionPhase>3)throw Error("invalid-style-request");for(const d of directions)if(!["same","unknown",...styleGrounds].includes(raw.cardinalNeighbors[d])||!Number.isInteger(raw.edgeContourIDs[d])||raw.edgeContourIDs[d]<0||raw.edgeContourIDs[d]>3)throw Error("invalid-style-edge");return structuredClone(raw);}
export function rgbaToRoleMap(rgba,width=MACRO,height=MACRO){if(rgba.length!==width*height*4)throw Error("invalid-source-rgba");const out=new Uint8Array(width*height);for(let i=0;i<out.length;i++){const p=i*4,l=rgba[p]*.2126+rgba[p+1]*.7152+rgba[p+2]*.0722;out[i]=l<45?0:l<85?1:l<130?2:l<185?3:4;}return out;}
export function roleMapToNeutralRGBA(roles){const out=new Uint8ClampedArray(roles.length*4);for(let i=0;i<roles.length;i++)out.set(roleNeutralRGBA[roles[i]],i*4);return out;}
const hex=v=>[parseInt(v.slice(1,3),16),parseInt(v.slice(3,5),16),parseInt(v.slice(5,7),16),255];
export function recolorRoleMap(roles,palette){if(!Array.isArray(palette)||palette.length!==5)throw Error("invalid-semantic-palette");const colors=palette.map(v=>Array.isArray(v)?[...v,255].slice(0,4):hex(v)),out=new Uint8ClampedArray(roles.length*4);for(let i=0;i<roles.length;i++)out.set(colors[roles[i]],i*4);return out;}
const mirror=(v,size,on)=>on?size-1-v:v;
export function macroRoleAt(roleMap,point,px,py,featureVariant=0){if(roleMap.length!==MACRO*MACRO)throw Error("invalid-macro-role-map");const bx=Math.floor(point.x/4),by=Math.floor(point.y/4),mx=((point.x%4)+4)%4,my=((point.y%4)+4)%4,flipX=((bx+featureVariant)&1)===1,flipY=((by+(featureVariant>>1))&1)===1,x=mirror(mx*16+px,64,flipX),y=mirror(my*16+py,64,flipY);return roleMap[y*64+x];}
export const contourProfiles=Object.freeze([[0,0,1,1,2,2,1,0,0,1,2,1,1,0,0,0],[1,2,2,1,0,0,1,2,1,0,0,1,2,2,1,0],[0,1,2,2,1,0,0,0,1,1,2,2,1,0,0,1],[2,1,0,0,1,2,2,1,0,0,1,2,1,0,1,2]]);
const priority={chasm:0,deepWater:1,water:2,stone:3,ice:3,rubble:3,soil:4,sand:4,ash:4,mud:4,groundcover:5,growth:6};
const edgeDepth=(i,id)=>1+contourProfiles[id][i];
function inEdge(d,x,y,id){return d==="north"?y<edgeDepth(x,id):d==="south"?y>=16-edgeDepth(x,id):d==="west"?x<edgeDepth(y,id):x>=16-edgeDepth(y,id);}
export function composeRoleTile(request,roleMaps){const r=normalizeStyleRequest(request),map=roleMaps[r.ground];if(!map)throw Error("missing-ground-role-map");const out=new Uint8Array(256);for(let y=0;y<16;y++)for(let x=0;x<16;x++)out[y*16+x]=macroRoleAt(map,r.point,x,y,r.featureVariant);for(const d of directions){const n=r.cardinalNeighbors[d];if(n==="same"||n==="unknown"||n===r.ground)continue;if(!roleMaps[n])throw Error("missing-neighbor-role-map");const depth=r.ground==="deepWater"&&n==="water",accepts=(r.ground==="groundcover"&&n==="growth")||priority[n]>priority[r.ground];if(!depth&&!accepts)continue;for(let y=0;y<16;y++)for(let x=0;x<16;x++)if(inEdge(d,x,y,r.edgeContourIDs[d]))out[y*16+x]=depth?Math.max(3,out[y*16+x]):macroRoleAt(roleMaps[n],r.point,x,y,r.featureVariant);}return out;}
export function motionRoleOverlay(request){const r=normalizeStyleRequest(request),out=new Int8Array(256).fill(-1);if(!["water","deepWater","groundcover","growth"].includes(r.ground))return out;const phase=(r.motionPhase+r.featureVariant)%4,sets={water:[[2,5,3,5],[8,11,9,11]],deepWater:[[3,8,5,8]],groundcover:[[4,10,4,9],[11,4,12,4]],growth:[[5,11,5,10],[10,5,11,5]]}[r.ground];for(const [x0,y0,x1,y1] of sets){const dx=phase===1?1:phase===3?-1:0,dy=phase===2?-1:0;for(let x=Math.min(x0,x1);x<=Math.max(x0,x1);x++){const y=Math.round(y0+(y1-y0)*(x-Math.min(x0,x1))/Math.max(1,Math.abs(x1-x0))),xx=x+dx,yy=y+dy;if(xx>=0&&yy>=0&&xx<16&&yy<16)out[yy*16+xx]=4;}}return out;}
export function compositeRGBA(request,roleMaps,palette){const roles=composeRoleTile(request,roleMaps),rgba=recolorRoleMap(roles,palette),motion=motionRoleOverlay(request);for(let i=0;i<motion.length;i++)if(motion[i]>=0)rgba.set(Array.isArray(palette[motion[i]])?[...palette[motion[i]],255].slice(0,4):hex(palette[motion[i]]),i*4);return{roles,rgba,motion};}
export function snowCoverageRoles(sourceRoles){if(sourceRoles.length!==MACRO*MACRO)throw Error("invalid-snow-role-map");const out=new Int8Array(sourceRoles.length);for(let i=0;i<sourceRoles.length;i++)out[i]=sourceRoles[i]<2?-1:sourceRoles[i];return out;}
export function applySnowCover(baseRGBA,snowRoles,point,featureVariant,palette){if(baseRGBA.length!==1024||snowRoles.length!==4096)throw Error("invalid-snow-composite");const out=new Uint8ClampedArray(baseRGBA),colors=palette.map(v=>Array.isArray(v)?[...v,255].slice(0,4):hex(v));for(let y=0;y<16;y++)for(let x=0;x<16;x++){const role=macroRoleAt(snowRoles,point,x,y,featureVariant);if(role>=0)out.set(colors[role],(y*16+x)*4);}return out;}
export const applySurfaceCover=applySnowCover;
export function applySurfaceDeposits(baseRGBA,roles,point,featureVariant,{snow=false,ash=false,snowPalette,ashPalette,maximumCoverage=.70}={}){if(!snow&&!ash)return new Uint8ClampedArray(baseRGBA);const out=new Uint8ClampedArray(baseRGBA),limit=Math.floor(256*maximumCoverage),owned=new Uint8Array(256);let count=0;const apply=(enabled,offset,palette)=>{if(!enabled)return;const colors=palette.map(v=>Array.isArray(v)?[...v,255].slice(0,4):hex(v));for(let y=0;y<16;y++)for(let x=0;x<16;x++){const i=y*16+x,role=macroRoleAt(roles,point,x,y,featureVariant+offset);if(role<0||owned[i]||count>=limit)continue;out.set(colors[role],i*4);owned[i]=1;count++;}};apply(snow,0,snowPalette);apply(ash,1,ashPalette);return out;}
export const geometrySignature=roles=>sha256(Buffer.from(roles));
