import {hash} from "./generator.js";
export const mixedInkCandidateVersion="mixed-ink-candidate-0.1.0";
export const mixedInkPresets=Object.freeze({red:Object.freeze({cyan:0,magenta:82,yellow:78,depth:12}),yellow:Object.freeze({cyan:0,magenta:4,yellow:88,depth:5}),green:Object.freeze({cyan:72,magenta:0,yellow:76,depth:10}),cyan:Object.freeze({cyan:82,magenta:0,yellow:3,depth:7}),blue:Object.freeze({cyan:76,magenta:68,yellow:0,depth:14}),violet:Object.freeze({cyan:48,magenta:78,yellow:0,depth:12}),neutralDark:Object.freeze({cyan:68,magenta:68,yellow:68,depth:76})});
const keys=["cyan","magenta","yellow","depth"],exact=(v,expected,label)=>{if(!v||typeof v!=="object"||Array.isArray(v)||JSON.stringify(Object.keys(v).sort())!==JSON.stringify([...expected].sort()))throw new Error(`invalid-${label}-fields`);};
export function normalizeInkRecipe(value){exact(value,[...keys,"conversionVersion"],"ink-recipe");if(value.conversionVersion!==mixedInkCandidateVersion)throw new Error("mixed-ink-version-mismatch");const result={};for(const key of keys){if(!Number.isInteger(value[key])||value[key]<0||value[key]>100)throw new Error(`invalid-ink-channel:${key}`);result[key]=value[key];}if(keys.every(k=>result[k]===0))throw new Error("no-colored-ink-mixed");return Object.freeze({...result,conversionVersion:value.conversionVersion});}
export function inkRecipeFromPreset(id){const p=mixedInkPresets[id];if(!p)throw new Error(`unknown-ink-preset:${id}`);return normalizeInkRecipe({...p,conversionVersion:mixedInkCandidateVersion});}
export function convertInkRecipe(value){const r=normalizeInkRecipe(value),paper=[236,228,210],d=1-r.depth/100*.78,channels=[paper[0]*(1-r.cyan/100*.82)*d,paper[1]*(1-r.magenta/100*.79)*d,paper[2]*(1-r.yellow/100*.84)*d].map(n=>Math.max(12,Math.min(244,Math.round(n)))),patternID=["crosshatch","diagonal","stippling","strata"][hash(JSON.stringify(r))%4];return Object.freeze({srgb:Object.freeze(channels),patternID,conversionVersion:r.conversionVersion,description:describeInk(channels,r)});}
function describeInk([red,green,blue],r){const max=Math.max(red,green,blue),min=Math.min(red,green,blue),depth=max<70?"deep":max>180?"pale":r.depth>55?"dark":"muted";let hue;if(max-min<20)hue="neutral";else if(red>=green&&red>=blue)hue=green>blue*1.3?"orange-red":blue>green*1.25?"violet-red":"red";else if(green>=red&&green>=blue)hue=blue>red*1.25?"blue-green":red>blue*1.25?"yellow-green":"green";else hue=red>green*1.25?"violet":"blue";return `${depth} ${hue}`;}
export function resolveInkWell(request){exact(request,["version","unlock","mode","recipe","savedMixtures","selectedSourceID"],"ink-well-request");if(request.version!==mixedInkCandidateVersion||!["locked","inkMixing"].includes(request.unlock)||!["ash","mixed"].includes(request.mode))throw new Error("invalid-ink-well-request");if(request.mode==="ash"&&request.recipe!==null)throw new Error("ash-must-have-nil-recipe");if(request.mode==="mixed"&&request.recipe===null)throw new Error("mixed-ink-requires-recipe");if(request.unlock==="locked"&&request.mode!=="ash")throw new Error("ink-mixing-not-unlocked");if(!Array.isArray(request.savedMixtures))throw new Error("invalid-saved-mixtures");if(request.unlock==="locked"&&request.savedMixtures.length)throw new Error("locked-mixer-has-saved-mixtures");const recipe=request.recipe&&normalizeInkRecipe(request.recipe),converted=recipe&&convertInkRecipe(recipe),unlocked=request.unlock==="inkMixing";return Object.freeze({evidenceRole:"assetlabMixerProposal",integrationReady:false,unlock:request.unlock,unlockOwner:"Isolde's Scriptorium · Ink mixing after Brush",mode:request.mode,storedAuthorship:recipe,preview:recipe?Object.freeze({...converted,label:`Mixed ink · ${converted.description}`}):Object.freeze({srgb:Object.freeze([32,30,28]),patternID:"ash-open",label:"Ash · Color left open"}),selectedSourceID:request.selectedSourceID,actions:Object.freeze({openMixer:unlocked,useForNextFocus:unlocked,applyToSelectedFocus:unlocked&&request.selectedSourceID!==null,saveMixture:unlocked&&recipe!==null,returnToAsh:unlocked&&request.mode==="mixed"}),accessibility:Object.freeze({label:recipe?`${converted.description} mixed ink`:`Ash ink, color left open`,value:recipe?`Cyan ${recipe.cyan}, Magenta ${recipe.magenta}, Yellow ${recipe.yellow}, Depth ${recipe.depth}`:"No explicit color instruction"})});}
