import {provisionalNollDescriptor,characterCommands} from "./character-kit.js";
import {distinctStationCommands} from "./place-kit.js";
import {tileContentCommands} from "./tile-content.js";
import {resourceWorldCommands} from "./resource-kit.js";

const canvas=document.getElementById("noll-proof"),x=canvas.getContext("2d"),c={bg:"#171614",panel:"#24221f",line:"#625b51",ink:"#eee5d5",muted:"#aaa397",accent:"#d6a85f"};
function text(v,px,py,size=8,color=c.ink){x.fillStyle=color;x.font=`${size}px monospace`;x.fillText(v,px,py);}
function draw(commands,px,py,scale=1,gray=false){x.save();if(gray)x.filter="grayscale(1)";for(const o of commands){x.fillStyle=o.color;x.fillRect(px+o.x*scale,py+o.y*scale,o.w*scale,o.h*scale);}x.restore();}
const noll=(profile,facing="north")=>characterCommands("provisional_noll",{profile,facing,descriptor:provisionalNollDescriptor});
function card(px,py,label,commands,scale=4,gray=false){x.fillStyle=c.panel;x.fillRect(px,py,116,116);x.strokeStyle=c.line;x.strokeRect(px+.5,py+.5,115,115);text(label,px+7,py+15,7,c.accent);draw(commands,px+26,py+27,scale,gray);}
function collisionRow(ox,oy){const entries=[noll("mapTopDown","north"),tileContentCommands({type:"traveller",revealed:true,discovered:true}),tileContentCommands({type:"wildDrop",revealed:true,discovered:true}),tileContentCommands({type:"portal",revealed:true,discovered:true}),tileContentCommands({type:"site",revealed:true,discovered:true}),...['salt','mercury','gold','quartz','adamant'].map(id=>resourceWorldCommands(id,{environment:'stone'})),resourceWorldCommands('rift_glass',{environment:'unstable'})];for(const [i,commands] of entries.entries()){x.fillStyle=i%2?"#262421":"#201f1d";x.fillRect(ox+i*32,oy,28,54);draw(commands,ox+6+i*32,oy+4,1,true);draw(commands,ox+2+i*32,oy+23,1.5,true);}}
function half(ox,gray=false){text(gray?"LITERAL GRAYSCALE":"COLOR",ox+12,24,9,c.accent);text("WORKING ART · NOT ACCEPTED CAST CANON",ox+12,42,7,c.muted);for(const [i,facing] of ["north","east","south","west"].entries())card(ox+12+(i%3)*122,58+Math.floor(i/3)*122,`MAP ${facing.toUpperCase()}`,noll("mapTopDown",facing),4,gray);card(ox+134,180,"BASE SIDE",noll("baseSide"),4,gray);card(ox+256,180,"COMBAT",noll("combat"),1.3,gray);text("IDENTITY COLLISION · VANCE / NOLL / HALLOWAY",ox+12,320,7,c.accent);for(const [i,id] of ["vance","provisional_noll","halloway"].entries()){const d=id==="provisional_noll"?noll("baseSide"):characterCommands(id,{profile:"baseSide"});card(ox+12+i*122,336,id==="provisional_noll"?"NOLL · WORKING":id.toUpperCase(),d,4,gray);}text("STAFFING DOES NOT CHANGE RECYCLER GEOMETRY",ox+12,470,7,c.accent);draw(distinctStationCommands("recycler",{palette:"warm"}),ox+22,492,3,gray);draw(distinctStationCommands("recycler",{palette:"warm"}),ox+190,492,3,gray);draw(noll("baseSide"),ox+246,544,2,gray);text("UNSTAFFED",ox+22,612,7,c.muted);text("NOLL AS SEPARATE OCCUPANT",ox+190,612,7,c.muted);text("No tool limbs · no coin eyes · no Recycler-shaped body",ox+12,640,7,c.muted);text("Placeholder: light build · compact wrap/knot · coat · free hands",ox+12,660,7,c.muted);}
function render(){x.imageSmoothingEnabled=false;x.fillStyle=c.bg;x.fillRect(0,0,800,840);half(6,false);half(406,true);text("UNLABELED NATIVE-GRAYSCALE COLLISION · NOLL FIRST",18,690,8,c.accent);collisionRow(18,706);text("SEPARATE KEY: Noll · traveller · drop · portal · site · salt · mercury · gold · quartz · adamant · Rift-glass",18,772,6,c.muted);text("PROVISIONAL NOLL · NAME / PRONOUNS / ART REMAIN REVIEWABLE",18,824,8,c.accent);}
render();
const evidence=["Provisional Noll descriptor is not part of the accepted 28-person catalogue","Working name Noll and they/them pronouns remain reviewable","Map view is straight top-down in north, east, south and west facings","Base uses village side view; combat uses accepted side-biased profile","Vance, Noll and Halloway remain distinct in literal grayscale","Noll remains a person outside the Recycler and an independent occupant when staffing it","Recycler geometry is identical staffed and unstaffed","No profession-derived anatomy, coin eyes, tool limbs or Recycler-shaped body"];document.getElementById("noll-accessible-list").replaceChildren(...evidence.map(v=>{const li=document.createElement("li");li.textContent=v;return li;}));
document.getElementById("save-noll-proof").addEventListener("click",()=>canvas.toBlob(async blob=>{try{const response=await fetch("/__artifact?name=provisional-noll-identity-proof-v0.2.png",{method:"POST",headers:{"Content-Type":"image/png"},body:blob});if(!response.ok)throw new Error(await response.text());const result=await response.json();document.getElementById("noll-status").textContent=`Saved ${result.path}`;}catch(error){document.getElementById("noll-status").textContent=`Save failed: ${error.message}`;}} ,"image/png"));
