import { renderCommands } from "./generator.js";
import { stationCatalogue,siteCatalogue,distinctStationCommands,physicalSiteCommands,siteOccupantCommands } from "./place-kit.js";
const byId=id=>document.getElementById(id),stations=byId("station-proof"),sites=byId("site-proof"),proof=byId("place-review-proof"),economyProof=byId("economy-station-proof");
function tile(commands,width,height){const canvas=document.createElement("canvas");canvas.width=width;canvas.height=height;renderCommands(canvas.getContext("2d"),width,height,commands);return canvas;}
function heading(context,text,x,y){context.fillStyle="#d8bd82";context.font="8px monospace";context.fillText(text,x,y);}
function label(context,text,x,y){context.fillStyle="#eee5d5";context.font="6px monospace";context.fillText(text,x,y);}
function gray(source){const canvas=document.createElement("canvas");canvas.width=source.width;canvas.height=source.height;const context=canvas.getContext("2d");context.drawImage(source,0,0);const image=context.getImageData(0,0,canvas.width,canvas.height);for(let i=0;i<image.data.length;i+=4){const value=Math.round(image.data[i]*.2126+image.data[i+1]*.7152+image.data[i+2]*.0722);image.data[i]=image.data[i+1]=image.data[i+2]=value;}context.putImageData(image,0,0);return canvas;}
function siteStateTile(state){const commands=[...physicalSiteCommands("signal_cairn",{state})];if(state==="guarded")commands.push(...siteOccupantCommands("guard"));return tile(commands,16,16);}
function drawStations(){const context=stations.getContext("2d");context.imageSmoothingEnabled=false;context.fillStyle="#171614";context.fillRect(0,0,stations.width,stations.height);heading(context,"WARM HOME SUBSTRATE",8,10);heading(context,"COLD ADAPTATION · IDENTICAL SILHOUETTES",304,10);stationCatalogue.forEach((entry,index)=>{const col=index%6,row=Math.floor(index/6),x=8+col*48,y=18+row*68;context.drawImage(tile(distinctStationCommands(entry.id,{palette:"warm",tier:2}),48,36),x,y);context.drawImage(tile(distinctStationCommands(entry.id,{palette:"cold",tier:2}),48,36),304+col*48,y);label(context,entry.id.slice(0,11),x,y+44);});}
function drawEconomyProof(){const context=economyProof.getContext("2d"),ids=["trading_post","recycler","storehouse","workshop","blacksmith"],states=[{state:"built",tier:1},{state:"built",tier:3},{state:"damaged",tier:1}];context.imageSmoothingEnabled=false;context.fillStyle="#171614";context.fillRect(0,0,economyProof.width,economyProof.height);heading(context,"UNLABELED NATIVE GRAYSCALE · WHOLE-MASS COLLISION",8,11);ids.forEach((id,index)=>{context.drawImage(gray(tile(distinctStationCommands(id,{palette:"warm"}),48,36)),8+index*92,18);label(context,String(index+1),29+index*92,61);});heading(context,"TRADING POST / RECYCLER · BUILT → TIER STRESS → DAMAGED",8,82);states.forEach((options,index)=>{context.drawImage(tile(distinctStationCommands("trading_post",options),48,36),8+index*56,90);context.drawImage(tile(distinctStationCommands("recycler",options),48,36),244+index*56,90);});label(context,"1 trading_post · 2 recycler · 3 storehouse · 4 workshop · 5 blacksmith",8,146);label(context,"staffing is a separate occupant; station geometry does not change",8,160);heading(context,"SHARED PRE-IDENTITY FOUNDATION · IDENTITY BEGINS WHEN BUILT",8,180);context.drawImage(tile(distinctStationCommands("trading_post",{state:"foundation"}),48,36),8,185);context.drawImage(tile(distinctStationCommands("recycler",{state:"foundation"}),48,36),64,185);label(context,"same lawful foundation; never use it to identify station kind",124,205);}
function drawSites(){const context=sites.getContext("2d");context.imageSmoothingEnabled=false;context.fillStyle="#171614";context.fillRect(0,0,sites.width,sites.height);heading(context,"WARM TOP-DOWN",8,10);heading(context,"ASH ADAPTATION · SAME PROFILE",184,10);siteCatalogue.forEach((entry,index)=>{const col=index%5,row=Math.floor(index/5),x=8+col*34,y=18+row*44;context.drawImage(tile(physicalSiteCommands(entry.id,{palette:"warm"}),16,16),x,y,32,32);context.drawImage(tile(physicalSiteCommands(entry.id,{palette:"ash"}),16,16),184+col*34,y,32,32);label(context,String(index+1).padStart(2,"0"),x+10,y+39);});}
function drawReview(){const context=proof.getContext("2d");context.imageSmoothingEnabled=false;context.fillStyle="#171614";context.fillRect(0,0,proof.width,proof.height);heading(context,"AUTHORED PLACE IDENTITY · PROCEDURAL PALETTE/WEAR ONLY",8,11);context.drawImage(stations,24,18,592,236);context.drawImage(sites,140,260,360,156);label(context,"18 SIDE-VIEW VILLAGE STATIONS",24,416);label(context,"15 TOP-DOWN WORLD SITES",448,416);heading(context,"STATION LIFECYCLE",24,432);["foundation","built","built","damaged"].forEach((state,index)=>context.drawImage(tile(distinctStationCommands("workshop",{state,tier:index===2?3:1}),48,36),24+index*56,438));label(context,"foundation  built  tier 3  damaged",24,482);heading(context,"SITE LIFECYCLE",312,432);["unsearched","searched","exhausted","guarded"].forEach((state,index)=>context.drawImage(siteStateTile(state),312+index*42,438,32,32));label(context,"unsearched searched exhausted guard occupant",312,482);heading(context,"UNLABELED NATIVE GRAYSCALE · COLLISION GROUPS",24,502);const ids=["constellation","survey_post","reliquary","anchorage","storehouse","workshop","blacksmith","distillery","channelworks"],states=[{state:"built",tier:1},{state:"built",tier:3},{state:"damaged",tier:1}];states.forEach((options,row)=>{label(context,["BUILT","TIER 3","DAMAGED"][row],2,526+row*48);ids.forEach((id,index)=>context.drawImage(gray(tile(distinctStationCommands(id,options),48,36)),48+index*64,510+row*48));});}
drawStations();drawEconomyProof();drawSites();drawReview();
byId("save-place-proof").addEventListener("click",()=>proof.toBlob(async blob=>{try{const response=await fetch("/__artifact?name=place-identity-adaptation-proof-v0.4.png",{method:"POST",headers:{"Content-Type":"image/png"},body:blob});if(!response.ok)throw new Error(await response.text());const result=await response.json();byId("place-status").textContent=`Saved ${result.path}`;}catch(error){byId("place-status").textContent=`Save failed: ${error.message}`;}},"image/png"));
byId("save-economy-place-proof").addEventListener("click",()=>economyProof.toBlob(async blob=>{try{const response=await fetch("/__artifact?name=economy-stations-proof-v0.1.png",{method:"POST",headers:{"Content-Type":"image/png"},body:blob});if(!response.ok)throw new Error(await response.text());const result=await response.json();byId("economy-place-status").textContent=`Saved ${result.path}`;}catch(error){byId("economy-place-status").textContent=`Save failed: ${error.message}`;}},"image/png"));
