import { defaults,cloneDescriptor,creatureCommands,presets,renderCommands,hash,canonicalJSON } from "./generator.js";
import { floraDefaults,floraCommands,transitionedTerrainCommands } from "./world-generator.js";
import { combatFixture,combatMetrics } from "./combat-generator.js";
import { rasterHash } from "./regression.js";

const byId=id=>document.getElementById(id),sheet=byId("golden-sheet"),context=sheet.getContext("2d");
const fixtures=[];
for(const [name,traits] of Object.entries(presets)){const descriptor=cloneDescriptor(defaults);descriptor.traits=cloneDescriptor(traits);for(const [profile,size] of [["world",16],["fight",48]])fixtures.push({key:`creature/${name}/${profile}`,name:`${name} · ${profile}`,size,commands:creatureCommands(descriptor,profile)});}
const floraFixtures={ordinary:floraDefaults,low_spreading:{...floraDefaults,speciesSeed:71,traits:{...floraDefaults.traits,stature:18,habit:"spreading"}},active:{...floraDefaults,speciesSeed:72,traits:{...floraDefaults.traits,defenceType:"active",defence:90}}};
for(const [name,descriptor] of Object.entries(floraFixtures))for(const [profile,size] of [["world",16],["detail",48],["hostile",48]])fixtures.push({key:`flora/${name}/${profile}`,name:`flora ${name} · ${profile}`,size,commands:floraCommands(descriptor,profile)});
for(const ground of ["soil","water","deepWater"])for(const adjacency of [0,5,10,15])fixtures.push({key:`terrain/${ground}/${adjacency}`,name:`${ground} · mask ${adjacency}`,size:16,commands:transitionedTerrainCommands({ground,adjacency,revealed:true,terrainSeedUInt32:404})});
fixtures.push({key:"terrain/fog",name:"fog · empty",size:16,commands:transitionedTerrainCommands({ground:"water",revealed:false})},{key:"terrain/crack",name:"soil · crack",size:16,commands:transitionedTerrainCommands({ground:"soil",revealed:true,cracking:true})});
const contracts=[{key:"combat/metrics",name:"combat metrics",contractHash:hash(canonicalJSON(combatMetrics))},...[["5v3",combatFixture("5v3")],["2v1",combatFixture("2v1")]].map(([mode,value])=>({key:`combat/${mode}/contract`,name:`combat ${mode} contract`,contractHash:hash(canonicalJSON(value))}))];

function draw(){context.fillStyle="#171614";context.fillRect(0,0,sheet.width,sheet.height);context.imageSmoothingEnabled=false;const columns=6,cellWidth=128,cellHeight=96;[...fixtures,...contracts].forEach((fixture,index)=>{const x=index%columns*cellWidth,y=Math.floor(index/columns)*cellHeight;context.fillStyle="#2b2925";context.fillRect(x+4,y+4,cellWidth-8,cellHeight-8);if(fixture.commands){const scratch=document.createElement("canvas");scratch.width=fixture.size;scratch.height=fixture.size;renderCommands(scratch.getContext("2d"),fixture.size,fixture.size,fixture.commands);const scale=fixture.size===16?3:1,drawSize=fixture.size*scale;context.drawImage(scratch,x+(cellWidth-drawSize)/2,y+8,drawSize,drawSize);}else{context.strokeStyle="#d6a85f";context.lineWidth=2;context.strokeRect(x+42,y+14,44,44);context.fillStyle="#d6a85f";context.font="bold 18px ui-monospace, monospace";context.fillText("JSON",x+43,y+43);}context.fillStyle="#eee8dc";context.font="9px ui-monospace, monospace";const label=fixture.name.length>20?`${fixture.name.slice(0,19)}…`:fixture.name;context.fillText(label,x+8,y+76);context.fillStyle="#aaa397";context.fillText(fixture.contractHash??rasterHash(fixture.commands,fixture.size,fixture.size),x+8,y+88);});}
function download(name,blob){const link=document.createElement("a"),url=URL.createObjectURL(blob);link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
let report={};
async function check(){const baseline=await fetch("fixtures/golden-v1.json").then(response=>{if(!response.ok)throw new Error(`baseline ${response.status}`);return response.json();}),current=Object.fromEntries([...fixtures.map(fixture=>[fixture.key,rasterHash(fixture.commands,fixture.size,fixture.size)]),...contracts.map(fixture=>[fixture.key,fixture.contractHash])]),keys=new Set([...Object.keys(baseline.hashes),...Object.keys(current)]),changes=[...keys].sort().filter(key=>baseline.hashes[key]!==current[key]).map(key=>({key,before:baseline.hashes[key]??null,after:current[key]??null}));report={baselineVersion:baseline.baselineVersion,checked:Object.keys(current).length,changed:changes.length,changes};byId("golden-result").textContent=changes.length?`${changes.length} changed output${changes.length===1?"":"s"}`:"Golden baseline matches";byId("golden-result").className=changes.length?"review-bad":"review-good";byId("golden-note").textContent=changes.length?"Review every changed tile or contract before accepting a new baseline.":"All canonical rasters and semantic contracts match golden-v1.";byId("golden-counts").textContent=`${report.checked} checked · baseline v${report.baselineVersion}`;byId("golden-changes").textContent=JSON.stringify(changes,null,2);}
byId("export-golden-png").addEventListener("click",()=>sheet.toBlob(blob=>download("assetlab-golden-review-v1.png",blob),"image/png"));
byId("export-golden-report").addEventListener("click",()=>download("assetlab-golden-report-v1.json",new Blob([JSON.stringify(report,null,2)],{type:"application/json"})));
draw();check().catch(error=>{byId("golden-result").textContent="Baseline check failed";byId("golden-note").textContent=error.message;});
