import {bugReporterContract,bugReporterFixture,reporterSceneCommands,localSaveResult,transportResult} from "./bug-reporter-kit.js";

const canvas=document.getElementById("reporter-proof"),x=canvas.getContext("2d"),c={bg:"#171614",panel:"#25231f",line:"#6a6257",ink:"#eee5d5",muted:"#aaa397",accent:"#d8aa62",map:"#55452f",route:"#ddbf70",good:"#8ca879",warn:"#c58d63"};
function text(v,px,py,size=8,color=c.ink){x.fillStyle=color;x.font=`${size}px monospace`;x.fillText(v,px,py);}
function box(px,py,w,h,fill=c.panel,stroke=c.line){x.fillStyle=fill;x.fillRect(px,py,w,h);x.strokeStyle=stroke;x.strokeRect(px+.5,py+.5,w-1,h-1);}
function button(px,py,w,label,enabled=true){box(px,py,w,38,enabled?"#6f542d":"#45433f",enabled?c.accent:c.line);text(label,px+12,py+24,8,enabled?c.ink:c.muted);}
function sceneImage(gray=false){const image=document.createElement("canvas");image.width=366;image.height=180;const q=image.getContext("2d");q.fillStyle="#20201d";q.fillRect(0,0,366,180);for(let row=0;row<5;row++)for(let col=0;col<10;col++){q.fillStyle=(row+col)%3?c.map:"#665039";q.fillRect(8+col*35,7+row*33,34,32);}for(const command of reporterSceneCommands){q.fillStyle=command.color;q.fillRect(command.x,command.y,command.w,command.h);}if(gray){const g=document.createElement("canvas");g.width=366;g.height=180;const z=g.getContext("2d");z.filter="grayscale(1)";z.drawImage(image,0,0);return g;}return image;}
function scene(px,py,gray=false){x.drawImage(sceneImage(gray),px,py);x.strokeStyle=c.line;x.strokeRect(px+.5,py+.5,365,179);text("CAPTURED · SHARED SCENE PIXELS",px+14,py+172,7,c.ink);}
function floating(px,py,gray=false){x.save();if(gray)x.filter="grayscale(1)";box(px,py,52,52,"#302b25",c.accent);x.fillStyle=c.accent;x.fillRect(px+13,py+14,26,18);x.fillStyle="#302b25";x.fillRect(px+18,py+18,16,2);x.fillRect(px+18,py+23,11,2);text("BUG",px+15,py+45,7,c.ink);x.restore();}
function placementStrip(px,py,gray=false){x.save();if(gray)x.filter="grayscale(1)";for(const [i,label] of ["BASE","WORLD","COMBAT"].entries()){const ox=px+i*120;box(ox,py,112,76,"#20201d");x.fillStyle=c.line;x.fillRect(ox+7,py+52,98,16);x.strokeStyle=c.ink;x.strokeRect(ox+7.5,py+52.5,97,15);x.fillStyle=c.accent;x.fillRect(ox+(i===1?8:87),py+(i===2?7:26),18,18);text(label,ox+7,py+16,6);text("44PT ACTION",ox+12,py+64,5,c.ink);}text("re-clamped free edge · Move Report Bug accessibility action",px,py+90,6,c.muted);x.restore();}
function sheet(px,py,gray=false,large=false){x.save();if(gray)x.filter="grayscale(1)";box(px,py,366,large?376:330);text("REPORT A BUG · PROPOSED",px+14,py+24,11,c.accent);text("Proposed pre-sheet capture ownership · not native-tested",px+14,py+42,7,c.muted);box(px+14,py+55,96,62,"#37352f");x.drawImage(sceneImage(gray),0,0,366,180,px+17,py+58,90,56);text("What happened?  required",px+124,py+70,8);box(px+124,py+80,226,large?76:58,"#171614");text("Route vanished behind",px+132,py+99,large?9:8);text("the raised tile.",px+132,py+116,large?9:8);const next=large?170:152;text("What did you expect?  optional",px+14,py+next,8);box(px+14,py+next+10,336,large?52:42,"#171614");text("Route stays visible on its surface.",px+22,py+next+29,large?9:8);const contextY=next+(large?78:65);text("Included: screenshot · build · screen · world · 20 actions",px+14,py+contextY,7,c.muted);text("Remove screenshot",px+14,py+contextY+20,7,c.accent);button(px+14,py+contextY+34,104,"Cancel");button(px+238,py+contextY+34,112,"Save report");x.restore();}
function formInsets(px,py,gray=false){x.save();if(gray)x.filter="grayscale(1)";box(px,py,178,96);text("CAPTURE UNAVAILABLE",px+8,py+16,6,c.warn);box(px+8,py+24,42,26,"#37352f");text("Route overlaps tile",px+58,py+37,6);text("text remains valid",px+58,py+49,5,c.muted);button(px+82,py+56,88,"Save",true);box(px+188,py,178,96);text("REQUIRED TEXT EMPTY",px+196,py+16,6,c.warn);box(px+196,py+24,162,26,"#171614");text("Describe what happened",px+196,py+62,6,c.warn);button(px+270,py+56,88,"Save",false);x.restore();}
function queue(px,py,gray=false){x.save();if(gray)x.filter="grayscale(1)";box(px,py,366,126);text("UNTRIAGED · bug-map-route-0017",px+14,py+24,9,c.accent);text("PROPOSED: Saved on this phone",px+14,py+47,9,c.good);text("UNSENT · proposed local outbox · not native-tested",px+14,py+67,7,c.muted);button(px+14,py+78,116,"View report");button(px+226,py+78,124,"Share / export");x.restore();}
function stateStrip(px,py,gray=false){x.save();if(gray)x.filter="grayscale(1)";const states=[["UNSENT","local safe",c.good],["SENDING","same ID",c.accent],["SUBMITTED","acknowledged",c.good],["NEEDS ATTENTION","still local",c.warn]];for(const [i,s] of states.entries()){box(px+i*90,py,84,70);text(s[0],px+5+i*90,py+19,6,s[2]);text(s[1],px+5+i*90,py+39,6,c.muted);x.fillStyle=s[2];x.fillRect(px+5+i*90,py+52,20,4);}x.restore();}
function half(ox,gray=false){text(gray?"LITERAL GRAYSCALE":"COLOR · 390PT",ox+12,18,8,c.accent);placementStrip(ox+12,30,gray);scene(ox+12,132,gray);floating(ox+314,144,gray);text("READY = CAPTURED PIXELS + REPORTER OVERLAY · PROPOSED",ox+12,328,7,c.muted);sheet(ox+12,344,gray,false);formInsets(ox+12,682,gray);queue(ox+12,790,gray);stateStrip(ox+12,928,gray);text("NEEDS ATTENTION owns Retry · SUBMITTED owns acknowledgement",ox+12,1008,6,c.muted);text("LARGE TEXT · SCROLL/REFLOW SAMPLE, NOT RUNTIME ACCEPTANCE",ox+12,1026,7,c.accent);box(ox+12,1038,366,104);text("What happened?",ox+24,1063,10);text("Route vanished behind the raised tile.",ox+24,1089,9);text("Save report",ox+254,1124,9,c.ink);text("RELEASE: control absent visually + accessibility",ox+12,1152,6,c.muted);}
function draw(){x.imageSmoothingEnabled=false;x.fillStyle=c.bg;x.fillRect(0,0,800,1175);half(6,false);half(406,true);text("PROPOSED FIXTURE · DEBUG ONLY · NO LIVE CAPTURE / PERSISTENCE / TRANSPORT CLAIM",18,1170,7,c.accent);}
draw();
const saved=localSaveResult(bugReporterFixture),attention=transportResult({...bugReporterFixture,state:"unsent"},{acknowledged:false}),states=[`${bugReporterContract.evidenceRole}; native integration ready: ${bugReporterContract.integrationReady}`,"Proposed floating Report Bug control is DEBUG-only, movable, and at least 44 points","Proposed captured scene uses the same scene commands as Ready after excluding only the reporter overlay","What happened is required; expected outcome and screenshot are optional","Captured context is bounded and lists its categories","Proposed local save result: "+saved.message+"; queue "+saved.queue,"Unsent is the proposed durable-local state; native persistence is not tested here","Retry belongs only to Needs attention and preserves the same stable BugReportID","Proposed transport failure result: "+attention.message,"Submitted is reserved for configured destination acknowledgement","Large text is a reflow sample; runtime scrolling and VoiceOver remain native gates","Grayscale preserves controls and states"];document.getElementById("reporter-accessible-list").replaceChildren(...states.map(v=>{const li=document.createElement("li");li.textContent=v;return li;}));
document.getElementById("save-reporter-proof").addEventListener("click",()=>canvas.toBlob(async blob=>{try{const response=await fetch("/__artifact?name=debug-bug-reporter-proof-v0.3.png",{method:"POST",headers:{"Content-Type":"image/png"},body:blob});if(!response.ok)throw new Error(await response.text());const result=await response.json();document.getElementById("reporter-status").textContent=`Saved ${result.path}`;}catch(error){document.getElementById("reporter-status").textContent=`Save failed: ${error.message}`;}} ,"image/png"));
