import {fitCommands,hash} from "./generator.js";const rect=(x,y,w,h,color)=>({op:"rect",x,y,w,h,color});
const rows=[
  ["rubble","node","mineral","heap"],["clay","node","mineral","mound"],["ore","node","mineral","vein"],["copper","node","mineral","nodules"],["silver","node","mineral","seam"],["gold","node","mineral","seam"],["quartz","node","mineral","crystal"],["obsidian","node","mineral","shard"],["salt","node","mineral","crystal"],["sulfur","node","mineral","nodules"],["mercury","node","mineral","pool"],["adamant","node","mineral","core"],
  ["fiber","node","flora","harvest"],["timber","node","flora","harvest"],["pulp","node","flora","harvest"],["resin","deposit","exudate","exudate"],["toxin","node","flora","harvest"],["spore","node","flora","harvest"],["reagent","node","flora","harvest"],["ichor","deposit","deposit","pool"],["rift_glass","node","unstableSubstrate","shard"],["essence_raw","wildDrop","energy","drop"],["mote","realityCurrency","reality","none"]
];
export const floraLinkedResourceIDs=Object.freeze(["timber","fiber","pulp","toxin","spore","reagent"]);
export const resourceCatalogue=Object.freeze(rows.map(([id,acquisitionKind,sourceClass,profile])=>Object.freeze({id,acquisitionKind,sourceClass,profile})));
const environments={soil:{dark:"#493927",body:"#806342",light:"#b7905d"},stone:{dark:"#36383b",body:"#686d70",light:"#aeb3b1"},ice:{dark:"#354b55",body:"#6f959e",light:"#c0d8d8"},ash:{dark:"#393638",body:"#6e696b",light:"#aaa2a0"},unstable:{dark:"#25222d",body:"#514b60",light:"#8d819e"},flora:{dark:"#263c28",body:"#53704c",light:"#92a963"}};
const accents={rubble:"#8b8175",clay:"#a56f4e",ore:"#858b8f",copper:"#b66e4c",silver:"#d1d3ce",gold:"#d5a84f",quartz:"#cabbd4",obsidian:"#40374d",salt:"#e4ddd0",sulfur:"#c7bc4d",mercury:"#aab5b7",adamant:"#6ba6a0",resin:"#c58945",ichor:"#80506f",rift_glass:"#82b7bc",essence_raw:"#8c82ca"};
const shapes={heap:[[2,9,12,5],[4,6,4,4],[9,7,4,3]],mound:[[2,8,12,6],[5,5,7,4]],vein:[[1,10,14,3],[4,7,3,4],[10,5,3,6]],nodules:[[2,9,5,5],[9,8,5,6],[6,5,4,4]],seam:[[1,8,14,3],[4,5,3,4],[11,10,3,3]],crystal:[[3,8,4,6],[7,3,4,11],[11,7,3,7]],shard:[[2,9,4,5],[6,4,4,10],[10,6,4,8]],pool:[[1,10,14,4],[4,8,8,3]],core:[[3,7,10,7],[6,4,4,4]],exudate:[[6,3,4,8],[3,10,10,4]],drop:[[6,3,4,6],[4,8,8,6]]};
function mineralRemainder(profile,p,accent){const byProfile={heap:[rect(2,12,4,2,p.dark),rect(9,11,3,3,accent)],mound:[rect(2,11,4,3,p.dark),rect(10,11,4,3,p.dark)],vein:[rect(2,9,4,4,p.dark),rect(10,7,4,5,p.dark)],nodules:[rect(3,11,3,3,p.dark),rect(10,10,2,2,accent)],seam:[rect(1,10,5,2,p.dark),rect(10,8,5,2,p.dark)],crystal:[rect(3,12,4,2,p.dark),rect(8,10,3,4,accent),rect(12,12,2,2,p.dark)],shard:[rect(2,12,3,2,p.dark),rect(7,10,3,4,accent),rect(12,11,2,3,p.dark)],pool:[rect(2,12,12,2,p.dark),rect(6,11,4,1,accent)],core:[rect(3,11,4,3,p.dark),rect(10,10,3,4,p.dark)]};return byProfile[profile]??[];}
export function resourceWorldCommands(id,{environment="stone",state="remaining"}={}){const entry=resourceCatalogue.find(item=>item.id===id);if(!entry)throw new Error(`unknown-resource-family:${id}`);if(entry.sourceClass==="unstableSubstrate"&&environment!=="unstable")throw new Error(`resource-context-mismatch:${id}:requires-unstable-substrate`);if(entry.acquisitionKind==="realityCurrency"||entry.acquisitionKind==="wildDrop")return[];const p=environments[entry.sourceClass==="flora"?"flora":environment]??environments.stone,accent=accents[id]??p.light;if(entry.sourceClass==="flora")return state==="exhausted"?[]:[rect(2,11,3,3,p.light),rect(11,11,3,3,p.light),rect(6,12,4,2,p.dark)];if(state==="exhausted"){if(entry.profile==="exudate")return[rect(4,12,8,2,p.dark),rect(7,10,2,2,accent)];return fitCommands(mineralRemainder(entry.profile,p,accent),16,16,0);}const c=[];(shapes[entry.profile]??[]).forEach(([x,y,w,h],i)=>c.push(rect(x,y,w,h,i%2?p.body:p.dark)));c.push(rect(entry.profile==="seam"?7:6,entry.profile==="pool"?11:6,3,2,accent));return fitCommands(c,16,16,0);}
export function resourceMinimapCommands(id,{revealed=false,discovered=false,state="remaining"}={}){const entry=resourceCatalogue.find(item=>item.id===id);if(!entry)throw new Error(`unknown-resource-family:${id}`);if(!revealed||!discovered||entry.acquisitionKind==="realityCurrency"||entry.acquisitionKind==="wildDrop")return[];if(state==="exhausted")return[rect(1,2,2,1,"#68625c")];return[rect(1,1,2,2,"#d8bd82"),rect(2,0,1,1,"#eee5d5")];}
export function resourceInteractionLabel(id,{state="remaining"}={}){const entry=resourceCatalogue.find(item=>item.id===id);if(!entry)throw new Error(`unknown-resource-family:${id}`);return`${id.replaceAll("_"," ")} · ${entry.acquisitionKind} · ${entry.profile} profile · ${state}`;}
export function resourceSilhouetteHash(commands){return hash(commands.map(({x,y,w,h})=>({x,y,w,h})));}
