import {fitCommands,hash} from "./generator.js";import {tileContentCommands} from "./tile-content.js";const rect=(x,y,w,h,color)=>({op:"rect",x,y,w,h,color});
const rows=[
  ["rubble","node","mineral","heap"],["clay","node","mineral","mound"],["ore","node","mineral","vein"],["copper","node","mineral","nodules"],["silver","node","mineral","seam"],["gold","node","mineral","seam"],["quartz","node","mineral","crystal"],["obsidian","node","mineral","shard"],["salt","node","mineral","crystal"],["sulfur","node","mineral","nodules"],["mercury","node","mineral","pool"],["adamant","node","mineral","core"],
  ["fiber","node","flora","harvest"],["timber","node","flora","harvest"],["pulp","node","flora","harvest"],["resin","deposit","exudate","exudate"],["toxin","node","flora","harvest"],["spore","node","flora","harvest"],["reagent","node","flora","harvest"],["ichor","deposit","deposit","pool"],["rift_glass","node","unstableSubstrate","shard"],["essence_raw","wildDrop","energy","drop"],["mote","realityCurrency","reality","none"]
];
export const floraLinkedResourceIDs=Object.freeze(["timber","fiber","pulp","toxin","spore","reagent"]);
export const resourceCatalogue=Object.freeze(rows.map(([id,acquisitionKind,sourceClass,profile])=>Object.freeze({id,acquisitionKind,sourceClass,profile})));
export const resourceColorContract=Object.freeze({version:"resource-color-1.0.0",substrate:"world-graded",identityMaterial:"canonical-static-accent",minimumIdentityPixels:2,sheen:"neutral-luminance-after-color",forbidden:"whole-resource-world-recolor"});
const environments={soil:{dark:"#493927",body:"#806342",light:"#b7905d"},stone:{dark:"#36383b",body:"#686d70",light:"#aeb3b1"},ice:{dark:"#354b55",body:"#6f959e",light:"#c0d8d8"},ash:{dark:"#393638",body:"#6e696b",light:"#aaa2a0"},unstable:{dark:"#25222d",body:"#514b60",light:"#8d819e"},flora:{dark:"#263c28",body:"#53704c",light:"#92a963"}};
const accents={rubble:"#8b8175",clay:"#b87350",ore:"#9b5b3c",copper:"#b86f4b",silver:"#d8d9d4",gold:"#e1ad43",quartz:"#d9cae3",obsidian:"#352c43",salt:"#eee8db",sulfur:"#dbcf43",mercury:"#cbd4d5",adamant:"#63aaa5",resin:"#d39442",ichor:"#87506f",rift_glass:"#82c2c7",essence_raw:"#8c82ca"};
const shapes={heap:[[2,9,12,5],[4,6,4,4],[9,7,4,3]],mound:[[2,8,12,6],[5,5,7,4]],vein:[[1,10,14,3],[4,7,3,4],[10,5,3,6]],nodules:[[2,9,5,5],[9,8,5,6],[6,5,4,4]],seam:[[1,8,14,3],[4,5,3,4],[11,10,3,3]],crystal:[[3,8,4,6],[7,3,4,11],[11,7,3,7]],shard:[[2,9,4,5],[6,4,4,10],[10,6,4,8]],pool:[[1,10,14,4],[4,8,8,3]],core:[[3,7,10,7],[6,4,4,4]],exudate:[[6,3,4,8],[3,10,10,4]],drop:[[6,3,4,6],[4,8,8,6]]};
// Research-guided top-down material grammar. Each tuple is x,y,w,h,tone and must carry identity
// before color or sheen: broken masonry, smooth clay, rusted iron, dendritic copper, wire silver,
// nuggets, prisms, glassy shards, salt cubes, sulfur crystals, cinnabar+bead, and so on.
const referenceShapes={
  rubble:[[1,10,5,4,"dark"],[5,7,5,7,"body"],[10,9,5,5,"dark"],[3,6,3,3,"light"],[10,5,3,4,"accent"]],
  clay:[[2,10,12,4,"dark"],[3,8,10,4,"accent"],[5,6,7,3,"body"],[7,5,4,2,"light"]],
  ore:[[2,8,4,6,"dark"],[5,5,7,9,"body"],[11,7,3,7,"dark"],[4,6,3,2,"accent"],[8,8,3,3,"accent"],[10,5,2,2,"light"]],
  copper:[[3,3,3,11,"accent"],[6,5,5,3,"accent"],[9,3,3,4,"body"],[6,10,6,3,"accent"],[11,9,3,5,"light"],[2,12,5,2,"dark"]],
  silver:[[2,5,3,3,"light"],[4,7,8,2,"accent"],[9,4,2,4,"light"],[11,7,3,5,"accent"],[6,9,2,5,"light"],[3,12,4,2,"body"]],
  gold:[[2,10,5,4,"accent"],[7,8,4,5,"light"],[11,11,4,3,"accent"],[5,5,4,3,"accent"],[9,5,3,2,"light"]],
  quartz:[[3,9,4,5,"body"],[6,3,4,11,"accent"],[10,7,4,7,"body"],[7,2,2,3,"light"],[11,6,2,3,"light"]],
  obsidian:[[2,10,4,4,"dark"],[5,5,3,9,"accent"],[8,2,3,12,"dark"],[11,7,3,7,"accent"],[8,3,1,7,"light"]],
  salt:[[2,9,5,5,"accent"],[6,4,5,5,"light"],[10,9,4,5,"body"],[3,10,2,2,"light"],[7,5,2,2,"body"],[11,10,2,2,"light"]],
  sulfur:[[2,11,12,3,"body"],[3,7,4,4,"accent"],[7,5,4,6,"light"],[11,8,3,3,"accent"],[8,3,2,3,"accent"]],
  mercury:[[1,10,14,4,"dark"],[2,9,11,4,"accent"],[5,7,7,4,"accent"],[10,6,3,3,"light"],[3,11,3,2,"body"],[13,8,2,2,"light"]],
  adamant:[[4,3,8,2,"accent"],[2,5,12,7,"body"],[4,12,8,2,"dark"],[4,6,2,5,"accent"],[10,6,2,5,"accent"],[6,5,4,2,"light"],[6,10,4,2,"dark"]],
  fiber:[[3,3,2,11,"light"],[6,2,2,12,"body"],[9,3,2,11,"light"],[12,4,2,10,"body"],[2,8,13,2,"accent"]],
  timber:[[1,6,12,7,"dark"],[2,7,11,5,"body"],[12,7,3,5,"accent"],[13,8,1,3,"light"],[4,8,2,2,"accent"],[7,8,2,2,"dark"]],
  pulp:[[2,10,12,3,"body"],[3,7,11,3,"light"],[4,4,9,3,"accent"],[11,3,3,2,"light"],[2,12,3,2,"dark"]],
  resin:[[7,2,3,3,"light"],[6,4,5,6,"accent"],[4,9,9,4,"body"],[6,12,5,2,"dark"],[8,5,1,3,"light"]],
  toxin:[[5,5,7,7,"body"],[7,3,3,3,"accent"],[3,7,3,3,"dark"],[11,7,3,3,"dark"],[7,8,3,3,"light"],[8,12,2,2,"accent"]],
  spore:[[2,10,4,4,"body"],[6,5,3,3,"light"],[11,9,4,4,"accent"],[9,3,2,2,"body"],[5,12,2,2,"light"],[12,5,2,2,"light"]],
  reagent:[[3,11,11,3,"dark"],[7,4,2,8,"body"],[3,6,5,3,"light"],[8,7,5,3,"accent"],[10,3,3,4,"light"],[5,10,3,3,"accent"]],
  ichor:[[1,11,14,3,"dark"],[3,8,9,4,"accent"],[10,6,3,4,"body"],[5,5,2,4,"accent"],[11,4,2,3,"light"]],
  rift_glass:[[2,6,4,8,"accent"],[4,3,3,9,"light"],[10,3,4,11,"accent"],[8,10,3,4,"dark"],[11,4,1,6,"light"]]
};
function mineralRemainder(profile,p,accent){const byProfile={heap:[rect(2,12,4,2,p.dark),rect(9,11,3,3,accent)],mound:[rect(2,11,4,3,p.dark),rect(10,11,4,3,p.dark)],vein:[rect(2,9,4,4,p.dark),rect(10,7,4,5,p.dark)],nodules:[rect(3,11,3,3,p.dark),rect(10,10,2,2,accent)],seam:[rect(1,10,5,2,p.dark),rect(10,8,5,2,p.dark)],crystal:[rect(3,12,4,2,p.dark),rect(8,10,3,4,accent),rect(12,12,2,2,p.dark)],shard:[rect(2,12,3,2,p.dark),rect(7,10,3,4,accent),rect(12,11,2,3,p.dark)],pool:[rect(2,12,12,2,p.dark),rect(6,11,4,1,accent)],core:[rect(3,11,4,3,p.dark),rect(10,10,3,4,p.dark)]};return byProfile[profile]??[];}
export function resourceWorldCommands(id,{environment="stone",state="remaining"}={}){const entry=resourceCatalogue.find(item=>item.id===id);if(!entry)throw new Error(`unknown-resource-family:${id}`);if(entry.sourceClass==="unstableSubstrate"&&environment!=="unstable")throw new Error(`resource-context-mismatch:${id}:requires-unstable-substrate`);if(entry.acquisitionKind==="realityCurrency"||entry.acquisitionKind==="wildDrop")return[];const p=environments[entry.sourceClass==="flora"?"flora":environment]??environments.stone,accent=accents[id]??p.light;if(state==="exhausted"){if(entry.sourceClass==="flora")return[];if(entry.profile==="exudate")return[rect(4,12,8,2,p.dark),rect(7,10,2,2,accent)];return fitCommands(mineralRemainder(entry.profile,p,accent),16,16,0);}const c=[],tones={dark:p.dark,body:p.body,light:p.light,accent};(referenceShapes[id]??(shapes[entry.profile]??[]).map((shape,index)=>[...shape,index%3===0?"dark":index%3===1?"body":"accent"])).forEach(([x,y,w,h,tone])=>c.push(rect(x,y,w,h,tones[tone])));return fitCommands(c,16,16,0);}
export const resourceSheenContract=Object.freeze({version:"resource-sheen-1.1.0",tickMilliseconds:360,cycleTicks:8,activeTicks:4,restTicks:4,phasePayload:"resource-sheen-1.1.0|mapSeedUInt64Decimal|runIndex|x|y",phaseHash:"FNV-1a-32 over UTF-8 bytes",clip:"revealed-discovered-remaining-resource-or-cue-alpha",reduceMotion:"static-frame-0",layer:"after-resource-before-route-selection-party-ui"});
function sheenFrameCommands(id,commands,frame=0){const entry=resourceCatalogue.find(item=>item.id===id);if(!entry)throw new Error(`unknown-resource-family:${id}`);if(!Number.isInteger(frame)||frame<0||frame>=resourceSheenContract.activeTicks)throw new Error("invalid-resource-sheen-frame");if(!commands.length)return[];const occupied=new Set();for(const command of commands)for(let y=command.y;y<command.y+command.h;y++)for(let x=command.x;x<command.x+command.w;x++)if(x>=0&&x<16&&y>=0&&y<16)occupied.add(`${x},${y}`);const pixels=[...occupied].map(key=>key.split(",").map(Number)).sort((a,b)=>a[1]-b[1]||a[0]-b[0]),sweep=pixels.filter(([x,y])=>(x+y-frame*3+32)%7===0).slice(0,4),selected=sweep.length?sweep:[pixels[(frame*5)%pixels.length]];return selected.map(([x,y])=>rect(x,y,1,1,"#fff4cf"));}
export function resourceSheenConformanceFrameCommands(id,commands,frame=0){return sheenFrameCommands(id,commands,frame);}
export function resourceSheenPhase(input){if(!input||typeof input!=="object"||Array.isArray(input)||Object.keys(input).sort().join(",")!=="mapSeedUInt64Decimal,runIndex,x,y")throw new Error("invalid-resource-sheen-phase-input");const {mapSeedUInt64Decimal,runIndex,x,y}=input;if(typeof mapSeedUInt64Decimal!=="string"||!/^(0|[1-9][0-9]{0,19})$/.test(mapSeedUInt64Decimal)||BigInt(mapSeedUInt64Decimal)>18446744073709551615n||![runIndex,x,y].every(Number.isSafeInteger)||runIndex<0)throw new Error("invalid-resource-sheen-phase-input");const payload=`${resourceSheenContract.version}|${mapSeedUInt64Decimal}|${runIndex}|${x}|${y}`;let value=0x811c9dc5;for(const byte of new TextEncoder().encode(payload)){value^=byte;value=Math.imul(value,0x01000193);}return Object.freeze({payload,fnv1a32:value>>>0});}
export function resourceSheenFrameForTick(phase,tick){if(!phase||Object.keys(phase).sort().join(",")!=="fnv1a32,payload"||!Number.isInteger(phase.fnv1a32)||phase.fnv1a32<0||phase.fnv1a32>0xffffffff||typeof phase.payload!=="string"||!Number.isSafeInteger(tick)||tick<0)throw new Error("invalid-resource-sheen-phase-input");const cycle=(phase.fnv1a32+tick)%resourceSheenContract.cycleTicks;return cycle>=2&&cycle<2+resourceSheenContract.activeTicks?cycle-2:null;}
export function resourceMapSheenCommands(request){if(!request||typeof request!=="object"||Array.isArray(request))throw new Error("invalid-resource-sheen-request");const expected=["bodyCommands","bodyKind","discovered","phase","reduceMotion","resourceID","revealed","state","tick"],actual=Object.keys(request).sort();if(JSON.stringify(actual)!==JSON.stringify(expected))throw new Error("unknown-or-missing-resource-sheen-field");const {resourceID,bodyKind,revealed,discovered,state,phase,tick,reduceMotion,bodyCommands}=request,entry=resourceCatalogue.find(item=>item.id===resourceID);if(!entry)throw new Error(`unknown-resource-family:${resourceID}`);if(typeof revealed!=="boolean"||typeof discovered!=="boolean"||typeof reduceMotion!=="boolean"||!["remaining","exhausted"].includes(state)||!Number.isSafeInteger(tick)||tick<0||!Array.isArray(bodyCommands))throw new Error("invalid-resource-sheen-request");if(entry.acquisitionKind==="realityCurrency")throw new Error(`resource-not-map-renderable:${resourceID}`);const requiredBody=entry.acquisitionKind==="wildDrop"?"wildDrop":"resourceCue";if(bodyKind!==requiredBody)throw new Error(`resource-sheen-body-mismatch:${resourceID}:${requiredBody}`);const resolvedPhase=resourceSheenPhase(phase);if(!revealed||!discovered||state!=="remaining"||bodyCommands.length===0)return[];const canonicalBody=entry.acquisitionKind==="wildDrop"?tileContentCommands({type:"wildDrop",revealed:true,discovered:true}):resourceWorldCommands(resourceID,{environment:entry.sourceClass==="unstableSubstrate"?"unstable":"stone"});if(resourceSilhouetteHash(bodyCommands)!==resourceSilhouetteHash(canonicalBody))throw new Error(`resource-sheen-mask-mismatch:${resourceID}`);const frame=reduceMotion?0:resourceSheenFrameForTick(resolvedPhase,tick);return frame===null?[]:sheenFrameCommands(resourceID,bodyCommands,frame);}
export function resourceInventoryIconCommands(id){const entry=resourceCatalogue.find(item=>item.id===id);if(!entry)throw new Error(`unknown-resource-family:${id}`);if(id==="essence_raw")return[rect(6,2,4,5,"#eee5d5"),rect(4,6,8,8,"#8c82ca"),rect(7,4,2,3,"#c6bff0")];if(id==="mote")return[rect(3,3,10,10,"#d5a84f"),rect(5,5,6,6,"#171614"),rect(7,2,2,12,"#eee5d5")];const environment=entry.sourceClass==="unstableSubstrate"?"unstable":"stone";return resourceWorldCommands(id,{environment});}
export function resourceMinimapCommands(id,{revealed=false,discovered=false,state="remaining"}={}){const entry=resourceCatalogue.find(item=>item.id===id);if(!entry)throw new Error(`unknown-resource-family:${id}`);if(!revealed||!discovered||entry.acquisitionKind==="realityCurrency"||entry.acquisitionKind==="wildDrop")return[];if(state==="exhausted")return[rect(1,2,2,1,"#68625c")];return[rect(1,1,2,2,"#d8bd82"),rect(2,0,1,1,"#eee5d5")];}
export function resourceInteractionLabel(id,{state="remaining"}={}){const entry=resourceCatalogue.find(item=>item.id===id);if(!entry)throw new Error(`unknown-resource-family:${id}`);return`${id.replaceAll("_"," ")} · ${entry.acquisitionKind} · ${entry.profile} profile · ${state}`;}
export function resourceSilhouetteHash(commands){const occupied=new Set();for(const {x,y,w,h} of commands)for(let py=y;py<y+h;py++)for(let px=x;px<x+w;px++)occupied.add(`${px},${py}`);return hash([...occupied].sort((a,b)=>{const [ax,ay]=a.split(",").map(Number),[bx,by]=b.split(",").map(Number);return ay-by||ax-bx;}));}
