import {tradingPostContract,tradingPostFixtures,resolveTradingPost,proposedTradingPostResult} from "./trading-kit.js";
import {distinctStationCommands} from "./place-kit.js";
import {characterCommands} from "./character-kit.js";
import {resourceInventoryIconCommands} from "./resource-kit.js";
import {itemIconCommands} from "./item-kit.js";

const canvas=document.getElementById("trading-proof"),x=canvas.getContext("2d"),colors={bg:"#171614",panel:"#24221f",line:"#625b51",ink:"#eee5d5",muted:"#aaa397",accent:"#d6a85f",disabled:"#4b4944",action:"#6f542d"};
function sprite(commands,width,height){const c=document.createElement("canvas");c.width=width;c.height=height;const q=c.getContext("2d");for(const o of commands){q.fillStyle=o.color;q.fillRect(o.x,o.y,o.w,o.h);}return c;}
function gray(image){const c=document.createElement("canvas");c.width=image.width;c.height=image.height;const q=c.getContext("2d");q.filter="grayscale(1)";q.drawImage(image,0,0);return c;}
function text(value,px,py,size=8,color=colors.ink){x.fillStyle=color;x.font=`${size}px monospace`;x.fillText(value,px,py);}
function iconFor(line){return line.kind==="resource"?sprite(resourceInventoryIconCommands(line.family),32,32):sprite(itemIconCommands(line.family),32,32);}
function identityHeader(ox,grayMode=false){const station=sprite(distinctStationCommands("trading_post",{palette:"warm"}),48,36),vance=sprite(characterCommands("vance",{profile:"baseSide"}),16,16),draw=image=>grayMode?gray(image):image;x.drawImage(draw(station),ox+12,18,72,54);x.drawImage(draw(vance),ox+49,48,16,16);x.drawImage(draw(vance),ox+92,48,16,16);text("TRADING POST",ox+124,29,12);text("Vance outside = at counter",ox+124,47,8,colors.muted);text("PROPOSED wallet 18 Gold Coins · fixture snapshot #4",ox+124,66,7,colors.accent);}
function tabs(ox,oy,active){for(const [index,label] of ["BUY","SELL"].entries()){x.fillStyle=label.toLowerCase()===active?colors.action:colors.panel;x.fillRect(ox+12+index*178,oy,170,36);text(label,ox+76+index*178,oy+23,10);}}
function cell(line,index,ox,oy,selected,grayMode=false,blocked=false){const px=ox+(index%6)*60,py=oy+Math.floor(index/6)*60;x.fillStyle=colors.panel;x.fillRect(px,py,54,54);x.strokeStyle=selected?(grayMode?"#fff":colors.accent):colors.line;x.lineWidth=selected?3:1;x.strokeRect(px+1.5,py+1.5,51,51);const icon=iconFor(line);x.drawImage(grayMode?gray(icon):icon,px+11,py+6,32,32);x.fillStyle="#111";x.fillRect(px+35,py+36,16,14);text(`×${line.quantity}`,px+36,py+47,7);if(blocked){x.fillStyle=grayMode?"#ddd":colors.accent;x.fillRect(px+3,py+39,12,4);x.fillRect(px+7,py+35,4,12);}else{x.fillStyle=grayMode?"#ddd":colors.ink;x.fillRect(px+4,py+42,12,3);} }
function detail(ox,oy,title,lines,action,enabled=true){x.fillStyle=colors.panel;x.fillRect(ox,oy,366,124);x.strokeStyle=colors.line;x.strokeRect(ox+.5,oy+.5,365,123);text(title,ox+10,oy+19,10,colors.accent);lines.forEach((line,index)=>text(line,ox+10,oy+40+index*16,index===0?9:8,index===0?colors.ink:colors.muted));x.fillStyle=enabled?colors.action:colors.disabled;x.fillRect(ox+244,oy+72,110,38);text(action,ox+258,oy+96,8,enabled?colors.ink:colors.muted);}
function stage(ox,oy,label,lines,action,mutates=false){x.fillStyle=colors.panel;x.fillRect(ox,oy,112,148);x.strokeStyle=mutates?colors.accent:colors.line;x.strokeRect(ox+.5,oy+.5,111,147);text(label,ox+7,oy+17,8,colors.accent);lines.forEach((line,index)=>text(line,ox+7,oy+39+index*16,7,index===0?colors.ink:colors.muted));x.fillStyle=mutates?colors.action:colors.disabled;x.fillRect(ox+7,oy+109,98,28);text(action,ox+15,oy+127,7);}
function phone(ox,grayMode=false){x.save();if(grayMode)x.filter="grayscale(1)";identityHeader(ox,grayMode);tabs(ox,88,"buy");tradingPostFixtures.stock.forEach((line,index)=>cell(line,index,ox+12,136,index===1,grayMode,false));text("CANNOT BUY: Copper ×4 requested · only 2 remain · confirm inactive",ox+12,202,7,colors.muted);const buy=resolveTradingPost({mode:"buy",wallet:18,stockState:"ready",line:tradingPostFixtures.stock[1],quantity:2});detail(ox+12,214,"Quartz · stock-402",[`2 × 6 Gold Coins = 12`,`wallet 18 → 6 · stock 2 → 0`,`destination Resource Pool`],"Review buy");text("BUY · PROPOSED PREVIEW / CONFIRM / RESULT DTO",ox+12,360,8,colors.accent);stage(ox+12,374,"PREVIEW",["stock-402","2 × 6 = 12","no mutation"],"Continue");stage(ox+134,374,"CONFIRM",["same line/qty","wallet 18→6","stock 2→0"],buy.confirmAction,true);const bought=proposedTradingPostResult(buy);stage(ox+256,374,"RESULT DTO",["2 Quartz",`wallet ${bought.walletAfter}`,"Resource Pool"],"Proposed");text("REOPEN #4 = IDENTICAL · AFTER EXPEDITION #5 = NEW SNAPSHOT",ox+12,536,7,colors.accent);tabs(ox,548,"sell");tradingPostFixtures.holdings.forEach((line,index)=>cell(line,index,ox+12,596,index===0,grayMode,line.eligibility==="cannotAct"));const sell=resolveTradingPost({mode:"sell",wallet:18,stockState:"awaitingRefresh",line:tradingPostFixtures.holdings[0],quantity:3});detail(ox+12,668,"Rubble · eligible",[`3 × 1 Gold Coin = 3`,`wallet 18 → ${sell.walletAfter} · holdings 7 → 4`,`proposed: selling works before stock refresh`],"Review sale");text("KEEP / CANNOT ACT · NO TEMPTING PRICE",ox+12,808,9,colors.accent);text("Worn by Mara · Identify first · Locked / Keep",ox+12,826,8,colors.muted);stage(ox+12,842,"PREVIEW",["3 Rubble","+3 Gold Coins","cancel = none"],"Continue");stage(ox+134,842,"CONFIRM",["same scope","wallet 18→21","holdings 7→4"],"Confirm sale",true);stage(ox+256,842,"RESULT DTO",["3 removed","+3 Gold Coins","rules-owned"],"Proposed");x.restore();}
function draw(){x.imageSmoothingEnabled=false;x.fillStyle=colors.bg;x.fillRect(0,0,800,1040);text("PROPOSED SEMANTIC FIXTURE · NOT LIVE · NOT INTEGRATION-GOLDEN",18,1022,8,colors.accent);phone(6,false);phone(406,true);text("COLOR · 390PT",18,1036,8,colors.accent);text("LITERAL GRAYSCALE · SAME SEMANTICS",418,1036,8,colors.accent);}
draw();
const accessible=document.getElementById("trading-accessible-list"),states=["Proposed semantic fixture only; not live or integration-golden","Trading Post and authored base-side Vance cameo, proposed wallet 18 Gold Coins, fixture snapshot 4","Buy Quartz, quantity 2, proposed unit price 6 Gold Coins, total 12","Preview does not mutate; rules-owned Confirm buy is the proposed sole buy mutation","Proposed result DTO: wallet 6, stock zero, two Quartz in Resource Pool","Cannot buy four Copper: only two remain; confirm inactive","Reopen snapshot 4 is identical; expedition snapshot 5 is separately changed","Sell Rubble, quantity 3, proposed unit price 1 Gold Coin, total 3","Worn Pointed Blade cannot be sold: Worn by Mara","Unknown item cannot be sold: Identify before selling","Field Boots cannot be sold: Locked, Keep","Cancel changes nothing; atomic commit requires a future rules-owned DTO"];accessible.replaceChildren(...states.map(value=>{const li=document.createElement("li");li.textContent=value;return li;}));
document.getElementById("save-trading-proof").addEventListener("click",()=>canvas.toBlob(async blob=>{try{const response=await fetch("/__artifact?name=trading-post-vance-proof-v0.2.png",{method:"POST",headers:{"Content-Type":"image/png"},body:blob});if(!response.ok)throw new Error(await response.text());const result=await response.json();document.getElementById("trading-status").textContent=`Saved ${result.path}`;}catch(error){document.getElementById("trading-status").textContent=`Save failed: ${error.message}`;}} ,"image/png"));
