import { renderCommands,hash,canonicalJSON,commandBounds,safeFilePart } from "./generator.js";
import { floraDefaults,floraDefinitions,floraPresets,normalizeFlora,rebalanceFlora,floraCommands,transitionedTerrainCommands,sampleWorld,sampleMultiSpeciesWorld,adjacencyFor,crackOverlayCommands,groundTypes } from "./world-generator.js";
import { floraLiveContract } from "./live-contract.js";
import { tileContentTypes,tileContentCommands,minimapContentCommands } from "./tile-content.js";

const byId=id=>document.getElementById(id),allocations={woody:["woody","fibrous","fleshy"],fibrous:["woody","fibrous","fleshy"],fleshy:["woody","fibrous","fleshy"],cyan:["cyan","magenta","yellow"],magenta:["cyan","magenta","yellow"],yellow:["cyan","magenta","yellow"]};
let flora=JSON.parse(JSON.stringify(floraDefaults)),world=sampleMultiSpeciesWorld(flora,4);
const worldGrades={neutral:{red:0,green:0,blue:0,value:0},cool:{red:-10,green:2,blue:18,value:-3},warm:{red:16,green:4,blue:-10,value:3},strange:{red:10,green:-8,blue:18,value:-2}};
const selectedWorldGrade=()=>worldGrades[byId("world-grade")?.value??"neutral"],terrainVariety=()=>Number(byId("terrain-variety")?.value??4);
const VERSIONS={floraSchemaVersion:1,terrainSchemaVersion:1,grammarVersion:"world-grammar-0.2.0",compositorVersion:"rect-compositor-0.2.0",renderProfileVersion:"world-profiles-0.2.0"};
const canvases={world:byId("flora-world"),detail:byId("flora-detail"),hostile:byId("flora-hostile"),overheadProof:byId("flora-overhead-proof"),floraCatalogue:byId("flora-catalogue"),transitions:byId("transitions"),catalogue:byId("terrain-catalogue"),contentProof:byId("tile-content-proof"),map:byId("phone-map"),grayscale:byId("grayscale-map"),minimap:byId("minimap"),speciesProof:byId("multi-species-proof")};

function initializePresets(){const select=byId("flora-preset");for(const name of Object.keys(floraPresets))select.add(new Option(name.replace(/([A-Z])/g," $1").toLowerCase(),name));}
const speciesCount=()=>Number(byId("species-count")?.value??4);
initializePresets();byId("flora-preset").addEventListener("change",event=>{if(!event.target.value)return;flora=normalizeFlora({...flora,logicalID:event.target.value,traits:floraPresets[event.target.value]});world=sampleMultiSpeciesWorld(flora,speciesCount());renderAll();});
byId("species-count").addEventListener("change",()=>{world=sampleMultiSpeciesWorld(flora,speciesCount());renderAll();});

function buildControls(){const host=byId("flora-controls");for(const def of floraDefinitions){const wrapper=document.createElement("div");wrapper.className="trait";const label=document.createElement("label");label.textContent=def.label;label.htmlFor=`flora-${def.key}`;const input=def.options?document.createElement("select"):document.createElement("input");input.id=`flora-${def.key}`;input.dataset.flora=def.key;if(def.options)for(const option of def.options)input.add(new Option(option,option));else{input.type="range";input.min=def.min;input.max=def.max;input.step=1;}const output=document.createElement("output");output.className="trait-output";output.dataset.floraOutput=def.key;if(def.options){wrapper.classList.add("select-trait");wrapper.append(document.createElement("span"),label,input);}else{const head=document.createElement("div");head.className="trait-head";head.append(document.createElement("span"),label,output);wrapper.append(head,input);}input.addEventListener("input",()=>{const value=def.options?input.value:Number(input.value);if(def.allocation)rebalanceFlora(flora.traits,def.key,allocations[def.key],value);else flora.traits[def.key]=value;renderAll();});host.append(wrapper);}}
function sync(){byId("flora-seed").value=flora.speciesSeed;for(const def of floraDefinitions){document.querySelector(`[data-flora="${def.key}"]`).value=flora.traits[def.key];const output=document.querySelector(`[data-flora-output="${def.key}"]`);if(output)output.textContent=flora.traits[def.key];}}
function draw(canvas,commands){renderCommands(canvas.getContext("2d"),canvas.width,canvas.height,commands);}
function drawOver(context,commands){for(const command of commands){context.fillStyle=command.color;context.fillRect(command.x,command.y,command.w,command.h);}}
function pixelHash(canvas){const bytes=canvas.getContext("2d").getImageData(0,0,canvas.width,canvas.height).data;let h=0x811c9dc5;for(const b of bytes){h^=b;h=Math.imul(h,0x01000193);}return(h>>>0).toString(16).padStart(8,"0");}
function renderAll(){flora=normalizeFlora(flora);sync();const worldCommands=floraCommands(flora,"world"),detailCommands=floraCommands(flora,"detail"),hostileCommands=floraCommands(flora,"hostile");draw(canvases.world,worldCommands);draw(canvases.detail,detailCommands);draw(canvases.hostile,hostileCommands);drawFloraCatalogue();drawTransitions();drawTerrainCatalogue();drawMap();drawDiagnostics(worldCommands,detailCommands,hostileCommands);byId("flora-hash").textContent=`descriptor ${hash(canonicalJSON(flora))}`;byId("flora-world-hash").textContent=`pixels ${pixelHash(canvases.world)}`;byId("flora-detail-hash").textContent=`pixels ${pixelHash(canvases.detail)}`;byId("flora-hostile-hash").textContent=`pixels ${pixelHash(canvases.hostile)}`;if(document.activeElement!==byId("flora-json"))byId("flora-json").value=JSON.stringify(flora,null,2);canvases.world.style.width="128px";canvases.world.style.height="128px";for(const canvas of [canvases.detail,canvases.hostile]){canvas.style.width="240px";canvas.style.height="240px";}}
function drawFloraCatalogue(){const context=canvases.floraCatalogue.getContext("2d");context.clearRect(0,0,112,16);context.imageSmoothingEnabled=false;Object.entries(floraPresets).forEach(([name,traits],index)=>{const descriptor=normalizeFlora({...floraDefaults,logicalID:name,speciesSeed:700+index,traits});const scratch=document.createElement("canvas");scratch.width=scratch.height=16;renderCommands(scratch.getContext("2d"),16,16,floraCommands(descriptor,"world"));context.drawImage(scratch,index*16,0);});}
function drawTransitions(){const context=canvases.transitions.getContext("2d");context.clearRect(0,0,64,64);context.imageSmoothingEnabled=false;for(let mask=0;mask<16;mask++){const scratch=document.createElement("canvas");scratch.width=16;scratch.height=16;renderCommands(scratch.getContext("2d"),16,16,transitionedTerrainCommands({ground:"water",adjacency:mask,speciesSeed:flora.speciesSeed,revealed:true}));context.drawImage(scratch,(mask%4)*16,Math.floor(mask/4)*16);}}
function drawTerrainCatalogue(){const context=canvases.catalogue.getContext("2d");context.clearRect(0,0,64,48);context.imageSmoothingEnabled=false;groundTypes.forEach((ground,index)=>{const scratch=document.createElement("canvas");scratch.width=scratch.height=16;renderCommands(scratch.getContext("2d"),16,16,transitionedTerrainCommands({ground,adjacency:15,speciesSeed:404+index,revealed:true,featureVariant:index%terrainVariety(),worldGrade:selectedWorldGrade()}));context.drawImage(scratch,(index%4)*16,Math.floor(index/4)*16);});}
function drawMap(){const context=canvases.map.getContext("2d");context.clearRect(0,0,144,144);context.imageSmoothingEnabled=false;const mini=canvases.minimap.getContext("2d");mini.clearRect(0,0,36,36);mini.imageSmoothingEnabled=false;for(const cell of world.cells){const scratch=document.createElement("canvas");scratch.width=16;scratch.height=16;const commands=transitionedTerrainCommands({ground:cell.ground,adjacency:adjacencyFor(world,cell),speciesSeed:flora.speciesSeed+cell.x*31+cell.y*17,revealed:cell.revealed,cracking:false,elevation:cell.elevation,featureVariant:((flora.speciesSeed+cell.x*31+cell.y*17)>>>0)%terrainVariety(),worldGrade:selectedWorldGrade()});renderCommands(scratch.getContext("2d"),16,16,commands);const tile=scratch.getContext("2d");if(cell.flora&&cell.revealed){const plant=document.createElement("canvas");plant.width=16;plant.height=16;renderCommands(plant.getContext("2d"),16,16,floraCommands(flora,"world"));tile.drawImage(plant,0,0);}if(cell.route&&cell.revealed){tile.fillStyle="#e1c06f";tile.fillRect(6,6,4,4);}if(cell.portal&&cell.revealed){tile.fillStyle="#6cc6d5";tile.fillRect(4,4,8,8);tile.fillStyle="#132b38";tile.fillRect(6,6,4,4);}if(cell.site&&cell.revealed){tile.fillStyle="#d8b06a";tile.fillRect(4,5,8,7);tile.fillStyle="#4c3826";tile.fillRect(6,7,4,5);}if(cell.party&&cell.revealed){tile.fillStyle="#f7efe1";tile.fillRect(5,4,6,7);tile.fillStyle="#27231f";tile.fillRect(7,6,2,2);}if(byId("show-cracks").checked&&cell.cracking&&cell.revealed)drawOver(tile,crackOverlayCommands());context.drawImage(scratch,cell.x*16,cell.y*16);mini.fillStyle=!cell.revealed?"#17171a":cell.ground==="deepWater"?"#142c43":cell.ground==="water"?"#35758a":cell.growth==="high"?"#31552f":cell.growth==="low"?"#657b3d":"#80603e";mini.fillRect(cell.x*4,cell.y*4,4,4);if(cell.route&&cell.revealed){mini.fillStyle="#d8bd70";mini.fillRect(cell.x*4+1,cell.y*4+1,2,2);}if(cell.portal&&cell.revealed){mini.fillStyle="#66c7d7";mini.fillRect(cell.x*4,cell.y*4,4,4);mini.fillStyle="#142b38";mini.fillRect(cell.x*4+1,cell.y*4+1,2,2);}if(cell.site&&cell.revealed){mini.fillStyle="#e2ad59";mini.fillRect(cell.x*4,cell.y*4,4,4);mini.fillStyle="#4a3421";mini.fillRect(cell.x*4+1,cell.y*4+1,2,2);}if(cell.party&&cell.revealed){mini.fillStyle="#f2e8d5";mini.fillRect(cell.x*4,cell.y*4,4,4);}}const gray=canvases.grayscale.getContext("2d");gray.clearRect(0,0,144,144);gray.drawImage(canvases.map,0,0);const image=gray.getImageData(0,0,144,144);for(let i=0;i<image.data.length;i+=4){const value=Math.round(image.data[i]*.2126+image.data[i+1]*.7152+image.data[i+2]*.0722);image.data[i]=image.data[i+1]=image.data[i+2]=value;}gray.putImageData(image,0,0);}
function drawDiagnostics(worldCommands,detailCommands,hostileCommands){const wb=commandBounds(worldCommands),db=commandBounds(detailCommands),hb=commandBounds(hostileCommands),bounded=wb.minX>=0&&wb.maxX<=16&&wb.minY>=0&&wb.maxY<=16&&db.minX>=0&&db.maxX<=48&&db.minY>=0&&db.maxY<=48&&hb.minX>=0&&hb.maxX<=48&&hb.minY>=0&&hb.maxY<=48;setDiagnostic("world-bounds",bounded,bounded?"all three profiles inside canvas":"profile exceeds canvas");const stable=hash(floraCommands({...flora,specimenSeed:1},"world"))===hash(floraCommands({...flora,specimenSeed:999},"world"));setDiagnostic("flora-stability",stable,stable?"placement jitter does not alter species":"species changed with placement");const terrain=new Set(Array.from({length:16},(_,mask)=>hash(transitionedTerrainCommands({ground:"water",adjacency:mask}))));setDiagnostic("terrain-read",terrain.size===16,`${terrain.size}/16 adjacency masks distinct · deep water present`);}
function setDiagnostic(id,ok,text){byId(`${id}-dot`).className=`dot ${ok?"ok":"bad"}`;byId(`${id}-status`).textContent=text;}
function download(name,blob){if(!blob){status("Export failed.",true);return;}const link=document.createElement("a"),url=URL.createObjectURL(blob);link.href=url;link.download=safeFilePart(name,"asset");link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function worldFileStem(){return safeFilePart(flora.logicalID,"flora");}
function worldManifest(){const stem=worldFileStem(),contract=floraLiveContract(flora);return{manifestVersion:3,identityKind:"flora",logicalID:flora.logicalID,authoringDescriptor:flora,gameIdentity:contract.gameIdentity,renderHints:contract.renderHints,adapterDiagnostics:contract.adapterDiagnostics,pipelineVersions:VERSIONS,outputs:[{profile:"flora-world",file:`${stem}-flora-world.png`,pixelWidth:16,pixelHeight:16,pivot:{x:8,y:15},pixelHash:pixelHash(canvases.world)},{profile:"flora-detail",file:`${stem}-flora-detail.png`,pixelWidth:48,pixelHeight:48,pivot:{x:24,y:44},pixelHash:pixelHash(canvases.detail)},{profile:"flora-hostile",file:`${stem}-flora-hostile.png`,pixelWidth:48,pixelHeight:48,pivot:{x:24,y:44},pixelHash:pixelHash(canvases.hostile)},{profile:"integrated-map",file:`${stem}-phone-map.png`,pixelWidth:144,pixelHeight:144,pivot:{x:72,y:72},pixelHash:pixelHash(canvases.map)},{profile:"minimap",file:`${stem}-minimap.png`,pixelWidth:36,pixelHeight:36,pivot:{x:18,y:18},pixelHash:pixelHash(canvases.minimap)}]};}
function drawMultiSpeciesMap(){
  if(!world.species||world.species[0]?.speciesSeed!==flora.speciesSeed||hash(world.species[0]?.traits)!==hash(flora.traits))world=sampleMultiSpeciesWorld(flora,speciesCount());
  const context=canvases.map.getContext("2d");
  for(const cell of world.cells.filter(item=>item.flora&&item.revealed)){
    const commands=transitionedTerrainCommands({ground:cell.ground,adjacency:adjacencyFor(world,cell),speciesSeed:flora.speciesSeed+cell.x*31+cell.y*17,revealed:true,cracking:false,elevation:cell.elevation,featureVariant:((flora.speciesSeed+cell.x*31+cell.y*17)>>>0)%terrainVariety(),worldGrade:selectedWorldGrade()});
    context.save();context.translate(cell.x*16,cell.y*16);context.clearRect(0,0,16,16);drawOver(context,commands);drawOver(context,floraCommands(world.species[cell.floraSpecies]??flora,"world"));if(byId("show-cracks").checked&&cell.cracking)drawOver(context,crackOverlayCommands());context.restore();
  }
  const gray=canvases.grayscale.getContext("2d");gray.clearRect(0,0,144,144);gray.drawImage(canvases.map,0,0);const image=gray.getImageData(0,0,144,144);for(let i=0;i<image.data.length;i+=4){const value=Math.round(image.data[i]*.2126+image.data[i+1]*.7152+image.data[i+2]*.0722);image.data[i]=image.data[i+1]=image.data[i+2]=value;}gray.putImageData(image,0,0);
  byId("species-proof-status").textContent=`${world.species.length} stable species · ${world.cells.filter(cell=>cell.flora).length} placements`;
}
function drawMultiSpeciesEvidence(){
  const canvas=canvases.speciesProof,context=canvas.getContext("2d"),placements=world.cells.filter(cell=>cell.flora),repeat=placements.filter(cell=>cell.floraSpecies===0),low=placements.find(cell=>cell.ground==="groundcover"),high=placements.find(cell=>cell.ground==="growth"),beside=placements.find(cell=>world.cells.some(route=>route.route&&Math.abs(route.x-cell.x)+Math.abs(route.y-cell.y)===1));
  context.clearRect(0,0,canvas.width,canvas.height);context.imageSmoothingEnabled=false;context.fillStyle="#171614";context.fillRect(0,0,canvas.width,canvas.height);context.fillStyle="#d8bd82";context.font="8px monospace";context.fillText("COLOR · native 9×9",8,12);context.fillText("GRAYSCALE · native 9×9",160,12);context.fillText("MINIMAP · symbolic 2×",312,12);context.drawImage(canvases.map,8,20);context.drawImage(canvases.grayscale,160,20);context.drawImage(canvases.minimap,312,20,72,72);
  context.fillStyle="#eee5d5";context.font="7px monospace";const coordinate=cell=>cell?`(${cell.x},${cell.y})`:"n/a",repeatHash=world.species[0]?hash(floraCommands(world.species[0],"world")):"n/a";context.fillText(`repeat ${world.species[0]?.logicalID??"n/a"}: ${repeat.map(coordinate).join(" + ")} · pixels ${repeatHash} = ${repeatHash}`,8,174);context.fillText(`groundcover ${coordinate(low)} · tall growth ${coordinate(high)} · beside route/marker ${coordinate(beside)}`,8,186);context.fillText(`${world.species.map((item,index)=>`${index+1}:${item.logicalID}`).join(" · ")}`,8,198);
}
function drawContentCatalogue(){
  const canvas=canvases.contentProof,context=canvas.getContext("2d"),grounds=["mud","growth","rubble","chasm"];context.clearRect(0,0,canvas.width,canvas.height);context.imageSmoothingEnabled=false;context.fillStyle="#171614";context.fillRect(0,0,canvas.width,canvas.height);
  tileContentTypes.forEach((type,index)=>{const x=index*32+8,terrain=transitionedTerrainCommands({ground:index%2?"soil":"stone",revealed:true,speciesSeed:300+index});context.save();context.translate(x,8);drawOver(context,terrain);drawOver(context,tileContentCommands({type,revealed:true,discovered:true,portalDirection:"entry"}));context.restore();const scratch=document.createElement("canvas");scratch.width=scratch.height=16;renderCommands(scratch.getContext("2d"),16,16,[...terrain,...tileContentCommands({type,revealed:true,discovered:true,portalDirection:"entry"})]);const image=scratch.getContext("2d").getImageData(0,0,16,16);for(let i=0;i<image.data.length;i+=4){const value=Math.round(image.data[i]*.2126+image.data[i+1]*.7152+image.data[i+2]*.0722);image.data[i]=image.data[i+1]=image.data[i+2]=value;}scratch.getContext("2d").putImageData(image,0,0);context.drawImage(scratch,x,32);context.save();context.translate(x+6,56);drawOver(context,minimapContentCommands({type,revealed:true,discovered:true,portalDirection:"entry"}));context.restore();});
  context.save();context.translate(8,72);drawOver(context,transitionedTerrainCommands({ground:"stone",revealed:true}));drawOver(context,tileContentCommands({type:"portal",portalDirection:"exit",revealed:true,discovered:true}));context.restore();grounds.forEach((ground,index)=>{const x=72+index*16;context.save();context.translate(x,80);drawOver(context,transitionedTerrainCommands({ground,revealed:true,speciesSeed:500+index}));if(index<3){context.fillStyle="#e1c06f";context.fillRect(1,6,14,4);drawOver(context,tileContentCommands({type:["hazard","traveller","site"][index],revealed:true,discovered:true}));}context.restore();});context.fillStyle="#eee5d5";context.font="7px monospace";context.fillText("exit",8,116);context.fillText("mud / growth / rubble / chasm edge",72,116);context.fillText("rows: world / grayscale / disclosed minimap",8,130);context.fillText("empty node drop hazard portal cache site diary writing traveller",8,140);
}
function grayscaleCopy(source){const scratch=document.createElement("canvas");scratch.width=source.width;scratch.height=source.height;const context=scratch.getContext("2d");context.drawImage(source,0,0);const image=context.getImageData(0,0,scratch.width,scratch.height);for(let i=0;i<image.data.length;i+=4){const value=Math.round(image.data[i]*.2126+image.data[i+1]*.7152+image.data[i+2]*.0722);image.data[i]=image.data[i+1]=image.data[i+2]=value;}context.putImageData(image,0,0);return scratch;}
function drawOverheadFloraEvidence(){const canvas=canvases.overheadProof,context=canvas.getContext("2d");context.clearRect(0,0,canvas.width,canvas.height);context.imageSmoothingEnabled=false;context.fillStyle="#171614";context.fillRect(0,0,canvas.width,canvas.height);context.fillStyle="#d8bd82";context.font="8px monospace";context.fillText("COLOR · SAME SPECIES / SAME OVERHEAD CAMERA",8,11);context.fillText("GRAYSCALE · SHAPE BEFORE COLOR",8,91);context.fillText("MAP OWNERSHIP",232,11);context.drawImage(canvases.world,8,16,64,64);context.drawImage(canvases.detail,80,24);context.drawImage(canvases.hostile,144,24);context.drawImage(grayscaleCopy(canvases.world),8,96,64,64);context.drawImage(grayscaleCopy(canvases.detail),80,104);context.drawImage(grayscaleCopy(canvases.hostile),144,104);context.drawImage(canvases.map,232,16);context.fillStyle="#eee5d5";context.font="7px monospace";context.fillText("16 world",12,83);context.fillText("48 neutral",78,83);context.fillText("48 triggered",140,83);context.fillText("no horizon · no stem baseline · radial pose only",8,166);}
const renderSingleSpecies=renderAll;
renderAll=()=>{renderSingleSpecies();drawMultiSpeciesMap();drawMultiSpeciesEvidence();drawContentCatalogue();drawOverheadFloraEvidence();};
byId("export-multi-species-proof").addEventListener("click",()=>canvases.speciesProof.toBlob(blob=>download("multi-species-map-proof-v0.2.png",blob),"image/png"));
byId("save-flora-overhead-proof").addEventListener("click",()=>canvases.overheadProof.toBlob(async blob=>{try{const response=await fetch("/__artifact?name=flora-overhead-proof-v0.2.png",{method:"POST",headers:{"Content-Type":"image/png"},body:blob});if(!response.ok)throw new Error(await response.text());const result=await response.json();byId("flora-overhead-proof-status").textContent=`Saved ${result.path}`;}catch(error){byId("flora-overhead-proof-status").textContent=`Save failed: ${error.message}`;}},"image/png"));
byId("save-tile-content-proof").addEventListener("click",()=>canvases.contentProof.toBlob(async blob=>{try{const response=await fetch("/__artifact?name=tile-content-collision-proof-v0.2.png",{method:"POST",headers:{"Content-Type":"image/png"},body:blob});if(!response.ok)throw new Error(await response.text());const result=await response.json();byId("tile-content-proof-status").textContent=`Saved ${result.path}`;}catch(error){byId("tile-content-proof-status").textContent=`Save failed: ${error.message}`;}},"image/png"));
function status(message,error=false){byId("flora-status").textContent=message;byId("flora-status").style.color=error?"#e88c7c":"";}

buildControls();byId("world-grade").addEventListener("change",renderAll);byId("terrain-variety").addEventListener("change",renderAll);byId("flora-seed").addEventListener("input",event=>{flora.speciesSeed=Number(event.target.value);world=sampleWorld(flora);renderAll();});byId("reroll-world").addEventListener("click",()=>{flora.speciesSeed=Math.floor(Math.random()*0xffffffff);world=sampleWorld(flora);renderAll();});byId("reset-flora").addEventListener("click",()=>{flora=JSON.parse(JSON.stringify(floraDefaults));world=sampleWorld(flora);renderAll();});byId("show-cracks").addEventListener("change",renderAll);byId("apply-flora-json").addEventListener("click",()=>{try{flora=normalizeFlora(JSON.parse(byId("flora-json").value));world=sampleWorld(flora);status("Flora applied.");renderAll();}catch(error){status(`Invalid JSON: ${error.message}`,true);}});byId("download-flora-json").addEventListener("click",()=>download(`${flora.logicalID}-${flora.speciesSeed}.json`,new Blob([JSON.stringify(flora,null,2)],{type:"application/json"})));byId("download-world-manifest").addEventListener("click",()=>download(`${flora.logicalID}-world-manifest.json`,new Blob([JSON.stringify(worldManifest(),null,2)],{type:"application/json"})));byId("import-flora-json").addEventListener("change",async event=>{try{const file=event.target.files?.[0];if(!file)return;flora=normalizeFlora(JSON.parse(await file.text()));world=sampleWorld(flora);status("Flora imported.");renderAll();}catch(error){status(`Import failed: ${error.message}`,true);}});document.querySelectorAll("[data-world-export]").forEach(button=>button.addEventListener("click",()=>{const key=button.dataset.worldExport,canvas=key==="flora-world"?canvases.world:key==="flora-hostile"?canvases.hostile:canvases.detail;canvas.toBlob(blob=>download(`${flora.logicalID}-${key}.png`,blob),"image/png");}));byId("export-map").addEventListener("click",()=>canvases.map.toBlob(blob=>download(`${flora.logicalID}-phone-map.png`,blob),"image/png"));renderAll();
