import Link from '@/components/wiki-link';
import { DirectoryDetailsIntro, DirectoryIndex } from '@/components/directory-navigation';
import { GuideBreadcrumbs, RelatedGuides } from '@/components/guide-navigation';
import { PageIntro } from '@/components/page-intro';
import { PixelImage } from '@/components/pixel-image';
import { SiteFrame } from '@/components/site-frame';
import { TruthPair } from '@/components/truth-pair';
import { equipment, gearValue, humanize, itemProperties } from '@/lib/content';
import { craftingRecipes, recipeReadiness, systemFor } from '@/lib/crafting';
import { materialPropertyProblems } from '@/lib/crafting-overview';

const slots = ['weapon', 'offhand', 'head', 'armor', 'hands', 'feet', 'tool', 'keepsake'];
const recipeFor = (name: string) => craftingRecipes.find((recipe) => recipe.result === name);

export default function EquipmentPage() {
  return <SiteFrame sidebar><GuideBreadcrumbs items={[{ label: 'Home', href: '/' }, { label: 'Equipment' }]} /><PageIntro eyebrow="Reference" title="Equipment" summary="Compare gear by slot, then learn how to equip it, where it is stored, how materials affect it, and how crafting and reforging work. Each item page contains its complete facts." />
    <DirectoryIndex label="Browse equipment" entries={equipment.map((item) => ({ href: `/equipment/${item.slug}`, name: item.name, imageURL: item.assetURL, imageAlt: `${item.name} icon` }))} />
    <DirectoryDetailsIntro title="Compare equipment by slot" summary="Scan tier, rarity, combat facts, material properties, and how each item is made. Open an item for its complete entry." />
    {slots.map(slot => { const items = equipment.filter(item => item.gear?.slot === slot); if (!items.length) return null; return <section className="article-section" key={slot}><h2>{humanize(slot)}</h2><p className="catalogue-guidance">Select an item image or name to open its full entry.</p><div className="table-wrap data-table catalogue-summary"><table><thead><tr><th aria-label="Image" /><th>Item</th><th>Tier</th><th>Rarity</th><th>Combat facts</th><th>Material effects</th><th>How to make it</th></tr></thead><tbody>{items.map(item => { const recipe = recipeFor(item.name); const system = recipe ? systemFor(recipe.system) : null; return <tr key={item.id}><td><Link href={`/equipment/${item.slug}`} aria-label={`Open ${item.name}`}><PixelImage src={item.assetURL} alt={`${item.name} icon`} /></Link></td><td><Link href={`/equipment/${item.slug}`}>{item.name}</Link><small>{item.summary}</small></td><td>{gearValue(item, 'tier')}</td><td><span className={`rarity rarity-${item.rarity}`}>{humanize(item.rarity)}</span></td><td>{[gearValue(item, 'damage'), gearValue(item, 'reach')].filter(value => value !== '—').join(' · ') || 'See item details'}</td><td>{itemProperties(item).slice(0, 2).join(' · ') || '—'}</td><td>{recipe && system ? <><Link href={`/crafting/${recipe.system}`}>{system.station}</Link><small>{recipe.name} · {recipeReadiness(recipe)}</small></> : 'No crafting recipe is available yet'}</td></tr>; })}</tbody></table></div></section>; })}
    <section className="article-section two-column"><div><h2>Choose a compatible piece</h2><p>At Home, the picker shows compatible gear that is Stored, Waiting to sort, Worn by another person, or Carried in a world. Compare the worn piece with the selected replacement before choosing Equip.</p><p>Take it off removes only the current piece from that person. If the change is unavailable, the worn piece stays in place.</p></div><div><h2>Check where the gear is</h2><p>If someone else is wearing a piece, the game tells you rather than silently taking it from them. Gear carried during an expedition cannot be changed until the party returns. If no crafting recipe is listed, use the item page to check for another known way to obtain it.</p></div></section>
    <section className="article-section"><h2>Material choice is part of the finished piece</h2><p>Current recipes ask for one suitable material sample in each slot. The preview shows where it came from, its grade, and how it changes the result; one sample cannot fill two slots at once.</p><div className="definition-grid"><div><h3>Preview before making</h3><p>Change a selected material to compare the resulting item before confirming.</p></div><div><h3>Reset suggestion</h3><p>Reset restores the suggested selection. It does not craft or spend anything.</p></div><div><h3>Quality and history</h3><p>The finished item keeps the selected materials in its history and uses the quality shown in the preview.</p></div><div><h3>How to make it</h3><p>Open the linked station recipe for its ingredients, result, requirements, and reasons it may be unavailable.</p></div></div></section>
    <section className="article-section"><h2>Current eligibility and intended item statistics</h2><TruthPair current="Current recipes often use Hardness, Density, Insulation, Flexibility, Lustre, or Reactivity to decide whether a sample is allowed. Some makers also copy selected Insulation and Reactivity into the finished item’s saved material history." accepted="The physical family, type, or subtype decides whether a material fits a component. Its actual numerical properties change concrete finished-item statistics, and Poor, Common, Rare, or Exceptional quality scales that contribution. Every resulting number appears in the preview before confirmation." acceptedLabel="Intended design" /><div className="table-wrap"><table><thead><tr><th>Property</th><th>Intended equipment role</th></tr></thead><tbody>{materialPropertyProblems.map(([property, _current, intended]) => <tr key={property}><td><strong>{property}</strong></td><td>{intended}</td></tr>)}</tbody></table></div><p className="note-card"><strong>Will discuss with Aimee:</strong> the exact per-property, per-component conversion into damage, protection, initiative, resistance, potency, and other approved item statistics.</p></section>
    <section className="article-section"><h2>Crafting and reforging</h2><p>The Blacksmith makes gear from the recipe and materials you choose. Reforge changes one eligible Stored or Worn piece, shows its next cost and improvement, and keeps its construction history. A fully reforged piece cannot be improved again; if the chosen piece, available materials, or price changes, review the updated preview before confirming.</p><p>Use <Link href="/techniques">Techniques and Gambits</Link> for a character’s current skill limits, and <Link href="/statuses">Conditions and effects</Link> when a treatment or encounter effect is involved.</p></section>
    <RelatedGuides links={[{ label: 'Crafting', href: '/crafting' }, { label: 'Blacksmith', href: '/crafting/blacksmith' }, { label: 'Resources', href: '/resources' }, { label: 'Inventory and storage', href: '/systems/inventory-custody' }, { label: 'Party preparation', href: '/systems/party-preparation' }, { label: 'Combat', href: '/systems/combat' }]} />
  </SiteFrame>;
}
