import Link from 'next/link';
import { PageIntro } from '@/components/page-intro';
import { PixelImage } from '@/components/pixel-image';
import { SiteFrame } from '@/components/site-frame';
import { equipment, gearValue, humanize, itemProperties } from '@/lib/content';
import { craftingRecipes, recipeReadiness, systemFor } from '@/lib/crafting';

const slots = ['weapon', 'offhand', 'head', 'armor', 'hands', 'feet', 'tool', 'keepsake'];
const recipeFor = (name: string) => craftingRecipes.find((recipe) => recipe.result === name);

export default function EquipmentPage() {
  return <SiteFrame sidebar><PageIntro eyebrow="Reference" title="Equipment" summary="Compare every current gear entry by its usable slot and current combat facts. Open an item for its recipe route, ownership guidance, material facts and reforge links." />
    <section className="article-section note-card"><h2>Choosing and keeping gear</h2><p>At Home, the picker shows every compatible physical item you own: Stored, Waiting to sort, Worn by another person, or Carried in world. The worn item is shown separately. A piece worn by someone else can be swapped into the same slot; gear carried in an active expedition stays read-only until the party returns.</p><p>A “No current recipe published” row means this retained gear entry does not have a matching current craft output in the Player Wiki. It does not invent another acquisition route; use the Crafting directory for the station’s current outputs.</p><p>Use <Link href="/techniques">Techniques and Gambits</Link> for an actor’s current skill limits, and <Link href="/statuses">Conditions and effects</Link> when a weapon treatment or encounter effect is involved.</p></section>
    {slots.map(slot => { const items = equipment.filter(item => item.gear?.slot === slot); if (!items.length) return null; return <section className="article-section" key={slot}><h2>{humanize(slot)}</h2><p className="catalogue-guidance">Select an item image or name to open its full entry.</p><div className="table-wrap data-table catalogue-summary"><table><thead><tr><th aria-label="Image" /><th>Item</th><th>Tier</th><th>Rarity</th><th>Current combat facts</th><th>Other material facts</th><th>Current recipe route</th></tr></thead><tbody>{items.map(item => { const recipe = recipeFor(item.name); const system = recipe ? systemFor(recipe.system) : null; return <tr key={item.id}><td><Link href={`/equipment/${item.slug}`} aria-label={`Open ${item.name}`}><PixelImage src={item.assetURL} alt={`${item.name} icon`} /></Link></td><td><Link href={`/equipment/${item.slug}`}>{item.name}</Link><small>{item.summary}</small></td><td>{gearValue(item, 'tier')}</td><td><span className={`rarity rarity-${item.rarity}`}>{humanize(item.rarity)}</span></td><td>{[gearValue(item, 'damage'), gearValue(item, 'reach')].filter(value => value !== '—').join(' · ') || 'See item details'}</td><td>{itemProperties(item).slice(0, 2).join(' · ') || '—'}</td><td>{recipe && system ? <><Link href={`/crafting/${recipe.system}`}>{system.station}</Link><small>{recipe.name} · {recipeReadiness(recipe)}</small></> : 'No current recipe published'}</td></tr>; })}</tbody></table></div></section>; })}
  </SiteFrame>;
}
