import Link from '@/components/wiki-link';
import { DirectoryDetailsIntro, DirectoryIndex } from '@/components/directory-navigation';
import { GuideBreadcrumbs, RelatedGuides } from '@/components/guide-navigation';
import { PageIntro } from '@/components/page-intro';
import { PixelImage } from '@/components/pixel-image';
import { SiteFrame } from '@/components/site-frame';
import { TruthPair } from '@/components/truth-pair';
import { equipment, gearValue, humanize, itemProperties } from '@/lib/content';
import { craftingRecipes, recipeReadiness, systemFor } from '@/lib/crafting';
import { materialPropertyProblems } from '@/lib/crafting-overview';

const slots = ['weapon', 'offhand', 'head', 'armor', 'hands', 'feet', 'tool', 'keepsake'];
const recipeFor = (name: string) => craftingRecipes.find((recipe) => recipe.result === name);

export default function EquipmentPage() {
  return <SiteFrame sidebar><GuideBreadcrumbs items={[{ label: 'Home', href: '/' }, { label: 'Equipment' }]} /><PageIntro eyebrow="Reference" title="Equipment" summary="Compare every current gear entry by slot, then use the shared rules below for equipping, custody, material effects, crafting, and reforging. Each item page contains its complete individual facts." />
    <DirectoryIndex label="Browse equipment" entries={equipment.map((item) => ({ href: `/equipment/${item.slug}`, name: item.name, imageURL: item.assetURL, imageAlt: `${item.name} icon` }))} />
    <DirectoryDetailsIntro title="Compare equipment by slot" summary="Scan tier, rarity, combat facts, material properties, and current recipe route without repeating the full item entry." />
    {slots.map(slot => { const items = equipment.filter(item => item.gear?.slot === slot); if (!items.length) return null; return <section className="article-section" key={slot}><h2>{humanize(slot)}</h2><p className="catalogue-guidance">Select an item image or name to open its full entry.</p><div className="table-wrap data-table catalogue-summary"><table><thead><tr><th aria-label="Image" /><th>Item</th><th>Tier</th><th>Rarity</th><th>Current combat facts</th><th>Other material facts</th><th>Current recipe route</th></tr></thead><tbody>{items.map(item => { const recipe = recipeFor(item.name); const system = recipe ? systemFor(recipe.system) : null; return <tr key={item.id}><td><Link href={`/equipment/${item.slug}`} aria-label={`Open ${item.name}`}><PixelImage src={item.assetURL} alt={`${item.name} icon`} /></Link></td><td><Link href={`/equipment/${item.slug}`}>{item.name}</Link><small>{item.summary}</small></td><td>{gearValue(item, 'tier')}</td><td><span className={`rarity rarity-${item.rarity}`}>{humanize(item.rarity)}</span></td><td>{[gearValue(item, 'damage'), gearValue(item, 'reach')].filter(value => value !== '—').join(' · ') || 'See item details'}</td><td>{itemProperties(item).slice(0, 2).join(' · ') || '—'}</td><td>{recipe && system ? <><Link href={`/crafting/${recipe.system}`}>{system.station}</Link><small>{recipe.name} · {recipeReadiness(recipe)}</small></> : 'No current recipe published'}</td></tr>; })}</tbody></table></div></section>; })}
    <section className="article-section two-column"><div><h2>Choose a compatible piece</h2><p>At Home, the picker shows compatible physical gear that is Stored, Waiting to sort, Worn by another person, or Carried in world. Compare the current piece with the exact selected replacement before choosing Equip.</p><p>Take it off removes only the current piece from that person. A refused or unavailable change keeps the worn piece in place.</p></div><div><h2>Read location before moving it</h2><p>A piece worn by someone else is identified instead of being silently reassigned. Gear carried in an active expedition stays read-only until the party returns. “No current recipe published” does not invent another acquisition route.</p></div></section>
    <section className="article-section"><h2>Material choice is part of the finished piece</h2><p>Current material recipes ask for one exact eligible sample in each requirement. The preview shows its provenance, grade, and current result; one sample cannot fill two requirements at once.</p><div className="definition-grid"><div><h3>Preview before making</h3><p>Change a selected material to compare the resulting item before committing.</p></div><div><h3>Reset suggestion</h3><p>Reset restores the current suggested selection. It does not craft or spend anything.</p></div><div><h3>Quality and history</h3><p>The completed receipt keeps the selected material history and the quality shown by the current preview.</p></div><div><h3>Current recipe route</h3><p>Open the linked station recipe for its exact inputs, output, access, and refusal behavior.</p></div></div></section>
    <section className="article-section"><h2>Current eligibility and intended item statistics</h2><TruthPair current="Current recipes often use Hardness, Density, Insulation, Flexibility, Lustre, or Reactivity to decide whether a sample is allowed. Some makers also copy selected Insulation and Reactivity into the finished gear receipt." accepted="The physical family, type, or subtype decides whether a material fits a component. Its actual numerical properties change concrete finished-item statistics, and Poor, Common, Rare, or Exceptional quality scales that contribution. Every resulting number appears in the preview before confirmation." acceptedLabel="Intended design" /><div className="table-wrap"><table><thead><tr><th>Property</th><th>Intended equipment role</th></tr></thead><tbody>{materialPropertyProblems.map(([property, _current, intended]) => <tr key={property}><td><strong>{property}</strong></td><td>{intended}</td></tr>)}</tbody></table></div><p className="note-card"><strong>Will discuss with Aimee:</strong> the exact per-property, per-component conversion into damage, protection, initiative, resistance, potency, and other approved item statistics.</p></section>
    <section className="article-section"><h2>Crafting and reforging</h2><p>The Blacksmith’s Make work constructs current physical gear from the selected recipe and materials. Reforge chooses one exact eligible Stored or Worn piece, names its next cost and improvement, and keeps its construction history. A fully reforged piece stays unavailable; a changed piece, stock, or quote requires a fresh preview.</p><p>Use <Link href="/techniques">Techniques and Gambits</Link> for an actor’s current skill limits, and <Link href="/statuses">Conditions and effects</Link> when a treatment or encounter effect is involved.</p></section>
    <RelatedGuides links={[{ label: 'Crafting', href: '/crafting' }, { label: 'Blacksmith', href: '/crafting/blacksmith' }, { label: 'Resources', href: '/resources' }, { label: 'Inventory and custody', href: '/systems/inventory-custody' }, { label: 'Party preparation', href: '/systems/party-preparation' }, { label: 'Combat', href: '/systems/combat' }]} />
  </SiteFrame>;
}
