import Link from '@/components/wiki-link';
import { GuideBreadcrumbs, RelatedGuides } from '@/components/guide-navigation';
import { PageIntro } from '@/components/page-intro';
import { PixelImage } from '@/components/pixel-image';
import { SiteFrame } from '@/components/site-frame';
import { TruthPair } from '@/components/truth-pair';
import { canonicalStackExample, inventoryViews, legacyBandMigrationRules, legacyMigrationRules, materialCustodyFlow, materialIdentityHierarchy, qualityRules, sourceLotRules } from '@/lib/crafting-overview';
import { content } from '@/lib/content';

export default function InventoryCustodyGuide() {
  const supply = content.items.find((item) => item.consumable && item.assetURL);
  const gear = content.items.find((item) => item.gear && item.assetURL);
  const storehouse = content.stations.find((station) => station.id === 'storehouse');
  return <SiteFrame sidebar>
    <GuideBreadcrumbs items={[{ label: 'Systems', href: '/systems' }, { label: 'Inventory and storage' }]} />
    <PageIntro eyebrow="Current system guide" title="Inventory and storage" summary="Use the Storehouse to see what is stored or waiting, prepare identified supplies for the Field Kit, and check where each item is before selling, recycling, crafting, equipping, or replacing it." />
    <section className="article-section journey-strip">{storehouse?.assetURL && <Link href="/buildings/storehouse"><PixelImage src={storehouse.assetURL} alt="Storehouse building visual" size={64} /><span><strong>Storehouse</strong><small>Review stored items, material reserves, Field Kit planning, and Waiting.</small></span></Link>}{supply?.assetURL && <Link href={`/items/${supply.slug}`}><PixelImage src={supply.assetURL} alt={`${supply.name} supply icon`} size={64} /><span><strong>Carried supplies</strong><small>Use the exact item prepared for the active Field Kit.</small></span></Link>}{gear?.assetURL && <Link href={`/equipment/${gear.slug}`}><PixelImage src={gear.assetURL} alt={`${gear.name} gear icon`} size={64} /><span><strong>Gear ownership</strong><small>Compare the piece, its slot, and its current location.</small></span></Link>}</section>
    <section className="article-section"><h2>Current inventory and intended material stacks</h2><TruthPair current="The current game mixes counted World resources, individual natural materials that remember their source, and ordinary item stacks. These are not yet shown consistently across every service." accepted={`Mined resources use one simple exact-name quantity stack: Sand is Sand and Gold is Gold, always in the normal/green presentation. Ordinary flora materials stack by physical type or subtype without quality. Approved creature materials use subtype plus quality, such as ${canonicalStackExample}; expanding one reveals the exact species, colour, source world, values, and history behind its owned units. All material stacks are slot-free in the Field and Storehouse.`} acceptedLabel="Intended design" /></section>
    <section className="article-section"><h2>Material identity</h2><div className="table-wrap"><table><thead><tr><th>Level</th><th>Example</th><th>Purpose</th></tr></thead><tbody>{materialIdentityHierarchy.map(([level, example, use]) => <tr key={level}><td><strong>{level}</strong></td><td>{example}</td><td>{use}</td></tr>)}</tbody></table></div><h3>Creature-material quality</h3><p>Mined resources and ordinary flora materials do not use these bands. They remain ungraded and stack by exact material type or subtype and quantity.</p><div className="definition-grid">{qualityRules.map(([band, behavior]) => <div key={band}><h3>{band}</h3><p>{behavior}</p></div>)}</div></section>
    <section className="article-section"><h2>Choose how inventory is grouped</h2><p>Changing a view changes only how holdings are browsed. It never merges ownership, rewrites history, or changes what a recipe may consume.</p><div className="table-wrap"><table><thead><tr><th>View</th><th>Grouping</th><th>Meaning</th></tr></thead><tbody>{inventoryViews.map(([view, grouping, meaning]) => <tr key={view}><td><strong>{view}</strong></td><td>{grouping}</td><td>{meaning}</td></tr>)}</tbody></table></div></section>
    <section className="article-section"><h2>When a stack contains different sources</h2><p>The compact stack remains the normal view. The game asks you to choose a source only when that choice changes the result.</p><div className="definition-grid">{sourceLotRules.map(([rule, behavior]) => <div key={rule}><h3>{rule}</h3><p>{behavior}</p></div>)}</div></section>
    <section className="article-section"><h2>What happens to materials in an older save</h2><p>The migration preserves stock instead of guessing what an old generic sample “must have been.”</p><div className="definition-grid">{legacyMigrationRules.map(([rule, behavior]) => <div key={rule}><h3>{rule}</h3><p>{behavior}</p></div>)}</div><h3>Existing creature-material bands</h3><div className="table-wrap"><table><thead><tr><th>Existing band</th><th>New band</th></tr></thead><tbody>{legacyBandMigrationRules.map(([before, after]) => <tr key={before}><td>{before}</td><td>{after}</td></tr>)}</tbody></table></div><p>Peerless becomes Exceptional because Peerless will belong only to finished equipment. Existing world or flora stock becomes ungraded without losing its old sale value: that value remains on its legacy source lot. Exact Pulp and Resin can join their matching stacks; generic Timber, Fibre, Toxin, and Reagent remain Legacy unless their receipt proves a specific new material.</p></section>
    <section className="article-section"><h2>How the same material moves through the game</h2><div className="table-wrap"><table><thead><tr><th>Where you see it</th><th>How it works now</th><th>Intended design</th></tr></thead><tbody>{materialCustodyFlow.map(([surface, current, intended]) => <tr key={surface}><td><strong>{surface}</strong></td><td>{current}</td><td>{intended}</td></tr>)}</tbody></table></div></section>
    <section className="article-section"><h2>Read the location label</h2><div className="definition-grid"><div><h3>Stored</h3><p>Stored items are in the Storehouse. Open the exact stack before choosing an available transfer, sale, craft sample, gear change, or Recycler preview.</p></div><div><h3>Waiting</h3><p>Waiting holds returned items when storage cannot take them immediately. Resolve the exact keep-or-replace choice; returned loot is not silently discarded.</p></div><div><h3>Carried</h3><p>Carried supplies and haul belong to the active expedition. The world’s carried strip and Field Kit show their current quantity and identity.</p></div><div><h3>Worn</h3><p>Worn gear belongs to the named party member. A piece worn by another person is marked as such rather than silently moved to a different slot.</p></div></div></section>
    <section className="article-section two-column"><div><h2>Prepare the Field Kit at Home</h2><p>Open Storehouse, choose the exact eligible identified supply, and review the next Field Kit plan before departing. Instruments are listed separately from supplies. In the world, Field Kit shows only what was actually carried for that expedition.</p><p>When a satchel is full, choose the exact item or page to leave behind, or keep what is already carried. Cancelling keeps the present carried selection unchanged.</p></div><div><h2>Gear stays with its owner</h2><p>Gear selection starts from the chosen party member and slot. A Stored option can be equipped at Home when it fits; carried gear waits until the party returns Home. Take it off removes the current item from that one person, and an unavailable replacement leaves the current piece worn.</p><p><Link href="/equipment">Read equipment and material effects</Link></p></div></section>
    <section className="article-section note-card"><h2>Harvesting tools have their own space</h2><p>In the intended system, the opening Rock Pick, Axe, and Scythe fit a dedicated three-place tool roll—one place for each class. They do not use the satchel or Field Kit spaces meant for remedies, Pages, and other supplies. A better tool replaces the lower tier in its class, and only the tools actually packed for that expedition appear in the field selector.</p></section>
    <section className="article-section"><h2>Spend or move only what you selected</h2><div className="definition-grid"><div><h3>Trading Post</h3><p>Buy or sell the listing, stored item, Waiting item, or amount of material shown. If the price, stock, funds, space, or selected item changes, review the offer again before anything moves.</p></div><div><h3>Recycler</h3><p>Choose an eligible Stored piece of gear, then read its preview. Previewing changes nothing; only a completed dismantle removes that piece and adds the materials shown.</p></div><div><h3>Crafting and reforging</h3><p>Recipes use the Stored materials you select. Nothing is spent until the craft succeeds. Gear stations show whether the selected target is Stored or Worn before confirmation.</p></div><div><h3>Field use</h3><p>Select one carried item and, when needed, one target. If the item, target, turn, or world changes, reopen the detail and choose again; the game will not spend a different item.</p></div></div></section>
    <section className="article-section"><h2>When the game asks you to review a choice</h2><p>Selection, preview, Cancel, and Back let you inspect something without moving it. If the game says an item, slot, stock, target, or available space has changed, review the refreshed choice. It does not mean another item was used, sold, replaced, or dismantled.</p></section>
    <RelatedGuides links={[{ label: 'Move an item or material', href: '/actions/transfer-custody' }, { label: 'Equip gear', href: '/actions/equip' }, { label: 'Storehouse', href: '/buildings/storehouse' }, { label: 'Consumables and Field Kit', href: '/consumables' }, { label: 'Equipment', href: '/equipment' }, { label: 'Economy and exchange', href: '/trading' }, { label: 'Crafting', href: '/crafting' }, { label: 'Resources', href: '/resources' }]} />
  </SiteFrame>;
}
