import Link from 'next/link';
import { GuideBreadcrumbs, RelatedGuides } from '@/components/guide-navigation';
import { PageIntro } from '@/components/page-intro';
import { PixelImage } from '@/components/pixel-image';
import { SiteFrame } from '@/components/site-frame';
import { content } from '@/lib/content';

export default function InventoryCustodyGuide() {
  const supply = content.items.find((item) => item.consumable && item.assetURL);
  const gear = content.items.find((item) => item.gear && item.assetURL);
  const storehouse = content.stations.find((station) => station.id === 'storehouse');
  return <SiteFrame sidebar>
    <GuideBreadcrumbs items={[{ label: 'Systems', href: '/systems' }, { label: 'Inventory and custody' }]} />
    <PageIntro eyebrow="Current system guide" title="Inventory and custody" summary="Use Storehouse to see what is stored or waiting, prepare exact identified supplies for the Field Kit before departure, and read each item’s location before selling, recycling, crafting, equipping, or replacing it." />
    <section className="article-section journey-strip">{storehouse?.assetURL && <Link href="/services/storehouse"><PixelImage src={storehouse.assetURL} alt="Storehouse building visual" size={64} /><span><strong>Storehouse</strong><small>Review stored items, material reserves, Field Kit planning, and Waiting.</small></span></Link>}{supply?.assetURL && <Link href={`/items/${supply.slug}`}><PixelImage src={supply.assetURL} alt={`${supply.name} supply icon`} size={64} /><span><strong>Carried supplies</strong><small>Use the exact item prepared for the active Field Kit.</small></span></Link>}{gear?.assetURL && <Link href={`/equipment/${gear.slug}`}><PixelImage src={gear.assetURL} alt={`${gear.name} gear icon`} size={64} /><span><strong>Gear ownership</strong><small>Compare the piece, its slot, and its current location.</small></span></Link>}</section>
    <section className="article-section"><h2>Read the location label</h2><div className="definition-grid"><div><h3>Stored</h3><p>Stored items are in the Storehouse. Open the exact stack before choosing an available transfer, sale, craft sample, gear change, or Recycler preview.</p></div><div><h3>Waiting</h3><p>Waiting holds returned items when storage cannot take them immediately. Resolve the exact keep-or-replace choice; returned loot is not silently discarded.</p></div><div><h3>Carried</h3><p>Carried supplies and haul belong to the active expedition. The world’s carried strip and Field Kit show their current quantity and identity.</p></div><div><h3>Worn</h3><p>Worn gear belongs to the named party member. A piece worn by another person is marked as such rather than silently moved to a different slot.</p></div></div></section>
    <section className="article-section two-column"><div><h2>Prepare the Field Kit at Home</h2><p>Open Storehouse, choose the exact eligible identified supply, and review the next Field Kit plan before departing. Instruments are listed separately from supplies. In the world, Field Kit shows only what was actually carried for that expedition.</p><p>When a satchel is full, choose the exact item or page to leave behind, or keep what is already carried. Cancelling keeps the present carried selection unchanged.</p></div><div><h2>Gear stays with its owner</h2><p>Gear selection starts from the chosen party member and slot. A Stored option can be equipped at Home when it fits; carried gear waits until the party returns Home. Take it off removes the current item from that one person, and an unavailable replacement leaves the current piece worn.</p><p><Link href="/systems/equipment-materials">Read equipment and material effects</Link></p></div></section>
    <section className="article-section"><h2>Spend or move only the selected holding</h2><div className="definition-grid"><div><h3>Trading Post</h3><p>Buy or sell the exact listing, stored item, Waiting item, or reserve material amount shown in the current sheet. If price, stock, funds, capacity, or identity changes, the offer remains uncommitted.</p></div><div><h3>Recycler</h3><p>Choose an eligible Stored gear item, then read its preview. Previewing changes nothing; only a completed dismantle removes that selected piece and adds its shown yield.</p></div><div><h3>Crafting and reforging</h3><p>Recipe sockets use exact Stored material samples. A selection is not spent until the current craft completes. Gear stations identify whether the chosen target is Stored or Worn before their own preview and confirmation.</p></div><div><h3>Field use</h3><p>Select one carried item and one current target where required. A changed item, target, turn, or world state leaves the shown use uncommitted; reopen the detail and choose again.</p></div></div></section>
    <section className="article-section"><h2>Keep refusals useful</h2><p>Selection, preview, Cancel, and Back let you inspect a current holding without moving it. When a face says the exact item, slot, stock, target, or capacity changed, treat that as a request to review the refreshed current state—not as proof that another item was used, sold, replaced, or dismantled.</p></section>
    <RelatedGuides links={[{ label: 'Transfer custody', href: '/actions/transfer-custody' }, { label: 'Equip gear', href: '/actions/equip' }, { label: 'Storehouse and inventory', href: '/services/storehouse' }, { label: 'Field supplies', href: '/systems/field-supplies' }, { label: 'Equipment and material effects', href: '/systems/equipment-materials' }, { label: 'Trading Post', href: '/services/trading-post' }, { label: 'Recycler', href: '/services/recycler' }, { label: 'Crafting systems', href: '/crafting' }, { label: 'Resources', href: '/resources' }]} />
  </SiteFrame>;
}
