export const anchorageFirstAnchor = {
  travellerID: 'tovin',
  stationID: 'anchorage',
  frameID: 'anchor_frame',
  seamID: 'natural_anchor',
  construction: '200 Essence · 40 Iron Ore · 20 Quartz · 18 Pulp',
  frameRequirements: [
    '2 different world materials with Hardness 65+',
    '2 different world materials with Density 65+',
    '1 world material with Flexibility 55+',
    '1 world material with Reactivity 65+',
    '60 Essence',
  ],
  journey: [
    'Recruit Tovin. His arrival reveals one Anchorage foundation in Home → Realms.',
    'Build the foundation when you have the displayed 200 Essence, 40 Iron Ore, 20 Quartz, and 18 Pulp.',
    'Enter the Anchorage. Its empty portfolio keeps no realm and produces nothing merely because the room exists.',
    'For a portable alternative to a Seam, make one Anchor Frame from six different qualifying materials and 60 Essence. It goes to the Storehouse or Waiting destination shown and is not packed into the Field Kit automatically.',
    'On a revealed Atlas Seam, use Look and review that Seam’s current Essence quote. A Seam is one discovered site, not a promise about fogged ground elsewhere.',
    'Confirm the Atlas Seam, world, and displayed cost. Once the game finishes saving the anchor, the world remains available and the current expedition continues.',
    'After returning from the expedition, revisit the same saved realm from the Anchorage when you can pay the departure cost shown there.',
  ],
  frameCustody: [
    'An Anchor Frame is not required at an Atlas Seam. If you anchor through the natural Seam, an unused Frame stays in your carried inventory.',
    'An Anchor Frame travels only when you add it to the Field Kit plan. Crafting one does not pack it automatically.',
    'One Frame uses six different qualifying material units; ordinary counted resources such as Iron Ore, Quartz, or Pulp cannot substitute for one of them.',
    'The finished Frame is kept in the Storehouse or Waiting destination shown during construction. Inspecting it does not currently show the history of every material used.',
  ],
  seamConfirmation: [
    'Look and finding the Atlas Seam cost no turn, give no reward, and do not anchor a realm automatically.',
    'Confirming spends only the displayed Essence cost and anchors the Seam and realm you reviewed.',
    'Cancelling, a changed preview, another busy action, insufficient Essence, or a failed save spends nothing and leaves the current world information unchanged.',
    'A realm already held in the Anchorage cannot be paid for or anchored a second time.',
  ],
  firstRealm: [
    'Born anchored worlds, Atlas Seams, and Anchor Frames all preserve the same kind of world. The method used is part of its history, not a quality rank.',
    'Anchoring preserves the same realm and its state. It does not end the expedition, bring the current haul home, reset the world, duplicate a Frame, or create a delivery.',
    'The first anchored realm needs no immediate upkeep and has no person assigned to it. Sustain or Let rest becomes a separate choice later when a realm comes due.',
    'Work and Deliveries are not available yet: the first anchor does not choose renewable work or start passive production.',
  ],
  relaunch: [
    'If the game closes before a build or anchor succeeds, reopening shows the current requirements again and spends nothing.',
    'If the game closes after a build, Frame, or anchor succeeds, reopening restores that one result without charging again or making a duplicate.',
    'A later revisit uses the same saved realm snapshot; it does not regenerate the map, restore depleted unique sites, or collect a delivery.',
  ],
} as const;
