import Link from '@/components/wiki-link';
import { GuideBreadcrumbs, RelatedGuides } from '@/components/guide-navigation';
import { PageIntro } from '@/components/page-intro';
import { PixelImage } from '@/components/pixel-image';
import { SiteFrame } from '@/components/site-frame';
import { TruthPair } from '@/components/truth-pair';
import { content } from '@/lib/content';
import { recipesUsingResource } from '@/lib/crafting';
import { incrementalDelivery, progressionPlan } from '@/lib/crafting-overview';

const bandOrder = ['Staple', 'Uncommon', 'Rare', 'Precious', 'Nontradeable'];

function buildingUses(resourceID: string) {
  return content.stations.filter((station) =>
    station.buildCost.some(
      (cost) => (cost.id ?? cost.resource ?? cost.resourceID) === resourceID,
    ),
  );
}

export default function ProgressionReference() {
  const storehouse = content.stations.find((station) => station.id === 'storehouse');
  const firstGear = content.items.find((item) => item.gear && item.assetURL);
  return <SiteFrame sidebar>
    <GuideBreadcrumbs items={[{ label: 'Resources', href: '/resources' }, { label: 'Current progression' }]} />
    <PageIntro eyebrow="Player reference" title="Current progression" summary="Use this checklist to choose something you can do now. It follows the current journey from Writing and Binding through exploration, returning home, improving the Village, Research, party preparation, and the next expedition—without presenting future plans as playable." />
    <section className="article-section journey-strip"><Link href="/systems/world-writing"><img src={content.writingAssetURL} alt="Writing Desk parchment" /><span><strong>Write and Bind</strong><small>Shape the next Page and read its current preview.</small></span></Link><Link href="/systems/exploration"><img src={content.explorationVisuals.entryPortal} alt="Entry portal" /><span><strong>Explore and return</strong><small>Use the entry portal, visit discovered sites, and return when you are ready.</small></span></Link>{storehouse?.assetURL && <Link href="/buildings/storehouse"><PixelImage src={storehouse.assetURL} alt="Storehouse building visual" size={58} /><span><strong>Review what returned</strong><small>Check storage, Waiting, and the next Field Kit plan.</small></span></Link>}{firstGear?.assetURL && <Link href={`/equipment/${firstGear.slug}`}><PixelImage src={firstGear.assetURL} alt={`${firstGear.name} icon`} size={58} /><span><strong>Prepare the party</strong><small>Compare the worn piece, its slot, and its location before departure.</small></span></Link>}</section>
    <section className="article-section"><h2>Current task checklist</h2><ol className="numbered-guide"><li><span><strong>Read the next Page before Binding</strong><p>Choose a hand and ink, place and connect the marks, review the world preview, then Bind when the Page is ready.</p><p><Link href="/systems/world-writing">Open World Writing</Link></p></span></li><li><span><strong>Use the world to recover what you need</strong><p>Enter through the portal, Look at unfamiliar terrain or flora, search revealed sites, and choose which resources and items are worth bringing home.</p><p><Link href="/systems/exploration">Open Exploration</Link> · <Link href="/resources">Browse resources</Link></p></span></li><li><span><strong>Finish the return before planning again</strong><p>Read the expedition result, resolve anything in Waiting, then check the returned goods in the Storehouse. Plan the next Field Kit separately.</p><p><Link href="/buildings/storehouse">Open Storehouse and inventory</Link> · <Link href="/systems/inventory-custody">Read inventory and storage</Link></p></span></li><li><span><strong>Choose a Village improvement</strong><p>Compare foundations, station actions, recipes, and services you can afford now. A future name is not playable until its own page says it is ready.</p><p><Link href="/village">Browse Village buildings</Link> · <Link href="/crafting">Browse current crafting</Link> · <Link href="/trading">Compare Trading offers</Link> · <Link href="/recycling">Compare Recycler returns</Link></p></span></li><li><span><strong>Study available Research</strong><p>Open a visible Research entry, check its earlier upgrades and cost, then Study it when every requirement is ready.</p><p><Link href="/research">Open the Research directory</Link> · <Link href="/buildings/library">Open Library collections</Link></p></span></li><li><span><strong>Prepare people, gear, and supplies</strong><p>Choose the party, compare gear by slot and location, arrange Gambits if needed, and pack identified field supplies before the next Bind.</p><p><Link href="/buildings/party">Open Party and Gear</Link> · <Link href="/consumables">Read Field supplies</Link> · <Link href="/systems/combat">Read Combat</Link></p></span></li></ol></section>
    <section className="article-section two-column"><div><h2>Check the game before confirming</h2><p>This page connects the steps, but a particular building, recipe, Research entry, or world may not be ready in your campaign. Read its in-game preview for the current requirement, cost, result, and any reason it is unavailable.</p></div><div><h2>Keep Cottage supplies and expedition gear separate</h2><p>Stored goods, learned records, and completed upgrades remain at the Cottage. Field Kit supplies and gathered loot belong to the current expedition until the return review places them safely.</p></div></section>
    <section className="article-section"><h2>Current progression and intended expansion</h2><TruthPair current="The current campaign unlocks specific stations, Research, recipes, and actions through its existing traveller and construction sequence. Most advanced physical resources do not yet have a complete tool-gated harvesting and processing path." accepted="Worlds may contain advanced materials before the player can collect them. Better harvesting capabilities, processing facilities, facility upgrades, and narrower later recipes create progression without censoring what a generated world is allowed to contain." acceptedLabel="Intended design" /><div className="table-wrap"><table><thead><tr><th>Progression layer</th><th>Intended player rule</th></tr></thead><tbody>{progressionPlan.map(([layer, rule]) => <tr key={layer}><td><strong>{layer}</strong></td><td>{rule}</td></tr>)}</tbody></table></div></section>
    <section className="article-section"><h2>How the overhaul can arrive while the game remains playable</h2><div className="definition-grid">{incrementalDelivery.map(([slice, rule]) => <div key={slice}><h3>{slice}</h3><p>{rule}</p></div>)}</div></section>
    <section className="article-section"><h2>Current resource roles</h2><p>Compare every material in the implemented game by trade band, current crafting consumers, building uses, and the world conditions associated with it.</p></section>
    {bandOrder.map((band) => { const resources = content.resources.filter((resource) => resource.tradeBand === band); return <section className="article-section" key={band}><h2>{band}</h2><div className="table-wrap data-table"><table><thead><tr><th aria-label="Image" /><th>Resource</th><th>Craft recipes</th><th>Building recipes</th><th>World conditions</th></tr></thead><tbody>{resources.map((resource) => { const crafts = recipesUsingResource(resource.id); const buildings = buildingUses(resource.id); return <tr key={resource.id}><td><PixelImage src={resource.assetURL} alt={`${resource.name} inventory icon`} /></td><td><Link href={`/resources/${resource.slug}`}>{resource.name}</Link></td><td>{crafts.length ? `${crafts.length} — ${crafts.slice(0, 2).map((recipe) => recipe.name).join(', ')}${crafts.length > 2 ? '…' : ''}` : 'No documented craft recipe'}</td><td>{buildings.length ? `${buildings.length} — ${buildings.slice(0, 2).map((station) => station.name).join(', ')}${buildings.length > 2 ? '…' : ''}` : 'Not currently a building material'}</td><td>{resource.drivenBy}</td></tr>; })}</tbody></table></div></section>; })}
    <section className="article-section note-card"><h2>How to read the resource table</h2><p>A resource does not need dozens of uses to matter. A rare or nontradeable material may support one distinctive late-game purpose. Each resource page lists every current recipe and building that uses it.</p></section>
    <RelatedGuides links={[{ label: 'Your current journey', href: '/journey' }, { label: 'Getting started', href: '/getting-started' }, { label: 'World Writing', href: '/systems/world-writing' }, { label: 'Exploration', href: '/systems/exploration' }, { label: 'Village', href: '/village' }, { label: 'Research', href: '/research' }, { label: 'Party and Gear', href: '/systems/party-preparation' }]} />
  </SiteFrame>;
}
