import { CreatureHabitatDecisions } from '@/components/creature-habitat-decisions';
import { SolidDeposits } from '@/components/solid-deposits';
import { SeptemberDecisions } from '@/components/september-decisions';
import Link from '@/components/wiki-link';
import { GuideBreadcrumbs, RelatedGuides } from '@/components/guide-navigation';
import { PageIntro } from '@/components/page-intro';
import { SiteFrame } from '@/components/site-frame';
import { content } from '@/lib/content';

export default function Exploration() {
  return <SiteFrame sidebar><GuideBreadcrumbs items={[{ label: 'Systems', href: '/systems' }, { label: 'Exploration' }]} /><PageIntro eyebrow="System guide" title="Exploration" summary="Every expedition begins at an entry portal in a generated world. Reveal what is nearby, inspect uncertain terrain, gather what you can carry, and decide when to leave." />
    <SeptemberDecisions topic="exploration" />
    <section className="article-section"><h2>Every valid Page must make a world</h2><p><strong>Current limitation:</strong> A valid Page can still encounter a world-preparation failure. Existing recovery tries alternative layouts while preserving required resources, but it does not yet establish that every supported request will succeed. The recent preparation failure is a defect; asking for an unlucky world is not a player mistake.</p><p><strong>Decided intended behavior:</strong> Every valid supported Page must produce a playable world. Random generation must not leave you with a valid request that cannot be prepared. The game must build the required arrival, routes, lessons, resource sites and return options together while respecting what you wrote. It must not quietly substitute a generic world, change your request, remove promised resources or make you buy another attempt.</p><p>This does not promise every resource or traveller, a fully reachable map, or safety from the dangers you explore. Existing worlds and earned stock stay intact. Invalid or outdated input, missing materials, an unaffordable request or a failed save still need their own honest explanation; Page and Essence spending must succeed together with saving the prepared world.</p><p><strong>Conditional resources — decided intended:</strong> Required resources still depend on the actual world. Compatible rock and deposits establish mineral opportunities; plants need suitable soil, light, water and temperature, with enough connected growing land. Preparing a lawful route or more suitable ground must also reserve any early sources that those conditions require. Optional scenery cannot take their places, and the game cannot remove an already-required source to make preparation pass. This does not require every world to grow a forest or contain the whole starter catalogue.</p><p><strong>Not yet fully delivered:</strong> This requirement is decided. The complete guarantee remains unfinished; correcting one generation defect does not establish it for every supported world.</p><p><strong>Specific repair — delivered in378:</strong> Build378 corrects a preparation failure caused by an Apex creature being checked as an ordinary generated creature. The Apex keeps its existing body and rewards. Internal checks verified the reproduced request, saving and reopening. The exact earlier unsaved request was not recovered, so it is not claimed replayed. This specific repair does not establish the complete world-generation guarantee.</p></section>
    <CreatureHabitatDecisions />
    <SolidDeposits />
    {content.writingAssetURL && <figure className="feature-figure"><img src={content.writingAssetURL} alt="Writing Desk parchment" /><figcaption>Your Page shapes the world before Binding; the world still generates its own exact terrain, sites, creatures, and resources.</figcaption></figure>}
    <section className="article-section"><h2>What your Page can describe</h2><p>The World preview names the current pressures your Writing can influence. It helps you compare the direction of a Page before Binding, but it does not promise exact terrain, sites, creatures, or resources.</p><div className="definition-grid">{content.pressureTargets.map((target) => <div key={target.id}><h3>{target.name}</h3><p>{target.blurb}</p><small>{target.lowLabel} ↔ {target.highLabel}</small></div>)}</div><p><Link href="/systems/world-writing">Write and review a Page</Link></p></section>
    <div className="terrain-strip" aria-label="Examples of world terrain">{content.terrain.slice(0, 8).map(tile => <figure key={tile.name}><img src={tile.assetURL} alt={`${tile.name} terrain`} /><figcaption>{tile.name.replaceAll(/([a-z])([A-Z])/g, '$1 $2')}</figcaption></figure>)}</div>
    <section className="article-section"><h2>What stays on the map</h2><p><strong>Current in364:</strong> observed plants, resources, loose finds, travellers and places retain their last-known appearance outside sight. Enemy mobs disappear. Memory shows no hidden changes and grants no remote action. Observed collection or removal updates the saved record; older saves cannot invent details they never observed.</p><p>Physical sources reserve separate base tiles. A safe overlap correction preserves work, stock and access; known relocations show a saved notice. An ambiguous or unsafe group remains intact for further correction. Raw Essence appears as a blue droplet and stays collected after reopening; its remembered-fog appearance still awaits visual review.</p><div className="exploration-state-strip">{content.explorationVisuals.entryPortal && <figure><img src={content.explorationVisuals.entryPortal} alt="Entry portal" /><figcaption><strong>Entry portal</strong><br />Your arrival remains marked beneath the party.</figcaption></figure>}{content.explorationVisuals.unsearchedSite && <figure><img src={content.explorationVisuals.unsearchedSite} alt="Unsearched site" /><figcaption><strong>Unsearched site</strong><br />A discovered site remains a place you can inspect.</figcaption></figure>}{content.explorationVisuals.searchedSite && <figure><img src={content.explorationVisuals.searchedSite} alt="Searched site" /><figcaption><strong>Searched site</strong><br />Searching changes its state without erasing the place.</figcaption></figure>}</div></section>
    <section className="article-section"><h2>Reading the map</h2><p><strong>Current withdrawal — delivered in378:</strong> After Withdraw and Continue, the group you escaped gives you one complete move to another tile. It does not pursue or re-engage during any part of that move, even on slow terrain. Other creatures and world hazards remain dangerous, and the move still takes its usual time and Stability.</p><p>Looking, opening menus, cancelling a choice or trying a blocked move keeps the opportunity. Waiting, gathering, mining or committing another field action uses it up. Deliberately attacking an escaped foe or stepping onto its tile gives it up. A longer travel route protects only its first step. Saving and reopening preserves an unused opportunity; returning Home or entering another fight ends it.</p><p><strong>Current in377:</strong> After you choose Continue following a withdrawal, At this place immediately describes the tile your party actually returned to. Previously it could keep describing the tile you had left until your next field action. The panel stays in its usual position. The377 correction changed the location display only. Build378 adds the movement protection described above; other combat and recovery rules stay unchanged.</p><ul><li><strong>Unrevealed tiles stay unknown.</strong> Sites, portals, creatures, and deposits do not become reference facts until the game reveals them.</li><li><strong>The entry portal marks your arrival.</strong> It remains the identity of the tile beneath the starting position, including after you leave and return to the same saved world.</li><li><strong>Sites remain on their tiles.</strong> Searching may change a site from unlooted to depleted, but walking onto it does not erase what is there.</li><li><strong>Look is free.</strong> Inspect an adjacent tile to learn disclosed movement, terrain, growth, and danger information without spending a turn.</li></ul></section>
    <section className="article-section two-column"><div><h2>Flora and terrain</h2><p>Use Look before stepping onto an unfamiliar plant or tile. The Field Guide identifies a revealed Flora harvest; the terrain reference explains movement, sight, and current host relationships without predicting a hidden map.</p><p><Link href="/flora">Browse Flora harvest relationships</Link> · <Link href="/terrain">Browse terrain profiles</Link></p></div><div><h2>Resources and sites</h2><p>Resource deposits hold one resource at a specific place. Sites can be searched once their current conditions are met; a searched site keeps its identity while showing its depleted state.</p><p><Link href="/resources">Compare all resources</Link> · <Link href="/sites">Browse current site profiles</Link></p></div></section>
    <section className="article-section two-column"><div><h2>Return and defeat</h2><p>Return through a valid exit to resolve the expedition. Defeat uses the same expedition-outcome flow and returns the party to the Village review instead of continuing the world.</p></div><div><h2>Continue the same world</h2><p>Your active world keeps its current map, position, revealed state, portal and site state when you return to the same saved expedition after relaunching.</p></div></section>
    <section className="article-section"><h2>When a direction is blocked</h2><p><strong>Current limitation:</strong> At the map edge, an outward direction can currently give no useful explanation. Some movement checks instead describe it as a non-adjacent step. The party does not move or spend a turn.</p><p><strong>Decided intended — awaiting delivery:</strong> Pressing a direction beyond the world will explain that you have reached its edge. With Look armed, the same direction will show World boundary and end Look mode. Neither action will spend a turn, move the party or use up pending withdrawal protection. Other blocked terrain will keep its own reason.</p><p>The correction has passed three focused internal checks covering actual control actions, unchanged saved state, terrain rules and the existing collapse forecast. It is awaiting phone delivery; build378 does not include it.</p></section>
    <section className="article-section"><h2>Turns and field preparation</h2><p>A successful step or travel action advances the world under the movement rules. A blocked move does not spend a turn. Use Tile interacts only with the exact feature under the party; the Field Kit uses the supplies you prepared before departure.</p></section>
    <RelatedGuides links={[{ label: 'Move', href: '/actions/move' }, { label: 'Look', href: '/actions/look' }, { label: 'Search a site', href: '/actions/search-site' }, { label: 'Return Home', href: '/actions/return-home' }, { label: 'World Writing', href: '/systems/world-writing' }, { label: 'Combat', href: '/systems/combat' }, { label: 'Bestiary profiles', href: '/bestiary' }, { label: 'Sites and hazards', href: '/sites' }, { label: 'Storehouse and Field Kit', href: '/buildings/storehouse' }, { label: 'Resource reference', href: '/resources' }, { label: 'All systems', href: '/systems' }]} />
  </SiteFrame>;
}
