import Link from 'next/link';
import { GuideBreadcrumbs, RelatedGuides } from '@/components/guide-navigation';
import { PageIntro } from '@/components/page-intro';
import { SiteFrame } from '@/components/site-frame';
import { content } from '@/lib/content';

export default function Exploration() {
  return <SiteFrame sidebar><GuideBreadcrumbs items={[{ label: 'Systems', href: '/systems' }, { label: 'Exploration' }]} /><PageIntro eyebrow="System guide" title="Exploration" summary="Every expedition begins at an entry portal in a generated world. Reveal what is nearby, inspect uncertain terrain, gather what you can carry, and decide when to leave." />
    {content.writingAssetURL && <figure className="feature-figure"><img src={content.writingAssetURL} alt="Writing Desk parchment" /><figcaption>Your Page shapes the world before Binding; the world still generates its own exact terrain, sites, creatures, and resources.</figcaption></figure>}
    <section className="article-section"><h2>What your Page can describe</h2><p>The World preview names the current pressures your Writing can influence. It helps you compare the direction of a Page before Binding, but it does not promise exact terrain, sites, creatures, or resources.</p><div className="definition-grid">{content.pressureTargets.map((target) => <div key={target.id}><h3>{target.name}</h3><p>{target.blurb}</p><small>{target.lowLabel} ↔ {target.highLabel}</small></div>)}</div><p><Link href="/systems/world-writing">Write and review a Page</Link></p></section>
    <div className="terrain-strip" aria-label="Examples of world terrain">{content.terrain.slice(0, 8).map(tile => <figure key={tile.name}><img src={tile.assetURL} alt={`${tile.name} terrain`} /><figcaption>{tile.name.replaceAll(/([a-z])([A-Z])/g, '$1 $2')}</figcaption></figure>)}</div>
    <section className="article-section"><h2>What stays on the map</h2><div className="exploration-state-strip">{content.explorationVisuals.entryPortal && <figure><img src={content.explorationVisuals.entryPortal} alt="Entry portal" /><figcaption><strong>Entry portal</strong><br />Your arrival remains marked beneath the party.</figcaption></figure>}{content.explorationVisuals.unsearchedSite && <figure><img src={content.explorationVisuals.unsearchedSite} alt="Unsearched site" /><figcaption><strong>Unsearched site</strong><br />A discovered site remains a place you can inspect.</figcaption></figure>}{content.explorationVisuals.searchedSite && <figure><img src={content.explorationVisuals.searchedSite} alt="Searched site" /><figcaption><strong>Searched site</strong><br />Searching changes its state without erasing the place.</figcaption></figure>}</div></section>
    <section className="article-section"><h2>Reading the map</h2><ul><li><strong>Unrevealed tiles stay unknown.</strong> Sites, portals, creatures, and deposits do not become reference facts until the game reveals them.</li><li><strong>The entry portal marks your arrival.</strong> It remains the identity of the tile beneath the starting position, including after you leave and return to the same saved world.</li><li><strong>Sites remain on their tiles.</strong> Searching may change a site from unlooted to depleted, but walking onto it does not erase what is there.</li><li><strong>Look is free.</strong> Inspect an adjacent tile to learn disclosed movement, terrain, growth, and danger information without spending a turn.</li></ul></section>
    <section className="article-section two-column"><div><h2>Flora and terrain</h2><p>Use Look before stepping onto an unfamiliar plant or tile. The Field Guide identifies a revealed Flora harvest; the terrain reference explains movement, sight, and current host relationships without predicting a hidden map.</p><p><Link href="/flora">Browse Flora harvest relationships</Link> · <Link href="/terrain">Browse terrain profiles</Link></p></div><div><h2>Resources and sites</h2><p>Resource deposits hold one resource at a specific place. Sites can be searched once their current conditions are met; a searched site keeps its identity while showing its depleted state.</p><p><Link href="/resources">Compare all resources</Link> · <Link href="/sites">Browse current site profiles</Link></p></div></section>
    <section className="article-section two-column"><div><h2>Return and defeat</h2><p>Return through a valid exit to resolve the expedition. Defeat uses the same expedition-outcome flow and returns the party to the Village review instead of continuing the world.</p></div><div><h2>Continue the same world</h2><p>Your active world keeps its current map, position, revealed state, portal and site state when you return to the same saved expedition after relaunching.</p></div></section>
    <section className="article-section"><h2>Turns and field preparation</h2><p>A successful step or travel action advances the world under the movement rules. A blocked move does not spend a turn. Use Tile interacts only with the exact feature under the party; the Field Kit uses the supplies you prepared before departure.</p></section>
    <RelatedGuides links={[{ label: 'Move', href: '/actions/move' }, { label: 'Look', href: '/actions/look' }, { label: 'Search a site', href: '/actions/search-site' }, { label: 'Return Home', href: '/actions/return-home' }, { label: 'World Writing', href: '/systems/world-writing' }, { label: 'Combat', href: '/systems/combat' }, { label: 'Bestiary profiles', href: '/bestiary' }, { label: 'Site directory', href: '/sites' }, { label: 'Storehouse and Field Kit', href: '/services/storehouse' }, { label: 'Resource reference', href: '/resources' }, { label: 'All systems', href: '/systems' }]} />
  </SiteFrame>;
}
