import Link from 'next/link';
import { GuideBreadcrumbs, RelatedGuides } from '@/components/guide-navigation';
import { PageIntro } from '@/components/page-intro';
import { PixelImage } from '@/components/pixel-image';
import { SiteFrame } from '@/components/site-frame';
import { content } from '@/lib/content';

export default function EconomyExchangeGuide() {
  const trading = content.stations.find((station) => station.id === 'trading_post');
  const recycler = content.stations.find((station) => station.id === 'recycler');
  const spring = content.stations.find((station) => station.id === 'essence_spring');
  return <SiteFrame sidebar>
    <GuideBreadcrumbs items={[{ label: 'Systems', href: '/systems' }, { label: 'Economy and exchange' }]} />
    <PageIntro eyebrow="Current system guide" title="Economy and exchange" summary="Compare the exact current listing, resource quantity, refinement preview, or recycling yield before you confirm. The Village screens show what is available now and keep your current holdings unchanged when a choice cannot complete." />
    <section className="article-section journey-strip">{trading?.assetURL && <Link href="/services/trading-post"><PixelImage src={trading.assetURL} alt="Trading Post building visual" size={64} /><span><strong>Trading Post</strong><small>Buy current stock or sell eligible holdings and material quantities.</small></span></Link>}{recycler?.assetURL && <Link href="/services/recycler"><PixelImage src={recycler.assetURL} alt="Recycler building visual" size={64} /><span><strong>Recycler</strong><small>Preview a specific eligible gear item’s authored yield.</small></span></Link>}{spring?.assetURL && <Link href="/services/essence-spring"><PixelImage src={spring.assetURL} alt="Essence Spring building visual" size={64} /><span><strong>Essence Spring</strong><small>Refine Raw Essence into spendable Essence Crystals.</small></span></Link>}</section>
    <section className="article-section"><h2>Trading Post: current listings and material sales</h2><div className="definition-grid"><div><h3>Buy the exact listing</h3><p>Choose Buy, open the exact current listing, and review its item, quantity, price, and stock before confirming. Shop stock can rotate, so the displayed listing is the one you are buying.</p></div><div><h3>Sell an eligible holding</h3><p>Choose Sell and open the exact identified holding. Unidentified objects are not ordinary sale listings.</p></div><div><h3>Sell a material quantity</h3><p>Choose the exact material and quantity from the resource reserve. Material sales use that reserve rather than a Storehouse item slot.</p></div><div><h3>When a trade cannot complete</h3><p>If the shown listing has changed, funds are insufficient, or the selected holding is no longer available, the offer remains uncommitted and your current holdings stay where they are.</p></div></div><p><Link href="/services/trading-post">Open the Trading Post guide</Link> · <Link href="/resources">Compare resources</Link> · <Link href="/consumables">Browse consumables</Link> · <Link href="/curios">Browse curios</Link></p></section>
    <section className="article-section two-column"><div><h2>Refine Raw Essence</h2><p>At the Essence Spring, choose an amount of Raw Essence or the available refine-all option, review the exact current Crystal return, then commit the refinement. Raw Essence and spendable Essence are distinct.</p><p>If the amount or shown rate no longer matches, the reserve remains unchanged.</p><p><Link href="/services/essence-spring">Open the Essence Spring guide</Link></p></div><div><h2>Recycle a specific piece</h2><p>At the Recycler, select eligible stored gear and read its exact dismantling preview. The shown item is removed only after a completed dismantle; the authored material yield is then added.</p><p>Previewing does not consume gear. If the selected item or available capacity changes, the current gear remains in place.</p><p><Link href="/services/recycler">Open the Recycler guide</Link> · <Link href="/equipment">Compare equipment</Link></p></div></section>
    <section className="article-section"><h2>Plan with the current screen</h2><p>Prices, listing quantities, stock, refinement returns, and recycling yields are read from the current detail before you confirm. Use the current Village screen for the final choice, then return to Storehouse or the relevant resource and item page to review what you hold.</p></section>
    <RelatedGuides links={[{ label: 'Trading Post', href: '/services/trading-post' }, { label: 'Recycler', href: '/services/recycler' }, { label: 'Essence Spring', href: '/services/essence-spring' }, { label: 'Storehouse and inventory', href: '/services/storehouse' }, { label: 'Resources', href: '/resources' }, { label: 'All village services', href: '/services' }]} />
  </SiteFrame>;
}
