import Link from 'next/link';
import { GuideBreadcrumbs, RelatedGuides } from '@/components/guide-navigation';
import { PageIntro } from '@/components/page-intro';
import { PixelImage } from '@/components/pixel-image';
import { SiteFrame } from '@/components/site-frame';
import content from '@/data/player-content.json';

export default function Combat() {
  const weapon = content.items.find((item) => item.gear?.slot === 'weapon' && item.assetURL);
  const guard = content.items.find((item) => item.gear?.slot === 'armor' && item.assetURL);
  const traveller = content.travellers.find((person) => person.assetURL);

  return <SiteFrame sidebar><GuideBreadcrumbs items={[{ label: 'Systems', href: '/systems' }, { label: 'Combat' }]} /><PageIntro eyebrow="Current system guide" title="Combat" summary="Encounters show whose turn it is, then ask that acting party member to choose Attack, Techniques, an Item, or Withdraw. Read the current target and status facts before committing a choice." />
    <section className="article-section combat-reference"><h2>Prepare before an encounter</h2><p>Open the linked party and equipment pages when you need the current people or gear behind the encounter screen.</p><div className="combat-reference-strip">
      {traveller && <Link className="combat-reference-card" href={`/people/${traveller.slug}`}><PixelImage src={traveller.assetURL} alt={`${traveller.name} character visual`} size={48} /><span><strong>Party member</strong>{traveller.name}</span></Link>}
      {weapon && <Link className="combat-reference-card" href={`/equipment/${weapon.slug}`}><PixelImage src={weapon.assetURL} alt={`${weapon.name} weapon visual`} size={48} /><span><strong>Weapon</strong>{weapon.name}</span></Link>}
      {guard && <Link className="combat-reference-card" href={`/equipment/${guard.slug}`}><PixelImage src={guard.assetURL} alt={`${guard.name} protective gear visual`} size={48} /><span><strong>Protection</strong>{guard.name}</span></Link>}
    </div></section>
    <section className="article-section"><h2>Whose turn and what can be chosen</h2><p>The turn line and acting card identify the current combatant. When a party member is acting, the mounted action bar offers Attack, Techniques, Item, and Withdraw. The foe turn is not a second player action bar. A companion can be handed back to its Gambits or taken over for that next turn; edit the Gambit list between fights, not from this screen.</p><dl className="definition-grid"><div><dt>Attack</dt><dd>Choose Attack, then choose a living foe. The second-tap prompt keeps the target choice explicit, and Cancel leaves no attack committed.</dd></div><div><dt>Techniques</dt><dd>Open Techniques to see the acting character’s current learned options. A technique that is cooling or has no valid target stays unavailable.</dd></div><div><dt>Item</dt><dd>Open Item only when an eligible carried combat item is available, then choose the exact ally or foe required by that item.</dd></div><div><dt>Withdraw</dt><dd>Read the displayed Stability cost, confirm Withdraw, or cancel. The encounter keeps its current state until the confirmed choice resolves.</dd></div></dl></section>
    <section className="article-section two-column"><div><h2>Targets, damage, and defence</h2><p>Only living, currently eligible cards accept a target. Weapon damage kind and reach, foe armour and resistance, position, and the acting character’s current facts all shape the displayed result. Read target cards and the battle log rather than assuming that an unavailable or changed target was struck.</p><p>The current action bar has no separate Defend key: defensive value is shown through the current character, gear, target, and technique facts.</p></div><div><h2>Status and techniques</h2><p>Health and current encounter facts stay with each card. Read <Link href="/statuses">Conditions and effects</Link> before choosing a cure or guard, and <Link href="/techniques">Techniques and Gambits</Link> for an actor’s exact target and limit. A target or condition that no longer fits leaves the encounter unchanged rather than spending a different action.</p><p>Gambits are ordered rules for automated party decisions. The first enabled rule whose condition is true has priority; their current order is prepared on the Party page.</p></div></section>
    <section className="article-section"><h2>Finish, withdraw, or face defeat</h2><p>When an encounter reaches its current outcome, the action bar is replaced by that outcome’s next visible step. Withdrawing requires the shown confirmation. Defeat ends the active encounter and leads to the current expedition review; use the resulting review and Home screens for the present outcome rather than assuming an unshown result.</p><p><Link href="/systems/exploration">Read the exploration and return guide</Link> · <Link href="/systems/field-supplies">Prepare field supplies</Link></p></section>
    <RelatedGuides links={[{ label: 'Combat actions', href: '/actions/attack' }, { label: 'Conditions and effects', href: '/statuses' }, { label: 'Technique and Gambit directory', href: '/techniques' }, { label: 'Combat techniques and Gambits', href: '/systems/combat-techniques-gambits' }, { label: 'Party, Gear and Gambits', href: '/systems/party-preparation' }, { label: 'Compare equipment', href: '/equipment' }, { label: 'Combat supplies', href: '/systems/field-supplies' }, { label: 'Animals and companionship', href: '/systems/animals-companionship' }, { label: 'All systems', href: '/systems' }]} />
  </SiteFrame>;
}
