import Link from '@/components/wiki-link';
import { GuideBreadcrumbs, RelatedGuides } from '@/components/guide-navigation';
import { PageIntro } from '@/components/page-intro';
import { PixelImage } from '@/components/pixel-image';
import { SiteFrame } from '@/components/site-frame';
import content from '@/data/player-content.json';

export default function Combat() {
  const weapon = content.items.find((item) => item.gear?.slot === 'weapon' && item.assetURL);
  const guard = content.items.find((item) => item.gear?.slot === 'armor' && item.assetURL);
  const traveller = content.travellers.find((person) => person.assetURL);

  return <SiteFrame sidebar><GuideBreadcrumbs items={[{ label: 'Systems', href: '/systems' }, { label: 'Combat' }]} /><PageIntro eyebrow="Current system guide" title="Combat" summary="Encounters show whose turn it is, then ask that party member to choose Attack, a Technique, an Item, or Withdraw. Check the target and active conditions before confirming." />
    <section className="article-section"><h2>Walking crash repaired in379 — remaining lag open</h2><p>Build379 delivers the correction for the confirmed crash when a step begins an encounter, along with improvements that reduce repeated processing during movement and saving. Movement costs, encounter turn order, withdrawal protection and what the party can see or remember keep their existing rules. The affected step, encounter and saving were checked on a separate copy of the campaign. Installation and ordinary phone launch are verified. Walking can still pause while the campaign saves: that remaining lag is open, and smooth movement or a physical-phone gameplay walkthrough is not claimed.</p></section>
    <section className="article-section combat-reference"><h2>Prepare before an encounter</h2><p>Open the linked party and equipment pages when you need the current people or gear behind the encounter screen.</p><div className="combat-reference-strip">
      {traveller && <Link className="combat-reference-card" href={`/people/${traveller.slug}`}><PixelImage src={traveller.assetURL} alt={`${traveller.name} character visual`} size={48} /><span><strong>Party member</strong>{traveller.name}</span></Link>}
      {weapon && <Link className="combat-reference-card" href={`/equipment/${weapon.slug}`}><PixelImage src={weapon.assetURL} alt={`${weapon.name} weapon visual`} size={48} /><span><strong>Weapon</strong>{weapon.name}</span></Link>}
      {guard && <Link className="combat-reference-card" href={`/equipment/${guard.slug}`}><PixelImage src={guard.assetURL} alt={`${guard.name} protective gear visual`} size={48} /><span><strong>Protection</strong>{guard.name}</span></Link>}
    </div></section>
    <section className="article-section"><h2>Whose turn and what can be chosen</h2><p>The turn line and acting card identify who is acting. When a party member is acting, the action bar offers Attack, Techniques, Item, and Withdraw. A foe’s turn does not show a second player action bar. You can let a companion follow its Gambits or take control for its next turn; edit Gambits between fights, not here.</p><dl className="definition-grid"><div><dt>Attack</dt><dd>Choose Attack, then choose a living foe. The second prompt confirms the target; Cancel leaves the turn unchanged.</dd></div><div><dt>Techniques</dt><dd>Open Techniques to see what the acting character has learned. A technique that is cooling down or has no valid target stays unavailable.</dd></div><div><dt>Item</dt><dd>Open Item when a suitable combat item is carried, then choose the ally or foe that item can affect.</dd></div><div><dt>Withdraw</dt><dd>Read the Stability cost, confirm Withdraw, or cancel. The encounter remains unchanged until the choice succeeds.</dd></div></dl></section>
    <section className="article-section two-column"><div><h2>Targets, damage, and defence</h2><p>Only living, currently eligible cards accept a target. Weapon damage kind and reach, foe armour and resistance, position, and the acting character’s current facts all shape the displayed result. Read target cards and the battle log rather than assuming that an unavailable or changed target was struck.</p><p>The current action bar has no separate Defend key: defensive value is shown through the current character, gear, target, and technique facts.</p></div><div><h2>Status and techniques</h2><p>Health and current encounter facts stay with each card. Read <Link href="/statuses">Conditions and effects</Link> before choosing a cure or guard, and <Link href="/techniques">Techniques and Gambits</Link> for an actor’s exact target and limit. A target or condition that no longer fits leaves the encounter unchanged rather than spending a different action.</p><p>Gambits are ordered rules for automated party decisions. The first enabled rule whose condition is true has priority; their current order is prepared on the Party page.</p></div></section>
    <section className="article-section"><h2>Finish, withdraw, or face defeat</h2><p>When an encounter reaches its current outcome, the action bar is replaced by that outcome’s next visible step. Withdrawing requires the shown confirmation. Defeat ends the active encounter and leads to the current expedition review; use the resulting review and Home screens for the present outcome rather than assuming an unshown result.</p><p><strong>Current withdrawal — delivered in378:</strong> After Withdraw and Continue, the group you escaped gives you one complete move to another tile. It does not pursue or re-engage during any part of that move, even on slow terrain. Other creatures and world hazards remain dangerous, and the move still takes its usual time and Stability.</p><p>Looking, opening menus, cancelling a choice or trying a blocked move keeps the opportunity. Waiting, gathering, mining or committing another field action uses it up. Deliberately attacking an escaped foe or stepping onto its tile gives it up. A longer travel route protects only its first step. Saving and reopening preserves an unused opportunity; returning Home or entering another fight ends it.</p><p><strong>Current in377:</strong> After you choose Continue following a withdrawal, At this place immediately describes the tile your party actually returned to. Previously it could keep describing the tile you had left until your next field action. The panel stays in its usual position. The377 correction changed the location display only. Build378 adds the movement protection described above; other combat and recovery rules stay unchanged.</p><p><Link href="/systems/exploration">Read the exploration and return guide</Link> · <Link href="/consumables">Prepare field supplies</Link></p></section>
    <RelatedGuides links={[{ label: 'Combat actions', href: '/actions/attack' }, { label: 'Conditions and effects', href: '/statuses' }, { label: 'Techniques and Gambits', href: '/techniques' }, { label: 'Party and Gear', href: '/systems/party-preparation' }, { label: 'Compare equipment', href: '/equipment' }, { label: 'Consumables and Field Kit', href: '/consumables' }, { label: 'Animals and companionship', href: '/systems/animals-companionship' }, { label: 'All systems', href: '/systems' }]} />
  </SiteFrame>;
}
