import Link from '@/components/wiki-link';
import { GuideBreadcrumbs, RelatedGuides } from '@/components/guide-navigation';
import { PageIntro } from '@/components/page-intro';
import { PixelImage } from '@/components/pixel-image';
import { SiteFrame } from '@/components/site-frame';
import { content } from '@/lib/content';

export default function FieldSuppliesGuide() {
  const scentMask = content.items.find((item) => item.id === 'scent_mask');
  const solvent = content.items.find((item) => item.id === 'solvent');
  const healing = content.items.find((item) => item.consumable && item.consumable.effect === 'heal' && item.assetURL);
  return <SiteFrame sidebar>
    <GuideBreadcrumbs items={[{ label: 'Systems', href: '/systems' }, { label: 'Field supplies' }]} />
    <PageIntro eyebrow="Current system guide" title="Field supplies" summary="Prepare eligible identified supplies in the Field Kit at home, confirm the current plan before departure, then inspect one carried supply at a time in the world to choose its available target or use face." />
    <section className="article-section journey-strip">{healing?.assetURL && <Link href={`/items/${healing.slug}`}><PixelImage src={healing.assetURL} alt={`${healing.name} item icon`} size={58} /><span><strong>Healing supply</strong><small>Select one current party member as the target.</small></span></Link>}{solvent?.assetURL && <Link href={`/items/${solvent.slug}`}><PixelImage src={solvent.assetURL} alt="Solvent item icon" size={58} /><span><strong>Solvent</strong><small>Choose one carried unidentified curio to identify.</small></span></Link>}{scentMask?.assetURL && <Link href={`/items/${scentMask.slug}`}><PixelImage src={scentMask.assetURL} alt="Scent Mask item icon" size={58} /><span><strong>Scent Mask</strong><small>Apply the ready mask from its carried supply detail.</small></span></Link>}</section>
    <section className="article-section"><h2>Prepare the next Field Kit at home</h2><div className="definition-grid"><div><h3>Choose eligible supplies</h3><p>Use Storehouse to review the exact eligible identified supplies and move them into the next Field Kit plan. The visible bin count is the current capacity for that plan.</p></div><div><h3>Confirm the plan</h3><p>Review the suggested Field Kit and confirm it before departure. If its stock has changed or the selected supplies no longer fit, review the plan again instead of assuming it was carried.</p></div><div><h3>Instruments are separate</h3><p>The Field Kit has Instruments and Supplies sections. Pick next trip’s instruments at the Survey Post; carried instruments remain listed separately from supplies.</p></div><div><h3>Inspect in the world</h3><p>Open Field Kit, choose Supplies, select one carried item, then read its exact effect and available target faces before using it.</p></div></div><p><Link href="/services/storehouse">Open Storehouse and inventory</Link> · <Link href="/resources">Browse resources</Link> · <Link href="/crafting">Browse current preparation systems</Link></p></section>
    <section className="article-section two-column"><div><h2>Healing and other direct supplies</h2><p>A healing supply shows each current party member as a target with their displayed health. Choose the exact person you want to heal. Other ready supplies show their current Use now face when they do not require a separate target.</p><p>If a supply is unavailable or its displayed target no longer fits, it does not present a completed use.</p></div><div><h2>Scent Mask</h2><p>When ready, Scent Mask applies a mask for 12 turns. While it is active, its detail shows the remaining turns and the use face reads that the party is already masked.</p><p>The mask makes animals relying only on scent hesitate for one action. Other senses and close contact still detect the party; it does not hide creatures or affect apexes. <Link href="/statuses/scent-mask">Read its field-effect boundary</Link>.</p></div></section>
    <section className="article-section two-column"><div><h2>Solvent and carried curios</h2><p>Solvent shows only the carried unidentified curios it can identify. Choose one exact curio; when none are carried, the supply detail says so instead of completing an identification.</p><p><Link href="/curios">Browse curios and key items</Link></p></div><div><h2>Trying an unknown curio</h2><p>An unidentified curio says that its result is unknown and offers only its available party targets. Choose a target, then read the confirmation before selecting Try it. Cancel leaves the curio unused.</p></div></section>
    <section className="article-section"><h2>Commit the shown use</h2><p>Field Kit details keep the selected supply, its quantity, effect, and available target together. A completed use applies the current displayed action; closing, cancelling, or an unavailable target does not turn the selection into a completed use. Return to the supply detail whenever you need to compare the next carried item.</p><p>Supplies with a timed effect show their remaining turns in that detail. A ready Scent Mask is applied to the party; while it is active, the action stays unavailable until its displayed duration ends.</p></section>
    <RelatedGuides links={[{ label: 'Storehouse and inventory', href: '/services/storehouse' }, { label: 'Consumables', href: '/consumables' }, { label: 'Conditions and effects', href: '/statuses' }, { label: 'Curios and key items', href: '/curios' }, { label: 'Resources', href: '/resources' }, { label: 'Crafting systems', href: '/crafting' }, { label: 'Exploration', href: '/systems/exploration' }]} />
  </SiteFrame>;
}
