#!/usr/bin/env python3
"""Generate the native Recovered Teaching V1 catalogue from its frozen markdown authority."""
from pathlib import Path
import re

root = Path(__file__).resolve().parents[1]
source = (root / "docs/recovered-teachings-current.md").read_text()
rows = [line for line in source.splitlines() if line.startswith("|") and "`teaching." in line]
if len(rows) != 38:
    raise SystemExit(f"expected 38 rows, found {len(rows)}")

entries = []
for row in rows:
    cells = [cell.strip() for cell in row.strip().strip("|").split("|")]
    order = int(cells[0])
    teaching = re.search(r"`([^`]+)`", cells[1]).group(1)
    band = cells[2]
    reward = re.search(r"(?:Gambit|focus|symbol|capability) `([^`]+)`", cells[3]).group(1)
    if teaching.startswith("teaching.gambit."):
        kind, placement = "gambitComponent", "fieldInstruction"
    elif teaching.startswith("teaching.instruction."):
        kind, placement = "capability", "fieldInstruction"
    elif teaching.startswith("teaching.focus."):
        kind, placement = "focus", "localObservation"
    else:
        kind = "symbol"
        placement = "siteRubbing" if order >= 37 else ("quietCounterexample" if reward == "peace" else "warningNote")
    title = cells[-2] if order <= 36 else reward.replace("_", " ").title()
    copy = cells[-1].strip("“”")
    esc = lambda value: value.replace("\\", "\\\\").replace('"', '\\"')
    entries.append(
        f'        .init(order: {order}, id: "{teaching}", band: .{band}, '
        f'reward: .init(kind: .{kind}, id: "{reward}"), placement: .{placement}, '
        f'title: "{esc(title)}", instructionCopy: "{esc(copy)}")')

output = """// Generated by Scripts/generate_recovered_teachings.py. Do not hand-edit.\nimport Foundation\n\nextension RecoveredTeachingCatalogueV1 {\n    static let definitions: [RecoveredTeachingDefinitionV1] = [\n"""
output += ",\n".join(entries)
output += "\n    ]\n}\n"
(root / "Sources/Rules/RecoveredTeachingCatalogue.generated.swift").write_text(output)
