#!/usr/bin/env python3
"""Generate the DEBUG-only Swift meeting review corpus from Design's review Markdown."""
import base64
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SOURCES = [
    "traveller-meetings-early-hinge-review.md",
    "traveller-meetings-mature-core-review.md",
    "traveller-meetings-specialists-review.md",
    "traveller-meetings-transformation-endgame-review.md",
]


def clean(value: str) -> str:
    value = re.sub(r"\s+", " ", value.strip())
    return value.replace("\\|", "|")


def field(section: str, name: str) -> str:
    match = re.search(rf"\*\*{name}:\*\*\s*(.*?)(?=\n\n\*\*|\n## |\Z)", section, re.S)
    if not match:
        raise ValueError(f"missing {name}")
    return clean(match.group(1))


meetings = []
for source in SOURCES:
    text = (ROOT / "docs" / source).read_text()
    sections = re.split(r"(?m)^## ", text)[1:]
    for section in sections:
        name, _, body = section.partition("\n")
        if name.startswith(("Batch ", "Atlas ")):
            continue
        opening_match = re.search(r"\*\*Opening\*\*\s*(.*?)(?=\n\| Stable ID)", body, re.S)
        if not opening_match:
            continue
        exchanges = []
        for line in body.splitlines():
            if not line.startswith("| `"):
                continue
            columns = [clean(part) for part in line.strip().strip("|").split("|")]
            if len(columns) == 3:
                exchanges.append({"id": columns[0].strip("`"), "ask": columns[1], "reply": columns[2]})
        meetings.append({
            "travellerID": name.strip().split(" —", 1)[0].lower(),
            "source": source,
            "opening": clean(opening_match.group(1)),
            "exchanges": exchanges,
            "offer": field(body, "Offer"),
            "accepted": field(body, "Accepted"),
            "declined": field(body, "Declined"),
        })

payload = json.dumps(meetings, ensure_ascii=False, separators=(",", ":"))
encoded = base64.b64encode(payload.encode()).decode()
source = """// Generated by Scripts/generate_draft_meeting_corpus.py. Do not hand-edit.
#if DEBUG
import Foundation

enum DraftMeetingCorpus {
    struct Meeting: Codable, Equatable {
        struct Exchange: Codable, Equatable { let id: String; let ask: String; let reply: String }
        let travellerID: String
        let source: String
        let opening: String
        let exchanges: [Exchange]
        let offer: String
        let accepted: String
        let declined: String
    }

    private static let encodedJSON = "%s"
    static let decodeResult: Result<[Meeting], Error> = Result { try JSONDecoder().decode([Meeting].self, from: Data(base64Encoded: encodedJSON)!) }
    static let meetings: [Meeting] = (try? decodeResult.get()) ?? []
    static let decodingError: String? = { if case .failure(let error) = decodeResult { return String(describing: error) }; return nil }()
    static func meeting(for id: TravellerID) -> Meeting? { meetings.first { $0.travellerID == id.rawValue } }
}
#endif
""" % encoded

output = ROOT / "Sources" / "Content" / "DraftMeetingCorpus.generated.swift"
if "--check" in sys.argv:
    if not output.exists() or output.read_text() != source:
        print(f"{output.relative_to(ROOT)} is stale; regenerate with Scripts/generate_draft_meeting_corpus.py", file=sys.stderr)
        raise SystemExit(1)
elif "--write" in sys.argv:
    output.write_text(source)
else:
    print(source, end="")
