#!/usr/bin/env python3
"""Fail closed on new machine-oriented paths and stale generated output."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path, PurePosixPath


BASELINE_COMMIT = "0ab96a3cd36f5dba2e811b78aa4bebf7e9af1020"
HASH_ONLY_STEM = re.compile(r"^[0-9a-fA-F]{32,}$")
COPY_SUFFIX = re.compile(r"(?: |\()\d+\)?(?=\.[^.]+$)")
GENERATED_HEADER = re.compile(r"^// Generated by ([A-Za-z0-9_./-]+)\.")
SEMANTIC_FIELDS = ("id", "key", "stableKey", "semanticKey", "catalogueID", "assetID", "packID")
GENERIC_REFERENCE_KEYS = {
    "asset", "blob", "file", "filename", "path", "raster", "runtime", "source", "uri",
}
ALLOWED_GENERATORS = {
    "AssetLab/scripts/generate-mob-gear-native.py",
    "AssetLab/scripts/generate-town-building-registry.mjs",
    "Scripts/generate_combat_tree_v2.py",
    "Scripts/generate_draft_meeting_corpus.py",
}
ASSET_EVIDENCE_CHECK = "Scripts/verify_asset_evidence.py"


def git(root: Path, *arguments: str) -> str:
    return subprocess.check_output(
        ["git", *arguments], cwd=root, text=True, stderr=subprocess.STDOUT
    )


def changed_paths(root: Path, baseline: str = BASELINE_COMMIT) -> list[str]:
    tracked = git(root, "diff", "--name-only", "--diff-filter=ACMR", baseline, "--")
    untracked = git(root, "ls-files", "--others", "--exclude-standard")
    return sorted({line for output in (tracked, untracked) for line in output.splitlines() if line})


def semantic_label(value: object) -> bool:
    return (
        isinstance(value, str)
        and bool(value.strip())
        and not HASH_ONLY_STEM.fullmatch(value.strip())
    )


def exact_blob_reference(node: object, expected: str) -> bool:
    if isinstance(node, dict):
        for key, value in node.items():
            if isinstance(value, str) and PurePosixPath(value).as_posix() == expected:
                if semantic_label(key) and key not in GENERIC_REFERENCE_KEYS:
                    return True
                if any(semantic_label(node.get(field)) for field in SEMANTIC_FIELDS):
                    return True
            if exact_blob_reference(value, expected):
                return True
    elif isinstance(node, list):
        return any(exact_blob_reference(value, expected) for value in node)
    return False


def manifest_routes_blob(root: Path, path: Path) -> bool:
    parent = path.parent
    while parent != Path("."):
        manifest = root / parent / "manifest.json"
        if manifest.is_file():
            try:
                payload = json.loads(manifest.read_text(encoding="utf-8"))
            except (OSError, UnicodeDecodeError, json.JSONDecodeError):
                return False
            expected = path.relative_to(parent).as_posix()
            return exact_blob_reference(payload, expected)
        parent = parent.parent
    return False


def generator_for_output(root: Path, path: Path) -> tuple[str | None, str | None]:
    absolute = root / path
    if path.suffixes[-2:] == [".generated", ".swift"]:
        try:
            first_line = absolute.read_text(encoding="utf-8").splitlines()[0]
        except (OSError, UnicodeDecodeError, IndexError):
            return None, "generated Swift lacks a readable named-generator header"
        match = GENERATED_HEADER.match(first_line)
        if not match:
            return None, "generated Swift lacks a named-generator header"
        return match.group(1), None
    if path.suffixes[-2:] == [".generated", ".json"]:
        try:
            payload = json.loads(absolute.read_text(encoding="utf-8"))
        except (OSError, UnicodeDecodeError, json.JSONDecodeError):
            return None, "generated JSON is not a readable object"
        if not isinstance(payload, dict) or not isinstance(payload.get("generatedBy"), str):
            return None, "generated JSON lacks top-level generatedBy"
        return payload["generatedBy"], None
    return None, None


def normalized_generator(root: Path, value: str) -> str | None:
    candidate = PurePosixPath(value)
    if candidate.is_absolute() or ".." in candidate.parts:
        return None
    relative = candidate.as_posix()
    try:
        (root / relative).resolve().relative_to(root.resolve())
    except ValueError:
        return None
    return relative


def generator_command(root: Path, generator: str) -> list[str] | None:
    path = root / generator
    if not path.is_file():
        return None
    try:
        source = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return None
    if "--check" not in source:
        return None
    if path.suffix == ".py":
        return [sys.executable, generator, "--check"]
    if path.suffix in {".js", ".mjs"}:
        return ["node", generator, "--check"]
    return None


def path_violations(root: Path, relative: str) -> tuple[list[str], str | None]:
    path = Path(relative)
    violations: list[str] = []
    generator: str | None = None
    if COPY_SUFFIX.search(path.name):
        violations.append(f"copy-suffixed human filename: {relative}")
    if HASH_ONLY_STEM.fullmatch(path.stem):
        actual_hash = hashlib.sha256((root / path).read_bytes()).hexdigest()
        if path.stem != actual_hash:
            violations.append(f"hash-only filename does not match file bytes: {relative}")
        if "blobs" not in path.parts or not manifest_routes_blob(root, path):
            violations.append(f"hash-only file lacks an exact semantic manifest route: {relative}")
    if (root / path).is_file():
        raw_generator, error = generator_for_output(root, path)
        if error:
            violations.append(f"{error}: {relative}")
        elif raw_generator is not None:
            generator = normalized_generator(root, raw_generator)
            if generator is None:
                violations.append(f"generated output names an unsafe generator: {relative}")
    return violations, generator


def repository_violations(
    root: Path,
    paths: list[str],
    allowed_generators: set[str] = ALLOWED_GENERATORS,
) -> list[str]:
    violations: list[str] = []
    # Run every reviewed generator every time. This closes generator-only drift where the
    # generator changes but its checked-in output does not.
    generators: set[str] = set(allowed_generators)
    for relative in paths:
        path_errors, generator = path_violations(root, relative)
        violations.extend(path_errors)
        if generator is not None:
            if generator not in allowed_generators:
                violations.append(f"generated output uses an unreviewed generator: {generator}")
            else:
                generators.add(generator)
    for generator in sorted(generators):
        command = generator_command(root, generator)
        if command is None:
            violations.append(f"allowlisted generator has no executable --check gate: {generator}")
            continue
        result = subprocess.run(
            command,
            cwd=root,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            timeout=120,
            check=False,
        )
        if result.returncode != 0:
            detail = result.stdout.strip().splitlines()[-1:] or ["no diagnostic"]
            violations.append(f"generated output is stale for {generator}: {detail[0]}")
    return violations


def self_test() -> None:
    with tempfile.TemporaryDirectory(prefix="bookbinder-repository-guard-") as directory:
        root = Path(directory)
        subprocess.run(["git", "init", "-q"], cwd=root, check=True)
        subprocess.run(["git", "config", "user.email", "guard@example.invalid"], cwd=root, check=True)
        subprocess.run(["git", "config", "user.name", "Repository Guard"], cwd=root, check=True)
        (root / "seed.txt").write_text("seed\n", encoding="utf-8")
        subprocess.run(["git", "add", "seed.txt"], cwd=root, check=True)
        subprocess.run(["git", "commit", "-qm", "seed"], cwd=root, check=True)
        baseline = git(root, "rev-parse", "HEAD").strip()

        untracked = root / "AssetLab" / "manifest 2.json"
        untracked.parent.mkdir(parents=True)
        untracked.write_text("{}\n", encoding="utf-8")
        assert "AssetLab/manifest 2.json" in changed_paths(root, baseline)
        assert repository_violations(root, changed_paths(root, baseline))

        untracked.unlink()
        blob = root / "Review" / "blobs" / ("a" * 64 + ".png")
        blob.parent.mkdir(parents=True)
        blob.write_bytes(b"pixel")
        manifest = root / "Review" / "manifest.json"
        manifest.write_text("{}\n", encoding="utf-8")
        assert repository_violations(root, [blob.relative_to(root).as_posix()], set())
        manifest.write_text(json.dumps({"unrelated": "blobs/other.png"}), encoding="utf-8")
        assert repository_violations(root, [blob.relative_to(root).as_posix()], set())

        blob.unlink()
        blob_bytes = b"content-addressed pixel"
        blob = root / "Review" / "blobs" / (hashlib.sha256(blob_bytes).hexdigest() + ".png")
        blob.write_bytes(blob_bytes)
        manifest.write_text(
            json.dumps({"terrain.phone.night": "blobs/" + blob.name}), encoding="utf-8"
        )
        assert not repository_violations(root, [blob.relative_to(root).as_posix()], set())

        scripts = root / "Scripts"
        sources = root / "Sources"
        scripts.mkdir()
        sources.mkdir()
        generator = scripts / "make.py"
        output = sources / "Example.generated.swift"
        generated_json = sources / "Example.generated.json"
        expected = "// Generated by Scripts/make.py. Do not hand-edit.\nlet value = 1\n"
        expected_json = json.dumps(
            {"generatedBy": "Scripts/make.py", "value": 1}, sort_keys=True
        ) + "\n"
        generator.write_text(
            "import pathlib, sys\n"
            f"expected = {expected!r}\n"
            f"expected_json = {expected_json!r}\n"
            "output = pathlib.Path('Sources/Example.generated.swift')\n"
            "json_output = pathlib.Path('Sources/Example.generated.json')\n"
            "if '--check' in sys.argv:\n"
            "    current = output.read_text() == expected and json_output.read_text() == expected_json\n"
            "    raise SystemExit(0 if current else 1)\n",
            encoding="utf-8",
        )
        output.write_text(expected, encoding="utf-8")
        generated_json.write_text(expected_json, encoding="utf-8")
        generated_paths = ["Sources/Example.generated.swift", "Sources/Example.generated.json"]
        assert not repository_violations(root, generated_paths, {"Scripts/make.py"})
        output.write_text(expected + "// hand edit\n", encoding="utf-8")
        assert repository_violations(root, generated_paths, {"Scripts/make.py"})

        output.write_text(expected, encoding="utf-8")
        generated_json.write_text(
            json.dumps({"generatedBy": "Scripts/make.py", "value": 2}) + "\n", encoding="utf-8"
        )
        assert repository_violations(root, generated_paths, {"Scripts/make.py"})
        generated_json.write_text("{}\n", encoding="utf-8")
        assert repository_violations(root, ["Sources/Example.generated.json"], {"Scripts/make.py"})


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()
    if args.self_test:
        self_test()
        print("repository organization verifier self-test passed")
        return 0
    if not args.check:
        parser.error("choose --check or --self-test")

    root = Path(git(Path.cwd(), "rev-parse", "--show-toplevel").strip())
    violations = repository_violations(root, changed_paths(root))
    evidence_check = root / ASSET_EVIDENCE_CHECK
    if evidence_check.is_file():
        result = subprocess.run(
            [sys.executable, ASSET_EVIDENCE_CHECK, "--check"], cwd=root, text=True,
            stdout=subprocess.PIPE, stderr=subprocess.STDOUT, timeout=30, check=False,
        )
        if result.returncode != 0:
            detail = result.stdout.strip().splitlines()[-1:] or ["no diagnostic"]
            violations.append(f"AssetEvidence boundary failed: {detail[0]}")
    if violations:
        print("repository organization check failed:", file=sys.stderr)
        for violation in violations:
            print(f"- {violation}", file=sys.stderr)
        return 1
    print("repository organization check passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
