import Link from 'next/link';
import { GuideBreadcrumbs, RelatedGuides } from '@/components/guide-navigation';
import { PageIntro } from '@/components/page-intro';
import { SiteFrame } from '@/components/site-frame';
import { content } from '@/lib/content';

const steps = [
  ['1', 'Choose a hand', 'Select the writing tool whose marks and capabilities you want to work with.'],
  ['2', 'Choose ink', 'Choose the prepared or open ink treatment before laying out the request.'],
  ['3', 'Place and connect', 'Place Subjects, connect Focuses, then narrow them with Modifiers. Compounds hold complete statements in less space.'],
  ['4', 'Review and Bind', 'Read the World preview, correct the Page if needed, then Bind to create the expedition world.'],
];

export default function WorldWriting() {
  return <SiteFrame sidebar><GuideBreadcrumbs items={[{ label: 'Systems', href: '/systems' }, { label: 'World Writing' }]} /><PageIntro eyebrow="System guide" title="World Writing" summary="A Page is a request, not a tile-by-tile map. You arrange Sigils to influence the pressures and qualities of the world that Binding creates." />
    <figure className="feature-figure">{content.writingAssetURL && <img src={content.writingAssetURL} alt="The parchment used by the Writing Desk" />}<figcaption>The Writing Desk keeps the Page, writing tools, vocabulary, and World preview in one workspace.</figcaption></figure>
    <section className="article-section writing-visual-guide"><h2>What you work with</h2><p>These retained details appear in the same Writing Desk workspace: choose a tool, place a mark, then connect it to build the Page.</p><div className="writing-visual-strip">{content.writingVisuals.map((visual) => visual.assetURL && <figure key={visual.id}><img src={visual.assetURL} alt={visual.alt} /><figcaption>{visual.label}</figcaption></figure>)}</div></section>
    <section className="article-section"><h2>Write a Page in this order</h2><div className="step-grid">{steps.map(([number, title, text]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="article-section"><h2>The four building blocks</h2><dl className="definition-grid"><div><dt>Subject</dt><dd>What the request is about. The desk presents eight current Subjects: {content.pressureTargets.map((target) => target.name).join(', ')}.</dd></div><div><dt>Focus</dt><dd>A learned, linked Sigil asking the world to change its Subject. The active Subject shows only Focuses that can attach to it.</dd></div><div><dt>Modifier</dt><dd>Changes how a connected Focus is applied. Some appear only with their matching Subject; the separate Modifiers bin keeps the generic ladders together.</dd></div><div><dt>Compound</dt><dd>A reusable Sigil holding one complete statement in a smaller footprint. Your Runebook shows only compounds you have already formalized or recovered.</dd></div></dl></section>
    <section className="article-section two-column"><div><h2>Connect a readable request</h2><p>Place the Subject and its Focuses on the Page, then connect the marks that belong together. Add a Modifier only where the desk offers it for that Subject. The review surface names connected readable requests; an unconnected mark is not treated as the same request.</p><p>Change the Page before Binding if the review is not the request you mean. Loading a template replaces the current Page’s placed Sigils and connections only after its confirmation.</p></div><div><h2>Use compounds deliberately</h2><p>A compound keeps its complete statement together in a smaller footprint. Select a personal compound in My Runebook to inspect it before placing it. If the current Page has no valid origin for that compound’s shape, it remains unavailable rather than spilling into another part of the Page.</p></div></section>
    <section className="article-section"><h2>Ink reference</h2><p>Ash ink is unlimited and leaves the focus colour open. Once Ink Mixing is available, choose an eligible placed Focus, set Cyan, Magenta, Yellow, and Depth proportions, then either apply the mixture to that Focus or save it for the next eligible Focus.</p><div className="definition-grid"><div><h3>Materials</h3><p>Copper supplies Cyan, Ichor Magenta, Sulfur Yellow, and Obsidian Depth. Resin seals the prepared vial.</p></div><div><h3>Prepared applications</h3><p>Prepare a matching recipe to create a 12-application vial. Binding spends one matching application for each inked source it uses.</p></div><div><h3>What ink changes</h3><p>Mixed ink changes a Focus’s authored colour, not its meaning. The current Page request remains the same unless you change its placed and connected Sigils.</p></div><div><h3>When a colour cannot apply</h3><p>The Ink well lists only eligible placed source marks. If there is no eligible Focus, place one first; do not treat a mixture as applied to another kind of mark.</p></div></div><p><Link href="/crafting/writing-ink">Open prepared writing ink</Link> · <Link href="/resources">Open ink materials</Link></p></section>
    <section className="article-section two-column"><div><h2>What the preview tells you</h2><p>The World preview describes likely pressures and broad qualities without promising exact terrain, sites, creatures, or resources. Use it to compare the direction of the Page before spending the Bind.</p></div><div className="note-card"><h3>Editing is not Binding</h3><p>Ordinary Page editing lets you revise the request. The expedition begins only after an accepted Bind creates the world and the arrival sequence completes.</p></div></section>
    <RelatedGuides links={[{ label: 'Place a mark', href: '/actions/place-mark' }, { label: 'Connect marks', href: '/actions/connect-marks' }, { label: 'Bind a world', href: '/actions/bind-world' }, { label: 'Explore a world', href: '/systems/exploration' }, { label: 'Prepared writing ink', href: '/crafting/writing-ink' }, { label: 'Ink materials', href: '/resources' }, { label: 'Writing terms', href: '/glossary' }, { label: 'All systems', href: '/systems' }]} />
  </SiteFrame>;
}
