// Generated by AssetLab/scripts/generate-town-building-registry.mjs. Do not hand-edit.
import Foundation

enum TownBuildingVisualRegistry {
    static let generatorVersion = "town-building-generator-1.0.0"
    static let sourceManifestSHA256 = "893f2a6a76e833973d2329b0087dec9051e13b736d9f4000c2701de4255b15c4"

    private static let assetByStationID: [String: String] = [
        "workshop": "building-workshop-v1",
        "storehouse": "building-storehouse-v1",
        "library": "building-library-v1",
        "constellation": "building-constellation-v1",
        "bestiary": "building-bestiary-v1",
        "apothecary": "building-apothecary-v1",
        "survey_post": "building-survey-post-v1",
        "reliquary": "building-reliquary-v1",
        "scriptorium": "building-scriptorium-v1",
        "essence_spring": "building-essence-spring-v1"
    ]

    static func assetName(for stationID: StationID) -> String? {
        assetByStationID[stationID.rawValue]
    }
}
