import Link from '@/components/wiki-link';
import { GuideBreadcrumbs, RelatedGuides } from '@/components/guide-navigation';
import { PageIntro } from '@/components/page-intro';
import { PixelImage } from '@/components/pixel-image';
import { SiteFrame } from '@/components/site-frame';
import { content } from '@/lib/content';

const slots = ['Weapon', 'Off-hand', 'Head', 'Body', 'Hands', 'Feet', 'Tool', 'Keepsake'];

export default function PartyPreparationGuide() {
  const people = content.travellers.filter((person) => person.assetURL).slice(0, 3);
  const gear = content.items.find((item) => item.gear && item.assetURL);
  return <SiteFrame sidebar>
    <GuideBreadcrumbs items={[{ label: 'Systems', href: '/systems' }, { label: 'Party, Gear and Gambits' }]} />
    <PageIntro eyebrow="Current system guide" title="Party, Gear and Gambits" summary="Set who travels at the Firepit, review one person at a time in Party, equip the current eligible gear at home, and arrange Gambits in the order you want them considered in combat." />
    <section className="article-section journey-strip"><Link href="/buildings/firepit"><span><strong>Firepit</strong><small>Choose who is coming with you, staying at home, or posted in a realm.</small></span></Link>{people.map((person) => <Link href={`/people/${person.slug}`} key={person.id}>{person.assetURL && <PixelImage src={person.assetURL} alt={`${person.name} character visual`} size={58} />}<span><strong>{person.name}</strong><small>Open each person’s player record and current preparation page.</small></span></Link>)}{gear?.assetURL && <Link href={`/equipment/${gear.slug}`}><PixelImage src={gear.assetURL} alt={`${gear.name} icon`} size={58} /><span><strong>Gear</strong><small>Compare the exact stored piece with what that person is wearing.</small></span></Link>}</section>
    <section className="article-section two-column"><div><h2>Who can travel</h2><p>The Binder counts as one member of the five-person party. You can take up to four recruited companions with you; other recruited people can stay at home or be posted in a realm when that placement is available.</p></div><div className="note-card"><h3>Use the Firepit for placement</h3><p>The Firepit changes where a person is. Party is where you review that person’s health, rank, equipment, Training, and Gambits.</p><p><Link href="/buildings/firepit">Open the Firepit guide</Link></p></div></section>
    <section className="article-section"><h2>Placement and its current safeguards</h2><div className="definition-grid"><div><h3>Take them</h3><p>Choose the exact resident or posted person, review the placement, then confirm the transfer into the travelling party.</p></div><div><h3>Send Home</h3><p>Choose a travelling person to return them to the Village. Their current placement remains intact if the displayed transfer cannot complete.</p></div><div><h3>Party full</h3><p>When all four companion places are occupied, send someone Home before taking another traveller. A refused transfer does not replace a current party member.</p></div><div><h3>Prepare at home</h3><p>Gear and Gambit changes are made at home before the next encounter, not in the middle of a fight.</p></div></div></section>
    <section className="article-section"><h2>Review one person at a time</h2><p>Open a current party card, then use that person’s Gear, Training, Stats, and Gambits sections. The pager keeps each person’s preparation separate while you swipe between the current party members.</p><p><Link href="/buildings/party">Open the Party and Gear entry</Link></p></section>
    <section className="article-section"><h2>Gear: eight current slots</h2><p>Every person’s Gear section shows the current piece for each slot and the eligible alternatives you own. Compare the displayed power and any weapon damage or reach facts before equipping a piece.</p><div className="definition-grid">{slots.map((slot) => <div key={slot}>{slot}</div>)}</div><div className="two-column"><div><h3>Equip or replace</h3><p>Choose the exact candidate for that slot and confirm Equip. A piece worn by someone else is identified as such; it is not silently taken from them.</p></div><div><h3>Take it off</h3><p>Use Take it off to remove the currently worn piece. Carried gear is changed after you return home, so an unavailable field change leaves the current equipment in place.</p></div></div><p><Link href="/equipment">Browse current equipment</Link></p></section>
    <section className="article-section"><h2>Gambits: priority is the order</h2><p>Each person’s Gambits are checked from top to bottom. The first enabled rule that fits is the one used in combat, so drag rules into the priority you want before departing. Open the <Link href="/techniques">Techniques and Gambits directory</Link> to compare the owned component’s exact current result and limit.</p><div className="definition-grid"><div><h3>Write and edit</h3><p>A rule is assembled from the owned subject, condition, comparison, value, and action components. You can switch a rule off without deleting it.</p></div><div><h3>Keep the current order</h3><p>Delete only the exact rule you selected. Rules beyond a person’s current slots stay written but idle until a slot is available.</p></div><div><h3>When a rule cannot be written</h3><p>If no owned subject and action are available, no new rule is added. The existing list and its priority stay unchanged.</p></div><div><h3>In combat</h3><p>Gambits affect the current combat choice; use the Combat guide to understand the encounter actions around that choice.</p></div></div></section>
    <RelatedGuides links={[{ label: 'Firepit and travelling party', href: '/buildings/firepit' }, { label: 'People', href: '/people' }, { label: 'Equipment', href: '/equipment' }, { label: 'Conditions and effects', href: '/statuses' }, { label: 'Combat', href: '/systems/combat' }, { label: 'Techniques and Gambits', href: '/techniques' }, { label: 'Village', href: '/village' }, { label: 'All systems', href: '/systems' }]} />
  </SiteFrame>;
}
