import assert from "node:assert/strict";
import {authoredColorVocabulary,authoredColorByID,authoredColorScopeExamples,authoredColorGamutPolicy,resolveAuthoredColorID,resolveAuthoredColorPattern,oklchToSRGB} from "../src/authored-color-vocabulary.js";

assert.equal(authoredColorVocabulary.length,12);assert.deepEqual(authoredColorVocabulary.filter(x=>x.route==="starter").map(x=>x.id),["red","yellow","blue","grey"]);assert.deepEqual(authoredColorVocabulary.filter(x=>x.route==="later").map(x=>x.id),["cyan","magenta"]);assert.equal(new Set(authoredColorVocabulary.map(x=>x.id)).size,12);assert.equal(new Set(authoredColorVocabulary.map(x=>x.patternID)).size,12,"patterns redundantly distinguish vocabulary without hue");
assert.deepEqual(authoredColorVocabulary.filter(x=>x.route==="common").map(x=>x.id),["orange","green","violet","white","black","ochre"]);assert.ok(authoredColorVocabulary.every(x=>["starter","common","later"].includes(x.route)));
for(const entry of authoredColorVocabulary){assert.equal(entry.oklch.length,3);assert.ok(entry.oklch.every(Number.isFinite));assert.equal(authoredColorByID[entry.id].srgb.length,3);assert.ok(authoredColorByID[entry.id].srgb.every(n=>Number.isInteger(n)&&n>=0&&n<=255));}
assert.deepEqual(authoredColorScopeExamples,{sun:"emitter",smoke:"atmosphere",granite:"material",bloom:"flora"});assert.throws(()=>resolveAuthoredColorID("brown"),/unknown-authored-color:brown/);assert.throws(()=>resolveAuthoredColorID("pale"),/unknown-authored-color:pale/);
assert.ok(authoredColorByID.white.oklch[0]>authoredColorByID.grey.oklch[0]&&authoredColorByID.grey.oklch[0]>authoredColorByID.black.oklch[0]);assert.ok(authoredColorByID.white.oklch[1]<.03&&authoredColorByID.grey.oklch[1]<.03&&authoredColorByID.black.oklch[1]<.03,"achromatics are value/chroma cases");
assert.ok(Math.abs(authoredColorByID.ochre.oklch[2]-authoredColorByID.orange.oklch[2])>=20);assert.ok(authoredColorByID.ochre.oklch[1]<authoredColorByID.orange.oklch[1],"Ochre is earthier/lower chroma than Orange rather than a Brown alias");
assert.deepEqual(Object.fromEntries(authoredColorVocabulary.map(x=>[x.id,authoredColorByID[x.id].srgb])),{red:[222,59,61],yellow:[229,194,38],blue:[23,121,225],grey:[127,135,147],orange:[240,121,0],green:[57,158,67],violet:[132,81,201],white:[228,225,214],black:[29,34,41],ochre:[186,127,20],cyan:[0,182,199],magenta:[202,75,181]});assert.equal(authoredColorGamutPolicy.gamut,"per-channel linear-sRGB clipping");assert.throws(()=>oklchToSRGB([.5,.2]),/invalid-oklch-tuple/);
assert.equal(new Set(authoredColorVocabulary.map(x=>JSON.stringify(resolveAuthoredColorPattern(x.patternID)))).size,12,"resolved native-size pattern geometry is pairwise distinct");assert.throws(()=>resolveAuthoredColorPattern("missing"),/unknown-authored-color-pattern/);
assert.throws(()=>{authoredColorByID.red.oklch[0]=0;},TypeError);assert.throws(()=>{authoredColorByID.red.srgb[0]=0;},TypeError);
console.log("Asset Lab authored-color vocabulary candidate tests passed.");
