import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {catalogueItemIDs} from "../src/item-kit.js";
import {uncoveredCatalogueGroups,uncoveredCatalogueIDs,nextCatalogueProofIDs,catalogueCoverageSummary,compactIdentityBoundary} from "../src/catalogue-coverage.js";
const live=JSON.parse(await readFile(new URL("../../Sources/Content/Data/items.json",import.meta.url),"utf8")).items;
const pack=JSON.parse(await readFile(new URL("../integration/mob-gear-sprites-v1/manifest.json",import.meta.url),"utf8"));
const liveIDs=live.map(item=>item.id),liveGearIDs=live.filter(item=>item.kind==="gear").map(item=>item.id),packedGearIDs=pack.profiles.catalogueGear.sprites.map(sprite=>sprite.id),accepted=new Set([...catalogueItemIDs,...packedGearIDs]),uncovered=liveIDs.filter(id=>!accepted.has(id));
assert.equal(liveIDs.length,102);assert.equal(new Set(liveIDs).size,102);assert.deepEqual([...packedGearIDs].sort(),[...liveGearIDs].sort(),"the native gear pack must cover every exact live gear ID");assert.deepEqual(uncovered.sort(),[...uncoveredCatalogueIDs].sort());assert.deepEqual(catalogueCoverageSummary(liveIDs,packedGearIDs),{liveExpected:102,accepted:95,uncovered:7,nextProof:7});assert.deepEqual(Object.fromEntries(Object.entries(uncoveredCatalogueGroups).map(([key,ids])=>[key,ids.length])),{treasure:5,key:2});
for(const id of nextCatalogueProofIDs)assert.ok(live.some(candidate=>candidate.id===id),`${id} must remain an exact live catalogue ID`);assert.equal(new Set(nextCatalogueProofIDs).size,7);assert.equal(Object.keys(compactIdentityBoundary).length,6);assert.match(compactIdentityBoundary.craftedInstance,/familyID/);assert.match(compactIdentityBoundary.worldMaterial,/context-owned/);assert.match(compactIdentityBoundary.unknown,/disclosure-neutral/);
console.log("Asset Lab catalogue coverage audit tests passed.");
