import assert from "node:assert/strict";
import { namedCharacterCatalogue,characterProfiles,characterCommands,characterDescriptor,generatedCharacterDescriptor,binderTemplate,gearReach,silhouetteHash,identityHash } from "../src/character-kit.js";
import { commandBounds } from "../src/generator.js";
assert.equal(namedCharacterCatalogue.length,28);assert.equal(new Set(namedCharacterCatalogue.map(x=>x.id)).size,28);assert.equal(characterProfiles.world.camera,"top-down");assert.equal(characterProfiles.combat.camera,"side-biased");
const axes=["build","hair","garment","carry","asymmetry","personalPalette"];
for(const person of namedCharacterCatalogue){assert.deepEqual(Object.keys(person.descriptor).sort(),[...axes].sort());for(const profile of ["world","combat"]){const base=characterCommands(person.id,{profile}),bounds=commandBounds(base),spec=characterProfiles[profile];assert.ok(bounds.minX>=0&&bounds.minY>=0&&bounds.maxX<=spec.width&&bounds.maxY<=spec.height);assert.equal(identityHash(person.id,profile),silhouetteHash(base));for(const gear of ["blade","spear","bow","lightArmor","heavyArmor"])assert.notEqual(silhouetteHash(base),silhouetteHash(characterCommands(person.id,{profile,gear})),`${gear} must be visible`);assert.notEqual(silhouetteHash(base),silhouetteHash(characterCommands(person.id,{profile,pose:"passedOut"})));}}
for(const profile of ["world","combat"]){const hashes=namedCharacterCatalogue.map(person=>identityHash(person.id,profile));assert.equal(new Set(hashes).size,28,`all named ${profile} silhouettes must be pairwise distinct`);}
assert.notDeepEqual(binderTemplate,characterDescriptor("tovin"),"Binder must never inherit Tovin's identity");
assert.throws(()=>characterDescriptor("not_a_real_traveller"),/unknown-character-identity/);assert.deepEqual(gearReach,{blade:"close",spear:"mid",bow:"far"});
const warmGrade=characterCommands("mara",{environmentGrade:"warm"}),coldGrade=characterCommands("mara",{environmentGrade:"cold"});assert.equal(silhouetteHash(warmGrade),silhouetteHash(coldGrade),"environment grade must preserve identity geometry");assert.notDeepEqual(warmGrade,coldGrade,"environment grade must exercise a bounded color transform");assert.equal(characterDescriptor("mara").personalPalette,"ochre");
const ga=generatedCharacterDescriptor(42),gb=generatedCharacterDescriptor(42),gc=generatedCharacterDescriptor(43);assert.deepEqual(ga,gb);assert.notDeepEqual(ga,gc);assert.ok(axes.filter(axis=>ga[axis]!==gc[axis]).length>=2,"nearby generated seeds need meaningful structural variation");assert.deepEqual(characterCommands("generated_person",{generatedSeed:42}),characterCommands("generated_person",{generatedSeed:42}));
const namedDescriptors=new Set(namedCharacterCatalogue.map(person=>JSON.stringify(person.descriptor))),generatedDescriptors=Array.from({length:512},(_,seed)=>JSON.stringify(generatedCharacterDescriptor(seed)));assert.equal(new Set(generatedDescriptors).size,512,"first 512 generated identities must not collide");assert.ok(generatedDescriptors.every(descriptor=>!namedDescriptors.has(descriptor)),"generated identities must reserve exact named combinations");
const prone=namedCharacterCatalogue.map(person=>silhouetteHash(characterCommands(person.id,{profile:"combat",pose:"passedOut"})));assert.equal(new Set(prone).size,28,"prone poses must preserve pairwise named identity");assert.notEqual(silhouetteHash(characterCommands("halloway",{profile:"combat",pose:"passedOut"})),silhouetteHash(characterCommands("halloway",{profile:"combat",pose:"passedOut",gear:"blade"})),"passed-out gear must remain visible");
console.log("Asset Lab character identity tests passed.");
