import assert from "node:assert/strict";
import { namedCharacterCatalogue,characterProfiles,characterCommands,characterDescriptor,generatedCharacterDescriptor,binderTemplate,gearReach,mapFacings,mapTopDownContract,silhouetteHash,identityHash } from "../src/character-kit.js";
import { commandBounds } from "../src/generator.js";
import { defaults,creatureCommands } from "../src/generator.js";
import { tileContentCommands } from "../src/tile-content.js";
assert.equal(namedCharacterCatalogue.length,28);assert.equal(new Set(namedCharacterCatalogue.map(x=>x.id)).size,28);assert.equal(characterProfiles.world.camera,"compact-upright-proof");assert.equal(characterProfiles.mapTopDown.camera,"straight-top-down");assert.equal(characterProfiles.combat.camera,"side-biased");
const axes=["build","hair","garment","carry","asymmetry","personalPalette"];
for(const person of namedCharacterCatalogue){assert.deepEqual(Object.keys(person.descriptor).sort(),[...axes].sort());for(const profile of ["world","combat"]){const base=characterCommands(person.id,{profile}),bounds=commandBounds(base),spec=characterProfiles[profile];assert.ok(bounds.minX>=0&&bounds.minY>=0&&bounds.maxX<=spec.width&&bounds.maxY<=spec.height);assert.equal(identityHash(person.id,profile),silhouetteHash(base));for(const gear of ["blade","spear","bow","lightArmor","heavyArmor"])assert.notEqual(silhouetteHash(base),silhouetteHash(characterCommands(person.id,{profile,gear})),`${gear} must be visible`);assert.notEqual(silhouetteHash(base),silhouetteHash(characterCommands(person.id,{profile,pose:"passedOut"})));}}
for(const profile of ["world","combat"]){const hashes=namedCharacterCatalogue.map(person=>identityHash(person.id,profile));assert.equal(new Set(hashes).size,28,`all named ${profile} silhouettes must be pairwise distinct`);}
assert.notDeepEqual(binderTemplate,characterDescriptor("tovin"),"Binder must never inherit Tovin's identity");
assert.throws(()=>characterDescriptor("not_a_real_traveller"),/unknown-character-identity/);assert.deepEqual(gearReach,{blade:"close",spear:"mid",bow:"far"});
const warmGrade=characterCommands("mara",{environmentGrade:"warm"}),coldGrade=characterCommands("mara",{environmentGrade:"cold"});assert.equal(silhouetteHash(warmGrade),silhouetteHash(coldGrade),"environment grade must preserve identity geometry");assert.notDeepEqual(warmGrade,coldGrade,"environment grade must exercise a bounded color transform");assert.equal(characterDescriptor("mara").personalPalette,"ochre");
const exactGrade={red:14,green:3,blue:-12,value:-4},exactGraded=characterCommands("mara",{profile:"mapTopDown",worldGrade:exactGrade});assert.equal(silhouetteHash(exactGraded),silhouetteHash(characterCommands("mara",{profile:"mapTopDown"})),"exact world grade must preserve map geometry");assert.notDeepEqual(exactGraded,characterCommands("mara",{profile:"mapTopDown"}),"exact world grade must alter descriptor-owned colors");assert.throws(()=>characterCommands("mara",{profile:"mapTopDown",worldGrade:{red:"warm",green:0,blue:0,value:0}}),/invalid-character-world-grade/);
const ga=generatedCharacterDescriptor(42),gb=generatedCharacterDescriptor(42),gc=generatedCharacterDescriptor(43);assert.deepEqual(ga,gb);assert.notDeepEqual(ga,gc);assert.ok(axes.filter(axis=>ga[axis]!==gc[axis]).length>=2,"nearby generated seeds need meaningful structural variation");assert.deepEqual(characterCommands("generated_person",{generatedSeed:42}),characterCommands("generated_person",{generatedSeed:42}));
const namedDescriptors=new Set(namedCharacterCatalogue.map(person=>JSON.stringify(person.descriptor))),generatedDescriptors=Array.from({length:512},(_,seed)=>JSON.stringify(generatedCharacterDescriptor(seed)));assert.equal(new Set(generatedDescriptors).size,512,"first 512 generated identities must not collide");assert.ok(generatedDescriptors.every(descriptor=>!namedDescriptors.has(descriptor)),"generated identities must reserve exact named combinations");
const prone=namedCharacterCatalogue.map(person=>silhouetteHash(characterCommands(person.id,{profile:"combat",pose:"passedOut"})));assert.equal(new Set(prone).size,28,"prone poses must preserve pairwise named identity");assert.notEqual(silhouetteHash(characterCommands("halloway",{profile:"combat",pose:"passedOut"})),silhouetteHash(characterCommands("halloway",{profile:"combat",pose:"passedOut",gear:"blade"})),"passed-out gear must remain visible");
const overheadIDs=["mara","halloway","isolde","tovin","wren","ashe"],overheadProof=overheadIDs.map(id=>silhouetteHash(characterCommands(id,{profile:"mapTopDown"})));assert.equal(new Set(overheadProof).size,overheadProof.length,"first overhead proof identities must remain pairwise distinct");for(const id of overheadIDs)for(const facing of ["north","east","south","west"]){const bounds=commandBounds(characterCommands(id,{profile:"mapTopDown",facing}));assert.ok(bounds.minX>=0&&bounds.minY>=0&&bounds.maxX<=16&&bounds.maxY<=16,`${id}/${facing} must remain inside the exact 16px tile`);}for(const seed of [41,42,43,44])assert.deepEqual(characterCommands("generated_person",{profile:"mapTopDown",generatedSeed:seed}),characterCommands("generated_person",{profile:"mapTopDown",generatedSeed:seed}));assert.throws(()=>characterCommands("mara",{profile:"isometric"}),/unknown-character-profile/);
assert.deepEqual(mapFacings,["north","east","south","west"]);for(const facing of mapFacings){const commands=characterCommands("mara",{profile:"mapTopDown",facing}),bounds=commandBounds(commands);assert.ok(bounds.minX>=0&&bounds.minY>=0&&bounds.maxX<=16&&bounds.maxY<=16);}assert.notEqual(silhouetteHash(characterCommands("mara",{profile:"mapTopDown",facing:"north"})),silhouetteHash(characterCommands("mara",{profile:"mapTopDown",facing:"south"})),"facing axis must be visible by shape");assert.throws(()=>characterCommands("mara",{profile:"mapTopDown",facing:"upstage"}),/unknown-map-facing/);
assert.deepEqual(mapTopDownContract,{integrationFacingProfile:"mapTopDown",legacyUprightProfile:"world",camera:"straight-top-down",occlusion:"crown-over-upper-back",facePlane:false,ownershipOverlay:"game-owned",bounds:16});for(const id of ["mara","tovin"])assert.equal(new Set(mapFacings.map(facing=>silhouetteHash(characterCommands(id,{profile:"mapTopDown",facing})))).size,4,`${id} must expose four shape-distinct overhead facings`);
const portalHash=silhouetteHash(tileContentCommands({type:"portal",revealed:true,discovered:true})),siteHash=silhouetteHash(tileContentCommands({type:"site",revealed:true,discovered:true})),unknownCreatureHash=silhouetteHash(creatureCommands(defaults,"world"));for(const facing of mapFacings){const tovinHash=silhouetteHash(characterCommands("tovin",{profile:"mapTopDown",facing})),binderHash=silhouetteHash(characterCommands("binder",{profile:"mapTopDown",facing,descriptor:binderTemplate}));assert.notEqual(tovinHash,binderHash,`Tovin/Binder ${facing} must remain distinct`);for(const hash of [tovinHash,binderHash])assert.ok(![portalHash,siteHash,unknownCreatureHash].includes(hash),`${facing} hood+mantle must not collide with a POI or unknown creature`);}
console.log("Asset Lab character identity tests passed.");
