import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import Ajv from "ajv";
import {characterMapPipelineVersions,namedTravellerIDs,adaptCharacterMapRequest} from "../src/character-map-contract.js";

const schema=JSON.parse(await readFile(new URL("../schemas/character-map-request.schema.json",import.meta.url),"utf8")),validate=new Ajv({strict:true,allErrors:true}).compile(schema),grade={red:14,green:3,blue:-12,value:-4};
const named={pipelineVersions:characterMapPipelineVersions,profile:"mapTopDown",facing:"north",worldGrade:grade,identity:{identityKind:"namedTraveller",travellerID:"mara"}},generated={...named,facing:"east",identity:{identityKind:"generatedPerson",visualSeedUInt32:41}};
assert.equal(namedTravellerIDs.length,28);for(const request of [named,generated]){assert.equal(validate(request),true,JSON.stringify(validate.errors));const a=adaptCharacterMapRequest(request),b=adaptCharacterMapRequest(structuredClone(request));assert.equal(a.ok,true);assert.deepEqual(a,b);assert.match(a.rectangleHash,/^[0-9a-f]{8}$/);assert.match(a.pixelHash,/^[0-9a-f]{8}$/);assert.match(a.hashAlgorithm,/packager responsibility/);}
for(const request of [{...named,identity:{identityKind:"binder"}},{...named,identity:{identityKind:"quill"}}]){assert.equal(validate(request),true);const result=adaptCharacterMapRequest(request);assert.equal(result.ok,false);assert.equal(result.diagnostics[0].code,"missing-persisted-appearance");}
const missingSeed={...named,identity:{identityKind:"generatedPerson"}};assert.equal(validate(missingSeed),false);assert.equal(adaptCharacterMapRequest(missingSeed).diagnostics.some(issue=>issue.code==="missing-persisted-visual-seed"),true);
const unknownNested=structuredClone(named);unknownNested.identity.calling="surveyor";assert.equal(validate(unknownNested),false,"calling/stats must not enter identity adapter");assert.equal(adaptCharacterMapRequest(unknownNested).diagnostics.some(issue=>issue.code==="unknown-field"&&issue.path==="identity.calling"),true,"public adapter must enforce nested closure without AJV");const unknownTop=structuredClone(named);unknownTop.selected=true;assert.equal(validate(unknownTop),false);assert.equal(adaptCharacterMapRequest(unknownTop).diagnostics.some(issue=>issue.path==="selected"),true,"public adapter must enforce top-level closure without AJV");const unknownGrade=structuredClone(named);unknownGrade.worldGrade.temperature=80;assert.equal(validate(unknownGrade),false);assert.equal(adaptCharacterMapRequest(unknownGrade).diagnostics.some(issue=>issue.path==="worldGrade.temperature"),true);const wrongTuple=structuredClone(named);wrongTuple.pipelineVersions.mapTopDownRendererVersion="latest";assert.equal(validate(wrongTuple),false);assert.equal(adaptCharacterMapRequest(wrongTuple).diagnostics[0].code,"pipeline-version-mismatch");
console.log("Asset Lab character-map adapter contract tests passed.");
