import assert from "node:assert/strict";
import fs from "node:fs";import crypto from "node:crypto";import{fileURLToPath}from"node:url";import path from"node:path";
import {combatTrueGraphProofVersion,offenseTrueGraphNodes,offensePresentationNodes,validateTrueGraph,canLearnCombatNode,validateRoute,siegebreakerRoute,duelistRoute} from "../src/combat-tree-true-graph-kit.js";
import{combatTreeV2AuthoritySHA256,combatTreeV2Authority}from"../src/combat-tree-v2-authority.generated.js";
const authorityPath=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../../docs/combat-tree-v2-authority.json");
assert.equal(crypto.createHash("sha256").update(fs.readFileSync(authorityPath)).digest("hex"),combatTreeV2AuthoritySHA256);
assert.equal(combatTreeV2Authority.schemaVersion,2);
assert.ok(Object.isFrozen(combatTreeV2Authority.trees[0].disciplines[0].nodes));assert.throws(()=>combatTreeV2Authority.trees[0].disciplines[0].nodes.push("drift"),TypeError);
const authorityNodeIDs=combatTreeV2Authority.trees.flatMap(tree=>tree.disciplines.flatMap(discipline=>discipline.nodes.map(slug=>`combat.${tree.id}.${discipline.id}.${slug}`)));
assert.equal(authorityNodeIDs.length,72);assert.equal(Object.keys(combatTreeV2Authority.techniqueIDByNode).length,20);assert.ok(Object.keys(combatTreeV2Authority.techniqueIDByNode).every(id=>authorityNodeIDs.includes(id)));assert.equal(new Set(Object.values(combatTreeV2Authority.techniqueIDByNode)).size,20);
assert.equal(combatTreeV2Authority.techniqueIDByNode["combat.offense.swiftness.blur"],"blur");assert.equal(combatTreeV2Authority.techniqueIDByNode["combat.craft.emanation.quench"],"quench");assert.equal(combatTreeV2Authority.techniqueIDByNode["combat.craft.emanation.emanation_strike"],"emanation_strike");assert.equal(combatTreeV2Authority.techniqueIDByNode["combat.craft.shadow.vanish"],undefined);
const registryPath=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../../docs/combat-technique-registry-current.md"),registry=fs.readFileSync(registryPath,"utf8"),registryPairs=[...registry.matchAll(/^\| `([^`]+)` \| `([^`]+)` \|/gm)].map(([,nodeSuffix,techniqueID])=>[`combat.${nodeSuffix}`,techniqueID]);
assert.equal(registryPairs.length,20);assert.deepEqual(Object.fromEntries(registryPairs),combatTreeV2Authority.techniqueIDByNode);
assert.equal(combatTrueGraphProofVersion,"combat-true-graph-proof-0.3.0");
assert.equal(offenseTrueGraphNodes.length,24);
assert.deepEqual([1,2,3,4,5].map(d=>offenseTrueGraphNodes.filter(n=>n.depth===d).length),[3,6,6,6,3]);
assert.ok(offenseTrueGraphNodes.filter(n=>n.role==="capstone").every(n=>n.alternativeParents.length===2));
assert.ok(validateTrueGraph());
assert.equal(validateRoute(siegebreakerRoute).ok,true);
assert.equal(validateRoute(duelistRoute).ok,true);
assert.equal(canLearnCombatNode("combat.offense.force.breaking_blow",siegebreakerRoute.slice(0,6)),false);
assert.equal(canLearnCombatNode("combat.offense.force.breaking_blow",siegebreakerRoute.slice(0,7)),true);
assert.equal(validateRoute([...siegebreakerRoute.slice(0,4),"combat.offense.force.breaking_blow"]).ok,false);
const disconnectedMastery=["combat.offense.force.heavy_hand","combat.offense.force.overbear","combat.offense.force.stagger","combat.offense.precision.finish","combat.offense.precision.steady_hand","combat.offense.precision.weak_point","combat.offense.precision.keen_eye","combat.offense.force.shatter"];
assert.equal(canLearnCombatNode("combat.offense.force.breaking_blow",disconnectedMastery),false);
assert.throws(()=>validateTrueGraph([...offenseTrueGraphNodes,offenseTrueGraphNodes[0]]),/duplicate-combat-node|combat-node-count/);
assert.throws(()=>canLearnCombatNode("combat.offense.unknown.root",[]),/unknown-combat-node/);
for(const root of offenseTrueGraphNodes.filter(n=>n.role==="root"))assert.equal(offenseTrueGraphNodes.filter(n=>n.alternativeParents.includes(root.id)).length,2);
assert.ok(offenseTrueGraphNodes.every(n=>/^combat\.offense\.(force|precision|swiftness)\.[a-z0-9_]+$/.test(n.id)));
assert.deepEqual(offensePresentationNodes.filter(n=>n.grantsTechnique).map(n=>n.name),["Overbear","Shatter","Pry","Finish","Quicken","First Strike"]);
console.log("Asset Lab true combat graph tests passed.");
