import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { combatTreeV2Authority } from "../src/combat-tree-v2-authority.generated.js";
import { combatNodeGlyphEntries, combatGlyphCollisionFamilies, combatGlyphCrossDisciplineCollisions, combatTechniqueByNodeID, disciplineMotifs, resolveCombatNodeGlyph, resolveCombatActionGlyph, placeholderCombatPictogramCommands } from "../src/combat-node-glyph-kit.js";
const authorityIDs = combatTreeV2Authority.trees.flatMap((tree) => tree.disciplines.flatMap((discipline) => discipline.nodes.map((slug) => `combat.${tree.id}.${discipline.id}.${slug}`)));
assert.equal(combatNodeGlyphEntries.length, 72);
assert.deepEqual(combatNodeGlyphEntries.map((entry) => entry.id), authorityIDs);
assert.equal(new Set(combatNodeGlyphEntries.map((entry) => entry.id)).size, 72);
assert.equal(Object.keys(disciplineMotifs).length, 9);
assert.ok(combatNodeGlyphEntries.every((entry) => entry.referent.length > 10 && entry.motifID));
assert.equal(new Set(combatGlyphCollisionFamilies.flat()).size, 27);
assert.deepEqual(combatGlyphCrossDisciplineCollisions.map((group)=>group.length),[3,3,2,2,2,2]); assert.ok(combatGlyphCrossDisciplineCollisions.flat().every((id)=>authorityIDs.includes(id)));
const constitution = combatNodeGlyphEntries.find((entry) => entry.slug === "constitution");
assert.match(constitution.referent, /generic affliction/);
const quench = combatNodeGlyphEntries.find((entry) => entry.slug === "quench");
assert.match(quench.referent, /Burn Poison or Dazzle/);
assert.equal(Object.keys(combatTechniqueByNodeID).length,20); assert.equal(combatNodeGlyphEntries.filter((entry)=>entry.techniqueID!==null).length,20); assert.equal(combatTechniqueByNodeID["combat.offense.swiftness.blur"],"blur"); assert.equal(combatTechniqueByNodeID["combat.craft.shadow.vanish"],undefined);
const presentation = resolveCombatNodeGlyph({ nodeID: authorityIDs[0], state: "available", selected: true });
assert.equal(presentation.identity.id, authorityIDs[0]);
assert.deepEqual(presentation.layers, { frameState: "available", selected: true, techniquePip: false, capstoneFrame: false });
const blur=resolveCombatNodeGlyph({nodeID:"combat.offense.swiftness.blur",state:"owned",selected:false}); assert.equal(blur.layers.techniquePip,true); assert.equal(blur.layers.capstoneFrame,true); assert.deepEqual(resolveCombatActionGlyph("combat.offense.swiftness.blur"),{nodeID:"combat.offense.swiftness.blur",techniqueID:"blur",centralPictogramID:"combat.offense.swiftness.blur"});
assert.throws(()=>resolveCombatActionGlyph("combat.craft.shadow.vanish"));
assert.throws(() => resolveCombatNodeGlyph({ nodeID: "combat.offense.force.missing", state: "blocked", selected: false }));
assert.throws(() => resolveCombatNodeGlyph({ nodeID: authorityIDs[0], state: "available", selected: true, showTechnique: false, fallback: "F" }));
const copyMarkdown=await readFile(new URL("../../docs/combat-tree-node-copy-current.md",import.meta.url),"utf8"), effectRows=[...copyMarkdown.matchAll(/^\| ([^|]+) \| ([^|]+) \|$/gm)].filter(([,name])=>name!=="Node"), slug=(name)=>name.toLowerCase().replace(/[’']/g,"_").replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,"");
assert.equal(effectRows.length,72); assert.deepEqual(new Set(effectRows.map(([,name])=>slug(name))),new Set(combatNodeGlyphEntries.map((entry)=>entry.slug))); assert.ok(effectRows.every(([,name,effect])=>name.length>2&&/[.!]$/.test(effect.trim())));
const effects=Object.fromEntries(effectRows.map(([,name,effect])=>[slug(name),effect.trim()])); assert.match(effects.blur,/Once per encounter/); assert.match(effects.vanish,/ordinary combat retreat/); assert.match(effects.constitution,/Burn, Poison, Dazzle and Bleed/); assert.match(effects.quench,/Bleed and unchosen conditions remain/);
const placeholderHashes=combatNodeGlyphEntries.map((entry)=>JSON.stringify(placeholderCombatPictogramCommands(entry.id))); assert.equal(new Set(placeholderHashes).size,72); assert.ok(placeholderHashes.every((value)=>value.includes('"y":22'))); assert.throws(()=>placeholderCombatPictogramCommands("combat.unknown"));
console.log("Asset Lab 72-node combat glyph vocabulary tests passed.");
