import assert from "node:assert/strict";
import { combatFixture,combatMetrics,actorPosition,hitRect,allCombatPositions,rectsOverlap,validateCombatFixture } from "../src/combat-generator.js";
const crowded=combatFixture("5v3"),duel=combatFixture("2v1");
assert.equal(crowded.actors.filter(actor=>actor.side==="party").length,5);
assert.equal(crowded.actors.filter(actor=>actor.side==="foe").length,3);
assert.equal(duel.actors.filter(actor=>actor.side==="party").length,2);
assert.equal(duel.actors.filter(actor=>actor.side==="foe").length,1);
assert.deepEqual(validateCombatFixture(crowded),[]);
assert.deepEqual(validateCombatFixture(duel),[]);
assert.ok(crowded.actors.some(actor=>actor.state.unknown));
assert.ok(crowded.actors.some(actor=>actor.kind==="active-flora"));
for(const state of ["selected","legal","cannotReach","protected"])assert.ok(crowded.actors.some(actor=>actor.state[state]),`missing ${state} proof`);
assert.ok(crowded.actors.some(actor=>actor.state.selected&&actor.state.protected),"selected and protected must deliberately overlap");
const triple=crowded.actors.find(actor=>actor.state.unknown);assert.ok(!triple.state.legal&&triple.state.cannotReach&&triple.state.protected,"unknown back target must carry unknown, cannot-reach, and protected without legal");
assert.ok(crowded.actors.some(actor=>actor.state.legal&&actor.state.protected),"legal and protected must deliberately overlap elsewhere");
assert.equal(crowded.actors.find(actor=>actor.state.cannotReach).side,"foe","cannot-reach must describe a target, not incapacitate the party");
assert.ok(!crowded.actors.some(actor=>actor.state.legal&&actor.state.cannotReach),"legal and cannot-reach are mutually exclusive");
assert.ok(validateCombatFixture({mode:"invalid",actors:[{...crowded.actors[0],state:{...crowded.actors[0].state,legal:true,cannotReach:true}}]}).some(issue=>issue.includes("contradictory")));
assert.equal(duel.actors.find(actor=>actor.state.selected).kind,"Caustic bloom","2v1 selected actor supplies the far-reach proof");
const partyFront=actorPosition(crowded.actors.find(actor=>actor.side==="party"&&actor.rank==="front")),partyBack=actorPosition(crowded.actors.find(actor=>actor.side==="party"&&actor.rank==="back"));
assert.ok(partyFront.x>partyBack.x,"party front rank should face inward");
assert.equal(combatMetrics.width,216);
const positions=allCombatPositions();for(let a=0;a<positions.length;a++)for(let b=a+1;b<positions.length;b++)assert.equal(rectsOverlap(hitRect(positions[a]),hitRect(positions[b])),false,`hit regions overlap: ${positions[a].id} / ${positions[b].id}`);
console.log("Asset Lab combat-stage tests passed.");
