import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { allPreparationIDs, preparationFamilies, resolveFieldKit, previewPreparation } from "../src/consumable-field-kit-proof.js";
import { catalogueItemIDs, catalogueItemSilhouetteHash } from "../src/item-kit.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const live = JSON.parse(fs.readFileSync(path.join(root, "Sources/Content/Data/items.json"), "utf8"));
const liveConsumables = live.items.filter((item) => item.kind === "consumable").map((item) => item.id);
assert.deepEqual(allPreparationIDs, liveConsumables);
assert.deepEqual(Object.values(preparationFamilies).map((items) => items.length), [7, 4, 7]);
assert.ok(allPreparationIDs.every((id) => catalogueItemIDs.includes(id)));
assert.equal(new Set(allPreparationIDs.map(catalogueItemSilhouetteHash)).size, 18);
const request = { capacity: 3, stock: [{ itemID: "salve_lesser", count: 1 }, { itemID: "torch", count: 4 }, { itemID: "waystone", count: 0 }, { itemID: "venom", count: 2 }], entries: [{ itemID: "torch", desiredCount: 2, order: 2 }, { itemID: "salve_lesser", desiredCount: 3, order: 1 }, { itemID: "waystone", desiredCount: 1, order: 3 }, { itemID: "venom", desiredCount: 1, order: 4 }] };
const resolved = resolveFieldKit(request);
assert.deepEqual(resolved.rows.map(({ itemID, packedCount, stockShortageCount, unpackedCount, exclusionReason }) => ({ itemID, packedCount, stockShortageCount, unpackedCount, exclusionReason })), [{ itemID: "salve_lesser", packedCount: 1, stockShortageCount: 2, unpackedCount: 2, exclusionReason: null }, { itemID: "torch", packedCount: 2, stockShortageCount: 0, unpackedCount: 0, exclusionReason: null }, { itemID: "waystone", packedCount: 0, stockShortageCount: 1, unpackedCount: 1, exclusionReason: "no-stock" }, { itemID: "venom", packedCount: 1, stockShortageCount: 0, unpackedCount: 0, exclusionReason: null }]);
assert.equal(resolved.selectedBins, 4);
assert.equal(resolved.packedBins, 3);
const capacity = resolveFieldKit({ ...request, capacity: 1 });
assert.equal(capacity.rows.find((row) => row.itemID === "torch").exclusionReason, "capacity-full");
const capacityTorch = capacity.rows.find((row) => row.itemID === "torch");
assert.deepEqual({ stockShortageCount: capacityTorch.stockShortageCount, unpackedCount: capacityTorch.unpackedCount }, { stockShortageCount: 0, unpackedCount: 2 });
const notSelected = resolveFieldKit({ capacity: 1, stock: [{ itemID: "torch", count: 4 }], entries: [{ itemID: "torch", desiredCount: 0, order: 0 }] }).rows[0];
assert.deepEqual({ stockShortageCount: notSelected.stockShortageCount, unpackedCount: notSelected.unpackedCount, exclusionReason: notSelected.exclusionReason }, { stockShortageCount: 0, unpackedCount: 0, exclusionReason: "not-selected" });
assert.equal(previewPreparation({ itemID: "salve", quantity: 2, stockRevision: 4, previewRevision: 3, destinationAvailable: true }).canSubmit, false);
assert.equal(previewPreparation({ itemID: "salve", quantity: 2, stockRevision: 4, previewRevision: 4, destinationAvailable: false }).canSubmit, false);
assert.equal(previewPreparation({ itemID: "salve", quantity: 2, stockRevision: 4, previewRevision: 4, destinationAvailable: true }).canSubmit, true);
assert.throws(() => previewPreparation({ itemID: "salve", quantity: 0, stockRevision: 4, previewRevision: 3, destinationAvailable: "yes" }));
assert.throws(() => previewPreparation({ itemID: "salve", quantity: 1, stockRevision: 4, previewRevision: 4, destinationAvailable: true, extra: true }));
assert.throws(() => resolveFieldKit({ ...request, entries: [...request.entries, request.entries[0]] }));
console.log("Asset Lab consumable Field Kit proof tests passed.");
