import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { constellationProofVersion, constellationNode, constellationState, previewConstellationPurchase } from "../src/constellation-proof-kit.js";
assert.equal(constellationProofVersion, "constellation-proof-0.1.0");
const live = JSON.parse(fs.readFileSync(path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../Sources/Content/Data/constellation.json"), "utf8"));
assert.equal(live.nodes.length, 1);
assert.deepEqual({ id: live.nodes[0].id, name: live.nodes[0].name, icon: live.nodes[0].icon, effect: live.nodes[0].blurb, maxRank: live.nodes[0].maxRank, costs: live.nodes[0].moteCostPerRank }, constellationNode);
assert.equal(constellationState({ rank: 0, motes: 3 }).state, "affordable");
assert.equal(constellationState({ rank: 0, motes: 1 }).missing, 2);
assert.equal(constellationState({ rank: 1, motes: 0 }).state, "bought");
assert.throws(() => constellationState({ rank: 2, motes: 0 }));
assert.throws(() => previewConstellationPurchase({ rank: 2, motes: 5, expectedRevision: 2, currentRevision: 2 }));
assert.throws(() => constellationState({ rank: 0, motes: 3, extra: true }));
const insufficient = previewConstellationPurchase({ rank: 0, motes: 1, expectedRevision: 2, currentRevision: 2 });
assert.strictEqual(insufficient.before, insufficient.after);
assert.ok(Object.isFrozen(insufficient.before));
const stale = previewConstellationPurchase({ rank: 0, motes: 5, expectedRevision: 1, currentRevision: 2 });
assert.strictEqual(stale.before, stale.after);
assert.deepEqual(previewConstellationPurchase({ rank: 0, motes: 5, expectedRevision: 2, currentRevision: 2 }).after, { rank: 1, motes: 2 });
for (const forbidden of ["reset", "prestige", "survive everything", "companion"]) assert.ok(!`${constellationNode.name} ${constellationNode.effect}`.toLowerCase().includes(forbidden));
console.log("Asset Lab Constellation proof tests passed.");
