import assert from "node:assert/strict";
import {commandBounds} from "../src/generator.js";
import {hash} from "../src/generator.js";
import {economyIdentityContract,economyIdentityFixtures,economyIdentityCommands,economyIdentityHash,economyIdentityKey,economyContextRows} from "../src/economy-identity-kit.js";

assert.deepEqual(economyIdentityContract,{version:"economy-identity-bridge-1.1.0",evidenceRole:"assetCorrespondenceFixture",integrationReady:false,contexts:["inventory","tradingPost","recycler","blacksmith"],identityKinds:["resourceStack","worldMaterialSpecimen","ordinaryItem","foundGear","craftedGear"],playerFacingCategory:"world resources"});
assert.equal(economyIdentityFixtures.length,5);assert.equal(new Set(economyIdentityFixtures.map(item=>item.identityKind)).size,5);assert.equal(new Set(economyIdentityFixtures.map(economyIdentityKey)).size,5);assert.equal(new Set(economyIdentityFixtures.map(economyIdentityHash)).size,5,"bridge identities require distinct dominant icons");
for(const identity of economyIdentityFixtures){const commands=economyIdentityCommands(identity),bounds=commandBounds(commands);assert.ok(bounds.minX>=0&&bounds.minY>=0&&bounds.maxX<=32&&bounds.maxY<=32);const commandHashes=economyIdentityContract.contexts.map(context=>hash(economyContextRows(context).find(row=>row.identity.key===identity.key).commands));assert.equal(new Set(commandHashes).size,1,`${economyIdentityKey(identity)} icon commands must remain pixel-identical across contexts`);}
const material=economyIdentityFixtures.find(item=>item.identityKind==="worldMaterialSpecimen");assert.equal(material.materialKind,"quill");assert.match(material.resolvedDetail,/individual specimen/);assert.match(economyIdentityKey(material),/MaterialValue:quill:glassy browser:glassy/);assert.deepEqual(economyIdentityContract.contexts.map(context=>economyContextRows(context).find(row=>row.identity===material).contextHandle),["bin 4 · entry 2","not individually transferable","preview revision 22 · return 0","craft preview · bin 4 · entry 2"]);const found=economyIdentityFixtures.find(item=>item.identityKind==="foundGear");assert.equal(found.gearProfile.familyID,null);assert.equal(found.gearProfile.constructionTier,1);assert.equal(found.gearProfile.damage,"rend");assert.equal(found.resolvedDetail,"Authored salvage route · forged_edge_v1");const crafted=economyIdentityFixtures.find(item=>item.identityKind==="craftedGear");assert.equal(crafted.catalogID,"blade_chipped");assert.equal(crafted.gearProfile.familyID,"pointed_blade");assert.equal(crafted.gearProfile.constructionTier,2);assert.equal(crafted.gearProfile.damage,"pierce");assert.equal(crafted.gearProfile.reach,"close");assert.equal(crafted.gearProfile.consumedMaterials.length,2);assert.ok(crafted.gearProfile.consumedMaterials.every(entry=>Object.keys(entry.properties).length===6),"exact ordered receipt must retain all six MaterialProperties");
for(const mutate of [i=>{i.extra=true;},i=>{i.identityKind="craftedGear";},i=>{i.quantity=2;},i=>{i.resolvedDetail="invented";}]){const broken=structuredClone(economyIdentityFixtures[0]);mutate(broken);assert.throws(()=>economyIdentityCommands(broken));}
assert.throws(()=>economyContextRows("exchange"),/unknown-economy-context/);
console.log("Asset Lab five-identity economy bridge tests passed.");
