import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import {execFileSync} from "node:child_process";
import {createRequire} from "node:module";
import {fileURLToPath} from "node:url";
import {TILE_SIZE,CENTRAL_RESERVATION,DIRECTIONS,CUE_KINDS,CUE_PALETTE,BACKGROUNDS,rotateClockwise,cueLayer,cueStatePixels,tilePixels,partyMarkerPixels,opaqueCoordinates,alphaMask,literalGray,rgbaHash} from "../src/field-consequence-cue-kit.js";

const {createCanvas,loadImage}=createRequire(import.meta.url)("@napi-rs/canvas"),root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),".."),script=path.join(root,"scripts/export-field-consequence-cues.mjs"),artifact=path.join(root,"artifacts/field-consequence-cues-v0.1"),fixture=JSON.parse(fs.readFileSync(path.join(root,"fixtures/field-consequence-cues-v0.1/proof-fixtures.json")));
execFileSync(process.execPath,[script]);const manifestPath=path.join(artifact,"manifest.json"),firstManifest=fs.readFileSync(manifestPath),manifest=JSON.parse(firstManifest);
assert.equal(manifest.integrationReady,false);assert.equal(manifest.productionSource,"direct-logical-rgba");assert.deepEqual(manifest.layerOrder,["terrain-flora","party-disc-identity","consequence-cues","selection-interaction-outline"]);assert.deepEqual(manifest.tile,{width:16,height:16,pivot:{x:8,y:8},clip:"party-tile-only",centralReservation:CENTRAL_RESERVATION});assert.deepEqual(manifest.directions,DIRECTIONS);assert.deepEqual(manifest.kinds,CUE_KINDS);assert.equal(manifest.combinedStates.authoredBitmap,false);assert.deepEqual(manifest.visibility.cueFree,["fringe","hidden"]);for(const forbidden of ["pickup-animation","pickup-icons","native","PBX","golden","arrow","text","skull","plant","damage-number","terrain-adaptive-palette"])assert.ok(manifest.forbidden.includes(forbidden));

const bbox=points=>({minX:Math.min(...points.map(p=>p[0])),maxX:Math.max(...points.map(p=>p[0])),minY:Math.min(...points.map(p=>p[1])),maxY:Math.max(...points.map(p=>p[1]))}),inReservation=([x,y])=>x>=5&&x<=10&&y>=5&&y<=10,rgbaAt=(pixels,x,y)=>Array.from(pixels.slice((y*16+x)*4,(y*16+x)*4+4));
const northHarm=cueLayer("known-harm","north"),northSlow=cueLayer("slow","north"),harmPoints=opaqueCoordinates(northHarm),slowPoints=opaqueCoordinates(northSlow);
assert.deepEqual(bbox(harmPoints),{minX:3,maxX:12,minY:0,maxY:3});assert.equal(harmPoints.length,16,"shallow crescent stays <=10px wide and <=4px deep");assert.deepEqual(harmPoints.filter(([,y])=>y===0).map(([x])=>x),[3,4,11,12],"outer shoulders stay separated");assert.deepEqual(harmPoints.filter(([,y])=>y===1).map(([x])=>x),[4,5,10,11],"shoulders step inward");assert.deepEqual(harmPoints.filter(([,y])=>y===2).map(([x])=>x),[5,6,9,10],"second step stays open");assert.deepEqual(harmPoints.filter(([,y])=>y===3).map(([x])=>x),[6,7,8,9],"short inner bow joins the crescent");assert.deepEqual(slowPoints,[[7,0],[3,1],[7,1],[12,1],[4,2],[7,2],[11,2],[5,3],[10,3]],"slow owns exactly three disconnected three-pixel rays");assert.equal(slowPoints.length,9);assert.ok([...harmPoints,...slowPoints].every(point=>!inReservation(point)),"north sources preserve central 6×6");
const components=(pixels,diagonal=true)=>{const points=new Set(opaqueCoordinates(pixels).map(([x,y])=>`${x},${y}`)),groups=[];while(points.size){const first=points.values().next().value,queue=[first],group=[];points.delete(first);while(queue.length){const value=queue.pop(),[x,y]=value.split(",").map(Number);group.push([x,y]);for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){if(!dx&&!dy||!diagonal&&dx&&dy)continue;const key=`${x+dx},${y+dy}`;if(points.delete(key))queue.push(key)}}groups.push(group)}return groups};assert.equal(components(northHarm).length,1,"harm is one curved crescent");assert.deepEqual(components(northSlow).map(group=>group.length).sort((a,b)=>a-b),[3,3,3],"slow rays remain individually countable");
const luminance=rgba=>Math.round(rgba[0]*.2126+rgba[1]*.7152+rgba[2]*.0722);assert.ok(luminance(CUE_PALETTE.harmHighlight)>luminance(CUE_PALETTE.slowInner),"harm core is brighter than slow in literal grayscale");assert.ok(luminance(CUE_PALETTE.slowInner)>luminance(CUE_PALETTE.slowOuter),"each slow ray moves from darker outer to lighter inner value");assert.ok(luminance(CUE_PALETTE.harmHighlight)>luminance(CUE_PALETTE.harmBody),"harm crescent owns authored inner value pixels");assert.notDeepEqual(alphaMask(northHarm),alphaMask(northSlow),"geometry distinguishes harm and slow without hue");assert.notEqual(rgbaHash(literalGray(northHarm)),rgbaHash(literalGray(northSlow)));

for(const [turn,direction] of DIRECTIONS.entries()){for(const kind of CUE_KINDS){const source=cueLayer(kind,direction),expected=rotateClockwise(cueLayer(kind,"north"),turn);assert.deepEqual(source,expected,`${kind}/${direction} is exact ${turn*90}° integer rotation`);assert.equal(source.length,16*16*4);assert.ok(opaqueCoordinates(source).every(([x,y])=>x>=0&&x<16&&y>=0&&y<16&&!inReservation([x,y])));for(let i=3;i<source.length;i+=4)assert.ok(source[i]===0||source[i]===255,`${kind}/${direction} owns binary alpha`)}}

for(const [stateName,state] of Object.entries(fixture.states)){const componentLayers=[];for(const direction of DIRECTIONS)for(const kind of state[direction]??[])componentLayers.push({kind,direction,pixels:cueLayer(kind,direction)});const before=componentLayers.map(row=>rgbaHash(row.pixels)),combined=cueStatePixels(state);for(const row of componentLayers)for(const [x,y] of opaqueCoordinates(row.pixels))assert.deepEqual(rgbaAt(combined,x,y),rgbaAt(row.pixels,x,y),`${stateName} preserves ${row.kind}/${row.direction}`);assert.deepEqual(componentLayers.map(row=>rgbaHash(row.pixels)),before,"compositing cannot mutate component sources");assert.ok(opaqueCoordinates(combined).every(point=>!inReservation(point)))}
const worst=cueStatePixels(fixture.states.fourDirectionCombined),worstHarm=cueStatePixels(Object.fromEntries(DIRECTIONS.map(direction=>[direction,["known-harm"]]))),worstSlow=cueStatePixels(Object.fromEntries(DIRECTIONS.map(direction=>[direction,["slow"]])));assert.equal(components(worstHarm).length,4,"four-way harm remains four discrete crescents");assert.equal(components(worstSlow).length,12,"four-way slow retains twelve individually countable rays");assert.ok([0,1,14,15].some(y=>{for(let x=0;x<16;x++)if(rgbaAt(worst,x,y)[3]===0)return true;return false}),"four-direction worst case keeps perimeter gaps instead of merging into a ring");

for(const backgroundID of Object.keys(BACKGROUNDS)){const state={north:["known-harm","slow"]},cue=cueStatePixels(state),tile=tilePixels({backgroundID,state});for(const [x,y] of opaqueCoordinates(cue))assert.deepEqual(rgbaAt(tile,x,y),rgbaAt(cue,x,y),`${backgroundID} does not recolour fixed cues`)}
for(const visibility of ["fringe","hidden"]){const withCues=tilePixels({backgroundID:"denseGrowth",state:fixture.states.fourDirectionCombined,visibility}),withoutCues=tilePixels({backgroundID:"denseGrowth",state:{},visibility});assert.deepEqual(withCues,withoutCues,`${visibility} remains cue-free`)}
const marker=partyMarkerPixels(),layered=tilePixels({backgroundID:"darkStone",state:{north:["slow"]}});assert.notDeepEqual(rgbaAt(marker,7,2),rgbaAt(layered,7,2),"slow cue composites after the party disc");assert.deepEqual(rgbaAt(layered,7,7),rgbaAt(marker,7,7),"central party identity remains clear");

for(const kind of CUE_KINDS)for(const direction of DIRECTIONS){const record=manifest.sources[kind][direction],image=await loadImage(path.join(artifact,record.native.file)),scaled=await loadImage(path.join(artifact,record.scale400.file));assert.deepEqual([image.width,image.height],[16,16]);assert.deepEqual([scaled.width,scaled.height],[64,64]);assert.equal(record.rgbaSHA256,rgbaHash(cueLayer(kind,direction)));const canvas=createCanvas(16,16),context=canvas.getContext("2d");context.drawImage(image,0,0);const pixels=context.getImageData(0,0,16,16).data;for(let i=3;i<pixels.length;i+=4)assert.ok(pixels[i]===0||pixels[i]===255)}
for(const [file,width,height] of [["evidence/cardinal-cues-native.png",368,90],["evidence/cardinal-cues-400pct.png",368,178],["evidence/two-and-four-direction-states.png",520,190],["evidence/background-matrix.png",640,190],["evidence/visibility-matrix.png",480,190],["evidence/collision-bounds.png",384,192],["evidence/ordinary-phone-368x800.png",368,800],["evidence/ordinary-phone-368x800-grayscale.png",368,800]]){const image=await loadImage(path.join(artifact,file));assert.deepEqual([image.width,image.height],[width,height],file)}
execFileSync(process.execPath,[script]);assert.deepEqual(fs.readFileSync(manifestPath),firstManifest,"repeat export is byte-identical");console.log("Field consequence cue proof passed.");
