import assert from "node:assert/strict";
import {inkEconomyContractVersion,pigmentRecipes,previewPigmentProcess,previewVialPreparation,vialMeasureCost,vialYieldApplications} from "../src/ink-vial-contract.js";
import {mixedInkCandidateVersion} from "../src/mixed-ink-kit.js";
const stock={copper:2,ichor:1,sulfur:2,obsidian:1,resin:2,cyan:8,magenta:4,yellow:4,depth:4},recipe={cyan:68,magenta:32,yellow:8,depth:34,conversionVersion:mixedInkCandidateVersion};
assert.deepEqual(pigmentRecipes,{copper:{resourceID:"copper",base:"cyan",resourceUnits:1,measureYield:4},ichor:{resourceID:"ichor",base:"magenta",resourceUnits:1,measureYield:4},sulfur:{resourceID:"sulfur",base:"yellow",resourceUnits:1,measureYield:4},obsidian:{resourceID:"obsidian",base:"depth",resourceUnits:1,measureYield:4}});
const processed=previewPigmentProcess({version:inkEconomyContractVersion,resourceID:"copper",quantity:1,stock,stockRevision:7,previewRevision:7});assert.equal(processed.after.copper,1);assert.equal(processed.after.cyan,12);assert.deepEqual(processed.consumed,{copper:1});assert.deepEqual(processed.produced,{cyan:4});
assert.deepEqual(vialMeasureCost(recipe),{cyan:3,magenta:2,yellow:1,depth:2});const prepared=previewVialPreparation({version:inkEconomyContractVersion,recipe,stock,stockRevision:7,previewRevision:7});assert.equal(prepared.ok,true);assert.equal(prepared.after.resin,1);assert.equal(prepared.after.cyan,5);assert.equal(prepared.after.magenta,2);assert.equal(prepared.after.yellow,3);assert.equal(prepared.after.depth,2);assert.deepEqual(prepared.preparedVial,{recipe,remainingApplications:12});assert.deepEqual(prepared.consumed,{resin:1,cyan:3,magenta:2,yellow:1,depth:2});assert.equal(vialYieldApplications,12);
for(const rejected of [previewVialPreparation({version:inkEconomyContractVersion,recipe,stock:{...stock,resin:0},stockRevision:7,previewRevision:7}),previewVialPreparation({version:inkEconomyContractVersion,recipe,stock,stockRevision:8,previewRevision:7})]){assert.equal(rejected.ok,false);assert.strictEqual(rejected.before,rejected.after);assert.equal(rejected.preparedVial,null);}
assert.throws(()=>previewPigmentProcess({version:inkEconomyContractVersion,resourceID:"toxin",quantity:1,stock,stockRevision:7,previewRevision:7}),/unsupported-pigment-resource/);
assert.throws(()=>previewPigmentProcess({version:inkEconomyContractVersion,resourceID:"copper",quantity:Number.MAX_SAFE_INTEGER,stock:{...stock,copper:Number.MAX_SAFE_INTEGER,cyan:Number.MAX_SAFE_INTEGER},stockRevision:7,previewRevision:7}),/unsafe-integer/);assert.throws(()=>previewVialPreparation({version:inkEconomyContractVersion,recipe,stock,stockRevision:-1,previewRevision:-1}),/unsafe-integer/);
console.log("Asset Lab ink vial economy contract tests passed.");
