import assert from "node:assert/strict";
import {commandBounds,hash} from "../src/generator.js";
import {gearSlots,itemFamilies,itemGridColumns,itemIconCommands,itemIconHash,equipmentFixtures,resolveEquipmentFilter,locationSnapshots,itemDisplayMeta,itemLocationActions,itemCountLabel,equipmentGridSelectionProof,catalogueItemVisualVersion,catalogueItemIDs,catalogueItemIconCommands,catalogueItemSilhouetteHash,unknownItemIconCommands,resolveCatalogueItemIcon,tier2CatalogueVisualVersion,tier2CatalogueItemIDs,tier2ComparisonPairs,tier2CatalogueItemIconCommands,tier2CatalogueItemSilhouetteHash,tier3CatalogueVisualVersion,tier3CatalogueItemIDs,tier3ComparisonPairs,tier3CatalogueItemIconCommands,tier3CatalogueItemSilhouetteHash} from "../src/item-kit.js";
import {economyIdentityCommands,economyIdentityFixtures} from "../src/economy-identity-kit.js";
import {resourceInventoryIconCommands} from "../src/resource-kit.js";
assert.equal(itemGridColumns,6,"phone inventory and loot surfaces use six item icons per row");
assert.deepEqual(gearSlots,["weapon","offhand","head","armor","hands","feet","tool","keepsake"],"all exact live GearSlot raw values, including armor→Body, must remain covered");
const hashes=itemFamilies.map(itemIconHash);assert.equal(new Set(hashes).size,itemFamilies.length,"item families require whole-icon silhouette separation");
for(const family of itemFamilies){const b=commandBounds(itemIconCommands(family));assert.ok(b.minX>=0&&b.minY>=0&&b.maxX<=32&&b.maxY<=32);assert.deepEqual(itemIconCommands(family),itemIconCommands(family),"location/status cannot reroll identity");}
assert.throws(()=>itemIconCommands("unknown"),/unknown-item-family/);
for(const slot of ["all",...gearSlots]){const result=resolveEquipmentFilter(slot),expected=slot==="armor"?"Body":slot==="offhand"?"Off-hand":slot==="all"?"All":slot[0].toUpperCase()+slot.slice(1);assert.equal(result.items.every(item=>slot==="all"||item.slot===slot),true);assert.equal(result.displayName,expected);}
const weapons=resolveEquipmentFilter("weapon");assert.equal(weapons.baseline.id,"pointed-1");assert.equal(weapons.baseline.where,"Worn · Mara");assert.deepEqual(weapons.items.slice(0,4).map(item=>item.delta),["current · 6 damage","−2 damage","+1 damage · unavailable at home","+0 damage · Storehouse full"]);
const snapshots=locationSnapshots();assert.equal(new Set(snapshots.map(item=>item.where)).size,4);assert.equal(new Set(snapshots.map(item=>item.id)).size,1);assert.equal(new Set(snapshots.map(item=>item.family)).size,1);assert.equal(new Set(snapshots.map(item=>itemIconHash(item.family))).size,1);assert.equal(equipmentFixtures.some(item=>/better|green|red/i.test(item.delta)),false);assert.throws(()=>resolveEquipmentFilter("armor_alias"),/unknown-gear-slot/);
assert.equal(itemDisplayMeta(equipmentFixtures[equipmentGridSelectionProof.selectedOrdinaryIndex],equipmentGridSelectionProof.selectedOrdinaryIndex).rarity,"ordinary");assert.equal(itemDisplayMeta(equipmentFixtures[equipmentGridSelectionProof.unselectedFineIndex],equipmentGridSelectionProof.unselectedFineIndex).rarity,"fine");assert.equal(equipmentGridSelectionProof.selectedFineIndex,equipmentGridSelectionProof.unselectedFineIndex,"combined selection+fine uses the same fine fixture in the grayscale panel");assert.deepEqual(itemLocationActions("Worn · Mara"),["Take off","Inspect"]);assert.deepEqual(itemLocationActions("Stored"),["Equip","Inspect"]);assert.deepEqual(itemLocationActions("Overflow · safe"),["Store first","Inspect"]);assert.deepEqual(itemLocationActions("Carried · current world"),["Unavailable","Inspect"]);
for(const slot of gearSlots){for(const item of resolveEquipmentFilter(slot).items)assert.deepEqual(itemDisplayMeta(item),itemDisplayMeta(equipmentFixtures.find(candidate=>candidate.id===item.id)),`${item.id} metadata must not change under ${slot} filtering`);}assert.equal(itemDisplayMeta(resolveEquipmentFilter("keepsake").items[0]).known,false,"filtering must not identify an unknown item");assert.equal(itemDisplayMeta(resolveEquipmentFilter("head").items[0]).provenance,"Known inventory record","filtering must not assign first-cell crafted provenance");assert.throws(()=>itemDisplayMeta({id:"missing"}),/unknown-equipment-fixture/);
assert.equal(itemCountLabel(0),"0 items");assert.equal(itemCountLabel(1),"1 item");assert.equal(itemCountLabel(11),"11 items");
assert.equal(catalogueItemVisualVersion,"catalogue-item-visual-1.0.0");
assert.equal(catalogueItemIDs.length,30,"first exact-ID slice is 11 ordinary gear + 17 consumables + 2 curios");
assert.equal(new Set(catalogueItemIDs).size,catalogueItemIDs.length,"catalogue IDs map exactly once");
const catalogueHashes=catalogueItemIDs.map(catalogueItemSilhouetteHash);assert.equal(new Set(catalogueHashes).size,catalogueHashes.length,"every known first-slice item requires a distinct native grayscale silhouette");
for(const id of catalogueItemIDs){const bounds=commandBounds(catalogueItemIconCommands(id));assert.ok(bounds.minX>=0&&bounds.minY>=0&&bounds.maxX<=32&&bounds.maxY<=32,`${id} stays inside 32px`);assert.deepEqual(catalogueItemIconCommands(id),catalogueItemIconCommands(id),`${id} is deterministic`);}
assert.throws(()=>catalogueItemIconCommands("missing"),/unknown-catalogue-item/);
const unknownOccupied=new Set();for(const {x,y,w,h} of unknownItemIconCommands())for(let py=y;py<y+h;py++)for(let px=x;px<x+w;px++)unknownOccupied.add(`${px},${py}`);assert.equal(catalogueHashes.includes(hash([...unknownOccupied].sort())),false,"unknown wrapped mass cannot equal a known item");
const unknownHumming=resolveCatalogueItemIcon({catalogItemID:"curio_humming_shard",identified:false}),unknownKnot=resolveCatalogueItemIcon({catalogItemID:"curio_bound_knot",identified:false});assert.deepEqual(unknownHumming,unknownKnot,"unidentified curios cannot preview their eventual result");assert.notDeepEqual(resolveCatalogueItemIcon({catalogItemID:"curio_humming_shard",identified:true}),resolveCatalogueItemIcon({catalogItemID:"curio_bound_knot",identified:true}),"identified curios own distinct known identities");assert.throws(()=>resolveCatalogueItemIcon({catalogItemID:"blade_chipped",identified:false}),/unidentified-state-not-supported/);assert.throws(()=>resolveCatalogueItemIcon({catalogItemID:"curio_humming_shard",identified:false,rarity:"rare"}),/unknown-or-missing/);assert.throws(()=>resolveCatalogueItemIcon({catalogItemID:"missing",identified:true}),/unknown-catalogue-item/);
assert.equal(tier2CatalogueVisualVersion,"catalogue-tier2-proof-0.1.0");
assert.equal(tier2CatalogueItemIDs.length,11,"isolated tier-2 proof covers the exact approved eleven IDs");
assert.equal(new Set(tier2CatalogueItemIDs).size,11);
assert.deepEqual(tier2ComparisonPairs.map(pair=>pair[1]),tier2CatalogueItemIDs,"each tier-2 identity has one review counterpart");
const tier2Hashes=tier2CatalogueItemIDs.map(tier2CatalogueItemSilhouetteHash);
assert.equal(new Set([...catalogueHashes,...tier2Hashes]).size,catalogueHashes.length+tier2Hashes.length,"tier-2 and accepted known items require pairwise native silhouettes");
for(const id of tier2CatalogueItemIDs){const commands=tier2CatalogueItemIconCommands(id),bounds=commandBounds(commands);assert.ok(bounds.minX>=0&&bounds.minY>=0&&bounds.maxX<=32&&bounds.maxY<=32,`${id} stays inside 32px`);assert.deepEqual(commands,tier2CatalogueItemIconCommands(id),`${id} is deterministic`);for(const context of ["inventory","trading_post","recycler","blacksmith"])assert.equal(hash(commands),hash(tier2CatalogueItemIconCommands(id)),`${id} pixels stay fixed in ${context}`);}
assert.throws(()=>tier2CatalogueItemIconCommands("missing"),/unknown-tier2-catalogue-item/);
const occupiedHash=commands=>{const occupied=new Set();for(const {x,y,w,h} of commands)for(let py=y;py<y+h;py++)for(let px=x;px<x+w;px++)occupied.add(`${px},${py}`);return hash([...occupied].sort());};
const scale2=commands=>commands.map(command=>({...command,x:command.x*2,y:command.y*2,w:command.w*2,h:command.h*2}));
const crossDomain=[unknownItemIconCommands(),economyIdentityCommands(economyIdentityFixtures[0]),economyIdentityCommands(economyIdentityFixtures[1]),scale2(resourceInventoryIconCommands("essence_raw"))];
assert.equal(new Set([...tier2Hashes,...crossDomain.map(occupiedHash)]).size,tier2Hashes.length+crossDomain.length,"tier-2 icons remain distinct from unknown, Rubble, glassy quill, and Raw Essence in mixed economy grids");
assert.equal(tier3CatalogueVisualVersion,"catalogue-tier3-proof-0.1.0");
assert.equal(tier3CatalogueItemIDs.length,11,"isolated tier-3 proof covers the exact eleven catalogue IDs");
assert.deepEqual(tier3ComparisonPairs.map(pair=>pair[1]),tier3CatalogueItemIDs);
const tier3Hashes=tier3CatalogueItemIDs.map(tier3CatalogueItemSilhouetteHash);
assert.equal(new Set([...catalogueHashes,...tier2Hashes,...tier3Hashes]).size,catalogueHashes.length+tier2Hashes.length+tier3Hashes.length,"all accepted and candidate catalogue silhouettes remain pairwise distinct");
for(const id of tier3CatalogueItemIDs){const commands=tier3CatalogueItemIconCommands(id),bounds=commandBounds(commands);assert.ok(bounds.minX>=0&&bounds.minY>=0&&bounds.maxX<=32&&bounds.maxY<=32,`${id} stays inside 32px`);assert.deepEqual(commands,tier3CatalogueItemIconCommands(id),`${id} is deterministic`);}
assert.equal(new Set([...tier3Hashes,...crossDomain.map(occupiedHash)]).size,tier3Hashes.length+crossDomain.length,"tier-3 icons remain distinct from mixed economy bodies");
assert.throws(()=>tier3CatalogueItemIconCommands("missing"),/unknown-tier3-catalogue-item/);
console.log("Asset Lab item-icon tests passed.");
