import assert from"node:assert/strict";import fs from"node:fs";import path from"node:path";import{execFileSync}from"node:child_process";import{createRequire}from"node:module";import{fileURLToPath}from"node:url";
const{createCanvas,loadImage}=createRequire(import.meta.url)("@napi-rs/canvas"),root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),".."),script=path.join(root,"scripts/export-library-bookcase.mjs"),growthScript=path.join(root,"scripts/export-library-growth-sequence.mjs"),artifact=path.join(root,"artifacts/library-bookcase-v0.1"),run=()=>{execFileSync(process.execPath,[script]);execFileSync(process.execPath,[growthScript])};execFileSync(process.execPath,[script]);const api=await import(`${script}?test=${Date.now()}`);execFileSync(process.execPath,[growthScript]);const manifestPath=path.join(artifact,"manifest.json"),first=fs.readFileSync(manifestPath),m=JSON.parse(first);
assert.equal(m.schemaVersion,2);assert.equal(m.integrationReady,false);assert.equal(m.assetID,"library.bookcase.runtime-kit");assert.equal(m.states,undefined);assert.match(m.compositor.stateAuthority,/evidence PNGs are non-authoritative/);assert.deepEqual(Object.keys(m.sectionLayout),["diaries","bestiary","dictionary","fieldNotes","worldHistory"]);assert.match(m.countSemantics.bestiary,/Land, Shore, Water and Air/);
const boxes=Object.entries(m.sectionLayout);for(const[id,b]of boxes){assert.ok(b.width*2>=44&&b.height*2>=44,`${id} 44pt`);assert.ok(b.x>=0&&b.y>=0&&b.x+b.width<=184&&b.y+b.height<=260)}for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++){const[a,A]=boxes[i],[b,B]=boxes[j];assert.equal(A.x<B.x+B.width&&A.x+A.width>B.x&&A.y<B.y+B.height&&A.y+A.height>B.y,false,`${a}/${b} collision`)}
assert.deepEqual([0,1,2,4,7,10].map(api.stageForCount),["empty","loose-page","stitched-folio","softbound","hardcover","full-hardcover-with-slips"]);assert.deepEqual(api.volumesForCount(8),[8]);assert.deepEqual(api.volumesForCount(9),[8,1]);assert.deepEqual(api.dictionaryVolumeCounts(Array.from({length:7},(_,i)=>({id:`rune.${i+1}`,encountered:true}))),[7,0,0]);assert.deepEqual(api.dictionaryVolumeCounts(Array.from({length:8},(_,i)=>({id:`rune.${i+1}`,encountered:true}))),[7,1,0]);assert.deepEqual(api.objectMetrics("loose-page","vance",1),{width:8,height:7});assert.deepEqual(api.objectMetrics("stitched-folio","vance",2),{width:8,height:13});assert.deepEqual(api.objectMetrics("stitched-folio","vance",3),{width:9,height:13});
assert.deepEqual(Object.keys(m.sprites.stages),["loose-page","stitched-folio","softbound","hardcover","full-hardcover-with-slips"]);assert.ok(m.sprites.spineVariants.length>=12);assert.notDeepEqual(api.seededVariant("vance"),api.seededVariant("noll"));const silhouetteSignatures=[1,2,3,4].map(count=>{const stage=api.stageForCount(count),metrics=api.objectMetrics(stage,"vance",count);return`${stage}:${metrics.width}x${metrics.height}`});assert.equal(new Set(silhouetteSignatures).size,4,"1/2/3/4 silhouettes must remain pairwise distinct without color");
const image=await loadImage(path.join(artifact,m.shell.file)),base=createCanvas(184,260);base.getContext("2d").drawImage(image,0,0);const bytes=c=>c.toBuffer("image/png"),outsideEqual=(a,b,box)=>{const A=a.getContext("2d").getImageData(0,0,184,260).data,B=b.getContext("2d").getImageData(0,0,184,260).data;for(let y=0;y<260;y++)for(let x=0;x<184;x++)if(!(x>=box.x&&x<box.x+box.width&&y>=box.y&&y<box.y+box.height)){const n=(y*184+x)*4;for(let q=0;q<4;q++)assert.equal(A[n+q],B[n+q],`outside ${box.label} changed`)}};
const one={diaries:[{id:"vance",authoredOrder:1,pageCount:1}]},grown={diaries:[{id:"vance",authoredOrder:1,pageCount:7}]},added={diaries:[{id:"vance",authoredOrder:1,pageCount:1},{id:"noll",authoredOrder:2,pageCount:1}]},A=api.composeLibrary(base,one).canvas,B=api.composeLibrary(base,grown).canvas,C=api.composeLibrary(base,added).canvas;assert.notDeepEqual(bytes(A),bytes(B));assert.notDeepEqual(bytes(A),bytes(C));outsideEqual(A,B,m.sectionLayout.diaries);outsideEqual(A,C,m.sectionLayout.diaries);
const shuffled={...api.fixtures.developed,diaries:[...api.fixtures.developed.diaries].reverse(),bestiary:Object.fromEntries(Object.entries(api.fixtures.developed.bestiary).map(([k,v])=>[k,[...v].reverse()])),dictionary:[...api.fixtures.developed.dictionary].reverse(),fieldNotes:[...api.fixtures.developed.fieldNotes].reverse(),worldHistory:[...api.fixtures.developed.worldHistory].reverse()};assert.deepEqual(bytes(api.composeLibrary(base,api.fixtures.developed).canvas),bytes(api.composeLibrary(base,shuffled).canvas));assert.doesNotThrow(()=>api.composeLibrary(base,{diaries:Array.from({length:29},(_,i)=>({id:`traveller.${i}`,authoredOrder:i,pageCount:7}))}));
const normalized=api.normalizeCollection({diaries:[{id:"hidden",pageCount:0}],bestiary:{land:[],shore:[],water:["deep-water-seen"],air:[]},dictionary:[{id:"rune.2",encountered:true,known:false}]});assert.deepEqual(normalized.diaries,[]);assert.deepEqual(normalized.bestiary,{land:[],shore:[],water:["deep-water-seen"],air:[]});assert.deepEqual(normalized.dictionary,[{id:"rune.2",known:false}]);assert.equal(m.unknownRuneDisclosure,"??");assert.equal(m.undiscoveredPeopleAndSpecies,"absent");assert.match(m.deepWaterSemantics,/no combat or harvest inference/);
for(const record of[m.shell,...Object.values(m.sprites.stages),...m.sprites.spineVariants,...Object.values(m.attention)]){const im=await loadImage(path.join(artifact,record.file)),c=createCanvas(im.width,im.height),g=c.getContext("2d");g.drawImage(im,0,0);const d=g.getImageData(0,0,im.width,im.height).data,a=new Set();for(let i=3;i<d.length;i+=4)a.add(d[i]);assert.deepEqual([...a].sort((x,y)=>x-y),a.has(0)?[0,255]:[255])}
for(const key of["emptyPhone","earlyPhone","developedPhone","diaryAttentionPhone","bestiaryAttentionPhone","grayscalePhone","collisionDisclosurePhone","diaryOnePagePhone","diaryGrownPhone","diaryAddedPhone","bestiaryEightPhone","bestiaryNinePhone","dictionarySevenPhone","dictionaryEightPhone"])assert.deepEqual([m.evidence[key].width,m.evidence[key].height],[368,800]);assert.equal(m.evidence.diaryGrowthPhones.length,4);for(const record of m.evidence.diaryGrowthPhones)assert.deepEqual([record.width,record.height],[368,800]);assert.deepEqual([m.evidence.diaryGrowthSequence.width,m.evidence.diaryGrowthSequence.height],[1472,800]);assert.deepEqual([m.evidence.diaryGrowthGrayscale.width,m.evidence.diaryGrowthGrayscale.height],[1472,800]);assert.deepEqual(m.paperStageLegibility.sequence,[1,2,3,4]);assert.equal(new Set(m.evidence.diaryGrowthPhones.map(record=>record.sha256)).size,4);for(const stale of["library-empty-logical-184x260.png","library-early-logical-184x260.png","library-developed-logical-184x260.png"])assert.equal(fs.existsSync(path.join(artifact,"source",stale)),false);
run();assert.deepEqual(fs.readFileSync(manifestPath),first);console.log("Library runtime-composable collection kit passed");
