import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import Ajv2020 from "ajv/dist/2020.js";
import {createHash} from "node:crypto";
import {inflateSync} from "node:zlib";
import {liftedTerrainPipelineVersions,adaptLiftedTerrainRequest} from "../src/lifted-terrain-contract.js";
import {canonicalJSON} from "../src/generator.js";
import {rasterTokens} from "../src/regression.js";
const schema=JSON.parse(await readFile(new URL("../schemas/lifted-terrain-request.schema.json",import.meta.url),"utf8")),validate=new Ajv2020({strict:true,allErrors:true}).compile(schema);
const request={pipelineVersions:liftedTerrainPipelineVersions,ground:"soil",revealed:true,crumbled:false,cracking:false,elevation:2,adjacencyNESW:15,terrainSeedUInt32:82734192,featureVariant:2,worldGrade:{red:14,green:3,blue:-12,value:-4},southExposureLevels:1};
assert.equal(validate(request),true,JSON.stringify(validate.errors));const a=adaptLiftedTerrainRequest(request),b=adaptLiftedTerrainRequest(structuredClone(request));assert.equal(a.ok,true);assert.deepEqual(a,b);assert.equal(a.profile.width,16);assert.equal(a.profile.height,19);assert.match(a.pixelHash,/^[0-9a-f]{8}$/);
for(const mutate of [r=>{delete r.southExposureLevels;},r=>{r.extra=true;},r=>{r.worldGrade.temperature=80;},r=>{r.pipelineVersions.renderProfileVersion="latest";}]){const broken=structuredClone(request);mutate(broken);assert.equal(validate(broken),false);assert.equal(adaptLiftedTerrainRequest(broken).ok,false);}
const inconsistent=structuredClone(request);inconsistent.southExposureLevels=3;inconsistent.elevation=1;assert.equal(validate(inconsistent),true,"cross-field elevation semantics belong to the public adapter");assert.equal(adaptLiftedTerrainRequest(inconsistent).ok,false);
for(const forced of [{...request,revealed:false,southExposureLevels:1},{...request,crumbled:true,southExposureLevels:1},{...request,ground:"chasm",southExposureLevels:1},{...request,ground:"ice",southExposureLevels:1},{...request,ground:"growth",southExposureLevels:1},{...request,ground:"groundcover",southExposureLevels:1}])assert.equal(adaptLiftedTerrainRequest(forced).diagnostics.some(issue=>issue.code==="inconsistent-south-exposure"),true);
const vectorPack=JSON.parse(await readFile(new URL("../integration/lifted-terrain-v1/conformance-vectors.json",import.meta.url),"utf8")),sha=value=>createHash("sha256").update(Buffer.from(canonicalJSON(value))).digest("hex");for(const vector of vectorPack.vectors){const output=adaptLiftedTerrainRequest(vector.request);assert.equal(output.ok,true);assert.equal(sha(vector.request),vector.canonicalRequestSha256);assert.equal(sha(output.commands),vector.rectangleSha256);assert.equal(sha(rasterTokens(output.commands,16,19)),vector.pixelTokenSha256);}
const manifest=JSON.parse(await readFile(new URL("../integration/lifted-terrain-v1/manifest.json",import.meta.url),"utf8")),claimed=manifest.canonicalManifestSha256;delete manifest.canonicalManifestSha256;assert.equal(sha(manifest),claimed);assert.equal(manifest.outputs.length,2);for(const output of manifest.outputs){const bytes=await readFile(new URL(`../integration/lifted-terrain-v1/${output.file}`,import.meta.url));assert.equal(createHash("sha256").update(bytes).digest("hex"),output.fileSha256);const chunks=[];for(let at=8;at<bytes.length;){const length=bytes.readUInt32BE(at),type=bytes.toString("ascii",at+4,at+8);if(type==="IDAT")chunks.push(bytes.subarray(at+8,at+8+length));at+=12+length;}const raw=inflateSync(Buffer.concat(chunks)),pixels=Buffer.alloc(16*19*4);for(let y=0;y<19;y++)raw.copy(pixels,y*64,y*65+1,y*65+65);assert.equal(createHash("sha256").update(pixels).digest("hex"),output.decodedRgbaSha256);}
console.log("Asset Lab lifted-terrain adapter contract tests passed.");
