import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {createHash} from "node:crypto";
import {inflateSync} from "node:zlib";
import {groundTypes} from "../src/world-generator.js";
import Ajv from "ajv";

const root=new URL("../integration/map-slice-v1/",import.meta.url),manifest=JSON.parse(await readFile(new URL("manifest.json",root),"utf8")),schema=JSON.parse(await readFile(new URL("../schemas/map-slice-manifest.schema.json",import.meta.url),"utf8"));
const validate=new Ajv({allErrors:true,strict:true}).compile(schema);assert.equal(validate(manifest),true,JSON.stringify(validate.errors));for(const mutate of [value=>{value.pipelineVersions.surprise=1;},value=>{value.liveInputContract.flora.identity.surprise="x";},value=>{value.liveInputContract.floraFixtureVectors[0].swift.traits.tissue.surprise=1;},value=>{value.liveInputContract.worldGradeConformanceVectors[0].worldGrade.surprise=1;},value=>{value.minimap.portalException=true;},value=>{value.outputs[0].surprise=1;}]){const invalid=structuredClone(manifest);mutate(invalid);assert.equal(validate(invalid),false,"unknown nested field must be rejected by standards-compliant schema");}
assert.equal(manifest.identityKind,"topDownMapSliceConformancePack");assert.match(manifest.role,/not-exhaustive-runtime-atlas/);assert.deepEqual(manifest.liveInputContract.missingPersistedFields,[]);assert.equal(manifest.liveInputContract.worldGradeConformanceVectors.length,3);assert.equal(manifest.pipelineVersions.worldGradeAdapterVersion,"world-grade-1.0.0");assert.equal(manifest.fog.assetContainsPixels,false);assert.equal(manifest.fog.containsInformativePixels,false);assert.equal(manifest.fog.uniformFill,"#17171a");assert.match(manifest.fog.rule,/one invariant uniform fill/);assert.match(manifest.runtimeRequestContract.adjacencyRule,/exactly equals the center ground raw value/);assert.equal(manifest.minimap.visibilityOwnedByGame,true);assert.match(manifest.minimap.defaultRule,/every POI/);assert.doesNotMatch(JSON.stringify(manifest.minimap),/always-visible/);
assert.deepEqual(manifest.layerOrder,["terrain","flora","next-turn-warning","content","route-action-target","party-selection","visibility-gate"]);
const files=new Set();for(const output of manifest.outputs){assert.equal(output.role,"conformanceFixture");assert.ok(!files.has(output.file),`duplicate ${output.file}`);files.add(output.file);const bytes=await readFile(new URL(output.file,root));assert.equal(createHash("sha256").update(bytes).digest("hex"),output.fileSha256,`hash ${output.file}`);assert.match(output.pixelSha256,/^[0-9a-f]{64}$/);assert.deepEqual([...bytes.subarray(0,8)],[137,80,78,71,13,10,26,10]);}
for(const ground of groundTypes){const outputs=manifest.outputs.filter(output=>output.kind==="terrain"&&output.ground===ground);assert.equal(outputs.length,["water","deepWater","ice","chasm"].includes(ground)?16:1,ground);}
const fog=await readFile(new URL("overlay-fog-empty.png",root)),idat=[];for(let at=8;at<fog.length;){const length=fog.readUInt32BE(at),type=fog.toString("ascii",at+4,at+8);if(type==="IDAT")idat.push(fog.subarray(at+8,at+8+length));at+=12+length;}const raw=inflateSync(Buffer.concat(idat));for(let y=0;y<16;y++)for(let x=0;x<16;x++)assert.equal(raw[y*65+1+x*4+3],0,"fog alpha must be zero");
assert.ok(manifest.unsafeProofOnly.some(value=>value.includes("flora descriptors")));assert.ok(!manifest.outputs.some(output=>output.id.includes("abandon")));
assert.ok(!manifest.outputs.some(output=>output.id.includes("party-mara")));assert.match(manifest.tile.scaleRule,/nearest-neighbour-required/);assert.equal(manifest.seedContract.runtimeInput.startsWith("prederived terrainSeedUInt32"),true);
assert.equal(manifest.liveInputContract.floraFixtureVectors.length,2);assert.notEqual(manifest.liveInputContract.floraFixtureVectors[0].rectangleSha256,manifest.liveInputContract.floraFixtureVectors[1].rectangleSha256);assert.notEqual(manifest.liveInputContract.floraFixtureVectors[0].pixelSha256,manifest.liveInputContract.floraFixtureVectors[1].pixelSha256);
console.log("Asset Lab map-slice export contract tests passed.");
