import assert from "node:assert/strict";
import { stationCatalogue,siteCatalogue,distinctStationCommands,physicalSiteCommands,siteOccupantCommands,silhouetteHash } from "../src/place-kit.js";
import { commandBounds } from "../src/generator.js";
assert.equal(stationCatalogue.length,18);assert.equal(siteCatalogue.length,15);assert.equal(new Set(stationCatalogue.map(item=>item.id)).size,18);assert.equal(new Set(siteCatalogue.map(item=>item.id)).size,15);
for(const station of stationCatalogue){const warm=distinctStationCommands(station.id,{palette:"warm"}),cold=distinctStationCommands(station.id,{palette:"cold"}),bounds=commandBounds(warm);assert.equal(silhouetteHash(warm),silhouetteHash(cold),`${station.id} palette adaptation must preserve authored station identity`);assert.ok(bounds.minX>=0&&bounds.maxX<=48&&bounds.minY>=0&&bounds.maxY<=36);assert.notEqual(silhouetteHash(warm),silhouetteHash(distinctStationCommands(station.id,{state:"foundation"})));}
for(const id of ["constellation","survey_post","reliquary","anchorage","storehouse","workshop","blacksmith","distillery","channelworks"]){const states=[distinctStationCommands(id,{tier:1,state:"built"}),distinctStationCommands(id,{tier:3,state:"built"}),distinctStationCommands(id,{tier:1,state:"damaged"})].map(silhouetteHash);assert.equal(new Set(states).size,3,`${id} built/tier-3/damaged must remain visibly distinct`);}
for(const site of siteCatalogue){const warm=physicalSiteCommands(site.id,{palette:"warm"}),ash=physicalSiteCommands(site.id,{palette:"ash"}),bounds=commandBounds(warm),guarded=physicalSiteCommands(site.id,{state:"guarded"});assert.equal(silhouetteHash(warm),silhouetteHash(ash),`${site.id} palette adaptation must preserve authored site identity`);assert.ok(bounds.minX>=0&&bounds.maxX<=16&&bounds.minY>=0&&bounds.maxY<=16);assert.notEqual(silhouetteHash(warm),silhouetteHash(physicalSiteCommands(site.id,{state:"exhausted"})));assert.equal(silhouetteHash(warm),silhouetteHash(guarded),"guarded is occupant state, not site geometry");assert.ok(!guarded.some(command=>command.w===16&&command.color==="#74b8b0"),"guarded must never become a full-width accent badge");}
assert.ok(siteOccupantCommands("guard").length>0);
console.log("Asset Lab authored place-kit tests passed.");
