import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import {grounds,directions,familyBitmap,contourMask,normalizeTerrainLayerRequest,staticTerrainBody,motionOverlay,changedPixelCount} from "../src/terrain-layering-kit.js";
const root=path.resolve(import.meta.dirname,"..");
const artifact=path.join(root,"artifacts","terrain-layering-v0.1");
const req=(ground="soil",o={})=>({schemaVersion:"terrain-layers-v1",ground,point:{x:2,y:3},visualSeed:1773,worldGradeDescriptorHash:"world-grade-2-current",featureVariant:1,cardinalNeighbors:{north:"same",east:"same",south:"same",west:"same"},edgeContourIDs:{north:0,east:1,south:2,west:3},elevation:0,isCrumbled:false,isCracking:false,visibility:"full",motionBand:"moving",phaseOffset:7,presentationTick:0,reduceMotion:false,...o});
assert.equal(grounds.length,12);for(const g of grounds)for(let v=0;v<4;v++){const p=familyBitmap(g,v,1773);assert.equal(p.length,1024);for(let i=3;i<p.length;i+=4)assert.equal(p[i],255);}
for(let id=0;id<4;id++)for(const d of directions)assert.ok(contourMask(d,id).some(Boolean));
assert.throws(()=>normalizeTerrainLayerRequest({...req(),extra:true}),/fields/);assert.throws(()=>normalizeTerrainLayerRequest(req("bog")),/enum/);
const hiddenFact=req("soil",{cardinalNeighbors:{north:"unknown",east:"same",south:"same",west:"same"}});assert.deepEqual(staticTerrainBody(hiddenFact),staticTerrainBody({...hiddenFact,visualSeed:1773}),"unknown neighbor is invariant");
const equal=staticTerrainBody(req("soil",{elevation:0}));assert.deepEqual(equal,staticTerrainBody(req("soil",{elevation:2})),"elevation cannot create sidewalls or shade inside terrain body");
const seamless=staticTerrainBody(req("water",{cardinalNeighbors:{north:"same",east:"same",south:"same",west:"same"}}));const unknown=staticTerrainBody(req("water",{cardinalNeighbors:{north:"unknown",east:"unknown",south:"unknown",west:"unknown"}}));assert.deepEqual(seamless,unknown,"same/unknown neighbors cannot add a border or gutter");
const lowerAtSoil=staticTerrainBody(req("water",{cardinalNeighbors:{north:"same",east:"soil",south:"same",west:"same"}}));assert.notDeepEqual(lowerAtSoil,seamless,"higher-priority Soil must intrude irregularly into Water's side of the shared contour");const soilAtWater=staticTerrainBody(req("soil",{cardinalNeighbors:{north:"same",east:"same",south:"same",west:"water"}}));assert.deepEqual(soilAtWater,staticTerrainBody(req("soil")),"higher-priority tile must not gain a mirrored outline");
const fullMotion=motionOverlay(req("water",{presentationTick:8}));for(const visibility of ["fringe","remembered"])assert.ok(motionOverlay(req("water",{visibility,presentationTick:8})).every(v=>v===0));
assert.ok(fullMotion.some(v=>v));assert.deepEqual(motionOverlay(req("water",{reduceMotion:true,presentationTick:0})),motionOverlay(req("water",{reduceMotion:true,presentationTick:19})),"Reduce Motion is static");
const budgets={water:12,deepWater:8,groundcover:6,growth:8,ice:3};for(const [g,budget] of Object.entries(budgets)){let prior=motionOverlay(req(g,{visualSeed:g==="ice"?1776:1773,presentationTick:0,motionBand:"strong"}));for(let tick=1;tick<24;tick++){const now=motionOverlay(req(g,{visualSeed:g==="ice"?1776:1773,presentationTick:tick,motionBand:"strong"}));assert.ok(changedPixelCount(prior,now)<=budget,`${g} tick ${tick}`);prior=now;}}
const shuffled={};for(const key of Object.keys(req()).reverse())shuffled[key]=req()[key];assert.deepEqual(normalizeTerrainLayerRequest(req()),normalizeTerrainLayerRequest(shuffled));
const manifest=JSON.parse(fs.readFileSync(path.join(artifact,"manifest.json"),"utf8"));assert.equal(manifest.integrationReady,false);assert.deepEqual(manifest.grounds,grounds);assert.equal(manifest.contours.allAdjacencyCombinations,16);assert.equal(manifest.elevation.equalHeight,"no-shade-or-sidewall");assert.deepEqual(manifest.ruleReceipt,{geometry:"unchanged",passability:"unchanged",movement:"unchanged",sight:"unchanged",content:"unchanged"});assert.ok(manifest.outputs.length>=130);assert.ok(manifest.frameDifferences.every(x=>x.changed<=x.budget));
for(const file of ["evidence/static-368x800.png","evidence/static-grayscale-368x800.png","contact/water-all-adjacencies-400pct.png","contact/soil-all-adjacencies-400pct.png","contact/growth-all-adjacencies-400pct.png","evidence/mosaic-same-water-400pct.png","evidence/mosaic-same-soil-grayscale-400pct.png","evidence/mosaic-same-growth-native.png","evidence/mosaic-water-soil-pair-400pct.png","evidence/mosaic-soil-mud-pair-400pct.png","evidence/mosaic-growth-groundcover-pair-400pct.png","evidence/mosaic-turning-shoreline-400pct.png","evidence/mosaic-t-cross-junction-400pct.png","evidence/mosaic-equal-height-mixed-400pct.png","loop/frame-00.png"])assert.ok(fs.existsSync(path.join(artifact,file)),file);
assert.doesNotMatch(fs.readFileSync(path.join(root,"scripts/export-terrain-layering-proof.mjs"),"utf8"),/INTERACT/,"proof chrome cannot invent Interact");
assert.deepEqual(fs.readFileSync(path.join(artifact,"evidence/static-368x800.png")),fs.readFileSync(path.join(artifact,"evidence/hiddenMutation-368x800.png")),"hidden-neighbor mutation must be byte-identical");
assert.deepEqual(fs.readFileSync(path.join(artifact,"evidence/static-368x800.png")),fs.readFileSync(path.join(artifact,"evidence/rememberedMutation-368x800.png")),"remembered live mutation must not change frozen last-seen evidence");
assert.notDeepEqual(fs.readFileSync(path.join(artifact,"evidence/near-368x800.png")),fs.readFileSync(path.join(artifact,"evidence/far-368x800.png")),"near/far receipts must visibly separate while retaining geometry");
console.log("terrain layering kit tests passed");
