import assert from "node:assert/strict";import fs from "node:fs";import path from "node:path";import {spawnSync} from "node:child_process";import {wallGrounds,wallJoins,wallRoleMap,normalizeSouthWallRequest} from "../src/terrain-south-wall-v1.js";
const root=path.resolve(import.meta.dirname,".."),out=path.join(root,"integration/terrain-south-wall-v1"),run=()=>spawnSync(process.execPath,[path.join(root,"scripts/export-terrain-south-wall-v1.mjs")],{encoding:"utf8"});let r=run();assert.equal(r.status,0,r.stderr);const first=fs.readFileSync(path.join(out,"runtime/manifest.json"));r=run();assert.equal(r.status,0,r.stderr);assert.deepEqual(fs.readFileSync(path.join(out,"runtime/manifest.json")),first);const m=JSON.parse(first);
assert.equal(m.integrationReady,false);assert.deepEqual(m.profile.depths,[1,2,3]);assert.deepEqual(m.profile.wallSocket,{x:0,y:16,width:16,height:3});assert.equal(m.profile.pivot.y,18);assert.deepEqual(m.profile.grounds,wallGrounds);assert.deepEqual(m.profile.joins,wallJoins);assert.equal(m.profile.equalElevation,"no-wall");assert.equal(m.profile.hiddenOrOutOfMap,"no-wall");assert.ok(m.profile.layerOrder.indexOf("southWall")<m.profile.layerOrder.indexOf("supplementalContactShade"));
const req=(ground="stone",depth=3,join="span")=>({schemaVersion:"terrain-south-wall-v1",ground,southExposureLevels:depth,southNeighborDisclosure:"known",westContinuation:["span","rightCap"].includes(join),eastContinuation:["span","leftCap"].includes(join),featureVariant:0,worldGradeDescriptorHash:"receipt"});
for(const g of wallGrounds)for(const d of [1,2,3])for(const j of wallJoins){const a=wallRoleMap(req(g,d,j));assert.equal(a.length,48);assert.equal([...a].filter(v=>v>=0).length,16*d);assert.deepEqual(a,wallRoleMap(req(g,d,j)));}
for(const g of ["stone","soil","rubble"])for(const d of [1,2,3]){const span=wallRoleMap(req(g,d,"span"));for(let y=3-d;y<3;y++){assert.ok(span[y*16]>=0);assert.ok(span[y*16+15]>=0);}}
assert.ok([...wallRoleMap(req("stone",0,"isolated"))].every(v=>v===-1));for(const disclosure of ["hidden","outOfMap"]){const q={...req("stone",0,"isolated"),southNeighborDisclosure:disclosure};assert.ok([...wallRoleMap(q)].every(v=>v===-1));assert.throws(()=>normalizeSouthWallRequest({...q,southExposureLevels:1}),/undisclosed/);}
assert.throws(()=>normalizeSouthWallRequest({...req(),extra:true}),/fields/);assert.throws(()=>normalizeSouthWallRequest({...req(),ground:"water"}),/invalid/);assert.equal(Object.keys(m.assets).length,288);const files=fs.readdirSync(path.join(out,"runtime/assets"));assert.equal(files.length,new Set(Object.values(m.assets).map(x=>x.path)).size);for(const row of Object.values(m.assets)){assert.match(row.path,/^assets\/[a-f0-9]{64}\.png$/);assert.ok(fs.existsSync(path.join(out,"runtime",row.path)));}
for(const name of ["native-1x-color.png","native-2x-color.png","native-4x-color.png","native-1x-grayscale.png","native-2x-grayscale.png","native-4x-grayscale.png","phone-identical-a-368x800.png","phone-opposed-warm-368x800.png","phone-opposed-cool-368x800.png","phone-old-new-shade-only-1104x800.png"])assert.ok(fs.existsSync(path.join(out,"evidence",name)),name);
for(const scale of [1,2,4])for(const mode of ["color","grayscale"])assert.ok(fs.existsSync(path.join(out,"evidence",`composed-spans-${scale}x-${mode}.png`)));assert.ok(fs.existsSync(path.join(out,"evidence","phone-connected-spans-368x800.png")));
console.log(`terrain south wall v1 passed ${m.canonicalBodySHA256} ${Object.keys(m.assets).length} keys/${files.length} files`);
