import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import {spawnSync} from "node:child_process";
import {normalizeRuntimeRequest,layerOrder,depositKeys} from "../src/terrain-production-pack-v1.js";

const root=path.resolve(import.meta.dirname,".."),out=path.join(root,"integration/terrain-production-pack-v1"),manifestPath=path.join(out,"runtime/manifest.json");
const run=()=>spawnSync(process.execPath,[path.join(root,"scripts/export-terrain-production-pack-v1.mjs")],{encoding:"utf8"});
let r=run();assert.equal(r.status,0,r.stderr);const first=fs.readFileSync(manifestPath);r=run();assert.equal(r.status,0,r.stderr);assert.deepEqual(fs.readFileSync(manifestPath),first);
const m=JSON.parse(first),assetKeys=Object.keys(m.assets),cases=m.cases;
assert.equal(m.integrationReady,false);assert.equal(m.acceptedVisual.bodySHA256,"2a541033b71b638f1803e5a9477a0197c38f38d96ff199a4864d49bf551608dd");assert.equal(m.acceptedVisual.manifestSHA256,"5e70b17c91c8601ed895455364f2cd8a51e010e2cb2201f09dc2c02c826f3892");
assert.equal(m.runtimeContract.requestSchemaVersion,"terrain-layers-v2");assert.deepEqual(m.runtimeContract.layerOrder,layerOrder);assert.equal(m.runtimeContract.grounds.length,12);assert.deepEqual(m.runtimeContract.elevation,[0,3]);assert.deepEqual(m.runtimeContract.surfaceDeposits.keys,depositKeys);assert.equal(m.runtimeContract.surfaceDeposits.independent,true);assert.equal(m.runtimeContract.placeholderFallback,false);
assert.deepEqual(fs.readdirSync(out).sort(),["evidence","runtime"]);assert.deepEqual(fs.readdirSync(path.join(out,"runtime")).sort(),["assets","manifest.json"]);
const listed=new Set(Object.values(m.assets).map(x=>path.basename(x.path))),files=fs.readdirSync(path.join(out,"runtime/assets"));assert.equal(files.length,listed.size);assert.deepEqual(new Set(files),listed);
for(const row of Object.values(m.assets)){assert.match(row.path,/^assets\/[a-f0-9]{64}\.png$/);assert.ok(fs.existsSync(path.join(out,"runtime",row.path)));assert.equal(row.sha256,path.basename(row.path,".png"));assert.notEqual(row.kind,"conformanceRGBA");}
assert.equal(assetKeys.filter(k=>k.startsWith("edge/")).length,16);assert.ok(assetKeys.some(k=>k.startsWith("accepted/macro/")));assert.ok(assetKeys.some(k=>k.startsWith("accepted/motion/")));assert.ok(assetKeys.some(k=>k.startsWith("accepted/roles/snow-")));assert.equal(assetKeys.some(k=>k.startsWith("case/")),false);assert.ok(cases.every(x=>x.assetKey===undefined&&/^[a-f0-9]{64}$/.test(x.rgbaSHA256)&&JSON.stringify(x.orderedLayers)===JSON.stringify(layerOrder)));
const base=cases[0].request;assert.deepEqual(Object.keys(base).sort(),["cardinalNeighbors","edgeContourIDs","elevation","featureVariant","ground","isCracking","isCrumbled","motionBand","phaseOffset","point","presentationTick","reduceMotion","schemaVersion","surfaceDeposits","visibility","visualSeed","worldGradeDescriptorHash"].sort());assert.equal(normalizeRuntimeRequest({...base,elevation:3}).elevation,3);
for(const bad of [{...base,extra:true},{...base,paletteID:"invented"},{...base,deposits:{snow:true}},{...base,elevation:4},{...base,visibility:"hidden"},{...base,surfaceDeposits:{snow:false,ash:true}},{...base,cardinalNeighbors:{...base.cardinalNeighbors,north:"lava"}},{...base,worldGradeDescriptorHash:""},{...base,visualSeed:Number.MAX_SAFE_INTEGER+1},{...base,point:{x:Infinity,y:0}},{...base,presentationTick:1.5}])assert.throws(()=>normalizeRuntimeRequest(bad));
const values=field=>new Set(cases.map(x=>x.request[field]));assert.deepEqual([...values("visibility")].sort(),["fringe","full","remembered"]);assert.deepEqual([...values("motionBand")].sort(),["calm","moving","strong"]);assert.ok(cases.some(x=>x.request.reduceMotion));assert.ok(cases.some(x=>x.request.elevation===3));assert.ok(cases.some(x=>x.request.isCrumbled&&x.externalLayers.crumbled));assert.ok(cases.some(x=>x.request.isCracking&&x.externalLayers.cracking));assert.ok(cases.every(x=>x.externalLayers.genuineElevationContactShade==="external-not-owned"));assert.ok(cases.some(x=>x.request.surfaceDeposits.snow&&!x.request.surfaceDeposits.settledAsh));assert.ok(cases.some(x=>!x.request.surfaceDeposits.snow&&x.request.surfaceDeposits.settledAsh));assert.ok(cases.some(x=>x.request.surfaceDeposits.snow&&x.request.surfaceDeposits.settledAsh));
for(const pair of ["water-deepWater","stone-soil","groundcover-growth"])assert.ok(cases.some(x=>x.id.startsWith(`contact/${pair}/`)));
const visibility=cases.filter(x=>x.id.startsWith("visibility/"));assert.equal(new Set(visibility.map(x=>x.rgbaSHA256)).size,1);assert.equal(new Set(visibility.map(x=>x.motionSHA256)).size,1);
const activeVisibility=cases.filter(x=>x.id.startsWith("visibility-active/")),activeByVisibility=Object.fromEntries(activeVisibility.map(x=>[x.request.visibility,x]));assert.notEqual(activeByVisibility.full.rgbaSHA256,activeByVisibility.fringe.rgbaSHA256);assert.equal(activeByVisibility.fringe.rgbaSHA256,activeByVisibility.remembered.rgbaSHA256);assert.equal(activeByVisibility.fringe.rgbaSHA256,visibility[0].rgbaSHA256);assert.equal(activeByVisibility.fringe.motionSHA256,activeByVisibility.remembered.motionSHA256);
const elevations=cases.filter(x=>x.id.startsWith("external/elevation/"));assert.equal(elevations.length,4);assert.equal(new Set(elevations.map(x=>x.rgbaSHA256)).size,1);
for(const ground of ["water","deepWater","groundcover","growth"]){for(const band of ["calm","moving","strong"])assert.equal(cases.filter(x=>x.id.startsWith(`motion/${ground}/${band}/`)).length,4);const reduced=cases.filter(x=>x.id.startsWith(`motion/${ground}/reduced/`));assert.equal(reduced.length,2);assert.equal(reduced[0].motionSHA256,reduced[1].motionSHA256);assert.equal(reduced[0].rgbaSHA256,reduced[1].rgbaSHA256);}
assert.equal(Object.keys(m.pressurePalettes.rows).length,3);assert.ok(cases.every(x=>m.pressurePalettes.rows[x.request.worldGradeDescriptorHash]));
console.log(`terrain production pack v1 passed: ${assetKeys.length} assets, ${cases.length} cases, ${m.canonicalBodySHA256}`);
