import assert from "node:assert/strict";
import {tradingPostContract,tradingPostFixtures,resolveTradingPost,proposedTradingPostResult,cancelTradingPostPreview,tradingStockSnapshotHash,authoredResourceSellPrice} from "../src/trading-kit.js";
import {characterCommands} from "../src/character-kit.js";
import {hash} from "../src/generator.js";
assert.deepEqual(tradingPostContract,{version:"trading-post-ui-1.0.0",evidenceRole:"proposedSemanticFixture",integrationReady:false,collectionGrammar:"physical-object-six-across",ordinaryColumns:6,permanentNamesUnderIcons:false,selectionMutation:false,accessibilityColumns:"may-reduce-without-clipping",stationID:"trading_post",merchantID:"vance",stockOwnership:"proposed-persisted-snapshot",sellAvailability:"proposed-independent-of-stock-refresh",mutation:"rules-owned-confirm-only",currency:"goldCoins"});
assert.equal(tradingPostFixtures.stock.length,6,"ordinary phone merchant stock evidence must use exactly six tangible icons per row");assert.equal(tradingPostFixtures.holdings.length,6,"ordinary phone sell evidence must use exactly six tangible icons per row");
const buy=resolveTradingPost({mode:"buy",wallet:18,stockState:"ready",line:tradingPostFixtures.stock[1],quantity:2});assert.deepEqual(buy,{mode:"buy",state:"preview",title:"Quartz",quantity:2,unitPrice:6,total:12,walletBefore:18,walletAfter:6,remainingBefore:2,remainingAfter:0,mutationAllowed:false,confirmAction:"Confirm buy"});assert.equal(proposedTradingPostResult(buy).result,"2 added to Resource Pool");assert.equal(proposedTradingPostResult(buy).mutationAllowed,false,"AssetLab must not pretend to commit a rules-owned transaction");
assert.deepEqual(cancelTradingPostPreview(buy),{state:"cancelled",wallet:18,remaining:2,mutationAllowed:false,result:"No changes"});
const sell=resolveTradingPost({mode:"sell",wallet:18,stockState:"awaitingRefresh",line:tradingPostFixtures.holdings[0],quantity:3});assert.equal(sell.total,3);assert.equal(sell.walletAfter,21);assert.equal(sell.mutationAllowed,false,"preview must not mutate");assert.equal(proposedTradingPostResult(sell).result,"3 removed · 3 Gold Coins received");assert.equal(proposedTradingPostResult(sell).mutationAllowed,false);
for(const line of tradingPostFixtures.holdings.filter(item=>item.eligibility==="cannotAct")){const result=resolveTradingPost({mode:"sell",wallet:18,stockState:"ready",line,quantity:1});assert.equal(result.state,"cannotAct");assert.equal(result.mutationAllowed,false);assert.ok(result.reason);}
assert.equal(resolveTradingPost({mode:"buy",wallet:1,stockState:"ready",line:tradingPostFixtures.stock[1],quantity:1}).reason,"Need 5 more gold");assert.equal(resolveTradingPost({mode:"buy",wallet:18,stockState:"awaitingRefresh",line:tradingPostFixtures.stock[0],quantity:1}).reason,"Selling is still available");
assert.deepEqual(authoredResourceSellPrice("ore"),{band:"staple",sell:1,buy:3});assert.deepEqual(authoredResourceSellPrice("gold"),{band:"precious",sell:12,buy:null});assert.deepEqual(authoredResourceSellPrice("essence_raw"),{band:"nontradeable",sell:null,buy:null});assert.deepEqual(authoredResourceSellPrice("mote"),{band:"nontradeable",sell:null,buy:null});
const snapshot={refresh:tradingPostFixtures.refresh,stock:tradingPostFixtures.stock};assert.equal(tradingStockSnapshotHash(snapshot),tradingStockSnapshotHash(structuredClone(snapshot)),"open, close and reopen must preserve the persisted snapshot");assert.notEqual(tradingStockSnapshotHash(snapshot),tradingStockSnapshotHash({refresh:{...tradingPostFixtures.refresh,sequence:5,outcomeID:"outcome-18"},stock:tradingPostFixtures.stock}),"only a newly resolved expedition snapshot may change refresh identity");
const vanceOutside=characterCommands("vance",{profile:"baseSide"}),vanceAtCounter=characterCommands("vance",{profile:"baseSide"});assert.equal(hash(vanceOutside),hash(vanceAtCounter),"Vance's authored base-side identity must not change at the counter");assert.notEqual(hash(vanceOutside),hash(characterCommands("vance",{profile:"world"})),"Trading Post proof must not reuse the sign-like legacy upright profile");
assert.throws(()=>resolveTradingPost({mode:"sell",wallet:18,stockState:"ready",line:tradingPostFixtures.holdings[0],quantity:1,extra:true}),/invalid-trading-post-request-fields/);assert.throws(()=>resolveTradingPost({mode:"sell",wallet:18,stockState:"ready",line:{...tradingPostFixtures.holdings[0],extra:true},quantity:1}),/invalid-holding-line-fields/);
console.log("Asset Lab Trading Post resolver tests passed.");
