import assert from "node:assert/strict";
import {access,readdir,readFile} from "node:fs/promises";
const root=new URL("../",import.meta.url),pages=(await readdir(root)).filter(name=>name.endsWith(".html")).sort(),expected=["index.html","world.html","places.html","characters.html","full-cast.html","resources.html","equipment.html","trading.html","reporter.html","noll.html","bridge.html","combat.html","combat-ui.html","campaigns.html","launch.html","splashes.html","regression.html"];
for(const page of pages){const html=await readFile(new URL(page,root),"utf8"),nav=html.match(/<nav class="tool-nav"[\s\S]*?<\/nav>/)?.[0];assert.ok(nav,`${page} must retain the shared tool navigation`);const hrefs=[...nav.matchAll(/href="([^"]+)"/g)].map(match=>match[1]);assert.deepEqual(hrefs,expected,`${page} navigation drifted or dropped tools`);for(const match of html.matchAll(/(?:href|src)="([^"]+)"/g)){const target=match[1];if(/^(?:https?:|#|data:)/.test(target))continue;await assert.doesNotReject(access(new URL(target,new URL(page,root))),`${page} references missing local target ${target}`);}}
const css=await readFile(new URL("styles.css",root),"utf8");assert.match(css,/\.tool-nav\s*\{[^}]*position:\s*sticky[^}]*flex-wrap:\s*nowrap[^}]*overflow-x:\s*auto/s,"navigation must remain visible and horizontally reachable in narrow windows");assert.doesNotMatch(css,/body\s*\{[^}]*min-width:\s*980px/s,"desktop minimum width must not push navigation out of the viewport");
const regressionApp=await readFile(new URL("src/regression-app.js",root),"utf8"),regressionPage=await readFile(new URL("regression.html",root),"utf8");assert.match(regressionApp,/keys=Object\.keys\(current\)/,"browser review must compare only outputs actually represented on its sheet");assert.doesNotMatch(regressionApp,/new Set\(\[\.\.\.Object\.keys\(baseline\.hashes\),\.\.\.Object\.keys\(current\)\]\)/,"browser review must not misreport unrendered canonical outputs as deletions");assert.match(regressionPage,/complete canonical gate runs in the test suite/,"Golden Review must disclose its representative scope");
assert.match(css,/\.golden-stage canvas\s*\{[^}]*height:\s*auto/s,"expanded Golden Review evidence must retain its intrinsic pixel aspect ratio");
assert.match(regressionApp,/resource\/\$\{id\}\/remaining/,"Golden Review should visibly cover accepted resource bodies");assert.match(regressionPage,/id="golden-sheet" width="768" height="1152"/,"expanded resource evidence must not clip its final row");
console.log("Asset Lab web-shell navigation tests passed.");
