import assert from "node:assert/strict";import fs from "node:fs";import path from "node:path";import {PAGE,MARGIN,WRITING,SOCKET,AXIS,hands,states,proofLexemeIDs,pagePalette,blankPage,buildLexemeReceipt,resolveLexeme,markPart,stateOverlay,unreadMarker,mixedInk,placeMark,socketRect} from "../src/writing-page-a1-kit.js";
const root=path.resolve(import.meta.dirname,".."),artifact=path.join(root,"artifacts/writing-page-a1-v0.1"),read=(f,k)=>JSON.parse(fs.readFileSync(path.join(root,"..","Sources","Content","Data",f),"utf8"))[k],receipt=buildLexemeReceipt({targets:read("pressure_targets.json","targets"),sources:read("pressure_sources.json","sources"),qualifiers:read("qualifiers.json","qualifiers"),symbols:read("symbols.json","symbols"),shapes:read("rune_shapes.json","shapes")});
assert.deepEqual([PAGE,MARGIN,WRITING,SOCKET,AXIS],[172,5,162,27,6]);const page=blankPage();assert.equal(page.length,PAGE*PAGE*4);for(let i=3;i<page.length;i+=4)assert.equal(page[i],255);assert.ok(page.filter((_,i)=>i%4===0).length>0);for(let i=1;i<6;i++){const at=MARGIN+i*SOCKET;let v=0,h=0;for(let q=MARGIN;q<MARGIN+WRITING;q++){if(page[(q*PAGE+at)*4]!==page[(q*PAGE+at-1)*4])v++;if(page[(at*PAGE+q)*4]!==page[((at-1)*PAGE+q)*4])h++}assert.ok(v>WRITING*.75&&h>WRITING*.75,"guides stay legible and gently broken")}
const interiors=new Set();for(let y=5;y<167;y++)for(let x=5;x<167;x++)interiors.add(page[(y*PAGE+x)*4]+","+page[(y*PAGE+x)*4+1]+","+page[(y*PAGE+x)*4+2]);assert.ok(interiors.size<=5,"quiet bounded paper palette");
assert.equal(receipt.catalogueCounts.total,108);assert.equal(new Set(receipt.entries.map(e=>e.glyph.bitmap)).size,108,"full current lexeme glyph census collision-free");assert.deepEqual(receipt,buildLexemeReceipt({targets:read("pressure_targets.json","targets"),sources:read("pressure_sources.json","sources"),qualifiers:read("qualifiers.json","qualifiers"),symbols:read("symbols.json","symbols"),shapes:read("rune_shapes.json","shapes")}));assert.throws(()=>resolveLexeme(receipt,"not-real"),/unknown writing lexeme/);
for(const id of proofLexemeIDs){const e=resolveLexeme(receipt,id);for(const hand of hands){const p=markPart({receipt,lexemeID:id,hand});assert.equal(p.glyphBitmap,e.glyph.bitmap,"same skeleton all hands");assert.equal(p.pixels.length,p.width*p.height*4);const expected=hand==="charcoal"?[4,6]:hand==="brush"?[2,3]:[1,1];assert.ok(p.footprint>=expected[0]&&p.footprint<=expected[1],`${id} ${hand} footprint`);for(const cell of p.cells){let ink=0;for(let y=cell[1]*27;y<(cell[1]+1)*27;y++)for(let x=cell[0]*27;x<(cell[0]+1)*27;x++)if(p.pixels[(y*p.width+x)*4+3])ink++;assert.ok(ink>8,"every occupied cell visibly written")}}}
const ash=markPart({receipt,lexemeID:"verdant",hand:"brush"});for(const color of [[82,18,8,24],[48,78,0,32],[72,0,76,28]].map(([cyan,magenta,yellow,depth])=>mixedInk({cyan,magenta,yellow,depth}))){const m=markPart({receipt,lexemeID:"verdant",hand:"brush",color});for(let i=3;i<m.pixels.length;i+=4)assert.equal(ash.pixels[i],m.pixels[i],"ink changes owned mark pixels only")}
const pen=markPart({receipt,lexemeID:"plains",hand:"fountain"}),lum=hex=>{const h=hex.slice(1);return[0,2,4].map(i=>parseInt(h.slice(i,i+2),16)).reduce((s,v,i)=>s+v*[.2126,.7152,.0722][i],0)};assert.ok(lum(pagePalette.pen)<lum(pagePalette.fiber));
const geometrySignatures=new Set();for(const state of states){const o=stateOverlay(state,markPart({receipt,lexemeID:"plains",hand:"brush"}).cells),opaque=[];assert.equal(o.pixels.length,o.width*o.height*4);for(let i=3;i<o.pixels.length;i+=4)if(o.pixels[i]===255)opaque.push((i-3)/4);const signature=opaque.join(",");assert.ok(!geometrySignatures.has(signature),`${state} geometry must be pairwise distinct without colour`);geometrySignatures.add(signature);if(state==="legal")assert.ok(opaque.length>=36,"legal chevrons need strong visible geometry");if(state==="connectTarget")assert.ok(opaque.length>=26,"paired 5x5 endpoint diamonds need strong visible geometry")}assert.ok(unreadMarker().some((v,i)=>i%4===3&&v===255));
for(let r=0;r<6;r++)for(let c=0;c<6;c++){const s=socketRect(c,r);assert.ok(s.x>=5&&s.y>=5&&s.x+s.width<=167&&s.y+s.height<=167)}const one=markPart({receipt,lexemeID:"plains",hand:"fountain"});assert.equal(placeMark(page,one,5,5).length,page.length);assert.throws(()=>placeMark(page,markPart({receipt,lexemeID:"plains",hand:"charcoal"}),5,5),/outside page/);
const proof=JSON.parse(fs.readFileSync(path.join(root,"fixtures","writing-page-a1-v1","proof-fixtures.json"),"utf8"));assert.equal(proof.densePlacements.length,12);assert.deepEqual(proof.densePlacements.map(x=>[x.column,x.row]),[...Array.from({length:6},(_,column)=>[column,0]),...Array.from({length:6},(_,column)=>[column,5])]);assert.deepEqual(proof.densePlacements.map(x=>x.id),[...Array(3)].flatMap(()=>proofLexemeIDs));const saved=JSON.parse(fs.readFileSync(path.join(root,"fixtures","writing-page-a1-v1","lexeme-receipt.json"),"utf8"));assert.deepEqual(saved,receipt);const manifest=JSON.parse(fs.readFileSync(path.join(artifact,"manifest.json"),"utf8"));assert.equal(manifest.integrationReady,false);assert.equal(manifest.lexemeReceipt.glyphVersion,"writing-glyph-v1");assert.equal(manifest.states.shapeRedundancy,true);for(const f of ["contact/same-plains-three-hand-footprints-2x.png","contact/same-plains-three-hand-footprints-grayscale-2x.png","evidence/multi-cell-link-2x.png","contact/independent-state-overlays-grayscale-2x.png","evidence/dense-first-last-row-2x.png","evidence/dense-first-last-row-grayscale-2x.png","evidence/known-and-unknown-2x.png","evidence/socket-collision-2x.png"])assert.ok(fs.existsSync(path.join(artifact,f)),f);console.log("writing page A1 kit tests passed");
