#!/usr/bin/env python3
"""Export the exact-ID resource sprite pack from reviewed chroma-key atlases."""

from __future__ import annotations

import hashlib
import json
import base64
import sys
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[2]
PACK = ROOT / "AssetLab/integration/resource-sprites-v1"
CATALOGUE = ROOT / "Sources/Content/Data/resources.json"
SWIFT_OUTPUT = ROOT / "Sources/VisualRuntime/ResourceSpriteV1Registry.generated.swift"

PROFILES = {
    "inventory": {"size": 32, "colors": 8, "source": "inventory-atlas-alpha.png"},
    "map": {"size": 16, "colors": 6, "source": "map-atlas-alpha.png"},
    "field": {"size": 8, "colors": 3, "source": "field-atlas-alpha.png"},
}


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def quantize_opaque(image: Image.Image, colors: int) -> Image.Image:
    alpha = image.getchannel("A")
    opaque_rgb = Image.new("RGB", image.size, (0, 0, 0))
    opaque_rgb.paste(image.convert("RGB"), mask=alpha)
    quantized = opaque_rgb.quantize(colors=colors, method=Image.Quantize.FASTOCTREE).convert("RGBA")
    quantized.putalpha(alpha.point(lambda value: 255 if value >= 128 else 0))
    return quantized


def cell(atlas: Image.Image, index: int) -> Image.Image:
    column, row = index % 5, index // 5
    left = round(column * atlas.width / 5)
    right = round((column + 1) * atlas.width / 5)
    top = round(row * atlas.height / 5)
    bottom = round((row + 1) * atlas.height / 5)
    return atlas.crop((left, top, right, bottom))


def fitted_sprite(source: Image.Image, size: int, colors: int) -> Image.Image:
    bounds = source.getchannel("A").getbbox()
    if bounds is None:
        return Image.new("RGBA", (size, size), (0, 0, 0, 0))
    cropped = source.crop(bounds)
    maximum = size if size <= 8 else size - 2
    scale = min(maximum / cropped.width, maximum / cropped.height)
    width = max(1, round(cropped.width * scale))
    height = max(1, round(cropped.height * scale))
    resized = cropped.resize((width, height), Image.Resampling.NEAREST)
    resized = quantize_opaque(resized, colors)
    canvas = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    canvas.alpha_composite(resized, ((size - width) // 2, (size - height) // 2))
    return canvas


def occupied_pixels(image: Image.Image) -> int:
    return sum(1 for value in image.getchannel("A").tobytes() if value)


def silhouette_hash(image: Image.Image) -> str:
    mask = bytes(1 if value else 0 for value in image.getchannel("A").tobytes())
    return hashlib.sha256(mask).hexdigest()


def rgba_bytes(image: Image.Image) -> bytes:
    return image.convert("RGBA").tobytes()


def packed_sprite(image: Image.Image) -> tuple[list[int], str]:
    palette = [0]
    palette_index = {0: 0}
    indices = bytearray()
    for red, green, blue, alpha in image.convert("RGBA").getdata():
        rgba = (red << 24) | (green << 16) | (blue << 8) | alpha if alpha else 0
        if rgba not in palette_index:
            palette_index[rgba] = len(palette)
            palette.append(rgba)
        indices.append(palette_index[rgba])
    return palette, base64.b64encode(indices).decode()


def export_swift(resources: list[dict]) -> None:
    lines = [
        "// Generated by AssetLab/scripts/export-resource-sprite-pack.py. Do not hand edit.",
        "import Foundation",
        "",
        "enum ResourceSpriteV1Profile: String, CaseIterable, Sendable { case inventory, map, field }",
        "",
        "struct ResourceSpriteV1Asset: Sendable {",
        "    let width: Int",
        "    let height: Int",
        "    let paletteRGBA: [UInt32]",
        "    let indicesBase64: String",
        "    let decodedRGBASHA256: String",
        "",
        "    var rgbaPixels: [UInt8] {",
        "        guard let data = Data(base64Encoded: indicesBase64), data.count == width * height else { return [] }",
        "        var result: [UInt8] = []",
        "        result.reserveCapacity(width * height * 4)",
        "        for index in data {",
        "            guard Int(index) < paletteRGBA.count else { return [] }",
        "            let rgba = paletteRGBA[Int(index)]",
        "            result += [UInt8((rgba >> 24) & 0xff), UInt8((rgba >> 16) & 0xff),",
        "                       UInt8((rgba >> 8) & 0xff), UInt8(rgba & 0xff)]",
        "        }",
        "        return result",
        "    }",
        "}",
        "",
        "enum ResourceSpriteV1Registry {",
        "    static let packID = \"resource-sprites-v1\"",
        "    static let catalogueSHA256 = \"" + sha256(CATALOGUE) + "\"",
        "    static let orderedResourceIDs: [ResourceID] = [",
    ]
    lines.extend(f"        ResourceID(rawValue: \"{entry['id']}\")," for entry in resources)
    lines += ["    ]", "", "    static func asset(for id: ResourceID, profile: ResourceSpriteV1Profile) -> ResourceSpriteV1Asset? {", "        assets[id.rawValue]?[profile]", "    }", "", "    private static let assets: [String: [ResourceSpriteV1Profile: ResourceSpriteV1Asset]] = ["]
    for entry in resources:
        lines.append(f"        \"{entry['id']}\": [")
        for profile in ("inventory", "map", "field"):
            record = entry["profiles"][profile]
            if record is None:
                continue
            image = Image.open(PACK / record["path"]).convert("RGBA")
            palette, indices = packed_sprite(image)
            palette_swift = ", ".join(f"0x{value:08x}" for value in palette)
            lines.append(f"            .{profile}: .init(width: {image.width}, height: {image.height}, paletteRGBA: [{palette_swift}],")
            lines.append(f"                              indicesBase64: \"{indices}\", decodedRGBASHA256: \"{record['decodedRGBASHA256']}\"),")
        lines.append("        ],")
    lines += ["    ]", "}", ""]
    SWIFT_OUTPUT.write_text("\n".join(lines))


def proof_sheet(resources: list[dict]) -> Path:
    scales = {"inventory": 1, "map": 2, "field": 4}
    cell = 38
    profile_width = cell * 5
    sheet = Image.new("RGBA", (profile_width * 3, cell * 5), (24, 23, 22, 255))
    for profile_index, profile in enumerate(("inventory", "map", "field")):
        scale = scales[profile]
        for resource_index, entry in enumerate(resources):
            record = entry["profiles"][profile]
            if record is None:
                continue
            sprite = Image.open(PACK / record["path"]).convert("RGBA")
            enlarged = sprite.resize((sprite.width * scale, sprite.height * scale), Image.Resampling.NEAREST)
            column, row = resource_index % 5, resource_index // 5
            x = profile_index * profile_width + column * cell + (cell - enlarged.width) // 2
            y = row * cell + (cell - enlarged.height) // 2
            sheet.alpha_composite(enlarged, (x, y))
    output = PACK / "resource-sprites-v1-proof.png"
    sheet.save(output, optimize=False)
    return output


def generated_paths(resource_ids: list[str]) -> list[Path]:
    paths = [PACK / "manifest.json", PACK / "resource-sprites-v1-proof.png", SWIFT_OUTPUT]
    for profile in PROFILES:
        paths.extend(PACK / profile / f"{resource_id}.png" for resource_id in resource_ids
                     if not (profile == "map" and resource_id == "mote"))
    return paths


def main(*, check: bool = False) -> None:
    resource_data = json.loads(CATALOGUE.read_text())
    resources = resource_data["resources"]
    ids = [entry["id"] for entry in resources]
    if len(ids) != 23 or len(ids) != len(set(ids)):
        raise SystemExit("resource catalogue must contain exactly 23 unique IDs")
    outputs = generated_paths(ids)
    before = {path: path.read_bytes() if path.exists() else None for path in outputs} if check else {}

    manifest_entries = []
    for index, entry in enumerate(resources):
        exported = {"id": entry["id"], "name": entry["name"], "profiles": {}}
        for profile, spec in PROFILES.items():
            if profile == "map" and entry["id"] == "mote":
                exported["profiles"][profile] = None
                continue
            atlas_path = PACK / "source" / spec["source"]
            atlas = Image.open(atlas_path).convert("RGBA")
            sprite = fitted_sprite(cell(atlas, index), spec["size"], spec["colors"])
            if occupied_pixels(sprite) == 0:
                raise SystemExit(f"empty sprite: {profile}/{entry['id']}")
            output = PACK / profile / f"{entry['id']}.png"
            output.parent.mkdir(parents=True, exist_ok=True)
            sprite.save(output, optimize=False)
            exported["profiles"][profile] = {
                "path": str(output.relative_to(PACK)),
                "width": spec["size"],
                "height": spec["size"],
                "maxOpaqueColors": spec["colors"],
                "occupiedPixels": occupied_pixels(sprite),
                "silhouetteSHA256": silhouette_hash(sprite),
                "decodedRGBASHA256": hashlib.sha256(rgba_bytes(sprite)).hexdigest(),
                "fileSHA256": sha256(output),
            }
        manifest_entries.append(exported)

    proof = proof_sheet(manifest_entries)
    export_swift(manifest_entries)
    manifest = {
        "schemaVersion": 1,
        "packID": "resource-sprites-v1",
        "catalogueAuthority": "Sources/Content/Data/resources.json",
        "catalogueSHA256": sha256(CATALOGUE),
        "integrationReady": True,
        "profiles": {
            "inventory": {"logicalPixels": 32, "use": "collected Storehouse and economy identity"},
            "map": {"logicalPixels": 16, "use": "orthographic terrain overlay", "ineligibleIDs": ["mote"]},
            "field": {"logicalPixels": 8, "use": "compact exploration collection marker"},
        },
        "resources": manifest_entries,
        "constraints": {
            "mapCamera": "orthographic-top-down",
            "mapBackground": "transparent-no-terrain-patch",
            "fieldIsIndependentProfile": True,
            "nearestNeighborOnly": True,
            "namedOrderingIsNotIdentity": True,
        },
        "sourceAtlases": {
            name: {"path": f"source/{spec['source']}", "fileSHA256": sha256(PACK / "source" / spec["source"])}
            for name, spec in PROFILES.items()
        },
        "proofSheet": {"path": proof.name, "fileSHA256": sha256(proof)},
    }
    body = json.dumps(manifest, sort_keys=True, separators=(",", ":")).encode()
    manifest["canonicalBodySHA256"] = hashlib.sha256(body).hexdigest()
    (PACK / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")

    if check:
        changed = [path for path in outputs
                   if (path.read_bytes() if path.exists() else None) != before[path]]
        for path, contents in before.items():
            if contents is None:
                if path.exists():
                    path.unlink()
            else:
                path.write_bytes(contents)
        if changed:
            names = ", ".join(str(path.relative_to(ROOT)) for path in changed)
            raise SystemExit(f"resource sprite outputs are stale: {names}")


if __name__ == "__main__":
    arguments = sys.argv[1:]
    if arguments not in ([], ["--check"]):
        raise SystemExit("usage: export-resource-sprite-pack.py [--check]")
    main(check=arguments == ["--check"])
