#!/usr/bin/env python3
"""Generate the immutable native registry from mob-gear-sprites-v1 PNGs."""

from __future__ import annotations

import argparse
import base64
import hashlib
import json
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[2]
PACK = ROOT / "AssetLab/integration/mob-gear-sprites-v1"
TARGET = ROOT / "Sources/VisualRuntime/MobGearSpriteV1Registry.generated.swift"


def commands(path: Path) -> list[tuple[int, int, int, int, int]]:
    image = Image.open(path).convert("RGBA")
    result: list[tuple[int, int, int, int, int]] = []
    pixels = image.load()
    for y in range(image.height):
        x = 0
        while x < image.width:
            rgba = pixels[x, y]
            start = x
            while x + 1 < image.width and pixels[x + 1, y] == rgba:
                x += 1
            if rgba[3] > 0:
                packed = (rgba[0] << 24) | (rgba[1] << 16) | (rgba[2] << 8) | rgba[3]
                result.append((start, y, x - start + 1, 1, packed))
            x += 1
    return result


def asset_literal(path: Path, indent: str) -> str:
    image = Image.open(path).convert("RGBA")
    pixels = list(image.getdata())
    palette = [(0, 0, 0, 0)]
    for pixel in pixels:
        if pixel[3] > 0 and pixel not in palette:
            palette.append(pixel)
    if len(palette) > 255:
        raise ValueError(f"too many colors in {path}: {len(palette)}")
    indices = bytes(palette.index(pixel) if pixel[3] > 0 else 0 for pixel in pixels)
    source_commands = []
    for offset, index in enumerate(indices):
        if index == 0:
            continue
        rgba_tuple = palette[index]
        rgba = (rgba_tuple[0] << 24) | (rgba_tuple[1] << 16) | (rgba_tuple[2] << 8) | rgba_tuple[3]
        source_commands.append((offset % 32, offset // 32, 1, 1, rgba))
    normalized = bytearray()
    decoded = bytearray(32 * 32 * 4)
    for x, y, width, height, rgba in source_commands:
        normalized += bytes((x, y, width, height, (rgba >> 24) & 0xff, (rgba >> 16) & 0xff,
                             (rgba >> 8) & 0xff, rgba & 0xff))
        color = bytes(((rgba >> 24) & 0xff, (rgba >> 16) & 0xff, (rgba >> 8) & 0xff, rgba & 0xff))
        for py in range(y, y + height):
            for px in range(x, x + width):
                offset = (py * 32 + px) * 4
                decoded[offset:offset + 4] = color
    command_hash = hashlib.sha256(normalized).hexdigest()
    decoded_hash = hashlib.sha256(decoded).hexdigest()
    packed_palette = [f"0x{r:02x}{g:02x}{b:02x}{a:02x}" for r, g, b, a in palette]
    return ("MobGearPackedSprite.asset(palette: [" + ", ".join(packed_palette)
            + f"], indicesBase64: \"{base64.b64encode(indices).decode()}\", "
            + f"commandSHA256: \"{command_hash}\", decodedRGBASHA256: \"{decoded_hash}\")")


def generated_source() -> str:
    manifest = json.loads((PACK / "manifest.json").read_text())
    mob = manifest["profiles"]["mobDropInventory"]["sprites"]
    gear = manifest["profiles"]["catalogueGear"]["sprites"]
    lines = [
        "// Generated by AssetLab/scripts/generate-mob-gear-native.py. Do not hand edit.",
        "import Foundation", "", "private enum MobGearPackedSprite {",
        "    static func asset(palette: [UInt32], indicesBase64: String, commandSHA256: String,",
        "                      decodedRGBASHA256: String) -> NativeVisualRuntime.GeneratedPixelAsset {",
        "        let indices = Data(base64Encoded: indicesBase64) ?? Data()",
        "        let commands = indices.enumerated().compactMap { offset, index -> NativeVisualRuntime.PixelCommand? in",
        "            guard index > 0, Int(index) < palette.count else { return nil }",
        "            return .init(x: UInt8(offset % 32), y: UInt8(offset / 32), width: 1, height: 1,",
        "                         rgba: palette[Int(index)])",
        "        }", "        return .init(width: 32, height: 32, commands: commands,",
        "                     commandSHA256: commandSHA256, decodedRGBASHA256: decodedRGBASHA256)",
        "    }", "}", "", "enum MobGearSpriteV1Registry {",
        f'    static let packID = "{manifest["packID"]}"',
        f'    static let canonicalBodySHA256 = "{manifest["canonicalBodySHA256"]}"', "",
        "    static func mobDropAsset(for kind: MaterialKind) -> NativeVisualRuntime.GeneratedPixelAsset? {",
        "        mobDropAssets[kind.rawValue]", "    }", "",
        "    static let catalogueRegistry = CatalogueGearSpriteV1Registry()", "",
        "    private static let mobDropAssets: [String: NativeVisualRuntime.GeneratedPixelAsset] = [",
    ]
    for record in mob:
        lines.append(f'        "{record["id"]}": {asset_literal(PACK / "mob-drops" / record["file"], "        ")},')
    lines += ["    ]", "}", "", "struct CatalogueGearSpriteV1Registry: NativeVisualRuntime.Registry {",
              f'    let manifestSHA256 = "{manifest["canonicalBodySHA256"]}"',
              '    let pipelineVersion = "mob-gear-sprites-v1"',
              "    let canvasWidth: UInt8 = 32", "    let canvasHeight: UInt8 = 32", "",
              "    var assets: [NativeVisualRuntime.Entry] { Self.generatedAssets }", "",
              "    var explicitlyUnsupportedIDs: [String] { [] }", "",
              "    private static let generatedAssets: [NativeVisualRuntime.Entry] = ["]
    for record in gear:
        asset = asset_literal(PACK / "catalogue-gear" / record["file"], "            ")
        lines += ["        .init(",
                  f'            key: .init(catalogueID: "{record["id"]}", identified: true),',
                  f"            asset: {asset}", "        ),"]
    lines += ["    ]", "}", "",
              "struct CatalogueItemCompositeV1Registry: NativeVisualRuntime.Registry {",
              f'    let manifestSHA256 = "{manifest["canonicalBodySHA256"]}"',
              '    let pipelineVersion = "catalogue-consumables-placeholder-v1+mob-gear-sprites-v1"',
              "    let canvasWidth: UInt8 = 32", "    let canvasHeight: UInt8 = 32", "",
              "    var assets: [NativeVisualRuntime.Entry] {",
              "        CatalogueConsumablesPlaceholderV1Registry().assets + CatalogueGearSpriteV1Registry().assets",
              "    }", "",
              "    var explicitlyUnsupportedIDs: [String] {",
              "        CatalogueConsumablesPlaceholderV1Registry().explicitlyUnsupportedIDs.filter { id in",
              "            !CatalogueGearSpriteV1Registry().assets.contains { $0.key.catalogueID == id }",
              "        }", "    }", "}", ""]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    source = generated_source()
    if args.check:
        if not TARGET.exists() or TARGET.read_text() != source:
            raise SystemExit("native mob/gear registry drift")
        print("native mob/gear registry is current")
    else:
        TARGET.write_text(source)
        print(TARGET)


if __name__ == "__main__":
    main()
