import Link from '@/components/wiki-link';
import { GuideBreadcrumbs, RelatedGuides } from '@/components/guide-navigation';
import { PageIntro } from '@/components/page-intro';
import { PixelImage } from '@/components/pixel-image';
import { SiteFrame } from '@/components/site-frame';
import { TruthPair } from '@/components/truth-pair';
import { content } from '@/lib/content';
import { materialPropertyProblems } from '@/lib/crafting-overview';

const slots = ['Weapon', 'Off-hand', 'Head', 'Body', 'Hands', 'Feet', 'Tool', 'Keepsake'];

export default function EquipmentMaterialsGuide() {
  const weapon = content.items.find((item) => item.gear?.slot === 'weapon' && item.assetURL);
  const armour = content.items.find((item) => item.gear?.slot === 'armor' && item.assetURL);
  const blacksmith = content.stations.find((station) => station.id === 'blacksmith');
  return <SiteFrame sidebar>
    <GuideBreadcrumbs items={[{ label: 'Systems', href: '/systems' }, { label: 'Equipment and material effects' }]} />
    <PageIntro eyebrow="Current system guide" title="Equipment and material effects" summary="Compare the exact piece and its location at Home, use the eight current slots to keep each person equipped, and read a crafting or reforge preview before spending a selected material sample." />
    <section className="article-section journey-strip">{weapon?.assetURL && <Link href={`/equipment/${weapon.slug}`}><PixelImage src={weapon.assetURL} alt={`${weapon.name} equipment icon`} size={64} /><span><strong>Weapon facts</strong><small>Compare damage kind, reach, tier, and the exact current piece.</small></span></Link>}{armour?.assetURL && <Link href={`/equipment/${armour.slug}`}><PixelImage src={armour.assetURL} alt={`${armour.name} equipment icon`} size={64} /><span><strong>Protection facts</strong><small>Compare current protection and any displayed material properties.</small></span></Link>}{blacksmith?.assetURL && <Link href="/crafting/blacksmith"><PixelImage src={blacksmith.assetURL} alt="Blacksmith building visual" size={64} /><span><strong>Blacksmith</strong><small>Construct or reforge the exact stored or worn piece shown by the station.</small></span></Link>}</section>
    <section className="article-section"><h2>Eight current slots</h2><p>Each party member’s Gear section keeps equipment in these eight slots. Open one slot to compare what is worn with the eligible alternatives you own.</p><div className="definition-grid">{slots.map((slot) => <div key={slot}>{slot}</div>)}</div></section>
    <section className="article-section two-column"><div><h2>Choose a compatible piece</h2><p>A candidate must fit the selected slot and be available at Home. The detail comparison shows the current piece, the selected piece, and the displayed change in damage for a weapon or protection for another slot before you press Equip.</p><p>Take it off removes only the current piece from that person. A refused or unavailable change keeps the worn piece in place.</p></div><div><h2>Read location before moving it</h2><p>Options say whether they are Stored, carried, or worn by another person. Gear worn by another person is marked rather than silently reassigned. Carried gear cannot be changed until you return Home, so its Equip face stays unavailable in the field.</p></div></section>
    <section className="article-section"><h2>Material choice is part of the finished piece</h2><p>When a current crafting recipe asks for samples, select one exact eligible stock sample for every listed requirement. The candidate detail shows the sample’s displayed provenance and grade; ineligible samples stay named with their current reason instead of being used by mistake.</p><div className="definition-grid"><div><h3>Preview before making</h3><p>The recipe preview shows the completed piece’s current facts from the selected samples. Change a socket selection to compare that next preview before committing.</p></div><div><h3>Keep the exact requirement</h3><p>One sample already selected for another requirement is not offered again for the active requirement. Reset suggestion returns the current suggested selection; it does not craft anything.</p></div><div><h3>Quality and history</h3><p>The current craft surfaces describe selected materials as deciding the finished piece’s quality and history. Use the displayed preview and requirements for the exact recipe instead of assuming one material affects every family alike.</p></div><div><h3>Current recipe routes</h3><p>Open a station recipe for its exact inputs, output, and material choices. The table links the finished item back to its equipment facts.</p></div></div></section>
    <section className="article-section"><h2>Intended material stats</h2><TruthPair current="Current recipes often use Hardness, Density, Insulation, Flexibility, Lustre, or Reactivity to decide whether a sample is allowed in a socket. Some current makers also copy selected Insulation and Reactivity into a finished gear receipt." accepted="The physical family, type, or subtype decides whether a material fits a component. The material’s actual numerical properties remain attached and change concrete finished-item statistics; Poor, Common, Rare, or Exceptional quality scales that contribution. The preview must show every resulting number before the player confirms." acceptedLabel="Intended design" /><div className="table-wrap"><table><thead><tr><th>Property</th><th>Intended equipment role</th></tr></thead><tbody>{materialPropertyProblems.map(([property, _current, intended]) => <tr key={property}><td><strong>{property}</strong></td><td>{intended}</td></tr>)}</tbody></table></div><p className="note-card"><strong>Still to settle with Aimee:</strong> The exact per-property, per-component conversion into damage, protection, initiative, resistance, potency, and other approved item statistics.</p></section>
    <section className="article-section"><h2>Construction and reforge routes</h2><p>The Blacksmith’s Make tab builds current physical gear from the selected recipe and samples. Its Reforge tab chooses one exact eligible piece; the preview names the next cost and the displayed improvement while the construction tier remains with that piece. A fully reforged piece stays unavailable, and a changed piece, stock, or cost asks you to review the refreshed result rather than applying an old preview.</p><p>Other current gear families have their own station recipe pages. Follow the recipe’s station link for its access and material requirements.</p><p><Link href="/crafting/blacksmith">Open Blacksmith construction</Link> · <Link href="/crafting">Browse all current crafting systems</Link></p></section>
    <RelatedGuides links={[{ label: 'Browse equipment', href: '/equipment' }, { label: 'Blacksmith construction', href: '/crafting/blacksmith' }, { label: 'Crafting systems', href: '/crafting' }, { label: 'Resources', href: '/resources' }, { label: 'Party, Gear and Gambits', href: '/systems/party-preparation' }, { label: 'Combat', href: '/systems/combat' }]} />
  </SiteFrame>;
}
